### PR TITLE
don't purge author url if equal site_url so we don't purge all urls

### LINKED ISSUE #5887: Security Plugin(s) renders wp-rocket useless
Not sure how many Security Plugins use that "feature" this way, but it would be very easy to avoid this pitfall and lessen support requests (like we had one):

WP Cerber has a feature called "Stop exposing user details" (`nouserpages_bylogin ` in code). The way they implemented it renders WP Rocket useless.

The feature sets - via `add_filter('author_link'…)` - all author pages queried via `get_author_posts_url()` to the SITE-URL.

WP-Rocket uses `get_author_posts_url()` to delete the author page of the post from the cache in `rocket_clean_post()`.

However, due to the WP Cerber feature this adds the SITE-URL to the `$purge_urls` array.
Means that every time a post is changed (product, order,...), the entire site cache is deleted.

A simple check (something like `get_author_posts_url() != SITE-URL`) or alike would avoid this drama.

Regards,
Thomas

### PR DESCRIPTION
**Pull request by mostafa-hisham**
## Description

check if the author url if equal to site_url so we don't purge it to void purge all urls

Fixes #5887 

## Type of change

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No
## How Has This Been Tested?

- [ ] Unit test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by CrochetFeve0251 — APPROVED** [review]

**Comment by vmanthos** [comment]
@mostafa-hisham This will still be a problem in the case of a subfolder installation, e.g. https:/example.com/wp/, where the home URL is set to  https:/example.com/. ([Giving WordPress Its Own Directory](https://wordpress.org/documentation/article/giving-wordpress-its-own-directory/)).

In that case, `site_url()` returns `https:/example.com/wp/` while the `$author_url` is https:/example.com/. 
`home_url()` returns the correct URL.

Both `home_url` and `site_url` can be filtered:
https://github.com/WordPress/wordpress-develop/blob/9fae40ae696d771e044b2913bd54a28244c1901b/src/wp-includes/link-template.php#L3445
https://github.com/WordPress/wordpress-develop/blob/9fae40ae696d771e044b2913bd54a28244c1901b/src/wp-includes/link-template.php#L3509

Although I haven't found a way to manipulate them in the context of this PR, it'd be nice if you could take a look into them and change, if necessary, the logic used in protecting cache clearing.

**Comment by mostafa-hisham** [comment]
I edited the PR to check the home_url too
@vmanthos

**Comment by vmanthos** [comment]
@mostafa-hisham I'm still getting the issue on the same scenario I mentioned earlier, and it's because of a trailing `/`.

I'm adding the author's URL like this:
```PHP
add_filter( 'author_link', function( $link ) { return 'https://wpsub.test/'; }, 99, 1 );
```

Here are the logged values of:
**Author's link:** https://wpsub.test/
**Site URL**: https://wpsub.test/wp
**Home URL**: https://wpsub.test

As you can see, the author's URL is still different from the home URL and this causes the whole cache to be cleared.

I believe `rtrim( $author_url, '/' )` should do it.

Can you please look into this?

**Comment by mostafa-hisham** [comment]
@vmanthos could you please check it again?

**Review by vmanthos — APPROVED** [review]
Working as expected! :+1: 

@piotrbak I think we can close #3246.

**Pull request merged**
