### PR TITLE
Closes #6527: Images intersecting viewport considered as lcp candidates

### LINKED ISSUE #6527: 3.16 enhancement - Images intersecting the viewport should be considered as LCP candidates
**Context**
The current LCP detection only keeps images fully in the viewport as candidates. As discussed [here](https://wp-media.slack.com/archives/C06CQPWEJSK/p1711650334582609?thread_ts=1711580400.684789&cid=C06CQPWEJSK), this is excluding potential candidates that we should keep.

**Expected behavior**
- The LCP must be selected as the largest image in terms of area visible in the viewport among all images in the viewport or intersecting it.

**Acceptance Criteria**
- Prepare a page with two images: ImageA (size: 200x200, fully in the viewport) and ImageB (size:300x300, only 300x1 visible in the viewport).
- Clear the cache and critical image data for this page.
- Visit this page.
- Check in the DB that the LCP is image A.

- Repeat with  ImageA (size: 200x200, fully in the viewport) and ImageB (size:300x300, only 300x250 visible in the viewport). Check in the DB that the LCP is image B.

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #6527 

This PR modifies the `lcp-beacon.js` file to change the way the Largest Contentful Paint (LCP) is calculated. The changes include creating a new function `isIntersecting(rect)` that checks if an image is intersecting the viewport and modifying the area computation to account only for the visible part of the image.

### User documentation

This change will improve the accuracy of the LCP calculation by considering images that intersect the viewport, not just those fully within it. This can lead to more accurate performance measurements and better user experience.

### Technical documentation

The `isIntersecting(rect)` function checks if an image is intersecting the viewport by comparing the top and left properties of the image's bounding rectangle with the viewport's dimensions. The area computation is modified to calculate the visible area of the image by taking the minimum of the image's dimensions and the viewport's dimensions minus the image's position.

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies
N/A

## Risks
N/A

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitly.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] I listed the introduced external dependencies explicitly on the PR.
- [x] I validated the repo-specific guidelines from CONTRIBUTING.md.

### CODE REVIEW

**Review by MathieuLamiot — APPROVED** [review]
Looks good.

**Comment by Mai-Saad** [comment]
Test Note:
- We have a test case here https://wpmediaqa.testrail.io/index.php?/cases/view/15358 
- related slack discussion https://wp-media.slack.com/archives/C070482U1TK/p1713903575198689
- we may need to add related templates in e2e if it wasn't there (desktop templates different than mobile for now)

**Comment by Miraeld** [comment]
@Mai-Saad Not sure why but I can't add any result on the test plan, 
But here you go:

### Step 1
Works perfectly. 

### Step 2
Works perfectly.

### Step 3
Works perfectly.

**Comment by Mai-Saad** [comment]
> @Mai-Saad Not sure why but I can't add any result on the test plan,

As that was just test case not inside test plan (as it's single test). Thanks for sharing the results :pray:

**Pull request merged**
