### PR TITLE
Revert delay js script to 3.9.4.1

### PR DESCRIPTION
**Pull request by iCaspar**
## Description

Per conversation with @GeekPress we're replacing the DelayJS script with the version from 14 July, plus the changes into the `page-visibility`.

## Type of change

- [X] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by engahmeds3ed — APPROVED** [review]

**Comment by iCaspar** [comment]
Turns out that the `page-visiblity` branch also included the bug from the "double-click fix".
In consultation with @piotrbak we're going to roll it back to exactly the same script as was in the 3.9.4.1 release here.

**Review by Mai-Saad — APPROVED** [review]
Working as expected, failed tests due to revert 
Notes:
1- Avada menu in  mobile view is not displayed till user interaction (same on the trunk, we need to GH that if not there) and it's clickable normally on newlabs test site
2- When testing Avada on mega, **the menu is not working** + image not displayed there even with user interaction (same on the trunk) ===> Adding exclusions mention [here](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions) , will fix the problem
3- When using Divi, only header displayed till user interaction => exclusions from doc fix that
4- Menu of Divi will need double click to work
[testrail-report-302.pdf](https://github.com/wp-media/wp-rocket/files/7516249/testrail-report-302.pdf)

**Comment by developerabdullah1** [comment]
Presto player not working with wp rocket. and video not showing on it. lot's of plguin list on this URL. https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions
Presto player is not list. I have try every possible way but it's still not working with wp rocket. could you please tell us. How to fix it

**Comment by piotrbak** [comment]
Hello @developerabdullah1 please reach to our Support Team and ask for help:
https://wp-rocket.me/support/

**Pull request merged**
