### PR TITLE
add delay js script after meta charset if exists

### LINKED ISSUE #4121: Charset declaration is missing or occurs too late in the HTML (in some cases)
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
On some occasions, Lighthouse & PageSpeed will show the following "Best Practice" notification: 

`Charset declaration is missing or occurs too late in the HTML`

**To Reproduce**
1. Enable Delay JavaScript Execution
2. Check a cached page source code
3. Run a test on Lighthouse with "Best Practices" enabled
4. See the error

From my testing, this will happen occasionally on some sites.

**Expected behavior**
Inject the IE fallback script after the meta tag defining the `charset` to prevent the recommendation from showing. 

**Screenshots**
image

**Additional context**
The notification is prompted because we add our IE fallback script (6300 bytes) right after the opening heading tag, which pushes the `<meta charset>` below the first 1024 bytes threshold. 

https://github.com/wp-media/wp-rocket/blob/4f86c478c74e962eb6361b59a0f0b575adab27a9/inc/Engine/Optimization/DelayJS/Subscriber.php#L98-L112

We could possibly run a check before defining the `$pattern`. If there is a meta tag defining the `charset`, it can be targeted with a pattern. 

`/<head[^>]*>/i` would be kept as a fallback in case there is no meta tag defining the `charset`.

Ticket - https://secure.helpscout.net/conversation/1551660251/273982/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by mostafa-hisham**
## Description
add delay js script after meta charset if exists

Fixes #4121 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] unit and integration test

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by piotrbak** [comment]
@mostafa-hisham I have some concerns here:
1. I think that we should also make sure that `<meta charset="UTF-8">` is in the <head> element. Right now, if HTML document doesn't have the charset defined in the head, but someone is writing a post and include it in the post content, we'll add our script in the post content:
image

2. That kind of markup is also acceptable:
```
<meta name="keywords" 
   charset="UTF-8"
   content="Hello!" />
```

3. That kind of markup too, but I think it's the same as above in terms of regex:
```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
```

4. I remember that it was a product decision to put this script at the very top od the head. If charset is defined in, for example, bottom of the head (which doesn't produce errors in HTML validator), we'll add our script there. @GeekPress Is that acceptable from your point of view?

**Comment by mostafa-hisham** [comment]
@piotrbak 
I updated the code to only find the correct meta charset tags
```
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
```
in `<head></head>` only and add the script after it if found

can you please check if it works ?

**Comment by piotrbak** [comment]
@mostafa-hisham When I add charset rule **above** the head, we're also adding our script there, outside the head.

I think this is an edge case and problem with HTML, not sure if we should handling this. Let's ask @Tabrisrp

**Comment by mostafa-hisham** [comment]
@piotrbak @Tabrisrp 
I think Regex is not the best solution to handle this issue, there are a lot of cases that need to be handled 
- Meta tag is above <head>
- a lot of lines between Meta tag and closing </head> tag

I did some research and most people use 
- [get_meta_tags()](https://www.php.net/manual/en/function.get-meta-tags.php) 
but it takes The path to the HTML file, as a string. This can be a local file or an URL. not HTML String
-  DOMdocument() & xpath

I will do more research maybe i find a better regex for it

**Review by piotrbak — CHANGES_REQUESTED** [review]
Unfortuantely, it doesn't work well.

1. When there's no `charset` definition in `head`, but it's present in the body, we'll take it and paste to the head.
2. When there's a `charset` definition in `head` and there's another one in the body, we'll move the one form head to the top and **erase** the second one

I believe, just like in the previous approach, that we should look for the meta charset only in the `<head></head>`

**Review by piotrbak — APPROVED** [review]
Seems that we're good here! 🎉 
[testrail-report-254.pdf](https://github.com/wp-media/wp-rocket/files/7137681/testrail-report-254.pdf)

**Pull request merged**
