### PR TITLE
update WP CS to 3.0

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Update the WordPress coding standards version to the new 3.0

## Type of change

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

No grooming

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).

### CODE REVIEW

**Review by engahmeds3ed — APPROVED** [review]
Awesome job

**Comment by MathieuLamiot** [comment]
@Tabrisrp Are we ok to merge this one for the next minor?
(cc @piotrbak @vmanthos)

**Comment by remyperona** [comment]
For me yes

**Comment by vmanthos** [comment]
@Tabrisrp It seems there are some conflicts with the `develop` after merging https://github.com/wp-media/wp-rocket/pull/6165.
Can you please check them? :pray:

**Comment by remyperona** [comment]
@vmanthos It's updated

**Review by vmanthos — APPROVED** [review]

**Pull request merged**
