### PR TITLE
Closes #7146: 3.18: Preconnect for Google fonts isnot removed when Host Google fonts locally option is enabled

### LINKED ISSUE #7146: 3.18: Preconnect for Google fonts isnot removed when Host Google fonts locally option is enabled
**Describe the bug**
While Host google fonts option is on, we shouldn't add preconnect/prefetch for Google fonts and if it was there , we shall remove it as mentioned here https://github.com/wp-media/wp-rocket/issues/7066. However, it is still there `<link href='https://fonts.gstatic.com/' crossorigin rel='preconnect' />`

**To Reproduce**
1. WPR 3.18-alpha1 installed and activated
2. Enable Host google fonts locally
3. Visit page with GFs  i.e https://new.rocketlabsqa.ovh/combine-v1-v2-fonts/
4. check page source => `<link href='https://fonts.gstatic.com/' crossorigin rel='preconnect' />` is there

**Expected behavior**
- When the feature is enabled, will remove all preconnect/prefetch links related to the Google Fonts
`fonts.gstatic.com` delivers the font files
`fonts.googleapis.com` delivers font CSS
- We'll introduce a filter to disable this behavior

**Screenshots**
Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #7146 
It'll remove the preconnect tag when google font hosting is ON and loaded from a local font. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Detailed scenario

Just follow the issue scenario.

### Documentation

This pull request involves a significant update to the pattern used for removing preconnect and prefetch links in the `remove_preconnect_and_prefetch` function within the `Controller.php` file. The main change is the adjustment of the regular expression pattern to improve its accuracy and efficiency.

Changes to the regular expression pattern:

* [`inc/Engine/Media/Fonts/Frontend/Controller.php`](diffhunk://#diff-3f1e418966792d4b51109c090fb00e9fe1ec75469559e0ce738d27d386e0f974L186-R186): Updated the regular expression pattern in the `remove_preconnect_and_prefetch` function to better match and remove preconnect and prefetch links. The new pattern is more precise in identifying the `rel` attribute and its values, ensuring that it correctly handles various whitespace and attribute order scenarios.
### New dependencies

None

### Risks

None

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

### CODE REVIEW

**Review by jeawhanlee — APPROVED** [review]

**Comment by hanna-meda** [comment]
Thank you, @Miraeld, for the PR.
Confirming that preconnect and prefetch links are now removed on PR, for Google Fonts while Host Google fonts locally option is enabled.
Screenshot 2024-12-02 at 18 47 58

**Review by wordpressfan — CHANGES_REQUESTED** [review]
@Miraeld I think this is risky to remove all `link` with `rel` equals `preconnect` or `dns-prefetch`, what do u think?
instead we may get the common pattern for the local fonts if that option is enabled, what do u think?

**Comment by jeawhanlee** [comment]
Good Catch

**Comment by Miraeld** [comment]
@wordpressfan , we could add the google font domain to make it less general. Haven't thought of that.

**Comment by hanna-meda** [comment]
@wordpressfan, thanks for pointing this out. You’re absolutely correct—it’s clear from the screenshot that all preconnect instances have been removed, whereas the first one should have been retained. Moving this back to “In Progress” as a result.
Screenshot 2024-12-03 at 14 03 50

**Comment by Miraeld** [comment]
@wordpressfan & @hanna-meda  regex has been changed to be far less general. :)

**Review by remyperona — APPROVED** [review]

**Review by hanna-meda — APPROVED** [review]
Thank you once again, @Miraeld, for this PR.
Everything looks good now: the `prefetch` and `preconnect` lines related to `fonts.gstatic` and `googleapi` are removed while unrelated `link rel="preconnect"` and `link rel="dns-prefetch"` entries remain intact.

**Pull request merged**
