### PR TITLE
Closes #4299 Delete term used CSS after editing

### LINKED ISSUE #4299: Used CSS is not cleared after editing a taxonomy
**Before submitting an issue please check that you’ve completed the following steps:**
YES - Made sure you’re on the latest version
YES - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We are not clearing the used css after editing a category, or product category.
If the category has, for example, description-related CSS, it won't be included since the element is new.
The customers will have to clear the used css to update it. The only way they have is to clear the whole Used CSS, This is problematic for big sites.

**To Reproduce**
1. Edit a Category description
2. Check the corresponding Used CSS Row, it won't be cleared

**Expected behavior**
Clear the specific Used Css of a taxonomy after it has been is updated
 
**Additional context**
Ticket: https://secure.helpscout.net/conversation/1602558912/287775/
The ticket contains a custom snippet that does the job of removing the used css for a specific taxonomy by hooking a wpdb request into `edit_term` (not very elegant, I know :) )

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
## Description

With this PR, we will delete the used CSS for a specific term after it has been edited.

Fixes #4299

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Unit/Integration tests

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by iCaspar — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Tabrisrp Currently we delete the Used CSS entry when editing category, however, 
1- if we added additional CSS in appearance -> customize -> additional CSS for this category (without any edits in category page) => used CSS won't be removed nor updated to the latest styles when visiting the category page even after manual cache clear, is this in the scope of PR? (in order to see the latest styles, we need to manually  clear used CSS)
2- when deleting a category while having an entry in used CSS, it is not removed from the used CSS table as same as post/page, shouldn't category entry be removed from the used CSS table once it is deleted?

**Comment by remyperona** [comment]
1. It's not in scope of this PR
2. It makes sense to add that yes, I added a new commit to handle it

**Comment by Mai-Saad** [comment]
Now deleted Category is deleted from used CSS table, however, if we have a parent category, editing/deleting parent category will only remove its entry from the used CSS table and will not affect child URLs, do we need to remove child URLs too?

**Comment by remyperona** [comment]
I don't think we need to

**Review by Mai-Saad — APPROVED** [review]
Working as expected then considering child taxonomy aren't affected by parent edit/delete
[testrail-report-298.pdf](https://github.com/wp-media/wp-rocket/files/7465811/testrail-report-298.pdf)

**Pull request merged**
