### PR TITLE
Multi tiers upgrade - part 2

### LINKED ISSUE #7177: Multi Tiers upgrade new structure - part 2 - UI in settings page
**Is your feature request related to a problem? Please describe.**
Part of this issue: https://github.com/wp-media/wp-rocket.me/issues/4326 we need to show the upgrades section in WP Rocket settings page based on the data passed from that issue #7176 

**Describe the solution you'd like**
Here we need to show the sections as it's now but depending on the data passed from #7176 with this new multi stacked items (inside select dropdown).

As initial state of this dropdown select box, we will show the first item details (name, price, and upgrade link on the CTA) and once we change the selected item, we will update (name, price, and upgrade link on the CTA) to reflect the selected item.

We will try to use the current UI, just change the source of data and add this select dropdown which will require some JS code changes.

**Additional context**
No

### PR DESCRIPTION
**Pull request by wordpressfan**
# Description

Fixes #7177

UI changes for upgrade Multi tiers.

## Type of change

- [x] New feature (non-breaking change which adds functionality).

## Detailed scenario

Everything is mentioned in the issue.

### Documentation

We added custom-select new stylying/scripts to be exactly as in the website.

### New dependencies

No

### Risks

No

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification

*If some mandatory items are not relevant, explain why in this section.*

# Additional Checks
- [x] In the case of complex code, I wrote comments to explain it.
- [x] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [x] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

**Comment by wordpressfan** [comment]
@marija-nikolic attaching here how it looks like, please note that I mocked the prices and just added a few license types just for testing, so here we need a feedback on just the UI plz.

Without active promo campaign:
https://github.com/user-attachments/assets/11624c6f-75c6-4fcc-84aa-b4ddfd528d06

With active promo campaign:
https://github.com/user-attachments/assets/3396f180-2c67-4f2e-8df9-8ad260f33a51

Let me know if u see any UI issue that needs to be fixed.
Thanks.

**Comment by marija-nikolic** [comment]
> @marija-nikolic attaching here how it looks like, please note that I mocked the prices and just added a few license types just for testing, so here we need a feedback on just the UI plz.
> 
> Without active promo campaign: https://github.com/user-attachments/assets/11624c6f-75c6-4fcc-84aa-b4ddfd528d06
> 
> With active promo campaign: https://github.com/user-attachments/assets/3396f180-2c67-4f2e-8df9-8ad260f33a51
> 
> Let me know if u see any UI issue that needs to be fixed. Thanks.

Thank you! 
We should re-use the popup we have right now in the plugin and just edit the name/price/URL + add dropdown on Multi.

Screenshot of the current pop-up (for Single license):
image

For dropdown, you can do the same Nicolas did for the account page:
image

The dropdown should be narrower than the CTA, with a gray border around it (same line width and color as the large square).
image

**Comment by marija-nikolic** [comment]
@wordpressfan Here is how open dropdown looks like:

image

**Comment by wordpressfan** [comment]
Adjusted all the points mentioned above:

**Without active promo campaign:**

https://github.com/user-attachments/assets/b6c03a0d-ee7c-43b4-99c9-20dcafa087a6

**With active promo campaign:**


https://github.com/user-attachments/assets/a2efb2a8-9755-44f3-aff8-14628274002a

**Comment by marija-nikolic** [comment]
> Adjusted all the points mentioned above:
> 
> **Without active promo campaign:**
> 
>  multi-tiers-part2-marija-v2-2024-12-19_02.53.23.mp4 
> **With active promo campaign:**
> 
>  multi-tiers-part2-marija-v2-promo-2024-12-19_02.55.08.mp4


Hi, thank you! 

- Could you please ensure that the Growth and Multi boxes are the same height? It also looks like the alignment of the dropdown and CTA buttons could be slightly adjusted.

image

- Also Growth plan should be 10 websites, and in dropdown we should have 50/100/500 websites
See the screenshot from the account page:
image

- Please adjust the space at the bottom of the dropdown and the text in the dropdown shouldn't be bolded (see the 2nd screenshot)- you can copy what we have on the account page
image
image

**Comment by marija-nikolic** [comment]
Same for the design with active promo banner, plus I noticed that dropdown is wider then it should be:

image

**Comment by wordpressfan** [comment]
> Could you please ensure that the Growth and Multi boxes are the same height? It also looks like the alignment of the dropdown and CTA buttons could be slightly adjusted.

Both have the same height now:
Screenshot from 2024-12-19 09-47-55

The alignment with buttons are already in the center, I zoomed on them to show u.

image

> Also Growth plan should be 10 websites, and in dropdown we should have 50/100/500 websites

As I mentioned above, it's all about the UI because I mocked the data for now, once getting the UI approved, we will get the real data from the API with the real numbers.

> Please adjust the space at the bottom of the dropdown and the text in the dropdown shouldn't be bolded (see the 2nd screenshot)- you can copy what we have on the account page

image

I'm checking now the last point

**Comment by wordpressfan** [comment]
Screencast after latest changes:


https://github.com/user-attachments/assets/90f98fca-4420-43af-93de-bdd916c03117

**Comment by marija-nikolic** [comment]
Thank you very much @wordpressfan 

Please make sure that the open dropdown menu is not wider:
image


It seems the boxes are nearly square. Could you please check the height-to-width ratio and adjust it to match what we had before or use the ones on the account page as a reference?
image

**Comment by wordpressfan** [comment]
What do u think about that?

image

and 

image

**Comment by marija-nikolic** [comment]
> What do u think about that?
> 
> image
> 
> and
> 
> image

Thank you! Great! If you could just put them a bit closer, like it's on the current pop up:
image

image

**Comment by wordpressfan** [comment]
I'm going to merge this one and prepare the main feature PR description as @marija-nikolic approved the current screenshots/screencasts.

**Pull request merged**
