### PR TITLE
Fixes #2804 Remove "disabled" attribute on Email address and API key fields

### LINKED ISSUE #2804: License validation sometimes fails when moving domains/creating staging sites
When creating a staging site or moving the site to a new domain, in many cases, a "Search & replace" is performed to replace the original domain, e.g. **domainA.com** with the new domain, e.g. **domainB.com**.

Since WP Rocket saves the WP Rocket's account email in the database, if the owner has an email like `user@domainA.com`, that will become `user@domainB.com`, and the license validation will fail.

The issue can be fixed by adding the license's info in the `wp-config.php`:
```PHP
define( 'WP_ROCKET_EMAIL', 'ACCOUNT_EMAIL');
define( 'WP_ROCKET_KEY', 'API_KEY');
```

**To Reproduce**
1. Create a site domainA.com.
2. Change its domain to domainB.com.
3. Perform a "Search & Replace" in the database to replace domainA.com with domainB.com.
4. Try to activate WP Rocket.

**Additional context**
WP Engine's staging creation mechanism seems to be doing the database replacement.

**Tickets:**
* https://secure.helpscout.net/conversation/1197140885/173483
* https://secure.helpscout.net/conversation/1194749805/172788/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by GeekPress**
Close #2804

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by piotrbak** [comment]
@Tabrisrp I have some questions/concerns:
1. If the User/API is defined (and changed) in the wp-config.php, we won't be able to overwrite it anyway.
2. I'm not able to use this field correctly, it doesn't let me through when passing the correct data. `license-data.php` and `wp-config.php` definitions work just fine. Steps to reproduce:
- Validate your WP Rocket instance on the site
- Go to the Database Manager and modify `wp_rocket_settings` from the `wp_options`. Change your email to another one.
- Refresh WP Rocket dashboard, you should be redirected to the License Validation page
- Fill in the correct API data and Validate License
- I'm staying on the same screen with the following error:
`License validation failed. Our server could not resolve the request from your website.`
3. Do you think it's worth enabling the API field at all?

**Comment by remyperona** [comment]
For 1), it's true but the issue also should not happen in that case, as those values in wp-config.php would not be modified during staging.

For 2), I pushed a code update to fix that

For 3), I'm thinking this change would also help us close #2456, what do you think?

**Comment by piotrbak** [comment]
@Tabrisrp Here's what I did and it's not working as expected:
- Installed a site as `wp-media.me` using HOSTS file
- Used my license `piotr@wp-media.me`
- Changed the domain to `wp-medias.me`
- Local by Flywheel seems to be looking for `http://wp-media.me` when replacing, so I needed to run Search and Replace
- Did a search and replace
- WP Rocket licensing page is displayed with the `piotr@wp-medias.me`
- I'm changing it to the correct `piotr@wp-media.me` and validating the license
- Page reloads with the wrong `piotr@wp-medias.me`
- Tried a couple of times
Seems that the database has priority over the fields and the fields are not updating the DB.

Regarding 3. I think that customers will be still reaching our support to learn the API key. The difference is that they'll use fields instead of `wp-config.php`. What do you think?

**Comment by remyperona** [comment]
Yeah, this issue is more complicated than expected to handle. I propose to put it back on the burner for now, and come back with a more robust approach.

**Comment by remyperona** [comment]
@piotrbak Do we want to work on this in the future or close it?

**Comment by piotrbak** [comment]
I think that the PR can be closed, we might look for a different approach at some point

**Pull request closed without merging**
