### PR TITLE
Closes #3069 Promotions in the plugin

### LINKED ISSUE #3069: Display promotions in the plugin
## What are we proposing to do? 

With this enhancement, we will notify single and plus users directly in the plugin when there is a promotion going. They will be able to upgrade their license with the discounted price by clicking a link on the WP Rocket dashboard. They will be redirected to our checkout page. No payment will proceed from the customer website directly.

<p></p>

More info:  
<https://docs.google.com/document/d/1TtENtXMzyUoUbBCiYuHfcfuxKp5WThe1NJVY9L86aNI/edit#heading=h.dz9zk3oob6p1>

<p></p>

### PR DESCRIPTION
**Pull request by Tabrisrp**
Closes #3069 

Display promotions directly in the plugin for single and plus licenses.

### Acceptance criteria
In case we have a promotion going, we will display:
- A notification bubble next to WP Rocket in the WordPress admin panel. This bubble will be dismissed once people have accessed their dashboard once (uses a 2 weeks transient, based on the user ID)
- A dismissible notice on the dashboard tab (the dismiss uses a 2 weeks transient, based on the user ID)

#### Promotion banner
- Displayed only if the license expires in more than 30 days
- Doesnt't display for whitelabel users
- Text changes slightly depending on if the license is single or plus (for the upgrade choices)
- The countdown is dynamic, based on the end date of the promotion

#### Upgrade popin
When a promotion is running:
- An additional "savings" block is displayed
- The regular price is displayed, next to the promotion price, smaller and striked

### CODE REVIEW

**Comment by piotrbak** [comment]
@Tabrisrp What about whitelabeled customers?

**Comment by Tabrisrp** [comment]
Yes you're right I forgot it, the promo doesn't show for whitelabel

**Comment by piotrbak** [comment]
@Tabrisrp Do we have any promotion set right now? The banner doesn't seem to be outputted...

If not, can we have a possibility to set it up or simulate it somehow in a reliable way?

**Comment by piotrbak** [comment]
@Tabrisrp During the QA I noticed a JS error. Steps to reproduce:
1. Visit the dashboard page with a promo banner displayed
2. Close the banner
3. Refresh the page

Screencast:
https://jmp.sh/NVr8FIU

Error itself:
https://snippi.com/s/emxuab6

Pointing here:
`e.querySelector(".rocket-countdown-days")`

**Comment by piotrbak** [comment]
@Tabrisrp Things worked as expected, you can see my comments below, I don't think those are blockers:
- HTML of the upgrade banner is present in the HTML when using the `Whitelabel` or expired licenses. We're exposing the emails and API keys in the source then.
- In the `wpr-admin.js` we're using forEach, so some parts of the dashboard might not work on IE11. Everything related to this branch seems to be just fine. Case similar to this one https://github.com/wp-media/wp-rocket/issues/3140

Comment:
We should remember about clearing the license transient when upgrading. The promo + the below issue scenario wasn't tested:
https://wp-media.slack.com/archives/C43T1AYMQ/p1602769059213100

**Review by piotrbak — APPROVED** [review]
Worked as expected. Tested cases are present in the report:
[testrail-report-46.pdf](https://github.com/wp-media/wp-rocket/files/5404059/testrail-report-46.pdf)

**Pull request merged**
