### PR TITLE
Improve (no glob) and add tests for rocket_clean_files().

### PR DESCRIPTION
**Pull request by hellofromtonya**
This PR does the following for `rocket_clean_files()`:

- replaces `glob()` with SPL
- improves the function for speed and memory usage
- adds unit and integration tests

Multiple cleaning functions will use the same iterator patterns. To reduce redundancy and increase reuse, this PR:

- moves the iterators to private internal functions
- updates `rocket_clean_domain()` to use the private functions

These private functions will become private methods when refactor and rearchitect.

## TODO

- [x] Validate current behavior with test data
- [x] Add unit and integration tests
- [x] Replace `glob`
- [x] Optimize
- [x] Move redundant code to reusable private/internal functions for reuse
- [ ] QA

### CODE REVIEW

**Comment by hellofromtonya** [comment]
@wp-media/dev-qa This PR is ready for QA. Please make sure that `rocket_clean_files()` and `rocket_clean_domain()` still work as they did before, i.e. there should no change to its behavior.

**Comment by hellofromtonya** [comment]
>🐛 However, when I call rocket_clean_domain() directly via functions.php, then all the folders in the wp-content/cache folder is deleted. This isn't right because other plugins can use the same folder and we shouldn't be deleting them. Seems like a bug.

@arunbasillal Can you share the code of how you called `rocket_clean_domain()` directly in the theme's `functions.php`? Was it within a callback or just in the root of the file? And do you have any i18n plugins installed?

**Comment by vmanthos** [comment]
@hellofromtonya 

I had a similar case, which I asked about in the Level 2 channel:
https://wp-media.slack.com/archives/C43T1AYMQ/p1587554387007900

**Comment by hellofromtonya** [comment]
I think the problem is not in `rocket_clean_domain()`, but rather, it's in a callback hooked into `'before_rocket_clean_domain'` which is fired in `rocket_clean_domain()`.  

@arunbasillal to confirm, please do the following:

- comment out line of code https://github.com/wp-media/wp-rocket/blob/improve/rocket_clean_files/inc/functions/files.php#L853
- then re-run your test with `rocket_clean_domain()` in your theme's `functions.php`

**Comment by hellofromtonya** [comment]
@piotrbak This PR is ready for QA.

**Comment by piotrbak** [comment]
Starting the QA

**Comment by hellofromtonya** [comment]
>However, there's one thing to consider @hellofromtonya. When passing URLs to the rocket_clean_files, we are purging everything recursively. 

Yes, this is correct. It cleans all of the files from what is given. As you note below, this PRs behavior matches current and release release’s behavior.

>If we pass the homepage, whole cache will be cleared, if we pass the taxonomy terms URL, all posts from this category will be cleared (if using default pretty permalink setup- example.com/category/post). This was also happening in the previous versions. It's similar situation to this one: #2549

@piotrbak Let’s pull the discussion either into Slack or an issue. It’ll be good to discuss.

**Pull request merged**
