### PR TITLE
3.13 Tweaks

### LINKED ISSUE #5823: 3.13 / Refactor Delay JS tweaks
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version  => 3.13_alpha1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
While exploratory testing, test execution and team discussion, We see that those points needs to be handled before the release

- [x] Rollback version needs to be updated to 3.12.6.1
- [x] Bump minimal WordPress version to 5.8
- [x] Lists should be sorted alphabetically
- [x] Checked exclusion still applied even after disable related plugin/theme

**To Reproduce**
For Checked exclusion still applied even after disable related plugin
1- check ninja form in DJS and save => jquery is excluded from DJS
2- deactivate ninja plugin
3- clear cache and check home page => jquery still excluded from DJS (if we re-enabled DJS , jquery won't be excluded)

**Expected behavior**
Exclusions of deactivated plugin/theme isnot applied

**Additional context**
Reference sheet https://docs.google.com/spreadsheets/d/1AhroWjZKXEpqtIWJdFIcBcvpeE961Gw-LM20wh8GxqA/edit#gid=0

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
## Description

Please include a summary of the change and which issue is fixed/closed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #5823

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

Please describe in this section if there is any change to the solution, and why.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by piotrbak** [comment]
@engahmeds3ed This is the wording that should be used:
- 3rd parties exclusions
- When using this feature you may notice that it takes some time, or user interaction for specific elements, e.g. a menu, or a form that is located in the viewport, to appear.
Select plugins, themes or services you'd like to exclude from being delayed.

**Comment by piotrbak** [comment]
Also, @wp-media/php, whenever @wp-media/qa accepts the changes, please go ahead and merge this PR and release the second alpha.

**Comment by vmanthos** [comment]
@engahmeds3ed With this PR `is_default` items aren't selected when activating the plugin after a clean install.
Can you please look into this?

**Review by CrochetFeve0251 — APPROVED** [review]

**Comment by Presskopp** [comment]
Looks like there's something missing in the phrase:
_When using this feature you may notice that it takes some time, or user interaction for specific elements, e.g. a menu, or a form that is located in the viewport, to appear._
gramatically.

Sorry need to correct myself: After posting I now get how it's meant. Could be a bit clearer, though.

**Pull request merged**
