### PR TITLE
Update CF APO compatiblity

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Use CF plugin class methods directly to manage purge everything and partial purge instead of using their hooks that don't work. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vmanthos** [comment]
@Tabrisrp I checked cache clearing and currently everything works except for:
* Clearing a URL's cache after the used CSS has been generated for it
* Clearing a URL's cache when using the "Clear Used CSS of this URL" admin bar menu item
* Clearing the cache of date archives
* With WPML, clearing the cache of a specific language clears the whole cache on Cloudflare. This is happening both when the main language is in its directory, and when it's not
* Cache Lifespan - we won't be handling this one according to @piotrbak 

Can you please look into these? :pray:

**Comment by piotrbak** [comment]
@vmanthos for the WPML it's okay for the initial release. Lifespan is expected to happen like this.

@Tabrisrp It would be great to fix the first two points, the third one only if we have enough time. The third (an most likely the last alpha would be released today in the afternoon/evening)

**Comment by vmanthos** [comment]
@piotrbak For WPML, @Mai-Saad reminded me of issue #5590. That's likely the reason for what I reported and it's not specific to this PR.

**Comment by piotrbak** [comment]
@vmanthos Well, looks like we are synced with cache then ;)

**Comment by remyperona** [comment]
I added purge after used CSS generation and clean.

The CF plugin doesn't have a public method to clean cache based on an URL value, only from post ID, so anything that is not a post type is not going to be cleaned currently. Maybe we can create an issue on their repo so they add a public method for that?

**Review by vmanthos — APPROVED** [review]
Thank you for the fixes, @Tabrisrp! :pray: 

The cache is cleared in both cases related to Remove Unused CSS.

We are good to go with this. :+1: 

**NOTE**

When WPML was enabled, clearing the used CSS for a URL wasn't clearing the cache on Cloudflare APO while our cache was cleared.

This requires further investigation.

**Review by CrochetFeve0251 — APPROVED** [review]

**Review by engahmeds3ed — APPROVED** [review]

**Pull request merged**
