### PR TITLE
Fixes #3083 Update delay JS RegEx to ignore space inside script tags

### LINKED ISSUE #3083: Delay JS - RegEx error when there are spaces in the </script> tag
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When there are spaces in the `</script>` tag, like `</script >` the RegEx in `preg_replace_callback()`:
```PHP
return preg_replace_callback( '/<script\s*(?<attr>[^>]*)?>(?<content>.*)?<\/script>/Uis', [ $this, 'replace_scripts' ], $html );
```
 will select the content until the next script tag, that doesn't have spaces.

If in that content there are scripts from our default delay JavaScript list, the whole content will be replaced, and the page can break.

You can see the RegEx issue here: [https://regex101.com/r/hZiXud/1/](https://regex101.com/r/hZiXud/1/)

**To Reproduce**

1. Add the following code on a page: http://snippi.com/raw/2uaob82
2. Enable **Delay JS**
3. Check the source code of the cached page for one of the classes in the snippet, e.g. `#thrive`
4. The code will not be there

**Expected behavior**

Properly pick up the closing script tag regardless of whether it includes spaces or not.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1277671782/193430?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by vmanthos**
## Description

I've updated the RegEx to ignore spaces either in the opening or closing `script` tag.

Fixes #3083.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

Yes, it is. I've added extra checks for spaces in the opening `<script>` tag, as well as the closing tag, to cover all cases.

## How Has This Been Tested?

A test run against the breaking sample:
https://regex101.com/r/hZiXud/1/

Which is working fine with the new RegEx: https://regex101.com/r/5RWVBd/1

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Review by Mai-Saad — COMMENTED** [review]
@vmanthos @Tabrisrp I have a couple of questions/notes:
1- Shall we support nested script? (In case application/xhtml+xml) -> currently we don't
2- What about the case of having > inside the string attribute? shouldn't we ignore it?
3- Spaces before script tag (opening "here script considered as content" or closure "js error exist") will result in a problem without cache `?nocache`  {This is same behavior with defer js and combine js but not delay js } Currently we are ignoring those cases with delay js which makes sense but on the other hand, it changes the behavior of browser if no cache.... is this fine?

**Comment by remyperona** [comment]
1) Nested scripts should not be supported, they are not valid
2) Probably an edge case, but we might be able to update the RegEx to `<\s*script\s*(?<attr>.*)?>(?<content>.*)?<\s*\/\s*script\s*>` to avoid that
3) Yes it's fine

**Comment by remyperona** [comment]
@Mai-Saad Pattern is updated, case 2 should pass now

**Comment by Mai-Saad** [comment]
@Tabrisrp #2 still consider > inside attribute string as the end of the attribute itself
Screenshot from 2021-02-24 08-27-02

**Comment by remyperona** [comment]
@Mai-Saad Sorry about that, I did another update that should work now

**Review by Mai-Saad — APPROVED** [review]
Since ignoring space before script tag is fine then this PR works as expected.
Note: we won't handle ">" inside attribute

**Pull request merged**
