### PR TITLE
Enhancement/5736 disable concat on rucss

### LINKED ISSUE #5736: Broken layout caused by Themify Ultra performance optimization and RUCSS
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 3.12.5.2
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The Themify Ultra theme has a file performance optimizations built in. The _Concate CSS_ optimization in the theme does the same thing as _Combine CSS files_ in WP Rocket.

When this optimization is used with Remove Unused CSS, it causes broken layout on the front-end, and safe listing CSS doesn't resolve the issue.

The only solution is to disable Concate CSS in Themify theme settings https://i.imgur.com/0sz5zCc.png

**To Reproduce**
1. Install Themify Ultra theme. The _Concate CSS_ optimization is enabled by default in theme settings.
2. Enable Remove Unused CSS, and check the broken layout after Used CSS is generated

**Expected behavior**
The _Concate CSS_ optimization in Themify Ultra theme should be disabled when Remove Unused CSS is enabled.

**Screenshots**
The _Concate CSS_ optimization in the theme [https://i.imgur.com/cyEU0OI.png](https://i.imgur.com/cyEU0OI.png).

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Fixed an issue with concat CSS from themify that conflicts with RUCSS.

For that we used a thirdparty class to disable that option when RUCSS is enabled.

Fixes #5736 

## Type of change

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?
It was different has the principal solution wasn't working but the idea stays the same.

## How Has This Been Tested?

- [ ] Test locally
- [ ] Automated Test 

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@CrochetFeve0251 I checked the PR. Themify's concatenation is disabled when Remove Unused CSS is enabled. This is for both desktop/mobile devices.

However, disabling our feature doesn't re-enable their concatenation according to the acceptance criterium no 2:
https://github.com/wp-media/wp-rocket/issues/5736#issuecomment-1519043276

Also, although we enable the DEV mode the respective option in _Themify Settings > Performance_ isn't checked. When checking it, **Disable Concate CSS** is checked as requested in the acceptance criteria.

Can you please look into these?

On a side note, maybe [this check](https://github.com/wp-media/wp-rocket/blob/5e784c8b7ab3b550b1f4bdab21909b8e5f617d11/inc/ThirdParty/Themes/Themify.php#L71-L73) should be moved before `$data = themify_get_data();`.

**Comment by vmanthos** [comment]
@CrochetFeve0251 

> Disabling our feature doesn't re-enable their concatenation.

This :point_up: was resolved. :pray: 

However:

1. The development mode in their settings isn't checked despite being enabled.
2. Even when Optimize CSS Delivery is disabled, it's now impossible to save the development mode and the CSS concatenation. Both of them remain unchecked, and so concatenation is applied, after manually enabling them. This isn't happening with `trunk`.

Can you please look into these? :pray:

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@CrochetFeve0251 After the latest commits, while "Dev Mode" seems to be enabled, if checking the admin bar, it actually isn't. This is reflected in Themify's settings and on the front end where the concatenated Themify CSS file is loaded.

Only after saving Themify's settings the "Dev mode" (without checking the respective checkboxes) is actually enabled.

Can you please look into this?

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
Thank you for the fixes, @CrochetFeve0251 ! :pray: 

Now everything is working as expected.

One last thing. Remove Unused CSS won't be cleared automatically after updating the plugin to the version with this fix. Is it something we need to do @piotrbak?

**Comment by piotrbak** [comment]
@vmanthos That's an acceptable thing. It doesn't make sense to add that kind of condition to the codebase, I believe. 

Thank you, Sir 🙏

**Review by vmanthos — APPROVED** [review]

**Pull request merged**
