### PR TITLE
Fixes #7102 Warning related to translations in WordPress 6.7

### LINKED ISSUE #7102: WordPress 6.7 Compatibility - Translations loading too early
**Describe the bug**

"Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the rocket domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. (This message was added in version 6.7.0.)"

As per the notice on WP 6.7.0, translations are being loaded too early and should be moved to another (init or later) hook.

### PR DESCRIPTION
**Pull request by remyperona**
# Description

Fixes #7102 

A change in WordPress 6.7 is warning when translations functions are used too early. This PR fixes the doing it wrong warnings in the plugin.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Detailed scenario

With WordPress 6.7 and WP Rocket 3.17.2, using query monitor to see it easily.

There should be doing it wrong warnings when loading pages in the admin. (also available in debug log)

With this PR, no doing it wrong warnings should happen.

### Documentation

This change delays the usage of translations functions to later, and also update the hook used to load the plugin textdomain, from `plugins_loaded` to `init`.

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.

### CODE REVIEW

**Review by jeawhanlee — APPROVED** [review]

**Comment by Mai-Saad** [comment]
Reproducible steps:
1- WP 6.7
2- Query monitor is installed
3- install and activate wpr 3.17.2.1 => notice query monitor displays `Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the rocket domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. (This message was added in version 6.7.0.)` 
in debug.log
`[14-Nov-2024 14:14:12 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>rocket</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/functions.php on line 6114`

**Comment by Mai-Saad** [comment]
@remyperona Thanks for the PR.
- The "doing it wrong" is not there now in query monitor
- But the text when updating the dynamic list is changed, is that intended?
Screenshot from 2024-11-14 15-38-09

**Comment by Mai-Saad** [comment]
@remyperona Thanks for the update, the dynamic lists text is displayed correctly now.
Notes:
- dynamic list update FR translation is not displayed on PR
Screenshot from 2024-11-15 08-26-16

- Using 3.17.2.1 with query monitor and having the doing wrong text at query monitor, after we update to the PR , the Doing wrong in query monitor will still be there till we manually refresh the page

/cc @piotrbak if nothing is needed for those notes then we can merge the PR.
[testrail-report-661.pdf](https://github.com/user-attachments/files/17772512/testrail-report-661.pdf)

**Comment by piotrbak** [comment]
@remyperona Is the problem with lack of FR translation fixed? Or it's not fixable for now?

**Comment by remyperona** [comment]
yes it's all good now

**Comment by Mai-Saad** [comment]
@remyperona Thanks for the update.
Now translations of the dynamic list update text are there only if `script_debug` is true, o.w translations won't be reflected.

**Review by Mai-Saad — APPROVED** [review]
translations are good now with script_debug

**Comment by ethanclevenger91** [comment]
@Mai-Saad did this go out in a release yet? I don't see anything definitive in the release notes.

**Pull request merged**
