### PR TITLE
Closes #3264 Optimize Google Fonts using the v2 API update

### LINKED ISSUE #3264: Issue when Google fonts using different APIs are combined
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Google fonts API v2 has introduced a new syntax and the main detail causing the issue on our end is that they now use semicolons to separate style instead of comas.

V1 - https://fonts.googleapis.com/css?family=Poppins:wght@100,200,300,400,500,600,700,800,900
V2 - https://fonts.googleapis.com/css2?family=Poppins:100;200;300;400;500;600;700;800;900

What happens is that if both APIs are used, our combined Google fonts is delivering the V2 fonts in a way that is not compatible with V1 (which is the one we use when delivering combined fonts).

https://fonts.googleapis.com/css?family=Lato:wght@100;300;400;700;900|Poppins:wght@100;200;300;400;500;600;700;800;900|Merriweather:400,700,900,400italic,700italic,900italic|Montserrat:400,700|Inconsolata:400&subset=latin,latin-ext&display=swap

As a result, in the combined file above, we have a lot of Lato and Poppins styles not loading.

**To Reproduce**
1. Add Google fonts using V1 and V2 APIs
2. Use the Google fonts optimization feature
3. See the error on the combined file

**Expected behavior**
We need a way to normalize fonts to use one API version before combining them.
Or we need to set a combined file per API version.

**Screenshots**
N/A

**Additional context**
APIs documentation: 
- V1 - https://developers.google.com/fonts/docs/getting_started
- V2 - https://developers.google.com/fonts/docs/css2

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by crystinutzaa**
Closes #3264

With this PR, we introduce a new class to handle the v2 API format for Google fonts URLs.

The optimization is now done separately for v1 and v2 URLs found on the page, to ensure everything works correctly.

A page using URLs from both versions will see 2 google fonts URLS.

### Acceptance criteria
- Google fonts URLs using the v2 are correctly combined together
- Google fonts URLs using the v1 are correctly combined together
- v1 and v2 URLs are not mixed together in the same URLs. If both are present on a page, 2 combined URLs are created, one for each version

### CODE REVIEW

**Comment by crystinutzaa** [comment]
@wp-media/php Team, anyone can check why this test fails only in legacy?
It seems fragile test in here and I am afraid if I fix it, will break other tests. It's strange because other PRs are working fine and there are no failures on legacy test:

```
1) WP_Rocket\Tests\Integration\inc\common\Test_RocketGetPurgeUrls::testShouldReturnUrls with data set "shouldReturnPostUrls" (array(array(20, false), array(1, 'test', '/test/', 'post', 2, 1, array(3, 4))), array('http://example.org/test/', 'http://example.org/blog/', 'http://example.org/next_post/', 'http://example.org/author/author_name/', 'http://example.org/test_parent/', 'http://example.org/test_parent_2/'))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     1 => 'http://example.org/blog/'
     2 => 'http://example.org/next_post/'
     3 => 'http://example.org/test/'
-    4 => 'http://example.org/test_parent/'
-    5 => 'http://example.org/test_parent_2/'
+    4 => 'http://example.org/test3/'
+    5 => 'http://example.org/test_parent/'
+    6 => 'http://example.org/test_parent_2/'
 )

Error: /home/runner/work/wp-rocket/wp-rocket/tests/Integration/inc/common/rocketGetPurgeUrls.php:82
```

**Comment by engahmeds3ed** [comment]
@crystinutzaa I saw this error before and I solved it by rerun the job again so I thought it's something not related to the code.
I re-ran this job to check.

**Review by remyperona — APPROVED** [review]

**Comment by Tabrisrp** [comment]
@wp-media/qa ready for QA

**Comment by piotrbak** [comment]
@Tabrisrp @crystinutzaa There is one thing in the `v2` combined output. We're adding `&` `#038;` instead of just `&`. It doesn't seem to be causing any negative effects, but I thought you should know about this.

`https://fonts.googleapis.com/css2?family=Goldman:wght@400;700&#038;family=Xanh+Mono:ital@0;1&#038;family=Markazi+Text:wght@450&#038;family=Raleway:wght@600;700&#038;family=Noto+Serif+JP:wght@400;700&#038;display=swap`

image

All the tests passed:
[testrail-report-80.pdf](https://github.com/wp-media/wp-rocket/files/5608551/testrail-report-80.pdf)

**Comment by Tabrisrp** [comment]
That's normal, it's the generated output by `esc_url()`

**Review by piotrbak — APPROVED** [review]

**Pull request merged**
