### PR TITLE
Use backend conditions for themes and plugins as is without lowercasing them.

### LINKED ISSUE #5915: Dynamic lists one-click list to check the same case to populate the UI
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.13.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When WP Rocket builds the one-click DJE exclusions, we are testing a `lowercase` `$plugin->condition` entry without making sure the array `$active_plugins` contains only lowercase items as well.

```
foreach ( $this->get_plugins_from_list() as $plugin_key => $plugin ) {
	if ( ! in_array( strtolower( $plugin->condition ), $active_plugins, true ) ) {
		continue;
	}

	$full_list['plugins']['items'][] = [
		'id'    => $plugin_key,
		'title' => $plugin->title,
		'icon'  => $this->get_icon( $plugin ),
	];
}
```

We do that here: 

https://github.com/wp-media/wp-rocket/blob/408433f0e4615b6226711cd9d91df2228d70cf2e/inc/Engine/Optimization/DelayJS/Admin/SiteList.php#L223

And here:

https://github.com/wp-media/wp-rocket/blob/408433f0e4615b6226711cd9d91df2228d70cf2e/inc/Engine/Optimization/DelayJS/Admin/SiteList.php#L509

This causes plugins with capital names to not match `in_array` against `$active_plugins`. 

Like `Ultimate_VC_Addons/Ultimate_VC_Addons.php`

We can either drop `strtolower` from `strtolower( $plugin->condition )` or make sure `$active_plugins` has all lowercase items by wrapping it inside `array_map('strtolower', $active_plugins)`. 

Will leave it to QA to decide the best approach. 

**To Reproduce**
1. Use a plugins with a capital name as part of its folder/main file.
2. Use DJE and make sure it's part of the dynamic lists.
3. See that the plugin won't show up on the one-click exclusions UI.

**Expected behavior**
We should reflect accurately the activated plugins on the website.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2231417008/417832?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
## Description

For plugins and theme names we used to make them all lowercase (the local names and the names that we get from backend) but with this change we will remove this and compare them with backend as is so it'll be case sensitive.

Fixes #5915

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking change which improves an existing functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

Please describe in this section if there is any change to the solution, and why.

## How Has This Been Tested?

Tested locally

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by piotrbak** [comment]
AC for QA:
1. Plugin conditions in the backend will be case sensitive starting from now, possibility to add condition with capital letter
2. No regression for regular, lowercase conditions

**Comment by piotrbak** [comment]
@engahmeds3ed Could you recheck if it's ready for review?

**Comment by engahmeds3ed** [comment]
@piotrbak yes it's ready for review.

**Review by remyperona — APPROVED** [review]

**Review by vmanthos — APPROVED** [review]
Working as expected! :+1: 

**NOTE**
Detection of themes/plugins will not work correctly if there are mismatches in the case used by themes/plugins, and the way those have been added in the back end.

**Pull request merged**
