### PR TITLE
Closes #5021 on incorrect  AS missing table notice

### LINKED ISSUE #5021: Action Scheduler missing tables notice may show up incorrectly
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ 
- Used the search feature to ensure that the bug hasn’t been reported before ✅ 

**Describe the bug**
The [missing action scheduler warning](https://github.com/wp-media/wp-rocket/blob/d6ac32fa837a6446ae788fe6c9640a0d5cf39928/inc/Engine/Optimization/RUCSS/Admin/Settings.php#L291) is showing up persistently on a customer's site. 

The tables are in fact in the database, but there are also duplicates (source unknown), which seem to trigger the warning:
https://jmp.sh/coWsNUk
(I have removed the db prefix)

**To Reproduce**
1. Activate WP Rocket
2. Create duplicate action scheduler tables
3. See error message

**Expected behavior**
WP Rocket should only show the warning when the required tables are really not there. 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1869443219/340827?folderId=377611

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

This PR fixes the incorrect display of missing AS tables.

Fixes #5021 

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality)

## How Has This Been Tested?

Automated & Manual Tests.

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by remyperona — COMMENTED** [review]
What happens here if the table prefix contains a number?

**Comment by jeawhanlee** [comment]
> What happens here if the table prefix contains a number?

I think this expression is meant to check if the table ends with a number `[0-9]+$`

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@jeawhanlee can still see the error if the duplicated table does not contain a number i.e `copy_wp_actionscheduler_actions` (adding a number at the end will work). can you please check?

**Comment by jeawhanlee** [comment]
@Mai-Saad Pushed a fix, please check again 🙏

**Comment by Mai-Saad** [comment]
@jeawhanlee thanks for the update. 
Can still see the error if copied table ends with number or special char i.e `wp_actionscheduler_actions2` or `wp_actionscheduler_actions*`

**Review by vmanthos — APPROVED** [review]
This is working as expected as far as the correct display of the AS tables notice goes.

@jeawhanlee Can you please make sure the `rocket_rucss_as_tables_count` is deleted when uninstalling WP Rocket? 🙏

**Comment by jeawhanlee** [comment]
> This is working as expected as far as the correct display of the AS tables notice goes.
> 
> @jeawhanlee Can you please make sure the `rocket_rucss_as_tables_count` is deleted when uninstalling WP Rocket? 🙏

here @vmanthos

**Comment by vmanthos** [comment]
Thank you, Sir!

This is working as expected! 👍

**Pull request merged**
