### PR TITLE
Fix#3991 Use dedicated filter for usedCSS content

### LINKED ISSUE #3991: 3.9 RUCSS - PHP Fatal error  - too few arguments passed in rocket_css_content
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

The issue was reported by Simon Duduica, the CTO of ShortPixel. 🙏

In `WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS` we pass only `$used_css` to the `rocket_css_content` filter here:
https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L586

contrary to how this is defined here:
https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/Engine/Optimization/CSSTrait.php#L68

This is causing a PHP Fatal error when the ShortPixelAI plugin is using our filter:
```
PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function ShortPixelAI::parse_cached_css(), 1 passed in /home/nginx/domains/example.com/public/wp-includes/class-wp-hook.php on line 292 and exactly 3 expected in /home/nginx/domains/example.com/public/wp-content/plugins/shortpixel-adaptive-images/includes/controllers/short-pixel-ai.class.php:1024
Stack trace:
#0 /home/nginx/domains/example.com/public/wp-includes/class-wp-hook.php(292): ShortPixelAI->parse_cached_css()
#1 /home/nginx/domains/example.com/public/wp-includes/plugin.php(212): WP_Hook->apply_filters()
#2 /home/nginx/domains/example.com/public/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(586): apply_filters()
#3 /home/nginx/domains/example.com/public/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(360): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->save_used_css_in_filesystem()
#4 /home/nginx/domains/example.com/public/wp-content/plugins/wp-rocket/in in /home/nginx/domains/example.com/public/wp-content/plugins/shortpixel-adaptive-images/includes/controllers/short-pixel-ai.class.php on line 1024
```

**To Reproduce**

1. Install [ShortPixelAI](https://wordpress.org/plugins/shortpixel-adaptive-images/).
2. Enable the **Replace in CSS files** option in _ShortPixel AI Settings > Areas_
3. Add a `<span>` element on a page, and set a `background-image` for that by storing the CSS in an external file.
4. Enable the RUCSS feature _AND_ CPCSS.
5. Check the `debug.log` for the error.

**Expected behavior**

Not causing PHP fatal errors when 3rd-parties use our filters.

**Additional context**

We need to additionally pass `$source, $target` to the filter.

**Ticket:** https://secure.helpscout.net/conversation/1532365411/268869?folderId=2135277

Similar to #2127.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
## Description

We need to use dedicated filter for used CSS content returned from treeshaker call.

Fixes #3991 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

Yes, just change the position of the filter to be before saving used CSS into the DB (the previous code was using it before saving into filesystem only so if CPCSS is disabled, this filter wasn't applied at all)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] At CDN integration test I used this filter to be covered.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by iCaspar — APPROVED** [review]

**Comment by piotrbak** [comment]
@engahmeds3ed How can we test the filter there? What's exactly expected?

**Comment by engahmeds3ed** [comment]
@piotrbak 

The first thing to test here is to test the main issue reported by the customer, so you will need to install the ShortPixel plugin and make sure the fatal error is not there (you will find all details at the issue itself).

The second thing that you need to test is to check replacing URLs used in internal CSS on the used CSS as follows:-
1. Create a page with internal CSS that has some CSS properties (URLs mainly) that should be replaced with the CDN URL.
2. Enable RUCSS.
3. Check the Used CSS and make sure that the URLs are replaced properly.

Thanks.

**Comment by piotrbak** [comment]
@engahmeds3ed When CPCSS is enabled + RUCSS + CDN, in the Used CSS file we are not rewriting the relative path assets. They're working just fine if the CPCSS is disabled and the RUCSS is internal.

**Review by Mai-Saad — COMMENTED** [review]
- Fatal error is fixed here
- If CDN was enabled after RUCSS, the URLs inside used CSS won't be updated till we manually clear used css then refresh page => I think this will be fixed here https://github.com/wp-media/wp-rocket/issues/3874
- We have another problem (can see it too on production zip with staging saas), in case CDN is enabled for images only or js only , the used css file URL is concatinated with shortpixel URL 
Screenshot from 2021-06-22 13-05-38
@engahmeds3ed @Tabrisrp will we fix this on the current PR?

**Comment by remyperona** [comment]
@Mai-Saad That seems to be an issue on Shortpixel side, not us?

@engahmeds3ed There is a conflict on this branch, can you fix it to be able to merge? 🙏🏼

**Comment by Mai-Saad** [comment]
@Tabrisrp even when RUCSS is off then CDN images only or js only applied => short pixel URL is concatenated with all CSS URLs 
Screenshot from 2021-06-22 17-45-26

**Comment by remyperona** [comment]
@Mai-Saad That looks like the default behaviour of ShortPixel for their API URL, I can see the CSS files are loading fine, so we have nothing to do.

**Review by Mai-Saad — APPROVED** [review]
Works as expected then. (failed test related to #3874 + short pixel concatenation)
[testrail-report-197.pdf](https://github.com/wp-media/wp-rocket/files/6699847/testrail-report-197.pdf)

**Pull request merged**
