### PR TITLE
Closes #7120: PHPStan - Discourage apply_filters in Favor of wpm_apply_filters_typed()

### LINKED ISSUE #7120: PHPStan - Discourage apply_filters in Favor of wpm_apply_filters_typed()
Add a PHPStan rule to detect the use of `apply_filters` and prompt developers to use `wpm_apply_filters_typed()` instead.

**Justification**:
**Code Quality**: Encourages the use of typed filters, improving type safety and reducing potential errors.
**Consistency**: Promotes a consistent approach to applying filters across the codebase.

Example:
The following will prompt an error:
``` php
$result = apply_filters('filter_name', $value);
```
In favor of:
``` php
$result = wpm_apply_filters_typed('filter_name', $value);
```

This rule will help ensure that all filters in the WP Rocket codebase are applied using the more robust and type-safe `wpm_apply_filters_typed()` function

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #7120
Nothing impacts users. 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

## Detailed scenario
N/a
### Documentation

This pull request includes several changes to enhance the PHPStan configuration and introduce a custom rule to discourage the use of `apply_filters` in favor of a typed alternative. The key changes include adding a new script to generate a PHPStan baseline, updating the PHPStan configuration file to include the baseline and new paths, and implementing a custom PHPStan rule.

Enhancements to PHPStan configuration:

* [`composer.json`](diffhunk://#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R237): Added a new script `run-stan-reset-baseline` to generate a PHPStan baseline.
* [`phpstan.neon.dist`](diffhunk://#diff-6f19df6a6307a48db0940e6897591fb08776d2db8a6134737aa708defdb5c92dR3-R15): Included the `phpstan-baseline.neon` file and added new paths to the `paths` parameter. Also, set `reportUnmatchedIgnoredErrors` to false. [[1]](diffhunk://#diff-6f19df6a6307a48db0940e6897591fb08776d2db8a6134737aa708defdb5c92dR3-R15) [[2]](diffhunk://#diff-6f19df6a6307a48db0940e6897591fb08776d2db8a6134737aa708defdb5c92dR57-R58)

Introduction of a custom PHPStan rule:

* [`phpstan.neon.dist`](diffhunk://#diff-6f19df6a6307a48db0940e6897591fb08776d2db8a6134737aa708defdb5c92dR57-R58): Added a new custom rule `WP_Rocket\Tests\phpstan\Rules\DiscourageApplyFilters` to the `rules` parameter.
* [`tests/phpstan/Rules/DiscourageApplyFilters.php`](diffhunk://#diff-1e2a56c614719afed07e3843568c17f817d549bba46d7703e17a67c81fb46767R1-R35): Implemented the `DiscourageApplyFilters` class to discourage the use of `apply_filters` and suggest using `wpm_apply_filters_typed` instead.

This will trigger an error with PHPStan if we are using `apply_filters` and recommend to use `wpm_apply_filters_typed()`. 
Example:
```
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   tests/Integration/inc/ThirdParty/Themes/Uncode/excludeDelayJs.php                                                                                                                                                          
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  26     Usage of apply_filters() is discouraged. Use wpm_apply_filters_typed() instead.                                                                                                                                            
         💡 We've created a wpm_apply_filters library to help you type hint your filters. You can use it to type hint your filters and make your code more predictable. More info: https://github.com/wp-media/apply-filters-typed  
  69     Usage of apply_filters() is discouraged. Use wpm_apply_filters_typed() instead.                                                                                                                                            
         💡 We've created a wpm_apply_filters library to help you type hint your filters. You can use it to type hint your filters and make your code more predictable. More info: https://github.com/wp-media/apply-filters-typed  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   tests/Integration/inc/ThirdParty/Themes/Uncode/excludeJs.php                                                                                                                                                               
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  26     Usage of apply_filters() is discouraged. Use wpm_apply_filters_typed() instead.                                                                                                                                            
         💡 We've created a wpm_apply_filters library to help you type hint your filters. You can use it to type hint your filters and make your code more predictable. More info: https://github.com/wp-media/apply-filters-typed  
  67     Usage of apply_filters() is discouraged. Use wpm_apply_filters_typed() instead.                                                                                                                                            
         💡 We've created a wpm_apply_filters library to help you type hint your filters. You can use it to type hint your filters and make your code more predictable. More info: https://github.com/wp-media/apply-filters-typed  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
```

### New dependencies

n/a
### Risks

n/a
# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

### CODE REVIEW

**Comment by MathieuLamiot** [comment]
Thanks @Miraeld !
To avoid breaking theme CI on the repo, could we apply this rule on the diff only for now? I think PHPCS offers this possibility.
We would benefit from the rule without having to update the whole codebase for now.

**Comment by Miraeld** [comment]
@MathieuLamiot Phpstan doesn't offer this possibility, per se the documentation.

**Comment by MathieuLamiot** [comment]
@Miraeld what about this? https://phpstan.org/user-guide/baseline

**Comment by Miraeld** [comment]
A `baseline` system has been introduced in this PR. A notion page will be created to explain more about it.

**Review by wordpressfan — CHANGES_REQUESTED** [review]
Does this work with you locally?
It doesn't work with me at all, I tested it like that:
Add `apply_filters( 'rocket_test', false )` to the code inside `inc/Engine` and run the command:
```
composer run run-stan-reset-baseline
```
but it shows that everything is OK.

image

Am I doing anything wrong here?

Also, do we need to handle the function `apply_filters_ref_array` also here?

**Comment by Miraeld** [comment]
> Does this work with you locally? It doesn't work with me at all, I tested it like that: Add `apply_filters( 'rocket_test', false )` to the code inside `inc/Engine` and run the command:
> 
> ```
> composer run run-stan-reset-baseline
> ```
> 
> but it shows that everything is OK.
> 
> image
> 
> Am I doing anything wrong here?
> 
> Also, do we need to handle the function `apply_filters_ref_array` also here?

Yea it's normal you are using the wrong command. 

Okay, let me explain quick here, and I'll explain deeper on Slack I think. 


### Why We’re Using the PHPStan Baseline

Introducing this new PHPStan rule across our codebase results in 557 errors because of how extensively we use `apply_filters`. However, the goal of this PR is **not to refactor all these instances** but to implement the rule itself.

To manage these existing issues without addressing them right now, we're leveraging PHPStan's **baseline system**.

---

### What is the Baseline?

The baseline acts as a "to-do list" for PHPStan. It records known errors and tells PHPStan to "ignore these for now." This allows us to focus on new issues while keeping the existing ones acknowledged but not flagged during analysis.

---

### Updating the Baseline

The Composer command I added (`run-stan-reset-baseline`) lets you update the baseline file with the latest list of known errors. This ensures PHPStan won't report the existing 557 issues during its checks.

---

This approach allows us to adopt the new rule without overwhelming ourselves with fixing historical issues immediately. Let me know if you need further elaboration!




---

About `apply_filters_ref_array`, I'm not sure, what @CrochetFeve0251 & @remyperona think about it ?

**Review by wordpressfan — APPROVED** [review]
aha, got it, now it works on my side, thanks for explanation

**Pull request merged**
