### PR TITLE
Enhancement/6213 prevent 400

### LINKED ISSUE #6213: Limit numbers of pending RUCSS jobs to avoid being late on fetching the result and hence getting a 400 Bad Json
**Context**
Several users with an high number of pages on their websites reported issues with RUCSS feature, resulting in "400: Bad JSON".
Some investigations showed that, when starting the process of RUCSS optimization on the plugin for the whole website, the first URLs were correctly optimized but at some point, all jobs started to return 400: Bad JSON. This seem linked to the fact that the website does not manage to fetch all jobs in the expected schedule: too many actions to fecth results are planned and a good part of them take place to late, when the job is stale on the server side.

**Expected behavior**
The plugin should not send new jobs if it is not capable of fetching them back in the appropriate time window. Therefore, we should keep the number of pending jobs under control:
- If the website is fast enough, jobs start in pending and are quickly completed, allowing for more jobs to be created immediately.
- If the website is slow, jobs start in pending and we wait for them to be completed. There is no use putting more jobs in the queue as the website won't be able to fetch them in time anyway.
The maximum number of pending + in progress job must be configurable with a filter for instance. With a special value (for instance 0?) the configuration means that the limit must be disable (come back to the current state).

**Acceptance Criteria**
- No regression on the RUCSS feature. Especially in case of 408: the retry job must be created no matter what.
- Emulate a website that never tries to fetch results. Start RUCSS on all website. The number of pending jobs must stop at the given threshold.
- Then, complete and/or fail one job. A new job must be created for a new page.
- The filter allows to change the number of pending jobs authorized, and also to remove the limitation.

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description
Limit the number of request done to the SAAS.

For that we introduced a new status `on-submit` that will buffer requests.

Fixes #6213

## Type of change

*Please delete options that are not relevant.*

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

No.

# Checklists

## Generic development checklist

- [ ] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*
FYI: I know unit tests are not passing.

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@CrochetFeve0251 This is a first take on the PR. 

- [x] Currently, the interval for the `rocket_rucss_on_submit_jobs` event matches that of `rocket_remove_rucss_failed_jobs_cron_interval`:

https://github.com/wp-media/wp-rocket/blob/dc7fa0ac4717120b855950f92f9893be1395744b/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php#L193

If somebody uses/used that filter to delay the handling of failed jobs that will affect when `to-submit` jobs are handled.

@wp-media/productrocket Is this something we want or should a new filter be introduced to handle the interval for `rocket_rucss_on_submit_jobs`?

- [ ] The `rocket_rucss_max_pending_jobs` [filter](https://github.com/wp-media/wp-rocket/blob/dc7fa0ac4717120b855950f92f9893be1395744b/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L1002) should be safeguarded from values that can be evaluated to `0`, e.g. `false`, `null`, `array()` or `1`, e.g. `true`, [ 150], etc.

This is because if there are no `pending` and `in-progress` jobs the `to-submit` jobs won't be processed:
https://github.com/wp-media/wp-rocket/blob/dc7fa0ac4717120b855950f92f9893be1395744b/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php#L141-L145

- [ ] The `rocket_rucss_hash` [filter](https://github.com/wp-media/wp-rocket/blob/dc7fa0ac4717120b855950f92f9893be1395744b/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L607) should be safeguarded from incorrect values.

**Comment by CrochetFeve0251** [comment]
@Mai-Saad #6204 will be merged with that branch

**Comment by vmanthos** [comment]
@CrochetFeve0251 I'm getting the following PHP fatal error in the `debug.log` regardless of whether the "Separate cache files for mobile devices" is enabled/disabled:

```PHP
PHP Fatal error:  Uncaught TypeError: WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS::send_api(): Argument #2 ($is_mobile) must be of type bool, string given, called in /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 1005 and defined in /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php:1034
Stack trace:
#0 /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(1006): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->send_api()
#1 /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php(108): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->process_on_submit_jobs()
#2 /var/www/example.com/htdocs/wp-includes/class-wp-hook.php(310): WP_Rocket\Engine\Optimization\RUCSS\Cron\Subscriber->process_on_submit_jobs()
#3 /var/www/example.com/htdocs/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#4 /var/www/example.com/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#5 /var/www/example.com/htdocs/wp-cron.php(191): do_action_ref_array()
#6 {main}
  thrown in /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 1033
```

Can you please look into this? :pray:

**Comment by Mai-Saad** [comment]
@CrochetFeve0251 Thanks for the updates. While exploring the PR, can see a fatal error in the following scenario, can you please check that :pray: 
1- The URL is on `to-submit` at the used CSS table (the URL is locked at the cache table)
2- Clear used CSS for this URL while logged in (The URL is still locked  but changed to pending in the cache table)
3- Visit the URL in the browser and refresh to cache the page => check debug.log
`[23-Oct-2023 07:28:03 UTC] PHP Fatal error:  Uncaught TypeError: WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS::reset_job(): Argument #1 ($id) must be of type int, string given, called in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 207 and defined in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php:255
Stack trace:
#0 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(207): WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS->reset_job()
#1 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(579): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->add_url_to_the_queue()
#2 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php(143): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->check_job_status()
#3 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Optimization\RUCSS\Cron\Subscriber->check_job_status()
#4 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#6 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/actions/ActionScheduler_Action.php(43): do_action_ref_array()
#7 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(65): ActionScheduler_Action->execute()
#8 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/RUCSSQueueRunner.php(206): ActionScheduler_Abstract_QueueRunner->process_action()
#9 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/RUCSSQueueRunner.php(175): WP_Rocket\Engine\Common\Queue\RUCSSQueueRunner->do_batch()
#10 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Common\Queue\RUCSSQueueRunner->run()
#11 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#12 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#13 /var/www/new.rocketlabsqa.ovh/htdocs/wp-cron.php(191): do_action_ref_array()
#14 {main}
  thrown in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php on line 255`

**Comment by CrochetFeve0251** [comment]
> @CrochetFeve0251 Thanks for the updates. While exploring the PR, can see a fatal error in the following scenario, can you please check that 🙏 1- The URL is on `to-submit` at the used CSS table (the URL is locked at the cache table) 2- Clear used CSS for this URL while logged in (The URL is still locked but changed to pending in the cache table) 3- Visit the URL in the browser and refresh to cache the page => check debug.log `[23-Oct-2023 07:28:03 UTC] PHP Fatal error: Uncaught TypeError: WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS::reset_job(): Argument #1 ($id) must be of type int, string given, called in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 207 and defined in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php:255 Stack trace: #0 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(207): WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS->reset_job() #1 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(579): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->add_url_to_the_queue() #2 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php(143): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->check_job_status() #3 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Optimization\RUCSS\Cron\Subscriber->check_job_status() #4 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #5 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action() #6 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/actions/ActionScheduler_Action.php(43): do_action_ref_array() #7 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(65): ActionScheduler_Action->execute() #8 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/RUCSSQueueRunner.php(206): ActionScheduler_Abstract_QueueRunner->process_action() #9 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/RUCSSQueueRunner.php(175): WP_Rocket\Engine\Common\Queue\RUCSSQueueRunner->do_batch() #10 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Common\Queue\RUCSSQueueRunner->run() #11 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #12 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action() #13 /var/www/new.rocketlabsqa.ovh/htdocs/wp-cron.php(191): do_action_ref_array() #14 {main} thrown in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php on line 255`

@Mai-Saad this seems linked to that bug : https://github.com/berlindb/core/issues/162.
I will cast the value for the moment.

**Review by vmanthos — APPROVED** [review]
This is working as expected as far as the acceptance criteria go.

**NOTES**

1. Both @Mai-Saad and I have come across URLs that were stuck `in-progress` with `1` or no retries:
image

This seems to be random, i.e. we don't have a way to reproduce the issue.

One thing to note is that there aren't any `rocket_rucss_job_check_status` jobs pending in Action Scheduler and therefore these are not processed. 
We are not able to tell whether those jobs weren't created in the first place or they somehow got deleted.

2. The `error 400` is still there:
image
Evidently, there is a delay in checking for jobs' results, although there isn't any more info about what has caused this for the specific URLs.

**Pull request merged**
