### PR TITLE
Load DelayJS script right after the opening <head>

### PR DESCRIPTION
**Pull request by remyperona**
## Description

After discussions, it was determined that the best place to load the script is right at the start of the document, after the `<head>` opening tag.

This PR reflects that change, using `rocket_buffer` to insert the script in the HTML.

## Type of change

- [x] Enhancement (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

- [x] Manual test
- [x] Updated automated test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by crystinutzaa — APPROVED** [review]

**Comment by remyperona** [comment]
@wp-media/qa Ready for QA

**Comment by piotrbak** [comment]
@Tabrisrp In this version, the script doesn't have any ID. It used to be:
`rocket-delay-js-js-after`

Is that fine?

**Comment by remyperona** [comment]
it's ok we didn't use the ID for this script. And the script itself is inserted after we have transformed the HTML, so it can't be delayed.

**Comment by piotrbak** [comment]
@Tabrisrp We're replacing only the first occurrence of the `<head>` here. I can see a potential problem when there's an HTML comment containing `<head>` above the real `<head>`.
image

Switching to replacing all occurrences of  `<head>` brings different cons. What do you think?

**Comment by remyperona** [comment]
Replacing multiple occurrences will bring more issues than the first one which is an edge case

**Review by piotrbak — APPROVED** [review]
Good to go!
[testrail-report-179.pdf](https://github.com/wp-media/wp-rocket/files/6466246/testrail-report-179.pdf)

**Pull request merged**
