### PR TITLE
Add optimization for Contact Form 7

### LINKED ISSUE #6241: Add optimization for Contact Form 7
**Is your feature request related to a problem? Please describe.**
Contact Form 7 enqueues JavaScript on every page regardless of if you use a form. 

**Describe the solution you'd like**
WP Rocket should include an optimization module specifically for CF7 that corrects this behavior, see #6215

**Describe alternatives you've considered**
This optimization was originally proposed directly for CF7 in https://github.com/rocklobster-in/contact-form-7/issues/1278 - however the maintainer did not want to add the change, saying instead that site owners should add code to change the behavior.

**Additional context**
See PR and CF7 Issue/PR.

### PR DESCRIPTION
**Pull request by adamsilverstein**
Only load Contact Form 7’s JavaScript if a form is present on the page.

## Description

The Contact Form 7 ("CF7") specific optimization ensures that CF7 front end scripts are only enqueued when the page contains a contact form.

fixes #6241 
## Type of change

* Use CF7 hooks and functions to optimize sites using CF7 as recommended by their docs
* Reduce excessive script loading for pages without contact forms, for example if the contact form is only used on a "Contact Us" page

## Is the solution different from the one proposed during the grooming?

*Please describe in this section if there is any change to the groomed solution, and why.*

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- Not yet tested

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

### CODE REVIEW

**Comment by westonruter** [comment]
Note this PR incorporates optimizations from a [standalone mini plugin](https://gist.github.com/westonruter/af6ce5699e4b5576f51a7cd901b80152). This was developed to fix https://github.com/rocklobster-in/contact-form-7/issues/1278 in which scripts and styles for CF7 are enqueued on every page even when there is no contact form present.

**Review by remyperona — APPROVED** [review]

**Review by Mai-Saad — APPROVED** [review]
Working as expected and js/css isn't loaded now unless it's used.

**Review by wordpressfan — APPROVED** [review]
Thanks @adamsilverstein , this is a great honor working with u on the same PR.

We will merge this PR but we need to revisit it to add tests and also change it a bit to have the callbacks registering inside the method `get_subscribed_events` after adding the bailout conditions there and small code formatting concepts that we use here like bailout early.
But the PR itself is good and working perfectly.

**Comment by adamsilverstein** [comment]
Thanks everyone for the attention on this, great to see this merged!

**Pull request merged**
