### PR TITLE
Fixes #3471 Update learn more URL for RocketCDN

### LINKED ISSUE #3471: Update RocketCDN link to new website
In the CDN tab of WP Rocket, currently the link `LEARN MORE ABOUT ROCKETCDN` points to: https://go.wp-rocket.me/rocket-cdn

This is the link: 
image

Please update it to: https://wp-rocket.me/rocketcdn/

Thanks!

### PR DESCRIPTION
**Pull request by remyperona**
Fixes #3471 

Update the learn more URL for RocketCDN in the big CTA banner.

### CODE REVIEW

**Review by crystinutzaa — APPROVED** [review]

**Comment by remyperona** [comment]
@wp-media/qa ready for QA

**Review by Mai-Saad — COMMENTED** [review]
@Tabrisrp The modal for get started contains useless vertical scroll
scroll
For reproducing:
precondition: WP Rocket activated
1- open the admin DB incognito 
2- WP Rocket settings -> CDN
3- click get started in RocketCDN banner
expected: no scroll
actual: vertical scroll
env: device:Dell G5 15, os: Ubuntu 18.04.5, browser: chrome

**Review by Mai-Saad — CHANGES_REQUESTED** [review]
@Tabrisrp CTA banner UI handling is needed with ar local of Dashboard (Dismiss icon + text)
popupAr
To reproduce:
1- open WP dashboard 
2- settings-> change local to arabic-> save 
3- open CDN in WP Rocket settings

expected: Dismiss icon aligned left , text ar or if En be correctly aligned
env: device:Dell G5 15, os: Ubuntu 18.04.5, browser: chrome

**Comment by Mai-Saad** [comment]
Since issues above arenot related directly to this PR so will open separate issues for it so we Merge this PR

**Review by Mai-Saad — APPROVED** [review]

**Pull request merged**
