### PR TITLE
Add more nonce actions in get_nonce_actions()

### PR DESCRIPTION
**Pull request by vmanthos**
Prevent errors related to admin-ajax requests and WooCommerce nonces.
**Related ticket:**
https://secure.helpscout.net/conversation/1116615241/153135?folderId=2135277

## TODO

- [x] Add tests
- [x] Move and rename files
- [x] QA -- since we moved/renamed files.

### CODE REVIEW

**Review by crystinutzaa — APPROVED** [review]

**Review by crystinutzaa — APPROVED** [review]

**Review by hellofromtonya — APPROVED** [review]

**Comment by Tabrisrp** [comment]
No QA needed since it has already been tested on customer websites before the initial PR was done

**Comment by hellofromtonya** [comment]
However @Tabrisrp We moved files and renamed them. We should do QA to make sure it works as expected.

**Comment by Tabrisrp** [comment]
Tagging @arunbasillal on this one then

**Review by Screenfeed — APPROVED** [review]

**Comment by arunbasillal** [comment]
Starting QA on this one

**Review by arunbasillal — APPROVED** [review]
Recreating the issue was tough, but @vmanthos was kind enough to help out. 

Since we were mainly testing if things worked even after moving around the files, I recreated the original issue. Original issue and steps to reproduce is documented here: https://hub.wp-media.me/wp-rocket/knowledge-base/issues/error-403-on-admin-ajax-requests-and-woocommerce-nonces/

- Tested by removing the exclusions. I was able to reproduce the issue
- Worked as expected with the current version 👍 

Video: https://youtu.be/AQum-nOaWPo

**Pull request merged**
