### PR TITLE
Closes #5474 Preconnect is not removed in all cases

### LINKED ISSUE #5474: Preconnect is not removed in all cases
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Yes
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
From 3.8.8, WP Rocket is detecting if there are Google Fonts before adding "preconnect" to a site, [here](https://github.com/wp-media/wp-rocket/issues/3219). However, this check doesn't work if you're viewing while logged-in (User Cache off) or bypassing WP Rocket with ?nowprocket and other query strings.

**To Reproduce**
1. Set up pa site without Google Fonts
2. Install and activated WP Rocket
3. Check the page's optimized version, it doesn't have the "preconnect"
4. If you visit the page with ?nowprocket  or while logged-in  (User Cache off), it does have the "preconnect"

**Expected behavior**
The Google Fonts check should be applied to all scenarios, including bypassed optimizations and while logged-in.

**Screenshots**
The behavior at ?nowprocket for my test site, https://camila.com.co/
image

**Additional context**
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1663690608273009
Ticket: https://secure.helpscout.net/conversation/1999948040/366451?folderId=2675957
This is currently a problem for customer because the external domain preconnect violates the GDPR law.

Thanks!

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

Applies preconnect only when optimization is allowed.

Fixes #5474 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?

Automated & Manual Tests.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@jeawhanlee This is working except for the case where:
1. Google fonts are loaded.
2. User Cache is enabled.
3. Viewing a page while logged in.

In this scenario, `preconnect` should be added but it isn't.

To wrap this up:

**No Google Fonts**

When Google fonts are _not_ loaded `preconnect` should _not_ be added in any case, i.e. for anonymous users, logged-in users (both when User Cache is enabled and disabled), and when `?nowprocket` is used.

**Google Fonts loaded**

When Google fonts are loaded `preconnect` _should_ be added for:
1. Anonymous users.
2. Logged-in users when User Cache is enabled.

It should _not_ be added for:
1.  Logged-in users when User Cache is disabled.
2. When `?nowprocket` is used.

**Review by remyperona — APPROVED** [review]

**Review by vmanthos — APPROVED** [review]
Thank you for the fix @jeawhanlee! :pray: 

This is working as expected. :+1:

**Comment by remyperona** [comment]
Update needed to fix the conflict

**Comment by piotrbak** [comment]
@jeawhanlee There's update needed in this PR to fix conflicts

**Pull request merged**
