### PR TITLE
Exclude lazyload styles from being removed from the page with RUCSS

### PR DESCRIPTION
**Pull request by engahmeds3ed**
## Description

We need to exclude lazyload styles from being removed from the page after RUCSS finishes its work on the page.

### CODE REVIEW

**Review by iCaspar — APPROVED** [review]

**Comment by engahmeds3ed** [comment]
@wp-media/qa ready for QA

@piotrbak this is the change u saw yesterday, feel free to validate it.

**Comment by piotrbak** [comment]
@engahmeds3ed I'm thinking, in the future, we might want to allow people to exclude the CSS using its attributes within the UI and using a filter, what do you think?

**Comment by engahmeds3ed** [comment]
Yes it will be easier to add a filter here, we can do that in the next minor release for sure

**Comment by piotrbak** [comment]
We're good to go here @engahmeds3ed

**Pull request merged**
