### PR TITLE
Add lazyload background property

### LINKED ISSUE #2588: Check for `background` property
To lazyload background images, we are looking for the` background-image` property:
https://github.com/wp-media/rocket-lazyload-common/blob/1ea0cf2ae5d302a0214e05176c1dda321b1d6690/src/Image.php#L65

But in some cases, a shorthand version of the `background` property can be used like that by [Related Posts Thumbnails Plugin for WordPress](https://wordpress.org/plugins/related-posts-thumbnails/) to display thumbnails:
`<div class="relpost-block-single-image" alt="Fashion Illustrator Bella" style="background: transparent url(https://lemontrend.com/vz01pro1/wp-content/uploads/2019/12/fashion-illustrator-bella-featured-150x150.jpg) no-repeat scroll 0% 0%; width: 150px; height: 150px;"></div>`

Which is correct:
https://developer.mozilla.org/en-US/docs/Web/CSS/background

We should also checking for that.

### PR DESCRIPTION
**Pull request by engahmeds3ed**
Fixes https://github.com/wp-media/wp-rocket/issues/2588

grab lazyload changes from lazyload repo.
https://github.com/wp-media/rocket-lazyload-common/pull/91

### CODE REVIEW

**Comment by piotrbak** [comment]
@engahmeds3ed @Tabrisrp There are pretty many different possibilities and some solutions might be dependent on the JavaScript on the frontend, so we need to be careful. Here's what I've found so far:
1. The following markup, when there's a color specified before the `url` is not working:
`<span style="background: #ccc url('/wp-content/rocket-test-data/images/fixtheissue.jpg?span') no-repeat;"></span>`
`<span style="background: #ccc url('/wp-content/rocket-test-data/images/fixtheissue.jpg?span');"></span>`
2. When there's the following markup:
`<figure style="background-image: url('/wp-content/rocket-test-data/images/Przechwytywanie.PNG?figure'); background: white;"></figure>`
We're processing it correctly with PHP and it becomes:
`<figure data-bg="https://rocketlabsqa.dev/wp-content/rocket-test-data/images/Przechwytywanie.PNG?figure" class="rocket-lazyload" style=" background: white;"></figure>`
However, after JS replacement is done, we're changing the initial `background-image` to the `background`:
`<figure class="rocket-lazyload lazyloaded" style="background: url(&quot;/wp-content/rocket-test-data/images/Przechwytywanie.PNG?figure&quot;) white;" data-ll-status="loaded"></figure>`
3. On the other hand the following markup changes the `background` to the `background-image`:
`<a style="background: url('/wp-content/rocket-test-data/images/fixtheissue.jpg?a');"></a>`
`<a class="rocket-lazyload lazyloaded" style="background-image: url(&quot;/wp-content/rocket-test-data/images/fixtheissue.jpg?a&quot;);" data-ll-status="loaded"></a>`

In the 2nd and 3rd points, my concern is about the possible CSS changes and JavaScript that would look for certain attributes and won't find them because they're changed by us.

**Comment by piotrbak** [comment]
@arunbasillal What do you think about the 2nd and 3rd case? ⬆️

**Comment by engahmeds3ed** [comment]
@piotrbak 
1. Solved now please check again.

From practice I got that JS checks if there is background attribute or not if found it will add the url into it otherwise it will create background-image property.
I will check the js code there to see exactly what is happening there.

**Comment by piotrbak** [comment]
@arunbasillal @Tabrisrp @engahmeds3ed The 1st issue is resolved with this fix. I came across a problem when there are a couple of backgrounds listed after the `,` in one `background` property.

It's described here:
https://github.com/wp-media/wp-rocket/issues/2708

Since we'll be adding this enhancement automatically to existing sites, more people will be affected.

4. That kind of markup:
`<a style="background:  linear-gradient(rgba(0, 0, 255, 0.5), rgba(255, 255, 0, 0.5)), url('/wp-content/rocket-test-data/images/fixtheissue.jpg?a5');"></a>`
becomes in PHP:
`<a data-bg="/wp-content/rocket-test-data/images/fixtheissue.jpg?a5" class="rocket-lazyload" style="background:  linear-gradient(rgba(0, 0, 255, 0.5), rgba(255, 255, 0, 0.5)), ;"></a>`
and the gradient is removed in the frontend:
`<a class="rocket-lazyload lazyloaded" style="background-image: url(&quot;/wp-content/rocket-test-data/images/fixtheissue.jpg?a5&quot;);" data-ll-status="loaded"></a>`

5. Similar to the above, when there are two `url()` in one `background` property:
`<a style="background: center / contain no-repeat url('/wp-content/rocket-test-data/images/fixtheissue.jpg?a5'), url('/wp-content/rocket-test-data/images/Przechwytywanie.PNG?figure') 50% 10% repeat-x blue;"></a>`
Becomes in PHP:
`<a data-bg="/wp-content/rocket-test-data/images/Przechwytywanie.PNG?figure" class="rocket-lazyload" style="background: center / contain no-repeat url('/wp-content/rocket-test-data/images/fixtheissue.jpg?a5'),  50% 10% repeat-x blue;"></a>`
And then the JS is erasing the `url()` from the `style=`:
`<a class="rocket-lazyload lazyloaded" style="background: url(&quot;/wp-content/rocket-test-data/images/Przechwytywanie.PNG?figure&quot;) center center / contain no-repeat, 50% 10% repeat-x blue;" data-ll-status="loaded"></a>`

**Comment by piotrbak** [comment]
@wp-media/productrocket We need your opinion.

There are some unexpected behaviors here. 2nd and 3rd points are related to the LL JavaScript switching between `background` and `background-image`. It can have some impact if the customer's custom script is doing something with one of those properties.

The 4th and 5th points are related to the double `url` issue which is already known. However, now it'll be impacting more customers since we'll be applying it to the `background` too, not only `background-image`.

**Comment by Tabrisrp** [comment]
I think adding support to lazyload on the background property should also add support for the multi background at the same time, to avoid creating any additional issue.

The lazyload script itself is compatible with multi background images, but it's using a different data attribute, so it needs to be handled differently.

This won't be ready for this week release, so going to punt this for now.

**Comment by jazir555** [comment]
Is development still continuing on this feature?

**Comment by remyperona** [comment]
It will for a future release

**Pull request closed without merging**
