### PR TITLE
Preserve the box rocket_activation_notice with update

### LINKED ISSUE #5889: The activation notice shows up after every update
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔
- Used the search feature to ensure that the bug hasn’t been reported before ✔

**Describe the bug**
There is a message after plugin activation, that says "WP Rocket is now activated...". This message should not be displayed after every plugin update if the user is dismissed it earlier.

**To Reproduce**
1. Install an older version of WR Rocket.
2. Open the `/wp-admin/options-general.php?page=wprocket#dashboard` page.
3. Click on the Dismiss `×` icon.
4. Update the plugin. 
5. Open the `/wp-admin/options-general.php?page=wprocket#dashboard` page again.
6. The Welcome notice is visible again.

**Expected behavior**
If the message is dismissed, never show it again. We know that the plugin is working. 

**Screenshots**
image

**Additional context**
–

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
## Description

Preserve the box rocket_activation_notice with update.

Fixes #5889

## Type of change

*Please delete options that are not relevant.*

- Bug fix (non-breaking change which fixes an issue).

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@engahmeds3ed Thanks for the PR. Please find exploratory test notes below:
1- If we dismiss the notice then deactivate WPR and activate WPR again. Notice will be displayed.
2- If we update from the previous version to the PR without dismissing notice before the update. it will be automatically dismissed.

**Comment by engahmeds3ed** [comment]
> @engahmeds3ed Thanks for the PR. Please find exploratory test notes below: 1- If we dismiss the notice then deactivate WPR and activate WPR again. Notice will be displayed. 2- If we update from the previous version to the PR without dismissing notice before the update. it will be automatically dismissed.

Good catch, based on the current code yes this is expected after checking this old code.
Let me try fixing that without affecting other boxes.

**Comment by engahmeds3ed** [comment]
@Tabrisrp do u remember why do we clear all rocket boxes with update?

**Comment by remyperona** [comment]
I do not, it's something that was there before my time. It probably made sense at some point, but not anymore.

**Comment by engahmeds3ed** [comment]
Thanks @Tabrisrp 

Summary: the [used function ](https://github.com/wp-media/wp-rocket/blob/136d94b9ea6eb33ba33c3e2143a623b4b37d86cc/inc/admin/upgrader.php#L28) we remove all dismissed notices for all users and only fire dismissing the following boxes with every update:

```
One or more plugins have been enabled or disabled, clear the cache if they affect the front end of your site.
```

and the second box is the activation notice.

Even if the user didn't dismiss both boxes, both will be dismissed based on the current code.

So based on the above discussion we have three solutions here:

1. Replace [this code](https://github.com/wp-media/wp-rocket/blob/901911571c027b0b4a5979651a52ef3c0edfbe5f/inc/functions/admin.php#L41-L42) with a direct query to delete all user boxes and keep only the dismissed boxes **but this is bad from performance point of view.**
2. Don't remove all boxes with update at all and keep what's ignored kept ignored.
3. Accept the PR as is with the issues that @Mai-Saad mentioned above as known issues.

I believe we need the @wp-media/productrocket decision here.

**Comment by piotrbak** [comment]
@engahmeds3ed @Tabrisrp Do you see any reason why the boxes might be cleared? It doesn't seem to be making sense currently

**Comment by engahmeds3ed** [comment]
> @engahmeds3ed @Tabrisrp Do you see any reason why the boxes might be cleared? It doesn't seem to be making sense currently

Really I don't know.

**Comment by piotrbak** [comment]
@engahmeds3ed Let's go with 2 then.

**Comment by Mai-Saad** [comment]
Scenario 2 here https://github.com/wp-media/wp-rocket/pull/6120#issuecomment-1708193183 is fixed, while 1 is still there

**Comment by engahmeds3ed** [comment]
Thanks @Mai-Saad it should work now, can u plz also validate this old issue https://github.com/wp-media/wp-rocket/issues/5423 as it was touched here in this PR.

**Comment by Mai-Saad** [comment]
Working as expected now both 1,2 are fine

**Pull request merged**
