### PR TITLE
Adding more Flatsome dynamic selectors

### LINKED ISSUE #4991: Flatsome: RUCSS compatibility with dynamic elements like  #row- , #text-
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.11.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Dynamic styles added by Flatsome aren't preserved 

**To Reproduce**
1. Flatsome active theme
2. Add a page with row, styled text using UX builder i.e http://mega.wp-rocket.me/flatsome/image-test/
3. Enable RUCSS
4. Open the page template and compare it to ?nowprocket

**Expected behavior**
Dynamic elements are preserved i.e `#row-` and `#text-`

**Screenshots**
With nowprocket
Screenshot from 2022-04-29 20-09-00

With RUCSS
Screenshot from 2022-04-29 20-08-47

**Additional context**
- Preserve `#row-` and `#text-` as we did [here](https://github.com/wp-media/wp-rocket/pull/4979) will fix the problem

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by DahmaniAdame**
Ticket- https://secure.helpscout.net/conversation/1889616387/343840/

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@DahmaniAdame @Tabrisrp `#banner-grid-` is already preserved on trunk now (probably `#banner-` is already covering that). Do we really need to add `#banner-grid-`?
For `#product-flip-,#product-grid-`, Do we need to make it only `#product-`?

**Comment by Mai-Saad** [comment]
As per discussion with @piotrbak we are good with the current implementation

**Review by Mai-Saad — APPROVED** [review]

**Comment by DahmaniAdame** [comment]
Removing `#banner-grid-` would make sense as it's overruled by `#banner-`.
For `#product-` instead of `#product-flip-` and `#product-grid-`, it's too broad and will likely grab unnecessary selectors used by other plugins.

**Comment by piotrbak** [comment]
For `#banner-grid-`, preserving it won't hurt us. I'm afraid that at some point we could do something with `#banner-` and it would destroy our compatiblity here. While now we're perfectly safe in those two scenarios

**Pull request merged**
