### PR TITLE
Stop the infinite loop when purging cache on Pagely

### PR DESCRIPTION
**Pull request by klong-pagely**
This relates to the following two issues:

https://github.com/wp-media/wp-rocket/issues/2664
https://github.com/wp-media/wp-rocket/issues/1759

There is a hook for pagely_cache_purge_after to run a rocket_clean_domain.  Then on rocket_clean_domain there is a hook for after_rocket_clean_domain to run a pagely cache purge.  This causes a loop where it just keeps purging and purging until a timeout happens.  

This pull simply adds a global variable which is set when either hook is called that stops the purge from continuing beyond a single cycle.

### CODE REVIEW

**Review by Tabrisrp — CHANGES_REQUESTED** [review]
Thank you for the PR!

Though, we don't want to go the way of using global variables in our code, as much as possible. Globals are hard to test, and need to be avoided whenever we can.

Ideally this part of the code would be refactored to a hosting subscriber in ìnc/ThirdParty/Hostings`, and instead of using a global, we can use a class property to check if the purge already ran in one method or the other.

**Comment by armanly** [comment]
Thank you for the update @Tabrisrp 

> Ideally this part of the code would be refactored to a hosting subscriber in ìnc/ThirdParty/Hostings`, and instead of using a global, we can use a class property to check if the purge already ran in one method or the other.

Just to clarify, are you asking Pagely to make those changes? We're happy to follow your feedback, just wanted clarification if that was something you're asking us to do or if you're able to take things from here.

We would really like to get this fixed soonish because it is causing issues for customers of WP Rocket using Pagely, as it causes purge calls to get stuck and it is generating support inquiries. If it will take substantially longer to refactor this the way you described, I would vote to remove what it does currently because it does not work correctly.

Thank you again and hope we can get this solved soon.

**Comment by Tabrisrp** [comment]
Hey @armanly,

The refactoring would take significantly longer, as we would also be writing automated tests for it, as part of our CI process.

Our team is also very busy right now working on a whole new feature, which doesn't give us time to work on this issue properly.

If that's ok with you, we could start with removing the problematic code, and code back to it when we have more availability, to do the refactor and improvements discussed.

Could you do the code changes to remove the problematic parts?

**Comment by klong-pagely** [comment]
Hello @Tabrisrp,

Updated pull request to simply comment out the code leading to a loop with a comment leading people back here to see your comment in case someone wants to take a stab at refactoring according to the wp-rocket guidelines.  This removes the infinite loop issue.

Downsides to this method:

-  If Pagely cache is cleared it won't clear wp-rocket cache.

Pro's

-  Left in place the Pagely cache clear after wp-rocket cache is cleared so a wp-rocket cache clear should work correctly.

**Review by Tabrisrp — APPROVED** [review]

**Pull request merged**
