### PR TITLE
Refactor gulpfile to be more dynamic

### LINKED ISSUE #6601: Update build script to generate production scripts individually
**Context**
The current build command generates multiple production scripts at the same time.

**Expected beavhior**
We should have a command to build each script individually, and one command to build everything.

### PR DESCRIPTION
**Pull request by wordpressfan**
Closes #6601

Here I restructured the the gulp tasks and split main tasks between css and js tasks and has a config file to define the gulp tasks and the corresponding method to do that task.

List of gulp tasks that can be called directly using gulp cli command are mentioned here:

https://github.com/wp-media/wp-rocket/blob/a8e8fead41e3103511a467bffaf634cdf3f75a9c/src/js/gulp/gulpconfig.js

Also I added main big scripts inside package.json

**Q:** Do we need to be backward compatible with the old gulp tasks that I removed in this PR?

### CODE REVIEW

**Comment by MathieuLamiot** [comment]
Should this PR be made a real PR and not a draft? As I see it's "Ready for review". Thanks!

**Review by Miraeld — APPROVED** [review]

**Comment by Khadreal** [comment]
`gulp build:sass:all` task did not complete every other tasks is fine.

cc @wordpressfan

**Comment by wordpressfan** [comment]
> `gulp build:sass:all` task did not complete every other tasks is fine.
> 
> cc @wordpressfan

Done

**Review by Khadreal — APPROVED** [review]

**Comment by remyperona** [comment]
Could you add somewhere (either in the main gulp file, or the readme) The list of all gulp commands, and what it does? That would be helpful for everyone old and new as a quick reference instead of having to inside the code.

**Comment by wordpressfan** [comment]
> Could you add somewhere (either in the main gulp file, or the readme) The list of all gulp commands, and what it does? That would be helpful for everyone old and new as a quick reference instead of having to inside the code.

Good idea, doing that now.

**Review by remyperona — APPROVED** [review]

**Pull request merged**
