### PR TITLE
Multi tiers upgrade feature - Base PR

### PR DESCRIPTION
**Pull request by wordpressfan**
# Description

Fixes https://github.com/wp-media/wp-rocket.me/issues/4326

*Explain how this code impacts users.*

## Type of change

- [x] New feature (non-breaking change which adds functionality).

## Detailed scenario

Everything is mentioned in the issue, the service team changed the API to return the available upgrades and we used that without doing any calculations on the plugin side.

### Documentation

Everything is mentioned in the issue and sub-issues.

### New dependencies

Now we depend on the new API, so we need to make sure that we release the API to the production site one day before releasing this change in plugin because we save the user API for one day.

**Update:** Now we have the API changes live.

### Risks

We need to validate also the upgrade process with older versions of the plugins to make sure they are working.

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification

*If some mandatory items are not relevant, explain why in this section.*

# Additional Checks
- [x] In the case of complex code, I wrote comments to explain it.
- [x] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [x] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

**Comment by Mai-Saad** [comment]
@wordpressfan Thanks for the PR. 
Note: 
- the arrow in the upgrade button is small and not centralized
- the selected option in multi can be highlighted when open the dropdown 
will leave it to @wp-media/product to share reference UI
@marija-nikolic Please check the UI of different forms
**Upgrade from multi 100**
Screenshot from 2024-12-20 13-47-57

**upgrade from multi 50** 
Screenshot from 2024-12-20 12-58-21
Screenshot from 2024-12-20 12-56-27
Screenshot from 2024-12-20 12-56-17

**upgrade from growth**
Screenshot from 2024-12-20 14-03-01
Screenshot from 2024-12-20 14-02-55
Screenshot from 2024-12-20 14-02-48
Screenshot from 2024-12-20 14-02-41


**upgrade from single**
Screenshot from 2024-12-20 12-52-07
Screenshot from 2024-12-20 13-59-10
Screenshot from 2024-12-20 13-59-02

**No upgrade for multi500**
Screenshot from 2024-12-20 14-18-21

**Comment by Mai-Saad** [comment]
Promo banner 
**for single**
Screenshot from 2024-12-20 14-48-04
Screenshot from 2024-12-20 14-47-54
Screenshot from 2024-12-20 14-47-13
Screenshot from 2024-12-20 14-46-57

**for plus**
Screenshot from 2024-12-20 14-51-07
Screenshot from 2024-12-20 14-51-00
Screenshot from 2024-12-20 14-50-53
Screenshot from 2024-12-20 14-50-45

**for growth**
Screenshot from 2024-12-20 14-52-49
Screenshot from 2024-12-20 14-52-43
Screenshot from 2024-12-20 14-52-36
Screenshot from 2024-12-20 14-52-29

**for multi 50**
Screenshot from 2024-12-20 14-54-19
Screenshot from 2024-12-20 14-54-08
Screenshot from 2024-12-20 14-54-02

**for multi100**

Screenshot from 2024-12-20 14-55-25

Screenshot from 2024-12-20 15-01-54

**multi 500, no promo**
Screenshot from 2024-12-20 15-04-18

**Comment by marija-nikolic** [comment]
Congrats, team, everything seems good to me. 👏 
I agree with what @Mai-Saad wrote:
- the arrow in the upgrade button is small and not centralized
- the selected option in multi can be highlighted when open the dropdown



Only one small thing: it should be written `Growth or Multi` on the yellow banner:
image

**Comment by Mai-Saad** [comment]
[testrail-report-676.pdf](https://github.com/user-attachments/files/18230920/testrail-report-676.pdf)

**Comment by Khadreal** [comment]
### Screenshot 
Fixed the copy on the yellow banner
Screenshot 2024-12-24 at 23 23 55
Aligned arrow 
Screenshot 2024-12-24 at 23 24 43
Screenshot 2024-12-24 at 23 27 57

cc @Mai-Saad, @marija-nikolic

**Comment by marija-nikolic** [comment]
> ### Screenshot
> Fixed the copy on the yellow banner Screenshot 2024-12-24 at 23 23 55 Aligned arrow Screenshot 2024-12-24 at 23 24 43 Screenshot 2024-12-24 at 23 27 57
> 
> cc @Mai-Saad, @marija-nikolic

Thanks, looks good.

**Comment by wordpressfan** [comment]
So we are fine here, thanks @Khadreal @marija-nikolic @Mai-Saad

**Pull request merged**
