### PR TITLE
Update Image Dimensions regex to only work on height and width attributes 

### LINKED ISSUE #5818: Adjust image dimensions regex to not delete the wrong `height` and `width` attributes
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.6.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

In the following method: 

https://github.com/wp-media/wp-rocket/blob/d9c8d3cd1a2f3fc0e450dae67d51962522bbbee6/inc/Engine/Media/ImageDimensions/ImageDimensions.php#L325-L335

The following regex is not considering `data-` or custom attributes ending `height` or `width` as part of their names: 

```
$changed_image = preg_replace( '/(height|width)=[\'"](?:\S+)*[\'"]\s?/i', '', $image );
```

Using markup like the following: 

```
<img class="logo-main scale-with-grid svg" src="/path/to/img.ext" data-retina="" data-height="" alt="Porty Cleaning Services" data-no-retina="">
```

This will result in the following: 

```
<img class="logo-main scale-with-grid svg" src="/path/to/img.ext" data-retina="" data-alt="Porty Cleaning Services" data-no-retina="">
```
In this specific case, there will be an SEO impact as the remaining `data-` portion will stick to `alt`, changing it's function. 

In other cases, the next attribute will lose its function, which might cause anything relying on it to break. Example, if JavaScript is looking for a specific attribute to change DOM.

Changing the following: 

```
$changed_image = preg_replace( '/(height|width)=[\'"](?:\S+)*[\'"]\s?/i', '', $image );
```

to: 
```
$changed_image = preg_replace( '/\s(height|width)=[\'"](?:\S+)*[\'"]\s?/i', ' ', $image );
```
will fix the issue. 

We will be looking for `height` and `width` attributes preceded by a space, and then replaced by as space. 

That should give an accurate replacement.

We should do the same to: 

https://github.com/wp-media/wp-rocket/blob/d9c8d3cd1a2f3fc0e450dae67d51962522bbbee6/inc/Engine/Media/ImageDimensions/ImageDimensions.php#L275-L276

By limiting the regex to `height` or `width` attributes only by requesting the existence of a space before them.

This can be done by changing:

```
preg_match( '/<img.*height=[\'\"](?<height>\S+)[\'\"].*>/i', $image, $initial_height );
preg_match( '/<img.*width=[\'\"](?<width>\S+)[\'\"].*>/i', $image, $initial_width );
```
to:
```
preg_match( '/<img.*\sheight=[\'\"](?<height>\S+)[\'\"].*>/i', $image, $initial_height );
preg_match( '/<img.*\swidth=[\'\"](?<width>\S+)[\'\"].*>/i', $image, $initial_width );
```

**To Reproduce**
1. Use the Image Dimensions feature
2. Use an image with a custom attribute ending with either `height` or `width`, example: `custom-height=500`
3. See that `custom-` will be preserved on the markup and stuck to the next attribute

**Expected behavior**
Images markup should break when using the Image Dimensions feature

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2183072962/407989/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by mostafa-hisham**
## Description

Update Image Dimensions regex to only work on height and width attributes 

Fixes #5818 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Integration tests

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jeawhanlee — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@mostafa-hisham Thanks for the PR, please find exploratory test note below:
**Before the PR**``  ===> will be ``
while **After the PR** it will be `` which will case `Error: Duplicate attribute width.`
can you please check?

**Comment by mostafa-hisham** [comment]
@Mai-Saad I pushed a fix for it.
could you please check it?

**Comment by Mai-Saad** [comment]
@mostafa-hisham Thanks for the update, the regression above is fixed. But we have other problems
-  while image dimensions is enabled with Lazyload (lazyload markup changes isnot working probably). Can you please check? (attached images on trunk vs PR while LL is enabled with Add missing image dimensions)
trunk_with LL
PR_with LL
- While Add missing dimensions only is checked, the structure of images in the UI changes, which was working fine on 3.13.0.2 and 3.13.1
Screenshot from 2023-04-18 10-53-15
Screenshot from 2023-04-18 10-53-09

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@mostafa-hisham The following markup:

```HTML
<img src="https://wprocketest.test/wp-content/uploads/2023/01/webinar-79.jpg" width=154 alt="">
```
which is valid HTML, is processed to this:
```HTML
<img width="1200" height="1600" src="https://wprocketest.test/wp-content/uploads/2023/01/webinar-79.jpg"154 alt="">
```
Note the stray `154` after the image's `src`. It doesn't cause issues as far as displaying the image goes, but will throw errors/warnings during validation.


With `trunk` the same becomes:
```HTML
<img width="1200" height="1600" src="https://wprocketest.test/wp-content/uploads/2023/01/webinar-79.jpg" width=154 alt="">	
```
Chrome/Firefox ignores `width=154` but an `Error: Duplicate attribute width.` is thrown during validation.

Can we somehow address this?

**Comment by mostafa-hisham** [comment]
@vmanthos Could you please check it again?

**Review by Mai-Saad — APPROVED** [review]
Working as expected
[testrail-report-483.pdf](https://github.com/wp-media/wp-rocket/files/11464873/testrail-report-483.pdf)
Note: some images may have dimensions different than nowprocket (differences exists in other ways on trunk too)

**Pull request merged**
