### PR TITLE
Fixes #4071 Exclude var gtm4wp from delay JS

### LINKED ISSUE #4071: Add Delay JS exclusion related to Google Tag Manager for WordPress
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Google Tag Manager for WordPress plugin is adding its JS variables without the usage of wp_enqueue_script. We might want to exclude the following pattern:
var gtm4wp_

**To Reproduce**
1. Install and configure Google Tag Manager for WordPress
2. Turn on Delay JS and keep our default exclusion list
3. Visit the page and check the console
4. See error related to: gtm4wp_id_prefix isn't defined

**Expected behavior**
Variable definitions should not be delayed.

**Additional context**

Google Tag Manager for WordPress is installed on 500,000+ active websites. 

The whole script:

```
<script type="text/javascript">//<![CDATA[
	var gtm4wp_datalayer_name = "dataLayer";
	var dataLayer = dataLayer || [];
	var gtm4wp_use_sku_instead        = 0;
	var gtm4wp_id_prefix              = '';
	var gtm4wp_remarketing            = 1;
	var gtm4wp_eec                    = 1;
	var gtm4wp_classicec              = false;
	var gtm4wp_currency               = 'HKD';
	var gtm4wp_product_per_impression = 10;
	var gtm4wp_needs_shipping_address = false;
	var gtm4wp_business_vertical      = 'retail';
	var gtm4wp_business_vertical_id   = 'id';
//]]>
</script>
```

Related ticket: https://secure.helpscout.net/conversation/1547254446/272681?folderId=273768

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by mostafa-hisham**
## Description
Delay JS exclusion  Google Tag Manager variable 

Fixes #4071

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?

- [x] Test locally 
- [x] Run unit and integration test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@mostafa-hisham @Tabrisrp before the error `gtm4wp_id_prefix` was displayed on the home page and product page, with this PR there is no error on the home page but we have another error on the product page (this error only when delay js is on with default exclusion) => I think we need to handle this, what do you think?

screenshot: 
Screenshot from 2021-06-22 17-12-21

Video:
https://user-images.githubusercontent.com/76941962/122951985-fc2b4900-d37d-11eb-9f78-051b6df662b9.mp4

**Comment by remyperona** [comment]
@Mai-Saad does it work if you exclude `var dataLayer_content`?

**Comment by Mai-Saad** [comment]
@Tabrisrp Yes, it works after exclude `var dataLayer_content` (No error on home nor product page)

**Comment by remyperona** [comment]
Ok let's add that also to the default exclusions @mostafa-hisham 

Sample code for the tests:
```
<script data-cfasync="false" data-pagespeed-no-defer type="text/javascript">//<![CDATA[
	var dataLayer_content = {"visitorDoNotTrack":1,"pagePostType":"product","pagePostType2":"single-product","pagePostAuthor":"remy","productRatingCounts":[],"productAverageRating":0,"productReviewCount":0,"productType":"simple","productIsVariable":0,"event":"gtm4wp.changeDetailViewEEC","ecommerce":{"currencyCode":"CAD","detail":{"products":[{"id":1762,"name":"Beanie","sku":1762,"category":"Accessories","price":18,"stocklevel":null}]}}};
	dataLayer.push( dataLayer_content );//]]>
</script>
```

**Comment by mostafa-hisham** [comment]
@Mai-Saad i excluded var dataLayer_content can you please check again?

**Review by Mai-Saad — APPROVED** [review]
Working as expected
[testrail-report-198.pdf](https://github.com/wp-media/wp-rocket/files/6699803/testrail-report-198.pdf)

**Review by remyperona — APPROVED** [review]

**Pull request merged**
