### PR TITLE
Cloudflare: Added logic to unregister

### LINKED ISSUE #6061: Further reduction of calls being made to Cloudflare APO
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
This issue is continuation of:
https://github.com/wp-media/wp-rocket/issues/6043

We'd like to enhance the Cloudflare cache clearing by adding URLs to their request instead of sending additional one.

For now this is not possible and blocked by:
https://github.com/cloudflare/Cloudflare-WordPress/issues/345

**Acceptance Criteria**
1. When updating the post only one request should be sent to Cloudflare API
2. Request should contain all URLs coming from `rocket_clean_files` array
3. URLs in the array should not be duplicated
4. We need to make sure taht the whole cache is not cleared while updating the single post

**Additional context**
I don't think someone from Cloudflare will resolve the above issue, we'll need to make the PR on our own.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Fix a issue where the Cloudflare API was called multiple times. For that we unregistered the call from Cloudflare plugin to let our logic in charge.

Fixes #6061 

## Type of change

*Please delete options that are not relevant.*

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

yes,
we had to unregister one more hook  `transition_post_status` from the Cloudflare plugin.

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof). (I need to have this PR install on rocketlabs to test the logic for real due to CF)
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@CrochetFeve0251 @piotrbak With this PR compared to trunk I see a reduction in the number of requests when `after_rocket_clean_files` fires, e.g. 11 vs 18. Still, these are 5 times the requests (2) I logged when WP Rocket wasn't there.

I did that by  adding the following:
```PHP
error_log( var_export( $files, true) . "\nResult: " . var_export( $this->responseOk($response), true ) . "\n", 3, ABSPATH . 'CLOUDFLARE_REQUESTS.log');
```
to the `/cloudflare/WordPressClientAPI.php` file in the `zonePurgeFiles()` method just before the `return` statement.

Both with the PR and `trunk`, `after_rocket_clean_files` fires twice. Each time a `DELETE` request is sent. These are followed by several more `DELETE` requests that aren't there when WP Rocket is deactivated.

Is there something more we can do about this?

**Comment by piotrbak** [comment]
@vmanthos What's the content of those?
`These are followed by several more DELETE requests`

**Comment by vmanthos** [comment]
@piotrbak Those are a combination of URLs, e.g. when updating `/hello-world` I got this:
https://gist.github.com/vmanthos/2e95fba69f647bf2b9aec30fb6534c0b

You can see there are only two entries of `rocket_clean_files`.

**Comment by vmanthos** [comment]
@piotrbak It seems those extra requests were coming from Remove Unused CSS - I had that disabled but there were probably some unfinished jobs. ¯\_(ツ)_/¯

The number of requests is the same as when WP Rocket is disabled. :tada: 

I'll continue the execution of the test plan and I'll add my findings when ready.

**Review by vmanthos — APPROVED** [review]
This is working as expected. :+1: 

**TestRail report:** [testrail-report-520.pdf](https://github.com/wp-media/wp-rocket/files/12555977/testrail-report-520.pdf)


**NOTE**
The following issue is still there:
https://github.com/wp-media/wp-rocket/issues/6078

**Comment by rfischmann** [comment]
Fingers crossed that this will be indeed fixed on 3.15.1! This issue has been pretty bad for our server since 3.14 was released last June.

**Pull request merged**
