### PR TITLE
Added logs to delayJs

### LINKED ISSUE #5786: Add Delay Javascript Execution to WP_ROCKET_DEBUG log output
**Is your feature request related to a problem? Please describe.**
Delay Javascript Execution optimization is not present in the WP_ROCKET_DEBUG, logger class output. 

**Describe the solution you'd like**
Add some log information to the WP_ROCKET_DEBUG output, this will be useful for the support team, to know which scripts are optimized by Delay Javascript Execution, if something is excluded per backend compatibility, admin UI , etc

**Additional context**

related slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1677693339218869

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Added logs to Delay Js. 
This helps Support Team to know which script is delayed or excluded and why.

Fixes #5786 

## Type of change

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Automated Test

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by CrochetFeve0251** [comment]
@alfonso100 would it match your need?

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@alfonso100 @piotrbak we list if script is delayed or excluded but for exclusion we will use the keword used for exclusion without classifying if from backend, UI or filter, is this what we want?
other thing, logs will be a lot i.e so far on test site for DJS 19K+, is this ok?
Screenshot from 2023-03-24 11-48-07
Screenshot from 2023-03-24 11-52-59

**Comment by piotrbak** [comment]
@Mai-Saad @CrochetFeve0251 Can we log **only excluded** scripts? Logging also delayed ones makes the log huge...

**Comment by CrochetFeve0251** [comment]
> @Mai-Saad @CrochetFeve0251 Can we log **only excluded** scripts? Logging also delayed ones makes the log huge...

@piotrbak We absolutely can but if I remember the support team wanted all.
Maybe we could check with them first?

**Comment by piotrbak** [comment]
@alfonso100 What do you think? Would excluded scripts only be enough? If we want to log also the delayed ones, the size of the log will be growing rapidly...

**Comment by alfonso100** [comment]
Yes! the excluded ones will be good. thanks 🙏

**Review by remyperona — APPROVED** [review]

**Review by Mai-Saad — APPROVED** [review]
Working as expected

**Comment by remyperona** [comment]
There is errors on the tests for this PR

**Comment by CrochetFeve0251** [comment]
> There is errors on the tests for this PR

This is fixed

**Pull request merged**
