### PR TITLE
Update process.php

### PR DESCRIPTION
**Pull request by drexlma**
#239 Fix 403 (and some other codes) pages are cached with check http_response_code

### CODE REVIEW

**Comment by drexlma** [comment]
sorry war falsch rum drin.

**Comment by Tabrisrp** [comment]
Hi,

Thank you for your contribution.

Did you check if the cache still works under PHP 5.3, since `http_response_code` was introduced in 5.4?

**Comment by drexlma** [comment]
PHP 5.3 is EOL since 14 Aug 2014 o.O 

Yes,  function_exists( 'http_response_code' ) <--

**Comment by Tabrisrp** [comment]
@GeekPress Can we make this part of the 3.0?

**Comment by GeekPress** [comment]
@Tabrisrp Yes! It will be easer without needed to have the 5.3 compatbility.

**Pull request merged**
