### PR TITLE
Reorganizes the test suites to our coding standard

### PR DESCRIPTION
**Pull request by hellofromtonya**
Makes our test suites comply with our ["Writing PHP Tests"](https://hub.wp-media.me/dev/dev-standards/writing-php-tests/) standard.

- Reorganizes the test classes to match the filesystem structure of their respective source code file
     - Moves all tests into `inc` folder
     - Moves all of the `inc/classes` tests into that folder
     - etc.
- Updates each affected test class namespace
- Renames test classes to comply with our coding standard
- Removes test method comments
- In a few cases, moves redundant mocking code to a `TestCase`. Keeping it DRY.
- Updates code coverage in phpunit.xml files

Notes:

- There are no source code changes.
- All changes are to the test suite only.

### CODE REVIEW

**Comment by hellofromtonya** [comment]
@Tabrisrp and @crystinutzaa I know this PR is HUGE. A few things to note:

1. No source code was touched. Therefore, there's no impact to 3.5's release.
2. All of the tests are now in `inc`. 
3. Because the test files moved and most were renamed, you'll see a deleted file and then the new file in the history. Argh. That makes it harder to code review. 
4. Tip: Go to the branch itself and look in the `tests` folder. I found that to be easier when checking the structure, namespace, and file names.

**Comment by Tabrisrp** [comment]
Shouldn't the tests for functions in `constants.php` be in a constants directory, and with the namespace `WP_Rocket\Tests\Unit\Inc\constants`?

**Comment by Tabrisrp** [comment]
There is some conflicts to fix

**Comment by hellofromtonya** [comment]
>There is some conflicts to fix

I was waiting for PR2348 to be merged, as it'll also cause merge conflicts. Then I can fix them both at the same time.

**Pull request merged**
