### PR TITLE
Apply more strict security rules with LCP

### LINKED ISSUE #6564: 3.16 - Secure LCP/ATF data from the AJAX endpoint and DB
**Context**
https://wp-media.slack.com/archives/CUT7FLHF1/p1713283119489009?thread_ts=1713277169.038639&cid=CUT7FLHF1

**Expected behavior**
- Consider escaping URLs before storing them
- Consider limiting the size storable in the lcp and viewport columns to prevent overloading the DB (up to 1k characters? per field?)
- Add unit tests on the AJAX endpoint and front-end LCP optimization to test against malformed URLs, including tentative of XSS, SQL injection, and too large data.

**Acceptance Criteria**
- Modify the beacon script to try and send ill-intentioned data to the LCP and ATF fields (XSS, SQL Injection). Launch the beacon script ; the data must either not be stored or sanitized/escaped before entering the DB. In debug mode, a log must be created to explain the data has been discarded because of this.
- Manually add ill-intentioned data to the LCP and viewport columns in the DB (XSS typically). Load the page with the LCP/ATF optimization. The ill-intentioned/corrupted URLs must not appear in the HTML (either sanitized/escaped, or optimization not applied). In debug mode, a log must be created to explain the data has been discarded because of this.
- Modify the beacon script to try and send very long data to the LCP and ATF fields. Trigger the beacon script. The long data must not be stored. In debug mode, a log must be created to explain the data has been discarded because of this.
- Those cases must be covered in built-in tests.

**Additional information**
The expected behavior might be reworked if we think about something else to protect against during the implementation. This has a bit of R&D.

### PR DESCRIPTION
**Pull request by wordpressfan**
# Description

Fixes #6564

Here we are applying more strict security rules when saving data into the DB and while retrieving the data on the frontend.

### User documentation

*Explain how this code impacts users.*

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
*Delete options that are not relevant.*

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [ ] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [ ] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [ ] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by MathieuLamiot** [comment]
Basic behavior seems OK when manually checking. I would say that to complete testing on this one, @wordpressfan you could:
1. Update the branch with the feature LCP/ATF branch (there are some needed fixes on the feature branch)
2. Run Rocket-E2E LCP/ATF tests (Mirael should be able to help) and make sure there is no regression with this PR compared to the feature branch (some tests fail on feature branch, the same should be failing on your PR).

(cc @wp-media/qa-team)

**Comment by remyperona** [comment]
Updated the PR from main branch to fix conflicts, but it's creating some failing tests

**Comment by remyperona** [comment]
I also think this should be validated with integration tests more than unit tests, because mocking the sanitizing and escaping functions is too complex, so if we really want to validate the input/output, we have ot run the tests with WordPress

**Review by MathieuLamiot — CHANGES_REQUESTED** [review]
Need integration tests to validate escaping & sanitizing with WordPress real methods.

**Comment by Miraeld** [comment]
Hello hello, 

I've fixed the unit tests and added integrations tests :)

**Review by MathieuLamiot — APPROVED** [review]

**Comment by Miraeld** [comment]
About QA Tests, I don't know if there are any test plans for it, but I've been playing on my local environment and e2e from this branch, and I don't see anything that wasn't working before. So for me it's fine. 
It's also covered by integration tests, so for me I would put it in QA Done @MathieuLamiot

**Comment by MathieuLamiot** [comment]
@Miraeld as mentioned [here](https://github.com/wp-media/wp-rocket/pull/6584#issuecomment-2077826964), I think making sure there are no regressions with Rocket-E2E 3.16 testing would be fine.

**Comment by MathieuLamiot** [comment]
And if it's all ✅ , don't forget to merge to avoid conflicts later on :)

**Comment by Miraeld** [comment]
I confirm, there are no regression on the e2e tests. ✅

**Pull request merged**
