### PR TITLE
Closes #6468: Imagify 3rd Compatibility

### LINKED ISSUE #850: After updating to 2.2 WP Rocket's WebP addon doesn't detect Imagify as a WebP compatible plugin
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
After updating to 2.2 WP Rocket's WebP addon doesn't detect Imagify as a WebP plugin anymore

**To Reproduce**
1. Update Imagify to 2.2
2. On WP Rocket, go to the WebP addon
3. See the message:  `We have not detected any compatible WebP plugin!`

**Expected behavior**
we should detect Imagify as a WebP compatible plugin

**Screenshots**
image

**Additional context**
ticket https://secure.helpscout.net/conversation/2533421582/479330?folderId=273761

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

### LINKED ISSUE #6468: Imagify update broke third compatibility
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
After updating to 2.2 WP Rocket's WebP addon doesn't detect Imagify as a WebP plugin anymore

**To Reproduce**
1. Update Imagify to 2.2
2. On WP Rocket, go to the WebP addon
3. See the message:  `We have not detected any compatible WebP plugin!`

**Expected behavior**
we should detect Imagify as a WebP compatible plugin

**Screenshots**
image

**Additional context**
ticket https://secure.helpscout.net/conversation/2533421582/479330?folderId=273761

**Acceptance Criteria (for WP Media team use only)**
On WP Rocket's end, expectations are as follows:
1. Imagify is disabled the compatibility is not displayed, no matter what nextgen display options were set when it was active
2. When Imagify is enabled and nextgen display is enabled, we should display compatibility banner and disallow usage of webp addon
3. When imagify is enabled and nextgen is disabled, we should display the compatibility banner saying that Imagify is enabled but webp display is disabled

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #6468

### Technical documentation

Since Imagify 2.2 update, an option has been renamed so we need to take it into account within WP Rocket to ensure the compatibility.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

# Checklists

## Feature validation

- [ ] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [x] I listed the introduced external dependencies explicitely on the PR.
- [x] I validated the repo-specific guidelines from CONTRIBUTING.md.

### CODE REVIEW

**Review by Khadreal — APPROVED** [review]

**Comment by Miraeld** [comment]
@hanna-meda I've made the change you mentioned [here](https://github.com/wp-media/wp-rocket/issues/6468#issuecomment-1985510332)

**Review by remyperona — CHANGES_REQUESTED** [review]
There is more references to the old option name in this class, can you also update them?

**Comment by Miraeld** [comment]
I've changed some more things @Tabrisrp

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Miraeld Thanks for the PR.

- Related test sheet https://docs.google.com/spreadsheets/d/159cC43SYw-1ZHjLAdqac4yNCypxuRHMNVRkPA76lQ6A/edit#gid=0 => light red cells can have separate GH as per discussion
- Regression: if we have avif off, webp on by default and display next gen off 
then we enabled webp add on at WPR
then we enabled display at imagify
then we refresh wpr addon page => addon is enabled in UI while it shall be off dimmed
will leave it to @piotrbak if we will fix here or not
- this warning (probably after switch to trunk at imagify), need further investigation and reproducible steps
`[12-Mar-2024 21:00:47 UTC] PHP Warning:  Undefined array key "display_webp_method" in /home/mai/Local Sites/apache/app/public/wp-content/plugins/wp-rocket/inc/classes/subscriber/third-party/plugins/Images/Webp/class-imagify-subscriber.php on line 227`

**Comment by piotrbak** [comment]
Let's see if that's an easy fix to door giht away (2nd point). If not, we'll leave it like it is

**Comment by Mai-Saad** [comment]
@Miraeld thanks, 2nd point is fixed now :tada:  (updated results in sheet 2 https://docs.google.com/spreadsheets/d/159cC43SYw-1ZHjLAdqac4yNCypxuRHMNVRkPA76lQ6A/edit#gid=1542810267)
If @piotrbak is ok in not detecting imagify in the following cases for now then we can merge this one 
- Avif is on , webp is off, display next-gen off
- Avif on , webp on using filter, display next-gen off

**Comment by piotrbak** [comment]
@Mai-Saad that's fine

Thank you @Miraeld

**Comment by Mai-Saad** [comment]
> this warning (probably after switch to trunk at imagify), need further investigation and reproducible steps
[12-Mar-2024 21:00:47 UTC] PHP Warning:  Undefined array key "display_webp_method" in /home/mai/Local Sites/apache/app/public/wp-content/plugins/wp-rocket/inc/classes/subscriber/third-party/plugins/Images/Webp/class-imagify-subscriber.php on line 227

The warning is happening with the following scenario, we need to fix it:
1- wpr active 
2- enable webp
3- install and activate imagify 2.1.3
@Miraeld can you please check?
Thanks for @wordpressfan  to reproduce.

For testing the fix of warning we need:

- [x] 1- install and activate imagify 2.1.3 while webp addon on 
- [x] 2- install and activate imagify 2.1.3 while webp addon off
- [x] 3- repeat 1,2 for imagify 2.2.0.1
- [ ] 4- update from 2.1.3 while webPoption/display on/on, on/off, off/off while webp addon on/off
- [ ] 5- rollback from 2.2.0.1 while avif/display on/on,  off/on, off/off while webp addon on/off

**Pull request merged**
