### PR TITLE
Fix/5585 prevent clearing all cache on restore

### LINKED ISSUE #5585: Restore post from trash clears the entire cache
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When you restore a post from the trash, the entire language cache is cleared. It will also clear the entire cache if WPML is not used.

After extensive debugging, i found the issue:

Function causing the issue:
inc/functions/files.php:rocket_clean_files

specifically:
get_rocket_parse_url( $url );

this function returns:
[host] => example.com
[path] => /de/
[scheme] => https
[query] => page_id=14136
[fragment] =>

After restoring the post from the trash, the URL of the post is https://example.com/de/?page_id=14136.
However, since only the path is used to determine the folder to delete, the entire cache folder for that language is deleted.

**To Reproduce**
1. Delete Post
2. Restore Post from Trash
3. go to wp-content/cache/wp-rocket/your-domain/
4. See folder is empty

**Expected behavior**
Should not do anything because the post is a draft when restored from the trash.

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Prevent clearing all cache on restoring a post.

We fixed that by finding back the right url from the post to replace the path by the right one.

Fixes #5585

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Test locally

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by jeawhanlee — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@CrochetFeve0251 Thanks for the PR. Currently, the cache is not cleared when restoring a page but it is cleared when restoring a product or post or media or custom post type or product. Can you please check?

**Review by mostafa-hisham — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@CrochetFeve0251 it isnot working now for any type i.e post , page , media. Can you please check? (merged develop to branch locally)

**Comment by CrochetFeve0251** [comment]
> @CrochetFeve0251 it isnot working now for any type i.e post , page , media. Can you please check? (merged develop to branch locally)

@Mai-Saad you are right there was a typo I added when I changed code to match standards you can test it is fixed now.

**Review by Mai-Saad — APPROVED** [review]
Working as expected
[testrail-report-447.pdf](https://github.com/wp-media/wp-rocket/files/10706593/testrail-report-447.pdf)

**Comment by DahmaniAdame** [comment]
This is creating the following issue with the UltimateMember plugin.
More details here thanks to @engahmeds3ed - https://wp-media.slack.com/archives/C056ZJMHG0P/p1685005570728209

**Pull request merged**
