### PR TITLE
Persistent dismiss of RUCSS success notice

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Persistently dismiss the RUCSS success notice, until the next time the used CSS is cleared, or the RUCSS is re-enabled.

Also update the content inside the RUCSS notices.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] Automated tests
- [x] Manual testing in the admin

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by mostafa-hisham — APPROVED** [review]

**Comment by Mai-Saad** [comment]
Fixes [30](https://github.com/wp-media/nodejs-treeshaker/issues/30), [31](https://github.com/wp-media/nodejs-treeshaker/issues/31)

Dismiss cases:
- Can dismiss notice after the success => won't appear after refresh page
- Can't dismiss notice before success => will appear again after refresh page

Message displayed after dismiss when:
- Notice displayed after clear used CSS while preload is enabled/disabled
- Notice displayed when reenabled the option
- Notice displayed when import settings which reenable RUCSS

Message content is correct if (contains WP Rocket:):
- preload is disabled => recommend enabling it
- preload is enabled => nothing mentioned for preload

**Comment by Mai-Saad** [comment]
The message is working fine in most of the cases but:
1- If we changed safelist => table is cleared and recreate home page but we display no msg about that, shouldn't we display the counter msg in this case? @Tabrisrp 
2- if we clear used CSS while preload is disabled, we mention at the success that home page used CSS is generated although it is not => we will probably try to fix this in separate PR

**Comment by remyperona** [comment]
@piotrbak Do we want to display the notice after updating the safelist?

**Comment by piotrbak** [comment]
@Tabrisrp Yes, let's do it
@Mai-Saad Thank you, good catch!

**Comment by remyperona** [comment]
It's added 👍🏼

**Review by Mai-Saad — APPROVED** [review]
Working fine now with safelist.

**Pull request merged**
