### PR TITLE
Closes #5742: HTML Shown in Sucuri add-on section

### LINKED ISSUE #5742: Some HTML is shown on WPR dashboard when Sucuri add-on is enabled and you go to Modify options
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version [*] checked 
- Used the search feature to ensure that the bug hasn’t been reported before [*] no previous issues related

**Describe the bug**
When Sucuri add-on is enabled, and you go to Modify options, some HTML code is shown in WPR dashboard: http://imageshack.com/a/img924/9611/IRbFd0.png

**To Reproduce**
1. Go to Add-ons tab 
2. Enable Sucuri add-on
3. Click on Modify options

**Expected behavior**

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description
Bypass html escaping for sucuri api key label.

Fixes #5742 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manual Test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by remyperona — CHANGES_REQUESTED** [review]
I don't like exceptions like this, I think we should change the label to remove the code tags instead

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@jeawhanlee Thanks for the PR `<code>` tag isnot displayed now. However on [doc](https://docs.wp-rocket.me/article/1120-sucuri-add-on) `{32 characters}/{32 characters}` was highlighted in grey, can we do the same here?

Screenshot from 2023-03-28 10-02-31

**Comment by jeawhanlee** [comment]
> @jeawhanlee Thanks for the PR `<code>` tag isnot displayed now. However on [doc](https://docs.wp-rocket.me/article/1120-sucuri-add-on) `{32 characters}/{32 characters}` was highlighted in grey, can we do the same here?
> 
> Screenshot from 2023-03-28 10-02-31

@Mai-Saad This was done in the first commit for this PR but as per @Tabrisrp comment [here](https://github.com/wp-media/wp-rocket/pull/5814#pullrequestreview-1341635796), it was better to take out the code tag to avoid such exceptions.

**Comment by Mai-Saad** [comment]
@jeawhanlee It seems fine for me. @piotrbak what do you think?

**Comment by piotrbak** [comment]
Agreed. @Mai-Saad

**Review by Mai-Saad — APPROVED** [review]
Working as expected then

**Pull request merged**
