### PR TITLE
Closes #4303 Update delay JS script

### LINKED ISSUE #4303: Update Delay JS script to the latest version
For the 3.9.3 release, we need to update the Delay JS script to the latest version available. This version fixes a bug to avoid the user clicks on a button and nothing happens.

Branch to be merged: `replay-events`

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Update delay JS script to its latest version, with better handling of click events happening before the scripts are loaded.

Fixes #4303

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality)

## How Has This Been Tested?

- [x] Automated tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Existing unit tests pass locally with my changes

### CODE REVIEW

**Review by iCaspar — APPROVED** [review]

**Comment by piotrbak** [comment]
@Tabrisrp What exactly should be tested here?

**Comment by remyperona** [comment]
@piotrbak From Gael:
> This pull request fixes the following issue:
>
>    the JS is not loaded yet (delayed)
>    the user clicks on a button that requires JS
>    the JS gets loaded
>    and... nothing happens about the clicked button
>
> With this change, click events are stored in a queue, then triggered when all the JS was loaded.

**Comment by Mai-Saad** [comment]
Do we expect double click on links at Safari fixed here? I can see it's still there.

https://user-images.githubusercontent.com/76941962/131669797-e907d32f-c2a4-4c37-8636-0676e2e62400.mp4

**Review by Mai-Saad — COMMENTED** [review]
Working as expected.
[testrail-report-246.pdf](https://github.com/wp-media/wp-rocket/files/7107187/testrail-report-246.pdf)

**Comment by inewton24** [comment]
> @piotrbak From Gael:
> 
> > This pull request fixes the following issue:
> > the JS is not loaded yet (delayed)
> > the user clicks on a button that requires JS
> > the JS gets loaded
> > and... nothing happens about the clicked button
> > With this change, click events are stored in a queue, then triggered when all the JS was loaded.

Don't work on IOS 14 Safari, but work on IOS 14 Chrome. And if script is excluded from delay - we have double click on both browsers. Real device, not emulator. Emulator IOS 14 Safari is working.

**Pull request merged**
