### PR TITLE
Closes #5121 on Remove rocket CDN subscription link

### LINKED ISSUE #5121: Cancel RocketCDN subscription
**Is your feature request related to a problem? Please describe.**

There are 2 ways to stop a RocketCDN subscription: 
- from the WP Rocket plugin, CDN tab
- from the account pages of WP Rocket, RocketCDN Billing tab

We would like to keep only one of these 2 ways. 

**Describe the solution you'd like**

In the WP Rocket plugin, CDN tab, remove the `Manage Subscription` link.

Capture d’écran 2022-06-08 à 15 32 19

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

This PR closes the request on removing rocket CDN subscription management on WPR.

Fixes #5121 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

This solution is no way different from the proposed.

# Checklist:

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by jeawhanlee** [comment]
Do we need to also remove in the related translation`(.po)` files?

**Review by CrochetFeve0251 — APPROVED** [review]

**Comment by remyperona** [comment]
You don't need to edit the po file

**Comment by piotrbak** [comment]
@jeawhanlee The branch is causing fatal error. We also need to remove this call:
https://github.com/wp-media/wp-rocket/blob/08d91c6d504db5fe4e44957aef6baecb1238c2b8/inc/Engine/CDN/RocketCDN/AdminPageSubscriber.php#L59

**Review by mostafa-hisham — APPROVED** [review]

**Review by piotrbak — APPROVED** [review]
Working as expected. No report because of TestRail problems

**Pull request merged**
