### PR TITLE
Fixed ESI comment tags removed on HTML minify.

### PR DESCRIPTION
**Pull request by juliquiron**
Solves issue #253

### CODE REVIEW

**Comment by GeekPress** [comment]
@juliquiron It seems to have a conflict on the wp-rocket.php. Will it be possible to fix it to be able to accept the merge?

Thanks

**Comment by juliquiron** [comment]
Yes, but the conflict is in the version definition added by Tabrisrp. @GeekPress which should be the version `2.9` or `2.8.23`?

**Comment by GeekPress** [comment]
@Tabrisrp The right version should be 2.8.23.

**Comment by juliquiron** [comment]
So in this case makes no sense to have the base branch `branch-2.9`... The conflict is this:
```
  6 <<<<<<< HEAD
  7 Version: 2.9
  8 =======
  9 Version: 2.8.23
 10 >>>>>>> master
```
and
```
 26 <<<<<<< HEAD
 27 define( 'WP_ROCKET_VERSION'             , '2.9' );
 28 =======
 29 define( 'WP_ROCKET_VERSION'             , '2.8.23' );
 30 >>>>>>> master
```
so let's set the correct base branch and this will solve the conflict. In other case this should  be solved on merge process...

**Comment by GeekPress** [comment]
@juliquiron My bad, sorry I though it was related to an other constant. For WP_ROCKET_VERSION in the branch "branch-2.9", the version must be 2.9

**Comment by juliquiron** [comment]
@GeekPress updated, no merge conflicts now.

**Comment by GeekPress** [comment]
@juliquiron Thanks for your contribution, could you contact us at contact@wp-rocket.me and provide us your WP Rocket's account email? We will offer you 3 months free on your expiration date.

**Comment by juliquiron** [comment]
Thanks! service@netzstrategen.com

**Comment by GeekPress** [comment]
Thanks, it's done 😃

**Pull request merged**
