### PR TITLE
Fix Preload to add legacy sitemaps

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Fetch old sitemap in the `sitemaps` option to prevent a wave of request from the customers to the support.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [ ] Automatic tests.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by remyperona** [comment]
@piotrbak the option is removed from the code, so the next time the settings are saved, it's going to be removed from the DB and not available anymore after

**Comment by piotrbak** [comment]
@Tabrisrp Ah, I thought it's not removed from the options API. Do you have any idea if we have option to automatically preserve custom sitemaps from the previous version? 🤔

**Comment by remyperona** [comment]
I added the value to the hidden fields, it should be preserved that way.

**Review by engahmeds3ed — APPROVED** [review]

**Review by piotrbak — APPROVED** [review]
Works as expected.

**Pull request merged**
