### PR TITLE
Add RUCSS notices for processing & success

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Add admin notices on WP Rocket settings page when enabling RUCSS or when clearing the used CSS.

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## How Has This Been Tested?

- [x] Enabling RUCSS in the options
- [x] Clearing the used CSS from the action button

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by piotrbak** [comment]
@Tabrisrp Could you merge new approach into this PR?

**Comment by remyperona** [comment]
Done

**Comment by piotrbak** [comment]
@Tabrisrp We need to handle better the update from previous version, right now:
1. RUCSS is enabled in previous version
2. We update the plugin
3. The success notice is displayed

I think we have two options here:
1. During the update clear the Used CSS + Cache, make a request to the homepage and display notice with counter.
2. Don't clear the Used CSS + cache and don't display the notice at all
What do you think?

The `seconds` and `batch size` values should be the ones that are coming from the actual batch + interval values, is this the case now? 🤔

**Comment by remyperona** [comment]
> The seconds and batch size values should be the ones that are coming from the actual batch + interval values, is this the case now?

Yes

For the notice, currently I don't have anything to prevent its display except when the processing transient is set. We could clear the used CSS and cache, knowing that the new system is going to be better too, so it can be a good idea?

**Comment by piotrbak** [comment]
@Tabrisrp Yes, I think so. Will we be able to preload the homepage too?

**Comment by piotrbak** [comment]
@Tabrisrp The batch size + interval values are coming from those filters, right? 
https://github.com/wp-media/wp-rocket/blob/be15a9d516f543713449095042c895baf06afb51/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L486
https://github.com/wp-media/wp-rocket/blob/be15a9d516f543713449095042c895baf06afb51/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L175

**Comment by remyperona** [comment]
@piotrbak I added the clear of cache and used CSS + homepage preload

The filters are correct yes

**Comment by piotrbak** [comment]
@Tabrisrp I think we're ready to go here.

**Pull request merged**
