### PR TITLE
Closes #6174: Change the order of language menu

### LINKED ISSUE #6174: Make the "All languages" button the first option inside the "Clear cache" menu
**Is your feature request related to a problem? Please describe.**
Customers using multilingual plugins need to hover on the "Clear cache" option, and scroll down to the bottom to reach and click on the "All languages" button, when apparently, that's the most common to use.

**Describe the solution you'd like**
The "All language" button should be easier to access by being the top link under the "Clear cache" option.

**Additional context**
Ticket request: https://secure.helpscout.net/conversation/2357195073/441899?folderId=2675957

### PR DESCRIPTION
**Pull request by Khadreal**
## Description
Change the language order for the admin bar, move all language to the top of the options.

Fixes #6174 

## Type of change
- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?
No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

### CODE REVIEW

**Review by jeawhanlee — APPROVED** [review]

**Comment by Mai-Saad** [comment]
The clear menu has all languages option 1st now for translate press and Polylang but still the last option for WPML. Is this acceptable @piotrbak ?

Note:
Not related to PR and already on the trunk, with Polylang, the clear cache of sublang sometimes not working i.e on test site clear cache of ar not working while working for fr . And if we clear main lang (en), it will clear en and ar. (added comment here https://github.com/wp-media/wp-rocket/issues/6094#issuecomment-1888669774)

**Comment by piotrbak** [comment]
@Mai-Saad @Khadreal As far as I can see, WPML is handled here:
https://github.com/wp-media/wp-rocket/blob/8b64400a9c36ec5c0a26df238946cea389fc2a34/inc/functions/i18n.php#L12

**Comment by Mai-Saad** [comment]
Working as expected now. (tested with translatepress, WPML, and Polylang)
Note: already on the trunk, while using WPML, at page view, the list UI isnot displayed probably.
Screenshot from 2024-01-22 11-03-38

**Comment by Khadreal** [comment]
Please could you share a screenshot of what the list UI looks like ? cc @Mai-Saad 

Edit - The screenshot wasn't showing when I saw the comment first but could see it when I take a look at it again

**Comment by Khadreal** [comment]
Screenshot 2024-01-23 at 10 48 55
The UI was displaying properly when I check https://rocketlabsqa.ovh/wp-admin/

**Pull request merged**
