### PR TITLE
fix noscript issue

### LINKED ISSUE #4119: Multiple CSS files arenot removed from page source while RUCSS + Woocommerce are enabled
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.0.5
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the bug**
CSS external files aren't removed from the source while Woocommerce is enabled

**To Reproduce**
Precondition:
- Woocommerce enabled
- RUCSS enabled after fresh install

1. Either create a new page template and check the source or
2. Clear used CSS and access existing page template and check its source i.e https://new.rocketlabsqa.ovh/template4071/
3. Multiple CSS files are still in the source 

**Expected behavior**
CSS files are removed from the source

**Screenshots**
Screenshot from 2021-06-30 18-50-08

**Additional context**
- Disable Woocommerce plugin will fix the problem
- After discussion with @engahmeds3ed it impacts from this change #4017 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
## Description

Adjust the noscript exclusion regex.

Fixes #4119 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [ ] Add test fixtures on the code level.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by iCaspar — APPROVED** [review]

**Comment by piotrbak** [comment]
There are some issues with the regex. After first round of tests we were removing the content from `<noscript></noscript>` 

The latest update brought us to the starting point when the files between the multiple `<noscript>` tags are preserved. I'm in touch with @engahmeds3ed. Writing it here for the records only

**Comment by engahmeds3ed** [comment]
@piotrbak We will take another approach in code to make the regex simpler as suggested by @iCaspar to search only on the HTML after removing all noscripts in the page.

I'm not sure that we can release today as it's too late for all.

**Review by Mai-Saad — APPROVED** [review]
Already tested by @piotrbak yesterday and all tests went fine.
[testrail-report-205.pdf](https://github.com/wp-media/wp-rocket/files/6753204/testrail-report-205.pdf)
**update:** we did update in regex to handle space before closing > and rechecking tests

**Comment by Mai-Saad** [comment]
Tests passed.
note: 
- we may have issues related to styles of new templates, not related to this PR (will check if we have GH for that)

**Pull request merged**
