### PR TITLE
Closes #7064 CDN Compatibility for host fonts locally

### LINKED ISSUE #7064: 3.18 - CDN compatibility part
**User Story**
As a user with the CDN option, I want locally stored Google Fonts and CSS files to be loaded from the CDN

**Acceptance Criteria**
1. The feature will rewrite paths to the CSS files to the CDN paths
2. The feature will rewrite paths to the fonts to the CDN paths
3. The feature will rewrite paths to the fonts to the CDN paths when the CSS method will be set to be internal one with the filter

### PR DESCRIPTION
**Pull request by remyperona**
# Description

Fixes #7064 

Apply CDN URL on local fonts CSS & fonts files

## Type of change

- [x] Sub-task of #7039 

## Detailed scenario

- Enable CDN
- local CSS and fonts should have their URLs rewrittent to the CDN URL

### Documentation

Use the existing filters we have `rocket_css_url` and `rocket_css_content` to apply CDN.

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.

### CODE REVIEW

**Review by Miraeld — APPROVED** [review]

**Comment by hanna-meda** [comment]
Thanks for the PR, @remyperona. 
After testing it, I came across one finding:
	•	When a CDN is set up and then disabled, the CDN path sometimes remains in the CSS for font URLs, while other pages correctly display the local path.
Page example with local path in both CSS and font URLs (inside CSS file) =>
https://newer.rocketlabsqa.ovh/gf-v1v2-image/
Page example where local path in CSS but CDN path for font URLs (inside CSS file) =>
https://newer.rocketlabsqa.ovh/merianda-obscure-gf-font/
Screenshot 2024-12-06 at 19 03 40
Note: This can be reproduced also when using One's CDN service.

**Comment by remyperona** [comment]
Good catch, I fixed this in the PR that is handling clearing of the data https://github.com/wp-media/wp-rocket/pull/7110/commits/1ca09d9d0caf84b37ce7d7b7ee4aa8cba4aeee0f

**Comment by MathieuLamiot** [comment]
Should this go back to QA then? @remyperona @hanna-meda

**Comment by hanna-meda** [comment]
> I fixed this in the PR that is handling clearing of the data https://github.com/wp-media/wp-rocket/commit/1ca09d9d0caf84b37ce7d7b7ee4aa8cba4aeee0f

Checked the fix for [this](https://github.com/wp-media/wp-rocket/pull/7169#issuecomment-2523755100) on https://github.com/wp-media/wp-rocket/commit/1ca09d9d0caf84b37ce7d7b7ee4aa8cba4aeee0f but it can still be reproduced for some pages. @remyperona, if you'll continue to fix it on [task/7071-clear-data](https://github.com/wp-media/wp-rocket/compare/task/7071-clear-data) PR, then this task can be closed as done.

**Review by hanna-meda — APPROVED** [review]
Closing this as done with note that TCs in [TP](https://wpmediaqa.testrail.io/index.php?/runs/view/938&group_by=cases:section_id&group_order=asc) will be included and retested under #7110's testing plan. 
cc @Mai-Saad

**Pull request merged**
