### PR TITLE
Closes #6158: Problem with handling identical DOM elements with Lazyload background css images

### LINKED ISSUE #6158: Problem with handling two identical DOM elements with Lazyload Background CSS Images
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When we're dealing with two identical DOM elements with backgrounds, our script is not handling this properly.

**To Reproduce**
1. Use the latest WP Rocket version
2. Use the following markup https://pastebin.com/VnYkwUgv
3. Enable the Lazyload Background CSS Images feature
4. Visit the page in incognito mode
5. Images are not loaded with `variable not defined` message

**Additional Context**
This is not regression when comparing to https://github.com/wp-media/wp-rocket/pull/6150

**Acceptance Criteria (for WP Media team use only)**
1. We should handle two or more identical DOM elements having background images
2. We should not introduce regression compared to the previous state. The templates that could be used for e2e tests are available [here](https://github.com/wp-media/rocket-test-data/blob/master/templates/ll_bg_css_single_colon.php) and [here](https://github.com/wp-media/rocket-test-data/blob/master/templates/ll_bg_css_double_colon.php).

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

This PR fixes the issue with background images not being loaded when the same selector targets multiple identical elements.

Fixes #6158 

## Type of change

- Bug fix (non-breaking change which fixes an issue).

## Is the solution different from the one proposed during the grooming?
No with additions

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [x] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).

*Please describe any additional tests you performed.*
Manual Tests

### CODE REVIEW

**Review by CrochetFeve0251 — APPROVED** [review]

**Comment by CrochetFeve0251** [comment]
@vmanthos we should check if that has an impact on the performance

**Comment by vmanthos** [comment]
@jeawhanlee Thank you for the PR. The issue is resolved and the same goes for #6162.

Compared to `trunk` we are adding `data-rocket-lazy-bg`+`hash="loaded"` multiple times.

With `trunk`:
```HTML
<p class="background-image" data-rocket-lazy-bg="loaded">
```

With the PR:
```HTML
<p class="background-image" data-rocket-lazy-bg-d25b1213-8e34-47a0-b758-e24a86bc4be8="loaded" data-rocket-lazy-bg-8b7d8d75-736c-420a-a0be-b29038120de3="loaded" data-rocket-lazy-bg-3a4e5116-84c5-4db7-8f8e-ee1a1cf347ae="loaded" data-rocket-lazy-bg-5535c50e-07d4-44ee-8ddb-1c66dc167ef1="loaded" data-rocket-lazy-bg-e7398c8e-49cf-4329-bdd4-c350276d080a="loaded" data-rocket-lazy-bg-d0d3cf36-64b0-49c0-b7ea-ea21c0ed783e="loaded">
```

Although this doesn't seem to affect anything, it makes the code harder to check, e.g. when troubleshooting an issue. Is this something we can improve? :pray:

**Comment by CrochetFeve0251** [comment]
> @jeawhanlee Thank you for the PR. The issue is resolved and the same goes for #6162.
> 
> Compared to `trunk` we are adding `data-rocket-lazy-bg`+`hash="loaded"` multiple times.
> 
> With `trunk`:
> 
> ```
> <p class="background-image" data-rocket-lazy-bg="loaded">
> ```
> 
> With the PR:
> 
> ```
> <p class="background-image" data-rocket-lazy-bg-d25b1213-8e34-47a0-b758-e24a86bc4be8="loaded" data-rocket-lazy-bg-8b7d8d75-736c-420a-a0be-b29038120de3="loaded" data-rocket-lazy-bg-3a4e5116-84c5-4db7-8f8e-ee1a1cf347ae="loaded" data-rocket-lazy-bg-5535c50e-07d4-44ee-8ddb-1c66dc167ef1="loaded" data-rocket-lazy-bg-e7398c8e-49cf-4329-bdd4-c350276d080a="loaded" data-rocket-lazy-bg-d0d3cf36-64b0-49c0-b7ea-ea21c0ed783e="loaded">
> ```
> 
> Although this doesn't seem to affect anything, it makes the code harder to check, e.g. when troubleshooting an issue. Is this something we can improve? 🙏

@vmanthos to answer you each hash is the hash from the CSS variable loaded. I think it is more clear cause with this system we can now clearly know what image is loaded on the tag where before we didn't got that information.

Concerning the removal that gonna require to find a totally new fix and this syntax is a part of the solution.

**Review by vmanthos — APPROVED** [review]
This is working as expected! :+1: 

**TestRail Report:** [testrail-report-526.pdf](https://github.com/wp-media/wp-rocket/files/12647526/testrail-report-526.pdf)


**NOTE**

#6162 is resolved as well.

**Pull request merged**
