### PR TITLE
Modify RUCSS regex to match links with rel=preload and as=style or as=script

### LINKED ISSUE #4284: CSS files added using link preload might not be detected by our regex and processed by RUCSS
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The following markup is not caught by our regex and stays in the HTML source:
`<link rel="preload" id='preload-test' href="https://domain.com/wp-content/rocket-test-data/styles/minifycss_style.css" media='all' as='style' />`

**To Reproduce**
1. Add CSS file to the source using the above markup
2. Enable RUCSS
3. Visit the page
4. The CSS file stays in the source

**Expected behavior**
This is correct markup, we should handle it

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### LINKED ISSUE #4285: JS files added using link preload are not detected by our regex and not processed by JS fetcher
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The following markup is not caught by our regex and not sent to the SaaS:
`<link rel="preload" href="https://domain.com/wp-content/rocket-test-data/scripts/print-helloworld-v3.js" as="script">`

**To Reproduce**
1. Add JS file to the source using the above markup, make sure it contains something that would be used by JS fetcher
```
var element = document.getElementById("demo");
element.classList.add("mystyle3");
```
2. Make sure div with id `demo` is present in the source, and style for `.mystyle3` too
3. Enable RUCSS
4. Visit the page
5. The `.mystyle3` is not preserved

**Expected behavior**
This is correct markup, we should handle it

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by iCaspar**
## Description

During our investigation of https://github.com/wp-media/tree-shaker/issues/196 we discovered that a [similar case occurs with Aveda/ThemifyBuilder](https://github.com/wp-media/tree-shaker/issues/196#issuecomment-904718146).

In this case, unlike the original Divi issue, links with `rel="preload" as="style"` are not identified as stylesheets on the rocket side and therefore never (a) sent to warmup and (b) never removed from the page in the process of replacing original stylesheets with the usedCSS styles. The net effect is that, though the pages appear normally, they get no benefit from the RUCSS with respect to these stylesheets.

This PR modifies the regex used to identify stylesheets in the ResourceFetcher to include them.

Fixes #4284 
Fixes #4285 
Companion fix to https://github.com/wp-media/tree-shaker/issues/196. Note: Treeshaker PR **_MUST_** merge first to avoid breaking site appearance where above stylesheet html is used.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

See grooming and solution for https://github.com/wp-media/tree-shaker/issues/196#issuecomment-904718146.

## How Has This Been Tested?

TBA

# Checklist:

Please delete the options that are not relevant.

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Review by piotrbak — CHANGES_REQUESTED** [review]
@iCaspar We're fetching those CSS files now, but we're not removing the files itselves from source. Examples:
```
<link rel='preload' id='preload-test' href="/wp-content/rocket-test-data/styles/minifycss_style.css" media='all' as='style' />
<link rel='preload' id='preload-test-3' media='all' as='style' href="https://domain.com/wp-content/rocket-test-data/styles/font-display-applied.css" />
```

**Comment by piotrbak** [comment]
@iCaspar Also, there's a problem with JS handling, I can see that:
1. Both JS types are added to the database resources (`<script type='text/javascript'` and `<link rel="preload"` )
2. CSS classes added via `<script>` are preserved in the Used CSS
3. CSS classes added via `<link>` are not preserved in the Used CSS

**Comment by iCaspar** [comment]
Note on JS handling comments:
Both are accounted for in the resources table ✔️ 
CSS classes added via JS <link> are not preserved in the Used CSS -- will need fixed on the treeshaker side.

**Comment by iCaspar** [comment]
@wp-media/qa @piotrbak 
I think this is as far as we can go on the rocket side.
We should be removing processed preload-link-as-style tags from the html now.

The JS via preload-as-script not being included in UsedCSS will need to be fixed on the treeshaker side as the usedCSS is generated there.

**Comment by remyperona** [comment]
Closing this PR in favour of #5019

**Pull request closed without merging**
