### PR TITLE
Introduce PHPStan

### PR DESCRIPTION
**Pull request by szepeviktor**
Adding proper configuration, continuing the work of @Tabrisrp

### CODE REVIEW

**Comment by szepeviktor** [comment]
To benefit from @phpstan properties need to be defined (remove ignored error from `phpstan.neon.dist`) and tidy up PHPDoc blocks.

Level 4 is "normal", from that on robust code begins :)

**Comment by szepeviktor** [comment]
My suggestion is to have only have clean PHP files:

1. `namespace WP_Rocket; class xyz { ... }`
1. or `function get_rocket_xyz() { ... }`

No class instantiations and no add_action()-s outside functions.
See the output of `grep -rn '^\(add_action\|add_filter\)' inc/`

**Comment by szepeviktor** [comment]
Hello @Tabrisrp !

What would you like me to do?

**Comment by Tabrisrp** [comment]
Hi @szepeviktor,

thank you for contributing to the plugin!

Nothing more to do, we're going to review it, and integrate it in the plugin. Very useful to have your direct input for this one!

**Pull request merged**
