### PR TITLE
Savvii cache sync and move to new architecture

### LINKED ISSUE #1075: Savvii Compatibility. Caches not in sync
The varnish add-on showed the correct message. But clearing Savvii (via admin bar "Flush All Cache") did not clear WP Rocket cache. 

Couldn't test if WP Rocket cache clear was clearing Savvii cache, response headers always had this: `X-Varnish-Cache: MISS`

I have added `time()` in the website description (top left corner) to see if cache is being served or not. 

Logins: https://wp-media.slack.com/archives/CBJ2KQ0MU/p1531923312000499

### PR DESCRIPTION
**Pull request by iCaspar**
Closes #1075 

- Moves Savvii hosting to the new arcitecture
- Fixes cache syncing to use the correct nonce action.

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Tabrisrp** [comment]
@wp-media/qa Ready for testing on Savvii hosting

Things to look for:
- Varnish add-on auto-enabled and with the custom title
- Savvii server cache clearing when clearing WP Rocket cache
- WP Rocket cache clearing when clearing Savvii server cache via their plugin

**Review by Davidacu — COMMENTED** [review]
When I tried activating the plugin I got an error message, now I'm blocked because after that I can't even access the plugins section and I don't have FTP access, @GeekPress could you please help me get FTP access?

@iCaspar @Tabrisrp here is the errors I got when trying to activate the plugin, please have a look, Thanks!
https://i.imgur.com/xvEWWZm.png
https://i.imgur.com/NERpmZk.png

**Comment by Tabrisrp** [comment]
@Davidacu This issue should be fixed with my latest commit, sorry about that!

**Review by Davidacu — COMMENTED** [review]
I need to clarify a few things to test this, I have noticed a few things in this hosting:

1. If you navigate to the site and look at the page source you'll see the WP Rocket footprint at the bottom, the files are being served from disk from `wp-content/cache/wp-rocket` even when the Varnish cache is supposed to be enabled, we don't seem to disable our cache. - Is this intended?
https://i.imgur.com/KRUUYlA.png
2. When Clearing WP Rocket cache from the admin toolbar, I can not really test if the Varnish cache is purged, when I inspect the response, the header `X-Varnish-Cache=MISS` is returned every time. (Even with WP Rocket deactivated)
https://screencast-o-matic.com/watch/cYiu3EECuy
3. When Clearing Savvii cache via the "Flush all cache" button in the admin toolbar, I can see that WP Rocket cache is cleared, but not the cached minified files under `wp-content/cache/min` that are usually cleared when we manually clear WP Rocket cache. - shouldn't we clear the min folder as well?
https://screencast-o-matic.com/watch/cYiu3KECUB
4. When activating the plugin I got an error, the plugin was activated with no problem though.
https://i.imgur.com/6vmMJb8.png

**Comment by Tabrisrp** [comment]
I've sent an email to their support about this, waiting for their reply.

For your point 3 and 4, that's ok. Point 3 is normal, we don't need to clear the min files when clearing the server cache.

And point 4 is not related to us.

**Review by Davidacu — APPROVED** [review]
I can confirm that 
1. The Savvii cache is cleared after clearing WP Rocket cache.
2. WP Rocket cache is disabled since Varnish cache is being used.
3. Varnish addon identifies savvii hosting.

Find the test run results attached
[savvi-compatibility-test-run.pdf](https://github.com/wp-media/wp-rocket/files/4997551/testrail-report-4.pdf)

**Pull request merged**
