### PR TITLE
Closes #5902 Add renewal notice for expired license on plugins page

### LINKED ISSUE #5902: Notice for users with expired licenses in the plugin section of their WP admin
**Is your feature request related to a problem? Please describe.**
We are not displaying any notice to expired users when we have new major release when they visit the plugin section of their WP back-end.

**Describe the solution you'd like**
We would like to display not dismissible notice to expired users to inform them about new release and offer them to renew their license to access the latest updates.

**Additional context**
Text, links and all the details are listed in [this doc](https://docs.google.com/document/d/1v2EFCNUQ6tY0M9FPK_V-CqcxK3CQEpxsRWLBJB74-UQ/edit#) (and in this [Notion doc](https://www.notion.so/wpmedia/WIP-Notice-for-expired-users-in-the-plugin-section-d42b01a392f843fbaf85b9c5092ca700)).
A design is provided in the [Mocflow](https://wireframepro.mockflow.com/editor.jsp?editor=on&spaceid=&bgcolor=white&perm=Create&pcompany=Cecd420c47c5bcee150a8fd3c9a22c69d&ptitle=%5BWP%20Rocket%20Plugin%5D%20-%20Notice%20for%20expired%20users&category=wizard&projectid=MUNFYtvlHh&publicid=dc6c4bae66514fad878acdefcb3e9386#/page/D76ecc1e47592f640aaee520c26bb11af).

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Add a renewal notice for expired license on the plugins page under the WP Rocket row.

Fixes #5902

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

Only some minors changes.

## How Has This Been Tested?

- [x] Automated tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jeawhanlee — APPROVED** [review]

**Comment by engahmeds3ed** [comment]
@Tabrisrp 
What do u think about the discussion here:
https://wp-media.slack.com/archives/GUT7FLHF1/p1685365296749339

I tried it now with expired user and I got the following response from this used API
```
3.13|https://wp-rocket.me/xxxxxx/wp-rocket_3.13.zip%7C3.13
```

This user's latest version was 3.13, this means he will not see this PR's notice at all.

Will change it back to in progress till u validate that.

**Comment by remyperona** [comment]
I think that's a good catch, we would need to use the version from the plugin information endpoint instead to get the current version available

**Comment by engahmeds3ed** [comment]
> I think that's a good catch, we would need to use the version from the plugin information endpoint instead to get the current version available

Unfortunately, also plugin information endpoint is calling the code from check update file :( 
We may need to create a new file for this or adjust the current one to have a new attribute of latest release.

**Comment by remyperona** [comment]
@piotrbak Following Ahmed discovery, we will probably need an update on the website side too for this

**Review by engahmeds3ed — APPROVED** [review]

**Comment by vmanthos** [comment]
This is working fine except for the following minor points:

1. There is a border above the notice which isn't there in the mock file:
image

On mobile, there is a blank space on the left of the notice:
image

2. The URL of the "Learn more" should be `https://wp-rocket.me/blog/wp-rocket-3-X/` instead of `https://wp-rocket.me/blog/3-X`

@Tabrisrp Whenever you can! :pray:

**Comment by remyperona** [comment]
To fix those display issues, I would need to add a custom CSS file specifically for that, because I can't fix them with what WP offers. @piotrbak Do we want to do it?

**Comment by piotrbak** [comment]
@marija-nikolic Is this what's mentioned here acceptable from your point of view?
https://github.com/wp-media/wp-rocket/pull/5930#issuecomment-1609456889

**Comment by marija-nikolic** [comment]
> @marija-nikolic Is this what's mentioned here acceptable from your point of view? [#5930 (comment)](https://github.com/wp-media/wp-rocket/pull/5930#issuecomment-1609456889)


> @marija-nikolic Is this what's mentioned here acceptable from your point of view? [#5930 (comment)](https://github.com/wp-media/wp-rocket/pull/5930#issuecomment-1609456889)

Yes, I think it should be fixed. I am not sure how is this problematic and how much work is it for you?

**Comment by piotrbak** [comment]
@Tabrisrp We'll need to fix those points. Is it possible to inline this CSS?

**Comment by remyperona** [comment]
I'll see how I can handle it

**Comment by vmanthos** [comment]
The styling looks good now. :pray: 

"Learn more" still points to the wrong URL:
https://wp-rocket.me/blog/3-15/

According to the [doc](https://docs.google.com/document/d/1v2EFCNUQ6tY0M9FPK_V-CqcxK3CQEpxsRWLBJB74-UQ/edit) it should be:
https://wp-rocket.me/blog/wp-rocket-3-15/

For example, for `3.14` the URL is:
https://wp-rocket.me/blog/wp-rocket-3-14/

@Tabrisrp Can you please change that?

**Comment by vmanthos** [comment]
@Tabrisrp I got a PHP fatal error:
```PHP
PHP Fatal error:  Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, null given in /shared/httpd/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Plugin/RenewalNotice.php:99
Stack trace:
#0 /shared/httpd/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Plugin/RenewalNotice.php(99): explode('.', NULL)
#1 /shared/httpd/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Plugin/RenewalNotice.php(86): WP_Rocket\Engine\Plugin\RenewalNotice->extract_major(NULL)
#2 /shared/httpd/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Plugin/RenewalNotice.php(68): WP_Rocket\Engine\Plugin\RenewalNotice->is_major_version_available(NULL)
#3 /shared/httpd/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Plugin/UpdaterSubscriber.php(604): WP_Rocket\Engine\Plugin\RenewalNotice->add_expired_styles(NULL)
#4 /shared/httpd/example.com/htdocs/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Plugin\UpdaterSubscriber->add_expired_styles('')
#5 /shared/httpd/example.com/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#6 /shared/httpd/example.com/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /shared/httpd/example.com/htdocs/wp-admin/admin-header.php(125): do_action('admin_print_sty...')
#8 /shared/httpd/example.com/htdocs/wp-admin/plugins.php(605): require_once('/shared/httpd/w...')
#9 {main}
  thrown in /shared/httpd/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Plugin/RenewalNotice.php on line 99
```

The `wp_rocket_update_data` transient used here:
https://github.com/wp-media/wp-rocket/blob/5287e0768699ef1905a6269d46779c30c4df5191/inc/Engine/Plugin/UpdaterSubscriber.php#L598

doesn't have a `stable_version`. It's like this:
```javascript
(object) array(
   'slug' => 'wp-rocket',
   'plugin' => 'wp-rocket/wp-rocket.php',
   'new_version' => '3.14.1',
   'url' => 'https://wp-rocket.me/',
   'package' => 'https://wp-rocket.me/xxxxxxxx/wp-rocket_3.14.1.zip',
   'tested' => '6.2.2',
   'icons' => 
  array (
    '2x' => 'https://mega.wp-rocket.me/avada/wp-content/plugins/wp-rocket/assets/img/icon-256x256.png',
    '1x' => 'https://mega.wp-rocket.me/avada/wp-content/plugins/wp-rocket/assets/img/icon-128x128.png',
  ),
)
```

Can you please look into this?

**Comment by remyperona** [comment]
The `stable_version` value is supposed to come from the website, we had a PR about that. @nicomollet is it merged on the production site?

**Comment by nicomollet** [comment]
Yes @Tabrisrp it is on production since June 26th (https://github.com/wp-media/wp-rocket.me/releases/tag/v2023.06.26-0915)

A postman showing the latest version:

image

**Comment by remyperona** [comment]
Added a check for the `stable_version` property before passing the value to prevent the error

**Comment by vmanthos** [comment]
Thank you for the fix, @Tabrisrp! :pray: 

The styling of the notice:
image
is different compared to the [mock file](https://wireframepro.mockflow.com/editor.jsp?editor=on&spaceid=&bgcolor=white&perm=Create&pcompany=Cecd420c47c5bcee150a8fd3c9a22c69d&ptitle=%5BWP%20Rocket%20Plugin%5D%20-%20Notice%20for%20expired%20users&category=wizard&projectid=MUNFYtvlHh&publicid=3b6f909e6c3a4b4cb6bf2dcf1fcf1a0d#/page/D76ecc1e47592f640aaee520c26bb11af)
image

1. The border is `#d43436`.
2. The background color is `#fbf9e8`.
3. Links color is `#3984c6` and don't have an underline.

These are the final changes. :pray:

**Comment by remyperona** [comment]
Thank you, updated the styles

**Comment by marija-nikolic** [comment]
> Thank you for the fix, @Tabrisrp! 🙏
> 
> The styling of the notice: image is different compared to the [mock file](https://wireframepro.mockflow.com/editor.jsp?editor=on&spaceid=&bgcolor=white&perm=Create&pcompany=Cecd420c47c5bcee150a8fd3c9a22c69d&ptitle=%5BWP%20Rocket%20Plugin%5D%20-%20Notice%20for%20expired%20users&category=wizard&projectid=MUNFYtvlHh&publicid=3b6f909e6c3a4b4cb6bf2dcf1fcf1a0d#/page/D76ecc1e47592f640aaee520c26bb11af) image
> 
> 1. The border is `#d43436`.
> 2. The background color is `#fbf9e8`.
> 3. Links color is `#3984c6` and don't have an underline.
> 
> These are the final changes. 🙏

@vmanthos I think we can leave links underlined...(all links have an underline in other plugins notices).
I wanted to update in the Mocflow but I can see that the text is deleted (I will add it again, unless someone did that on purpose):
image

**Comment by vmanthos** [comment]
@Tabrisrp Thank you for the changes. According to @marija-nikolic, it seems you need to re-add the underline to the links. :sweat_smile: 
Also, the icon now is different:
image

It has to be an explanation mark in a red circle.

**Comment by marija-nikolic** [comment]
> @Tabrisrp Thank you for the changes. According to @marija-nikolic, it seems you need to re-add the underline to the links. 😅 Also, the icon now is different: image
> 
> It has to be an explanation mark in a red circle.

@Tabrisrp @vmanthos 
I mean, all other plugins have links underlined, so I think it would be better to have the same :)
 
About the colors, I apologize but I think it is mandatory to have the same as all other plugins (so I thought it is not necessary to specify in the doc 🙈):
#d63638 for the border and the icon
#fcf9e8 for background
#2782ad for link

**Comment by vmanthos** [comment]
So, the changes for @Tabrisrp to implement are:
1. The border and icon color is `#d63638`.
2. The background color is `#fcf9e8`.
3. Links are underlined and `#2782ad`
4. The icon is an exclamation mark in a  `#d63638` circle.

**Comment by piotrbak** [comment]
@Tabrisrp Is this one QA ready?

**Comment by vmanthos** [comment]
After the latest changes, the notice looks as expected:
image

When the user:
1. Has an expired license.
2. Has access to, e.g. `3.4.2`.
3. Has `3.4.1` installed, both the update notice and the notice of the current PR is displayed: 
image

@piotrbak @marija-nikolic Is this :point_up: OK?

**Comment by marija-nikolic** [comment]
> After the latest changes, the notice looks as expected: image
> 
> When the user:
> 
> 1. Has an expired license.
> 2. Has access to, e.g. `3.4.2`.
> 3. Has `3.4.1` installed, both the update notice and the notice of the current PR is displayed:
>    image
> 
> @piotrbak @marija-nikolic Is this ☝️ OK?

Yes, looks ok for me.

**Review by vmanthos — APPROVED** [review]

**Pull request merged**
