### PR TITLE
Update Action Scheduler package to 3.4.2

### LINKED ISSUE #5119: Action Scheduler deprecated DateTime warnings with PHP 8
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.11.3`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When using Remove Unused CSS with PHP 8 (tested with `8.1.6`) the following warnings pop up in the `debug.log`:
```
[08-Jun-2022 08:50:07 UTC] PHP Deprecated:  Return type of ActionScheduler_DateTime::setTimezone($timezone) should either be compatible with DateTime::setTimezone(DateTimeZone $timezone): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_DateTime.php on line 60
[08-Jun-2022 08:50:07 UTC] PHP Deprecated:  Return type of ActionScheduler_DateTime::getOffset() should either be compatible with DateTime::getOffset(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_DateTime.php on line 48
[08-Jun-2022 08:50:07 UTC] PHP Deprecated:  Return type of ActionScheduler_DateTime::getTimestamp() should either be compatible with DateTime::getTimestamp(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_DateTime.php on line 27
[08-Jun-2022 08:50:07 UTC] PHP Deprecated:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php on line 316
[08-Jun-2022 08:50:07 UTC] PHP Deprecated:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php on line 316
[08-Jun-2022 08:50:07 UTC] PHP Deprecated:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php on line 316
[08-Jun-2022 08:50:07 UTC] PHP Deprecated:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php on line 316
[08-Jun-2022 08:50:07 UTC] PHP Deprecated:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php on line 316
[08-Jun-2022 08:50:07 UTC] PHP Deprecated:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php on line 316
[08-Jun-2022 08:50:07 UTC] PHP Deprecated:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php on line 316
[08-Jun-2022 08:50:07 UTC] PHP Deprecated:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php on line 316
[08-Jun-2022 08:50:07 UTC] PHP Deprecated:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php on line 316
```

**To Reproduce**
1. Use PHP `8.1.6`
2. Enable WordPress's debugging.
3. Enable Remove Unused CSS.
4. Check the `debug.log` for the warnings.

**Expected behavior**

No warnings should appear in the debug.log when using Remove Unused CSS with the latest PHP versions.

**Additional context**

According to @engahmeds3ed (🙏) this is an issue on Action Scheduler's side.

Adding this here to discuss whether we are going to wait for AS to fix this or if we are going to do it.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
## Description

Update Action Scheduler package to the latest version 3.4.2

Fixes #5119 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

Not groomed as it's [XS]

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Tested the main functionality of AS and RUCSS

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by jeawhanlee — APPROVED** [review]

**Review by Mai-Saad — APPROVED** [review]
Working as expected.
Note: on the trunk, sometimes this warning is added to debug.log while Minify CSS, preload, and link preload are enabled + access home page/ hover over links. @piotrbak @engahmeds3ed do you think we need GH for this? what can cause this? it is totally random
`[13-Jun-2022 12:15:07 UTC] PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Minify/CSS/AbstractCSSOptimization.php on line 143`
[testrail-report-391.pdf](https://github.com/wp-media/wp-rocket/files/8893733/testrail-report-391.pdf)

**Comment by piotrbak** [comment]
@engahmeds3ed Do you know how this could happen?

**Comment by remyperona** [comment]
It's unrelated to the PR changes, it's something we need to change in the code to make sure we pass a string when a string is expected, which is not the case here.

**Comment by engahmeds3ed** [comment]
@Mai-Saad can u open GH issue for this one mentioning the page template u used.

It's exactly like what Remy said above, we can add more checks on this part of code but it's not related to this PR at all.

**Pull request merged**
