### PR TITLE
Fix undefined constant WP_ROCKET_CONFIG_PATH

### PR DESCRIPTION
**Pull request by crystinutzaa**
Fixes:

`Notice: Use of undefined constant WP_ROCKET_CONFIG_PATH - assumed 'WP_ROCKET_CONFIG_PATH' in /home/alfonsoc/public_html/rocket/wp-content/plugins/wp-rocket/inc/classes/logger/class-logger.php on line 236`

```

# | Time | Memory | Function | Location
-- | -- | -- | -- | --
1 | 0.0042 | 435704 | {main}( ) | .../index.php:0
2 | 0.0088 | 479232 | require_once( '/app/public/wp-admin/admin.php' ) | .../index.php:10
3 | 0.0110 | 493856 | require_once( '/app/public/wp-load.php' ) | .../admin.php:34
4 | 0.0134 | 505496 | require_once( '/app/public/wp-config.php' ) | .../wp-load.php:37
5 | 0.0163 | 591072 | require_once( '/app/public/wp-settings.php' ) | .../wp-config.php:109
6 | 0.0622 | 1367712 | include( '/app/public/wp-content/advanced-cache.php' ) | .../wp-settings.php:95
7 | 0.0964 | 1699928 | WP_Rocket\Buffer\Cache->__construct( ) | .../advanced-cache.php:63
8 | 0.0965 | 1699992 | WP_Rocket\Buffer\Cache->log( ) | .../class-cache.php:69
9 | 0.1045 | 1759904 | WP_Rocket\Logger\Logger::info( ) | .../class-abstract-buffer.php:120
10 | 0.1045 | 1759904 | WP_Rocket\Logger\Logger::get_logger( ) | .../class-logger.php:82
11 | 0.1789 | 2008264 | WP_Rocket\Logger\Logger::get_log_file_path( ) | .../class-logger.php:196


```

### CODE REVIEW

**Comment by Tabrisrp** [comment]
You're having to do that because of changes of PR #2120 included in this, it should _not_ be as it's being included and tested for 3.5.

I suggest to remove changes related to 2120 from this branch. And rebase this PR to branch-3.5/develop to fix the issue.

**Comment by Tabrisrp** [comment]
You have changes from 3.4.4 included in this PR

**Comment by crystinutzaa** [comment]
Yup...I was thinking to close this PR (without merging) and make a clean new PR which contains only this fix for branch-3.5. What do you think @Tabrisrp ?

**Comment by Tabrisrp** [comment]
it's probably easier than cleaning up this branch

**Pull request closed without merging**
