### PR TITLE
Fixes #5502 Add missing FR docs

### LINKED ISSUE #5502: More info French broken links
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.1.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Clicking more info link for Combine JS exclusion or Delay JS for fr profile displays nothing in the beacon

**To Reproduce**
1. Use Francais language on admin
2. Enable Minify JS and click more info for Combine JS exclusion
3. Click more info for Delay JS exclusion

**Expected behavior**
Relative doc displayed 
- As per the [slack discussion](https://wp-media.slack.com/archives/C02QL83AYUT/p1665576566188149)
For Minify JS file exclusions fr doc https://fr.docs.wp-rocket.me/article/243-exclure-js-externe-minification
For Combine JS inline exclusions fr doc https://fr.docs.wp-rocket.me/article/1109-exclure-les-js-inline-de-la-combinaison
For Delay JS fr https://fr.docs.wp-rocket.me/article/1626-reporter-l-execution-du-javascript 

**Screenshots**
Screenshot from 2022-10-12 09-06-10

Screenshot from 2022-10-12 09-06-05

Screenshot from 2022-10-12 16-58-12

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Add missing FR docs to Beacon

Fixes #5502

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Existing unit tests pass locally with my changes

### CODE REVIEW

**Review by mostafa-hisham — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Tabrisrp Working fine for mentioned links in the main ticket.
However, some other broken links were found in FR mode during the exploratory test.
1- Webp => EN is https://docs.wp-rocket.me/article/1282-webp
2- Exclusion from LazyLoad => EN is https://docs.wp-rocket.me/article/15-disabling-lazy-load-on-specific-images/?utm_source=wp_plugin&utm_medium=wp_rocket
3- Preload Exclusion => EN is https://docs.wp-rocket.me/article/1721-exclude-urls-from-being-preloaded?utm_source=wp_plugin&utm_medium=wp_rocket
4- Never Cache URL => Woocommerce link => EN is https://docs.wp-rocket.me/article/27-using-wp-rocket-on-your-ecommerce-site/?utm_source=wp_plugin&utm_medium=wp_rocket
@WordPresseur Do we have FR links and IDs to those URLs? :pray: 
Screenshot from 2022-10-24 10-38-00
Screenshot from 2022-10-24 10-37-52
Screenshot from 2022-10-24 10-37-36
Screenshot from 2022-10-24 10-37-23

**Comment by WordPresseur** [comment]
1- Webp => FR is https://fr.docs.wp-rocket.me/article/1286-compatibilite-webp - HS ID: [5d7b495e04286364bc8f12ef](https://secure.helpscout.net/docs/568e92e39033603f7da2e88a/article/5d7b495e04286364bc8f12ef)
2- Exclusion from LazyLoad => FR is https://fr.docs.wp-rocket.me/article/235-desactivez-le-lazyload-sur-des-images-specifiques - HS ID: [56967952c69791436155e60a](https://secure.helpscout.net/docs/568e92e39033603f7da2e88a/article/56967952c69791436155e60a)
3- Preload Exclusion => FR is https://fr.docs.wp-rocket.me/article/1722-exclure-url-du-prechargement - HS ID: [63496d5b8a552811521e52d2](https://secure.helpscout.net/docs/568e92e39033603f7da2e88a/article/63496d5b8a552811521e52d2/)
4- Never Cache URL => Woocommerce link => FR is https://fr.docs.wp-rocket.me/article/198-ecommerce - HS ID: [569431189033603f7da2fc13](https://secure.helpscout.net/docs/5d380a1d2c7d3a2ec4bf5540/article/569431189033603f7da2fc13)

**Comment by remyperona** [comment]
this is updated

**Review by Mai-Saad — APPROVED** [review]
Working as expected

**Pull request merged**
