### PR TITLE
Closes #6943 Change the way the description for the Clear button is displayed

### LINKED ISSUE #6943: Change the way the description for the Clear button is displayed
**Is your feature request related to a problem? Please describe.**
We had some feedback from the Support Team saying that the hover description is not clear enough. We'll move the description to the container itself.

**Describe the solution you'd like**
The text from the hover section of the **Clear** button placed in the Performance Hints section will be moved above it:
image

**AC**
1. The text used will be `This action will clear data for Optimize Critical Images and Lazy Render Content.`
2. The styling will be the same as in the `wpr-field-description` CSS class
3. No description on hover

### PR DESCRIPTION
**Pull request by Khadreal**
# Description

Fixes #6943 
Moved the text from the hover section of the Clear button to above it.

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

## Detailed scenario
Please check #6943 for detailed scenario.

### Documentation

Add text description to generate button file.

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I did not introduce unnecessary complexity.

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by MathieuLamiot** [comment]
@Khadreal Are you able to provide a screenshot of the change so that @piotrbak can validate? thanks

**Comment by MathieuLamiot** [comment]
https://github.com/user-attachments/assets/57e7a27e-d07c-4f68-b622-babad232b913

**Comment by MathieuLamiot** [comment]
@piotrbak Is this OK?

**Comment by piotrbak** [comment]
Looks good!

**Pull request merged**
