### PR TITLE
3.16 bug the warm up of lcpatf is not triggered when clicking clear critical images in the admin

### LINKED ISSUE #6516: 3.16 Bug - The warm-up of LCP/ATF is not triggered when clicking "Clear Critical Images" in the admin
**Context**
When clicking the "Clear Critical Images" button under teh WP Rocket menu in the WP admin, the warm-up process is not triggered.
To reproduce
-  install WP Rocket 3.16 (alpha), wait a bit. 
- Enable logs to track what is sent to the SaaS in the warm-up process (those logs might not be available by default, so add them if needed), or you can check on [Metabase](https://data.wp-media.me/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxNCwicXVlcnkiOnsic291cmNlLXRhYmxlIjo1NTAsIm9yZGVyLWJ5IjpbWyJkZXNjIixbImZpZWxkIiwxNDM4OSxudWxsXV1dfSwidHlwZSI6InF1ZXJ5In0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==) LCP/ATF jobs received by the SaaS (staging, you need to set the constant WP_ROCKET_SAAS_API_URL to https://rucss-director-staging.public-default.live2-k8s-cph3.one.com/)
- Click on the "Clear Critical Images" in the WP Admin panel (top of the screen, under WP Rocket menu).
- The warm-up process is not triggered (nothing in your logs, or on Metabase).

**Expected behavior**
The warm-up should be triggered everytime we do a truncate on the LCP/ATF table.
https://github.com/wp-media/wp-rocket/issues/6429#issuecomment-1969939046

**Acceptance Criteria**
- Repeat the "How to reproduce" scenario. You should have jobs sent to the SaaS.
- Check non-regression with other triggers: switch theme, change permalink structure, rocket_domain_options_changed. When those actions are triggered, the warm-up should also be triggered.

### PR DESCRIPTION
**Pull request by MathieuLamiot**
# Description

Move `rocket_after_clear_atf` firing in `delete_rows` to make sure it fires for all truncate.
Rename truncate method to something a bit more explicit

Fixes #6516 

### User documentation

the "Clear Critical Images" button in the WP Admin will now fire the warm-up process for LCP/ATF

### Technical documentation

NA

## Type of change
*Delete options that are not relevant.*

- [ ] New feature (non-breaking change which adds functionality).
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [x] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [x] I listed the introduced external dependencies explicitely on the PR.
- [x] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [x] I handled errors when needed.
- [x] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [x] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [x] I explicitely mentioned performance risks in the PR.
- [x] I explicitely mentioned security risks in the PR.

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Review by remyperona — APPROVED** [review]

**Comment by Miraeld** [comment]
Not sure if we need a review again on that, I've just added integrations tests related to the PR.

**Comment by MathieuLamiot** [comment]
@Miraeld The test you added checks that, when calling `rocket_saas_clean_all`, the DB is indeed truncated, right? How is it related to ensuring the warm-up is triggered?

**Comment by Miraeld** [comment]
I can't really test if the function `warm_up()` has been triggered as there are no output from it. 
However, I've added if the action `rocket_after_clear_atf` has been triggered. This is the action that leads to `warm_up()`.

**Comment by MathieuLamiot** [comment]
Thanks, I guess this can be merged then and moved to "Done". complete testing is covered by: https://github.com/wp-media/wp-rocket/issues/6429#issuecomment-2051901927

**Pull request merged**
