### PR TITLE
Fixes #4769 Exclude Photonic scripts from Delay JavaScript Execution 

### LINKED ISSUE #4769: Delay JS - The Photonic plugin breaks
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ (`3.10.8`)
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When Defer JavaScript files is active galleries that are added with the [Photonic Gallery & Lightbox for Flickr, SmugMug, Google Photos & Others](https://wordpress.org/plugins/photonic/) plugin aren't loading.

Excluding the following resolved the issue:
```HTML
/photonic/include/js/front-end/nomodule/combo-slider/photonic-baguettebox.min.js
/photonic/include/js/front-end/module/combo-slider/photonic-baguettebox.min.js
```

**To Reproduce**
1. Install the plugin.
2. Add a gallery on a page.
3. Visit it.
4. See error.

**Expected behavior**

Photonic should work when Delay JavaScript Execution is active.

**Additional context**

Exclude `/photonic/include/js/front-end/` in the core by adding it in the `$excluded` array:
https://github.com/wp-media/wp-rocket/blob/b34218065e5935e7482c7c60721becc26e237c97/inc/Engine/Optimization/DelayJS/HTML.php#L26-L73

**Ticket:** https://secure.helpscout.net/conversation/1800351383/328613?folderId=273766

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by vmanthos**
## Description

I've added:
`/photonic/include/js/front-end/`

in the `$excluded` array.

Fixes #4769 

## Type of change

Please delete options that are not relevant.

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

Not groomed.

## How Has This Been Tested?

- [x] I installed the plugin on my test site.
- [x] On the customer's website using the UI exclusion text area.

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@vmanthos on the test site we need to exclude `/photonic/include/ext/baguettebox/baguettebox.min.js` as well or we will have a console error. Can you please check :pray:
Screenshot from 2022-04-15 10-14-44

**Comment by vmanthos** [comment]
@Mai-Saad I've made changes to the PR. 
Can you please check this again?

**Comment by Mai-Saad** [comment]
@vmanthos Please find the current state below:
1- The new Photonic version 2.79 => gallery is not displayed till user interaction, is this ok now?
2- Older versions of Photonic i.e 2.69/2.70 => gallery is not displayed even with user interaction .. (if we excluded `/photonic/include/js/front-end/module/combo-slider/photonic-baguettebox.min.js` gallery will be displayed with no user interaction)
I think we need to update exclusion so it can work for new/old versions of Photonic. What do you think @vmanthos @piotrbak ?

**Comment by vmanthos** [comment]
@Mai-Saad This is ready for QA. 🙏 

For the changes please check the comment in the following commit:
https://github.com/wp-media/wp-rocket/pull/4772/commits/a5e3f31bd705e5a06470f5510e3199f812cfd59d

**Review by Mai-Saad — APPROVED** [review]
Working as expected now with 2.69 / 2.8  (gallery will be displayed with user interaction and no console error)

**Pull request merged**
