### PR TITLE
Temporarily Hide action scheduler past due

### LINKED ISSUE #5431: [WIP] Action Scheduler: lots of past-due rocket_preload_job_preload_url actions found
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
@webtrainingwheels noticed a trend: 
On some sites using **3.12.0.5** the `rocket_preload_job_preload_url` starts piling up. (6k, 70k, 80k entries)
Users are mentioning the entries are being created really fast.

Some cases are using **Rank Math SEO** as a common factor, but I can't confirm it is related

`Action Scheduler: 70197 past-due actions found; something may be wrong. Read documentation »" In clicking through, there are indeed many many "Rocket Preload" actions in Pending in Scheduled actions.
`
In one case where we have access, the only `action_scheduler_queue_runner_concurrent_batches` is ours, and set to 1
there are under 5k posts, but over 60k `rocket_preload_job_preload_url`

**Additional context**
Related tickets: 
https://secure.helpscout.net/conversation/2009676957/368580/
https://secure.helpscout.net/conversation/2009655193/368571/
https://secure.helpscout.net/conversation/2006498141/367846
https://secure.helpscout.net/conversation/2009599555/368564
https://secure.helpscout.net/conversation/2009599415/368563

Slack convo:
https://wp-media.slack.com/archives/C43T1AYMQ/p1663195462029489

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### LINKED ISSUE #5450: Hide past due actions in Action Scheduler
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Since Action Scheduler 3.5 version, users can see a tab with past-due actions. This doesn't play well with async actions, as the date can not be set and it ends up with filling the tab with all our actions and confusing our customers.

**To Reproduce**
1. Enable preload
2. All actions are being added to `Pending` tab and `Past-due`

**Expected behavior**
The fix needs to be implemented on the Action Scheduler side. From our point of view, we should hide this tab as we're flooded with tickets from confused customers.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
## Description

We need to hide the past due admin notice from Action Scheduler in case the users has the latest version of Action Scheduler used at any other plugin not to confuse them.

The main problem is inside Action Scheduler itself, because Async tasks don't have schedule date and just have zeros/null value so the following query which gets the past due actions:
https://github.com/woocommerce/action-scheduler/blob/trunk/classes/ActionScheduler_AdminView.php#L154-L158
needs some adjustment to only get the rows that have real dates there.

We need to keep our eyes on action scheduler code base to see if this issue is solved there to revert this PR's changes.

Also we will try contributing there to help getting this fix as soon as possible.

Fixes #5450

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

Not groomed.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit tests
- [x] Manual testing

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by CrochetFeve0251 — APPROVED** [review]

**Comment by remyperona** [comment]
We should create an issue on AS repository to talk about that

**Review by Mai-Saad — COMMENTED** [review]
Working as expected with the following notes.
1- Past-due tab won't be displayed even after disabling RUCSS/Preload
2- Past-due tab won't be displayed if the user used a filter to display it
`add_filter( 'action_scheduler_pastdue_actions_check_pre', '__return_true', 999 );`
if nothing further will be done on PR then we can merge it.

**Comment by GeekPress** [comment]
Thanks Mai. Yes, please go ahead with the merge.

**Comment by engahmeds3ed** [comment]
As mentioned, we don't use the filter `action_scheduler_pastdue_actions_check_pre` but we use the filter `action_scheduler_check_pastdue_actions` so they need to use it like that 
```
add_filter( 'action_scheduler_check_pastdue_actions', '__return_true', 999 );
```
so this will let the notice appear in Action Scheduler's page.

And to show the past-due status filter they may use the following snippet
```
add_filter( 'action_scheduler_extra_action_counts', function( $extra_actions ){
	$store = ActionScheduler::store();
    
	$pastdue_action_counts = ( int ) $store->query_actions( array(
		'status' => $store::STATUS_PENDING,
		'date'   => as_get_datetime_object(),
	), 'count' );

	if ( $pastdue_action_counts ) {
		$extra_actions['past-due'] = $pastdue_action_counts;
	}
    
    return $extra_actions;
}, 11 );
```

**Pull request merged**
