### PR TITLE
Closes #6634: Preload tag has incorrect markup if LCP element has at least 2 background-images among pseudo-elements

### LINKED ISSUE #6634: Preload tag has incorrect markup if LCP element has at least 2 background-images among pseudo-elements
**Before submitting an issue please check that you’ve completed the following steps:**
Yes - Made sure you’re on the latest version
Yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When LCP image is added as BG image via CSS with a relative path, we might include incorrect chars at the end: `%20url`

EDIT Mathieu Lamiot: I don't think that the use of a relative path is creating the issue here. See below, but I think the issue is that one element has 2 pseudo-elements with background-image and we "merge" the beginning of the 2nd with the 1st one.

example markup code. 
`<link rel="preload" as="image" href="https://www.site.com/wp-content/themes/image/img/home.jpg%20url" fetchpriority="high">
`

in the database it will be similar to this (is not the same image on my test site): 
`{"type":"bg-img","bg_set":[{"src":"https:\/\/site.com\/2022\/02\/img\/home.jpg url"}]}`

Per @MathieuLamiot research: 

> this is a bug on the beacon script. We'll need a dedicated GH issue, not the #6599
> The issue happens because of the syntax mentioned by Piotr with the url(...) to declare the background images.

> On this page: https://www.softactivity.com/, I retrieved the element featured-line:
```
let list = document.querySelectorAll('div')
let element = list[4]
```
> Then, I applied a few lines from the beacon script:
```
const computed_style = window.getComputedStyle(element, null);
			const bg_props = [
				computed_style.getPropertyValue("background-image"),
				getComputedStyle(element, ":after").getPropertyValue("background-image"),
				getComputedStyle(element, ":before").getPropertyValue("background-image")
			];

			const full_bg_prop = bg_props.filter(prop => prop !== "none").join("");
```
This gives` full_bg_prop = 'url("https://www.softactivity.com/wp-content/themes/soft-activity/img/home.jpg")url("https://www.softactivity.com/wp-content/themes/soft-activity/img/bg_slider_s.png")'`

I think this is then badly handled by those lines:
```
const matches = [...full_bg_prop.matchAll(css_bg_url_rgx)];
element_info.bg_set = matches.map(m => m[1] ? {src: m[1].trim() + (m[2] ? " " + m[2].trim() : "")} : {});
```

**To Reproduce**
1. Add an HTML element.
2. With a CSS background image: `background-image: url(../img/home.jpg);`
3. Generate the Critical images
4. See the markup error

**Expected behavior**
We should correctly extract relative images to avoid broken markup. 

**Screenshots**
https://i.imgur.com/ljn2ItQ.png

**Additional context**
Slack thread: 
https://wp-media.slack.com/archives/C072P5EU5DF/p1715797306772669

Ticket: 
https://secure.helpscout.net/conversation/2598679615/491736?folderId=2683093

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #6634 

### User documentation

It fixes the detection of background-image when there are multiple ones. 

### Technical documentation

Just fixes the regex to match what we are expecting.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

## Risks

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [x] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [x] I listed the introduced external dependencies explicitely on the PR.
- [x] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [x] I handled errors when needed.
- [x] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [x] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [x] I explicitely mentioned performance risks in the PR.
- [x] I explicitely mentioned security risks in the PR.

### CODE REVIEW

**Review by Khadreal — APPROVED** [review]

**Comment by Khadreal** [comment]
@Miraeld using the html below
```
<div class="multiple-bg">
<h2> Hello world</h2>
<p>Lorem ipsum</p>
</div>
<style>
.multiple-bg {
background-image: url(https://placehold.co/400x600/EEE/31343C);
}

.multiple-bg:after {
background-image: url(https://placehold.co/600x400/EEE/31343C);
}
</style>
```

I got this lcp data, should the pseudo element bg be there at all ?
`{"type":"bg-img","bg_set":[{"src":"https:\/\/placehold.co\/400x600\/EEE\/31343C"},{"src":"https:\/\/placehold.co\/600x400\/EEE\/31343C"}]}`

**Comment by MathieuLamiot** [comment]
@Miraeld @Khadreal To know if this is OK or not, we should check what is done to the HTML after optimization.
Can you share the HTML after optimization?

We expect to preload only `https://placehold.co/400x600/EEE/31343C`.

**Comment by Miraeld** [comment]
@Khadreal , from this [comment](https://github.com/wp-media/wp-rocket/issues/6634#issuecomment-2124847272) here, 
We can consider them as LCP "all of them". 
That's actually the behavior that's been implemented by default in the beacon script. However, it wasn't loading all of them as LCP as we had an issue with the regex. Now that the regex got fixed, the normal behavior is used again and load everything. 

@piotrbak do you prefer to load only one or all of them can be considered as LCP ?

**Comment by Khadreal** [comment]
I have this in preload
```
<link rel="preload" as="image" href="https://placehold.co/400x600/EEE/31343C" fetchpriority="high">
<link rel="preload" as="image" href="https://placehold.co/600x400/EEE/31343C" fetchpriority="high">
```
cc @Miraeld , @MathieuLamiot

**Comment by MathieuLamiot** [comment]
Thanks. So it is not behaving as expected as per https://github.com/wp-media/wp-rocket/issues/6634#issuecomment-2124847272 But the bug is fixed.
@piotrbak do you prefer to release as is and have a follow-up GH issue to prevent having multiple LCP preloaded? Or should we move this back to in-progress and not release it for now to fix this?

In any cases, we will need to run E2E against this PR once #6693 is fixed.

**Comment by MathieuLamiot** [comment]
The last commit from @Miraeld aims at fixing the issue of preloading multiple images.
We'll need:
- The resulting optimized HTML -> Done below
- Rocket-E2E for non-regression (once #6693 is fixed)

**Comment by Miraeld** [comment]
@Khadreal , @MathieuLamiot 
I've just commited a change, it now select only one element as mentioned in the issue comments. 
So the case @Khadreal reported is fixed. 

The resulting html is as follow:
`<link rel="preload" as="image" href="https://placehold.co/400x600/EEE/31343C" fetchpriority="high">` only.

**Comment by MathieuLamiot** [comment]
To confirm this:

After dev update, on http://mathieu.e2e.rocketlabsqa.ovh/lcp_bg_relative_attribute_incss/ the markup preload is:

`link rel="preload" as="image" href="https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testavif.avif" fetchpriority="high">

link rel="preload" as="image" href="https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testjpg.jpg" fetchpriority="high">`
The URLs in the preload are correct, and there is no preload for the pseudo element ::before.

In the DB, we don't store twice the data in src and bg_set anymore. as per the comment in create_object:
```
// Returned objects must always have a src for front-end optimization.
// Except bg-img and bg-img-set for which we use bg_set only.
// To keep it simple and safe for now, we enforce src for all, pending a refactor.
```


image

**Comment by MathieuLamiot** [comment]
About E2E:

```
Expected LCP for mobile - /wp-content/rocket-test-data/images/lcp/testsvg.svg for http://mathieu.e2e.rocketlabsqa.ovh/lcp_no_dimension_svg is not present in actual - {"type":"img","src":"https://discuss-assets.s3.amazonaws.com/original/3X/1/9/19823cc1f1f887d70755e0b500dd8ce2c51ba7f9.svg"}


Expected LCP for mobile - /wp-content/rocket-test-data/images/lcp/testavif.avif for http://mathieu.e2e.rocketlabsqa.ovh/lcp_no_dimensions_picture is not present in actual - {"type":"picture","sources":[{"srcset":"http://mathieu.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testwebp.webp","media":"(max-width: 700px)"},{"srcset":"http://mathieu.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testjpeg.jpeg","media":"(max-width: 450px)"}],"src":""}
```

1st one is always in error. I checked manually and I think the expected is wrong, I'll update Rocket-E2E.

For the second, it's already failing before I think. So we are good for this PR. 

Could be good to further check lcp_no_dimensions_picture.

**Pull request merged**
