### PR TITLE
Make sure to send mobile visit to saas warmup for OCI with a fresh install

### LINKED ISSUE #6752: On fresh installs, OCI warm-up for not-homepages might be missing mobile requests if the task is triggered before options are set
**Context**
https://wp-media.slack.com/archives/CUKB44GNN/p1719826680391649?thread_ts=1719582525.193069&cid=CUKB44GNN

When running the async tasks for not-homepages of OCI warm-up, there are cases where `cache_mobile` and `do_caching_mobile_files` options are not set. In this case, we don't send the mobile requests.

**Expected behavior**
On fresh installs, the OCI warm-up for non-homepages should always send requests for mobile & desktop, unless a filter is applied to control `cache_mobile` and `do_caching_mobile_files`.

**Acceptance Criteria**
⚠️ The issue is not happening consistently: several tries are required to make it happen, as it is a race condition between OCI Warm up and plugin initialization.
- On fresh install, without filters or manual changes on `cache_mobile` and `do_caching_mobile_files`, the plugin must send 2 requests to the SaaS for OCI Warm Up per eligible pages (mobile & dekstop).
- On fresh install, if a filter or manual change controls `cache_mobile` and `do_caching_mobile_files`, then the filter/manual change must be applied and the warm up requests must behave accordingly.
- On regular OCI warm-up (not a fresh install), without filters or manual changes on `cache_mobile` and `do_caching_mobile_files` , the plugin must send 2 requests to the SaaS for OCI Warm Up per eligible pages (mobile & dekstop).
- - On regular OCI warm-up (not a fresh install), if a filter or manual change controls `cache_mobile` and `do_caching_mobile_files`, then the filter/manual change must be applied and the warm up requests must behave accordingly.

**Additional information**
Proposed solution is to replace:

`return $this->options->get( 'cache_mobile', 0 ) && $this->options->get( 'do_caching_mobile_files', 0 );`

by 

`return $this->options->get( 'cache_mobile', 1 ) && $this->options->get( 'do_caching_mobile_files', 1 );`

in is_mobile() of the OCI warm-up controller.

It could be the occasion to remove:

```
		$plugin_version = (string) get_rocket_option( 'version', '' );
		if ( ! $plugin_version ) { // We are warming up a fresh installation. Options are not set yet.
			return true;
		}
```

### PR DESCRIPTION
**Pull request by wordpressfan**
# Description

Fixes #6752

### User documentation

For fresh installation or when the mobile cache settings are not set, we will consider it active by default.

### Technical documentation

Here we set the default value sent to `$this->options->get` to be 1.

## Type of change
*Delete options that are not relevant.*

- [x] Bug fix (non-breaking change which fixes an issue).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks

Can't think of any risk here.

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [x] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [x] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

### CODE REVIEW

**Comment by wordpressfan** [comment]
For @wp-media/qa-team you can use the following snippet to completely disable mobile cache options to be used to validate the mentioned AC:

```
add_filter( 'pre_get_rocket_option_cache_mobile', '__return_false' );
add_filter( 'pre_get_rocket_option_do_caching_mobile_files', '__return_false' );
```

**Comment by MathieuLamiot** [comment]
@wordpressfan A quick feedback, not blocking for the PR but more food for thought, to improve: we would lack integration tests that capture the AC better. Currently, all tests involving `sendToSaas()` seem to mock `options->get` so we test that `is_mobile` behaves as expected when options are set to 0 or 1. 
Unfortunately, I think there are no tests on the behavior we are trying to achieve here. We would need a test that ensures `is_mobile` (or `sendToSaaS`) behaves as expected when no callbacks to `get_rocket_option_cache_mobile` and `get_rocket_option_do_caching_mobile_files` (hence, mocking a fresh install). That would require a test that does not mock `options->get` itself.
Do you see what I mean? It might not be straightforward to implement, and I think manual test can do for now to avoid blocking the PR. But it would be good to keep in mind the approach of having built-in tests to validate the ACs.

**Comment by wordpressfan** [comment]
Totally agree with you @MathieuLamiot

**Review by Khadreal — COMMENTED** [review]
LGTM

**Comment by Mai-Saad** [comment]
Test summary https://wp-media.slack.com/archives/CUT7FLHF1/p1719910569290519?thread_ts=1719832961.594679&cid=CUT7FLHF1 . if newlabs state with a fresh install is considered an edge case and not a priority for now then we can merge with the following notes:
1- Adding the home page to DB correctly is pending 6746 (out of scope)
2- Sometimes AS won't create warmup actions thus nothing is sent to metabase nor DB (out of scope)

**Pull request merged**
