### PR TITLE
Fixes #4967 Added google fonts from RUCSS exclusions

### LINKED ISSUE #4967: Remove Google Fonts CSS when Remove Unused CSS is enabled
**Is your feature request related to a problem? Please describe.**
When Remove Unused CSS is enabled, we are not removing the Google Fonts CSS call, and that can trigger the Remove Unused CSS warning in PSI results.

In some cases, even our own **wpr-usedcss** is going to be listed together with the Google fonts, because any safelistings or automatic compatibility in our SaaS can make the used CSS a few Kbs bigger, and it will still be listed within the global audit.

**Describe the solution you'd like**
Since the fonts should be already referenced in the Used CSS, we can remove the Google Fonts stylesheets by default. And have a filter to reverse the removal if there are issues.

**Describe alternatives you've considered**
Or, it could be the opposite, we can have a filter to remove the font CSS for those cases where it is flagged in the PSI audit

**Additional context**
ticket: https://secure.helpscout.net/conversation/1856608038/338712/
slack convo: https://wp-media.slack.com/archives/C029G1B5HD2/p1650483560291209

Example audit
slack-imgs

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description
Fix a warning present on web.dev concerning web fonts when RUCSS is activated.
For that we excluded by default google fonts from RUCSS.

Fixes #4967 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Test on my test env

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by remyperona — CHANGES_REQUESTED** [review]
I think the solution is to remove the condition on L315, which is preserving the URLs from Google fonts, instead of adding it to the safelist

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@piotrbak @CrochetFeve0251 

The Google Fonts link files are removed when **Optimize Googe fonts** is enabled (https://i.vgy.me/9ifqmc.jpg), but aren't when it's disabled (https://i.vgy.me/4eqlp4.jpg).

Can you look into this? 🙏

**Comment by piotrbak** [comment]
@CrochetFeve0251 We need to handle that too. Would it be possible to have a filter to preserve Google Fonts (like we do now)?

It could be useful if there are any unexpected problems.

**Comment by vmanthos** [comment]
In addition to the previous comment, when **Optimize Google fonts** is activated we preload the combined Google font URL:
```HTML
<link rel="preload" as="style" href="[https://fonts.googleapis.com/css2?family=Koulen&#038;family=Macondo&#038;family=Smooch&#038;display=swap](https://fonts.googleapis.com/css2?family=Koulen&family=Macondo&family=Smooch&display=swap)" /><link rel="stylesheet" href="[https://fonts.googleapis.com/css2?family=Koulen&#038;family=Macondo&#038;family=Smooch&#038;display=swap](https://fonts.googleapis.com/css2?family=Koulen&family=Macondo&family=Smooch&display=swap)" media="print" onload="this.media='all'" /><noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Koulen&#038;family=Macondo&#038;family=Smooch&#038;display=swap" /></noscript>
```
This takes place here:
https://github.com/wp-media/wp-rocket/blob/95b6678f7ec80f0bf562b6e9ca2606fe0a499cc7/inc/Engine/Optimization/GoogleFonts/AbstractGFOptimization.php#L117-L122

This creates a request to Google. It's not flagged in PageSpeed Insights, but it's still there.

I removed that on my test site, and Google fonts loaded fine.

Given that we preload the used fonts, preloading the combined URL seems unnecessary. 

What do you think @piotrbak?

**Comment by piotrbak** [comment]
Yes, totally agree @vmanthos

**Comment by vmanthos** [comment]
After the latest changes, Google Fonts URLs are removed with/without "Optimize Google fonts". Also, no Google fonts CSS files, both combined and not-combined, are preloaded. So, we are good here.👍

@piotrbak One note about the following `preconnect`:
```HTML
<link rel="preconnect" href="https://fonts.googleapis.com/">
```

This is part of the code that someone will take from https://fonts.google.com/:



and it's still there when the Google Fonts URLs are removed by this PR:


This shouldn't be there now that no calls are made to https://fonts.googleapis.com/.

Would you like this to be handled in this PR or should I create a new GitHub issue?

**Comment by piotrbak** [comment]
@vmanthos @CrochetFeve0251 Let's handle it here too, doesn't make sense to come back to it later.

**Comment by vmanthos** [comment]
@CrochetFeve0251 With the latest commit, if the URL has a scheme, .e.g.:
```HTML
<link rel="preconnect" href="https://fonts.googleapis.com">
```

the `preconnect` will be removed.

It won't if no scheme is used:
```HTML
<link rel="preconnect" href="//fonts.googleapis.com">
```

This is because of the `preg_match()` here:
https://github.com/wp-media/wp-rocket/blob/1e5bb5b5366bad725565543e43319e5fafad081f/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L705

Can you please look into this?

I've also found that Storefront adds the following:
```HTML
<link rel='dns-prefetch' href='//fonts.googleapis.com' />
```

This also isn't necessary and should be removed the same way `preconnect` is. 🙏

**Review by vmanthos — APPROVED** [review]
This is working as expected. 👍
* Google Fonts URLs to CSS files are removed
* `dns-prefetch` and `preconnect` for fonts.googleapis.com are removed

**Comment by vmanthos** [comment]
@CrochetFeve0251 @Mai-Saad 🙏 discovered that when Google Fonts v1 are used, e.g.:
```HTML
<link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,100,300,100italic,300italic,400italic,500,500italic,700,700italic,900,900italic&display=auto" />
```

those aren't removed from used CSS because of the following being added:
```HTML
<link rel="preload" as="style" href="https://fonts.googleapis.com/css?family=Montserrat%3A400%2C600%2C700&#038;display=swap" />
```

Can you please take another look?

**Pull request merged**
