### PR TITLE
fix divi with delay js

### LINKED ISSUE #4263: Compatibility with new Divi update (4.10)
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In 4.10 version of Divi, they introduced a couple of enhancements and new features:
https://www.elegantthemes.com/blog/theme-releases/divi-performance

For now, the only feature that seems to be causing problems is `Enqueue jQuery Compatibility Script` (enabled by default). They're adding the following inline script to the top of the source:
http://snippi.com/s/cke9uvo

It causes problems with DelayJS and DeferJS. We need to exclude it to avoid errors in JS console (I haven't observed any problems with the functionalities of the site, but it's possible).

**To Reproduce**
1. Install newest Divi
2. Create a page in their page builder
3. Enable DelayJS and DeferJS in WPR settings

**Expected behavior**
We shouldn't cause any JS console errors

**Screenshots**
Errors when Delay and Defer are enabled:
image

Errors when only Delay is enabled:
image

Errors when only Defer is enabled:
image

**Additional context**
We can exclude them from Delay and Defer using the following pattern `jQuery,customHeadScripts` but we should make sure it doesn't cause any issues. In Mai's case on local it also excluded jQuery files.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by mostafa-hisham**
## Description

add Divi compatibility with new option "Enqueue jQuery Compatibility Script"

Fixes #4263 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

no

## How Has This Been Tested?

- [x] Test locally
- [x] unit and integration

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by piotrbak** [comment]
@mostafa-hisham When I'm enabling Delay JS, their script is not displayed anymore, that's good.

However, after disabling Delay JS, their script is not coming back until I disable WP Rocket. Could you check that?

**Comment by mostafa-hisham** [comment]
@piotrbak can you please check it now?

**Comment by piotrbak** [comment]
@mostafa-hisham It was fixed 🎉  One thing more though, when we're excluding the single page/post from the Delay JS feature, the Divi script is not added there :( 

To reproduce:
1. Enable Delay JS
2. Enable their affected feature
3. Edit the single page and deactivate Delay JS form the right sidebar
4. Visit the page in incognito

I think we should cover this too.

**Comment by mostafa-hisham** [comment]
@piotrbak Can you please check both cases after this change?

**Review by piotrbak — APPROVED** [review]
This one is good to go!
[testrail-report-241.pdf](https://github.com/wp-media/wp-rocket/files/7084650/testrail-report-241.pdf)

**Pull request merged**
