### PR TITLE
Fixes #4460 Prevent removing core lazyload on iframes when only images lazyload is enabled

### LINKED ISSUE #4460: Lazyload images is removing the default LL of wordpress for iframe
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When enabling LL image, the `loading="lazy"` for the iframe is removed. this will result in not delaying iframe scripts while delay js is enabled.

**To Reproduce**
Precondition:
- Having a page with some images/videos i.e https://new.rocketlabsqa.ovh/image-and-video/ 
- Notice iframe in source as follow with nowprocket 
`<iframe loading="lazy" title="Software Testing Tutorials for Beginners" width="750" height="422" src="https://www.youtube.com/embed/goaZTAzsLMk?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

1. Enable LL for images
2. Open the page and check the iframe in the source
`<iframe title="Software Testing Tutorials for Beginners" width="750" height="422" src="https://www.youtube.com/embed/goaZTAzsLMk?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

3. Try to enable Delay js
4. Scripts for  iframe aren't delayed

**Expected behavior**
Not changing iframe in source when LL image is enabled

**Screenshots**
Video for delay js with/without LL enabled

https://user-images.githubusercontent.com/76941962/139025126-2268047c-7045-4f9d-a42a-c5e2ba30f60f.mp4

https://user-images.githubusercontent.com/76941962/139025137-164ae55d-b171-4285-96e8-d0cea45c2af1.mp4

**Additional context**
- Enable LL for iframe and video will fix it

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
## Description

In this PR, the method `maybe_disable_core_lazyload()` is updated to return a different value based on the `$tag_name` (can be `img` or `iframe`), and the current values of our options.

This will avoid removing the core lazyload on iframes when only images lazyload is enabled in WP Rocket.

Also added missing unit and integration tests.

Fixes #4460

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Manual testing
- [x] Automated tests added

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by mostafa-hisham — APPROVED** [review]

**Comment by piotrbak** [comment]
@Tabrisrp I have two questions:
1. When `LazyLoad for iframes` is enabled, we're not removing the `loading=lazy` attribute, I thin it's fine, right?
2. When `Replace YouTube iframe with image` is enabled, inside the `<noscript>` we're adding the iframe without `loading=lazy` attribute. Do you think it's worth fixing?

**Comment by remyperona** [comment]
@piotrbak it's not that we are not removing it, but in fact we do (as we can see in the noscript tag value), but we are adding it back in our code in fact.

that explains point 2 too. I think it's all fine like this, nothing will break.

**Comment by piotrbak** [comment]
@Tabrisrp I think we're okay here. Another thing is that when excluding iframe from the lazyload, the `loading` attribute is not there too. I think it's okay, what do you think?

If so, it's ready to go!
[testrail-report-299.pdf](https://github.com/wp-media/wp-rocket/files/7462599/testrail-report-299.pdf)

**Comment by remyperona** [comment]
I think it's ok yes

**Pull request merged**
