### PR TITLE
Change enqueue position of the delay JS script depending on exclusions field value

### PR DESCRIPTION
**Pull request by remyperona**
## Description

As discussed during stand-up, the position of the delay JS script should change depending on if we have exclusions or not.

This PR updates the code to change the enqueue position depending on the option value:
- In footer if the field is empty
- In header if it's not

## Type of change

- [x] Enhancement (non-breaking change which adds functionality)

## How Has This Been Tested?

- [x] Manual testing with and without values in the exclusions field

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Existing unit tests pass locally with my changes

### CODE REVIEW

**Review by crystinutzaa — APPROVED** [review]

**Comment by GeekPress** [comment]
@Tabrisrp When the script is loaded in the header, it must be the first script. By keeping the default priority on `wp_enqueue_scripts `, I'm afraid it won't necessarily be the case.

**Comment by remyperona** [comment]
@GeekPress I updated the priority to `1`. That should be ok in most cases, but we never know what other plugins or themes do with this.

**Comment by remyperona** [comment]
@wp-media/qa Ready for QA

The delay JS script should now be included early in the `head` when there is a value in the delay JS exclusions field. If it's empty, it remains in the footer.

**Comment by GeekPress** [comment]
> @GeekPress I updated the priority to `1`. That should be ok in most cases, but we never know what other plugins or themes do with this.

The most important is to have our inline script before jQuery when jQuery isn't delayed.

**Review by piotrbak — APPROVED** [review]
Works as expected **with the newest version of the script from alpha6 only**:
[testrail-report-175.pdf](https://github.com/wp-media/wp-rocket/files/6436048/testrail-report-175.pdf)

Note, that I haven't tested the compatibilities with 3rd-parties yet

**Comment by remyperona** [comment]
Notion documentation updated to reflect this change.

**Pull request merged**
