### PR TITLE
use js_exclude_files from backend

### LINKED ISSUE #6024: Add a new backend exclusion field for Minify/Combine JS
**Is your feature request related to a problem? Please describe.**
As we did with other exclusions, we could move the JavaScript files array from `rocket_exclude_js` to the backend. 

The array: 
https://github.com/wp-media/wp-rocket/blob/c23eb7017ce24911f084771103b0beb495f3bf79/inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php#L50C1-L57

**Describe the solution you'd like**
Add a new fields inside our backend under _Exclusions > Minify/Combine JS_ tab in the Backend called `JS Excluded Files` or similar 

**Additional context**
Per discussion with @piotrbak, we cannot resolve issues like this one unless we add that logic: 
https://github.com/wp-media/wp-rocket/issues/5553

Otherwise, we would need to do PRs for such exclusions as we did in the past.

### PR DESCRIPTION
**Pull request by mostafa-hisham**
## Description

Fixes #6024 

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?

- [ ] Unit and integration tests

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@mostafa-hisham Can you please merge the SaaS side of the PR to the staging backend, so I can test it without affecting the production? :pray:

**Comment by vmanthos** [comment]
Thank you for the PR, @mostafa-hisham !

There is a "typo" here:
https://github.com/wp-media/wp-rocket/blob/7cae09139ff929796a698ae295df67110030c46a/inc/Engine/Optimization/DynamicLists/DynamicLists.php#L265

The SaaS is storing the exclusions in `exclude_js_files` while in the code we are looking for `js_exclude_files`.

Can you look into this, please? :pray:

**Comment by mostafa-hisham** [comment]
@vmanthos 

> The SaaS is storing the exclusions in exclude_js_files while in the code we are looking for js_exclude_files.

done
and deployed to staging

**Comment by vmanthos** [comment]
Thank you for the fix, @mostafa-hisham! :pray: 

This is working as expected! :+1: 

**TestRail Note:** [testrail-report-505.pdf](https://github.com/wp-media/wp-rocket/files/12066817/testrail-report-505.pdf)


**NOTES**
1. To match what was here:
https://github.com/wp-media/wp-rocket/blob/c23eb7017ce24911f084771103b0beb495f3bf79/inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php#L50C1-L57

the following must be added  to the production back end before the release:
```PHP
/wp-includes/js/dist/i18n.min.js
/interactive-3d-flipbook-powered-physics-engine/assets/js/html2canvas.min.js
/interactive-3d-flipbook-powered-physics-engine/assets/js/pdf.min.js
/interactive-3d-flipbook-powered-physics-engine/assets/js/three.min.js
/interactive-3d-flipbook-powered-physics-engine/assets/js/3d-flip-book.min.js
/google-site-kit/dist/assets/js/(.*).js
/wp-live-chat-support/public/js/callus(.*).js
```

2. These:
https://github.com/wp-media/wp-rocket/blob/7ff6ad04a6ad1b9c86bc032165d0a131eda9582a/inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php#L51-L55

are automatically excluded because of:
https://github.com/wp-media/wp-rocket/blob/7ff6ad04a6ad1b9c86bc032165d0a131eda9582a/inc/Engine/Optimization/Minify/JS/Minify.php#L39

Maybe we should revisit whether they should be added to the back end. That part of the code exists since 3 years ago, added by the following PR:
https://github.com/wp-media/wp-rocket/pull/2959

**Review by vmanthos — APPROVED** [review]

**Pull request merged**
