### PR TITLE
Added thirdparty class for translatepress

### LINKED ISSUE #5640: RUCSS wrong home_url detection with TranslatePress enabled
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.12.3.3
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
RUCSS is failing for all language homepages when TranslatePress plugin is used.
This is the same issue as shared here: https://github.com/wp-media/wp-rocket/issues/5065

The same solution provided by Ahmed resolves the issue:
https://github.com/wp-media/wp-rocket/issues/5065#issuecomment-1133745028

**To Reproduce**

1. Install and activate [TranslatePress](https://wordpress.org/plugins/translatepress-multilingual/) plugin
2. Add a language with a slug and save settings:
image
3. Enable Remove Unused CSS and visit URL like https://example.com/fr/ in the Incognito browser.
4. Wait for RUCSS to process this page.
5. The generation will fail at all attempts with `400 Bad json` error.

**Expected behavior**
Used CSS should be generated with no issues for language homepages.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/2102001423/390024/
Slack: https://wp-media.slack.com/archives/C029G1B5HD2/p1671727809871749

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Fixed an issue where the homepage from languages was miss detected which created isssue with the RUCSS.

Fixes #5640

## Type of change

Please delete options that are not relevant.
- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Automated Test 
- [ ] Manual Test

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by remyperona** [comment]
Some conflicts to fix

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@CrochetFeve0251 I'm still getting the `error 400` and `Bad json` message. 
Using Postman, I confirmed the SaaS can generate the used CSS for the tested URL.

The `TranslatePress::detect_homepage` method is returning the correct URL.

Can you please look into this? :pray:

**Review by remyperona — APPROVED** [review]

**Review by vmanthos — APPROVED** [review]
This is working as expected! :+1:

**Comment by vmanthos** [comment]
@wp-media/php Can you please resolve the conflicts in this PR and merge it to `develop` so it can be part of `3.14-alpha2`. 
Thank you in advance! :pray:

**Pull request merged**
