### PR TITLE
Closes #3076 Exclude from lazyload option & UI

### LINKED ISSUE #3076: Excluding images from Lazyload
## What are we proposing to do? 

To add a text area in WP Rocket UI that excludes images and iframes from LazyLoad. This text area will be located in the “Media” tab under LazyLoad.

<p></p>

The text area will be shared for both images and iframes and will allow users to exclude images and iframes from LazyLoad by entering the class name, filename, or domain src. 

## Why are we doing this?

This is a well requested feature and a common need for our customers. Currently they have to rely on [<u>snippets we provide in our documentation</u>](https://docs.wp-rocket.me/article/15-disabling-lazy-load-on-specific-images) or a helper plugin to disable images or iframe from LazyLoad. 

<p></p>

We hope to improve the experience of our customers and move one step further in the direction of making WP Rocket even more user friendly. 

## User expectations and experience. How will we do this feature?

- As described before we will be adding a text area to the WP Rocket UI

- This text area will be visible when either LazyLoad for images or iframes is enabled. If both these are disabled, then the text area can be hidden. 

- Any keyword that they enter in the text area will be used to exclude images and/or iframes from LazyLoad. 

## Technical Specs

Spec for text area UI:

- Title: **Excluded images or iframes**

- Description: **Specify keywords (e.g. image filename, CSS class, domain) from the image or iframe code to be excluded (one per line).**

- Placeholder: example-image.jpg

<p></p>

Other notes: 

- The UI should be able to accept a class-name, part of an image filename, or the domain name (src) all in one text area. One per line. 

- The same exclusions apply to both images and iframes. 

- Existing filters continue to exist and work (rocket_lazyload_excluded_attributes, rocket_lazyload_excluded_src, rocket_lazyload_iframe_excluded_patterns)

## Risks

We are not expecting any new issues to be caused by this enhancement. Since existing filters will work as they are now, no websites should be broken or unusable. Nothing changes for existing users. 

<p></p>

We might get a few questions on how to use the UI. This might be the first time many users learn about the possibility to exclude images from LazyLoad. This can be answered with documentation of course. 

## Acceptance Criteria

- The new UI is added as per the given specification. When none of the options for LazyLoad are enabled, the text area stays hidden. 

- Any class name, image filename, domain or iframe pattern added to the text area will prevent the image or iframe from LazyLoad. 

- Current filters continue to work as they do right now. 

## Documentation and Translations

The following documentations need to be updated:

- [<u>https://docs.wp-rocket.me/article/15-disabling-lazy-load-on-specific-images</u>](https://docs.wp-rocket.me/article/15-disabling-lazy-load-on-specific-images)

- [<u>https://docs.wp-rocket.me/article/1260-disable-lazyload-iframes</u>](https://docs.wp-rocket.me/article/1260-disable-lazyload-iframes)

- Since the doc linked from the UI is [<u>https://docs.wp-rocket.me/article/1141-using-lazyload-in-wp-rocket</u>](https://docs.wp-rocket.me/article/1141-using-lazyload-in-wp-rocket) it needs to be updated with explanations for using the text area for exclusion. 

- Helper plugin can be deprecated if needed - [<u>https://github.com/wp-media/wp-rocket-helpers/tree/master/lazyload/wp-rocket-lazyload-disable-src</u>](https://github.com/wp-media/wp-rocket-helpers/tree/master/lazyload/wp-rocket-lazyload-disable-src)

### PR DESCRIPTION
**Pull request by remyperona**
Closes #3076 

This PR adds an option and UI field to be able to exclude images/iframes from lazyload directly from WP Rocket, without the need to use an helper plugin.

## Acceptance Criteria
- The new UI is added to WP Rocket settings page
- Any class name, image filename, domain or iframe pattern added to the text area will prevent the image or iframe from LazyLoad
- Current filters continue to work as they do right now

### CODE REVIEW

**Comment by Tabrisrp** [comment]
@wp-media/qa Ready for QA

**Review by piotrbak — COMMENTED** [review]
@Tabrisrp Maybe more examples in the exclusion field could be useful:
`example.jpg`
`domain.com`
`class="image"`
What do you think? It might reduce some unnecessary tickets I believe.

In terms of functionality everything worked:
[testrail-report-77.pdf](https://github.com/wp-media/wp-rocket/files/5598014/testrail-report-77.pdf)

**Comment by Tabrisrp** [comment]
@piotrbak I followed the feature doc for this, but what do you think @arunbasillal ?

**Comment by arunbasillal** [comment]
We are talking about the placeholder text right? I think we could add the CSS class example because that is something that many users would use. Domain might be rare and the help text already mentions it?

What do you think @piotrbak? Good suggestion btw 🙌

**Comment by Tabrisrp** [comment]
I updated the placeholder, do you need to do more tests @piotrbak, or is it ready to merge?

**Review by piotrbak — APPROVED** [review]
@Tabrisrp It's ready to merge, all other tests passed

**Pull request merged**
