### PR TITLE
Added logic to keep error message

### LINKED ISSUE #6240: RUCSS fetch retries messages are not kept after 3rd retries
**Context**
Follow-up on this [GH issue](https://github.com/wp-media/wp-rocket/issues/6204) which has a bug.

**Bug reproduction**
- Start a RUCSS job from the plugin, and make all fetch results fail.
- After the 2nd fetch, error_message contains the 1st and 2nd failures.
- After the 3rd failed try, the job goes to status "failed" and error_message only contains the last error message.

**How to fix**
Use the concatenation logic of `update_message` in `make_status_failed` as well.

**Acceptance criteria**
Force a job to fail the 3 retries. Once in status failed, the error_message must contain the 3 successive error messages.

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Changed the logic to keep the error messages when passing the row to fail.

Fixes #6240

## Type of change

*Please delete options that are not relevant.*

- Bug fix (non-breaking change which fixes an issue).

# Checklists

## Generic development checklist

- [ ] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
blocked by https://wp-media.slack.com/archives/CUT7FLHF1/p1698568840406219

**Comment by CrochetFeve0251** [comment]
> blocked by https://wp-media.slack.com/archives/CUT7FLHF1/p1698568840406219

Looks like there was a casting issue, I fixed it.

**Comment by Mai-Saad** [comment]
@CrochetFeve0251 Thanks for the update,  still it isnot working. now status is switched to pending with Job id 1 then after a while, it is switched to to_submit where job id is cleared then switched to pending with a new job id while retries are always 0. Can you please check :pray: 
Note: tested on new labs with the latest version of PR merged with dev locally. the related test case that was passing on 3.15.2 https://wpmediaqa.testrail.io/index.php?/cases/view/12667&group_by=cases:section_id&group_id=3166&group_order=asc&display_deleted_cases=0

**Comment by CrochetFeve0251** [comment]
> @CrochetFeve0251 Thanks for the update,  still it isnot working. now status is switched to pending with Job id 1 then after a while, it is switched to to_submit where job id is cleared then switched to pending with a new job id while retries are always 0. Can you please check :pray: 
> Note: tested on new labs with the latest version of PR merged with dev locally. the related test case that was passing on 3.15.2 https://wpmediaqa.testrail.io/index.php?/cases/view/12667&group_by=cases:section_id&group_id=3166&group_order=asc&display_deleted_cases=0

What you described seems like a 408 error from the SAAS, what error you have inside the rows?

**Comment by CrochetFeve0251** [comment]
@Mai-Saad I checked in local and the retries are incrementing normally.

**Comment by Mai-Saad** [comment]
> What you described seems like a 408 error from the SAAS, what error you have inside the rows?

@CrochetFeve0251 Both errors and retries are not added there.

**Comment by MathieuLamiot** [comment]
Discussed [here](https://wp-media.slack.com/archives/CUT7FLHF1/p1698568840406219)

**Comment by Mai-Saad** [comment]
All the error msgs are there now except for 408 (it will change status to to-submit and clear msgs)

**Pull request merged**
