### PR TITLE
Fixed duplicate query on RUCSS

### LINKED ISSUE #6068: Duplicate query when checking rucss table
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
There is a duplicate query when we check if the RUCSS table exists. 
`SHOW TABLES LIKE 'wp\\_wpr\\_rucss\\_used\\_css`

**To Reproduce**
1. Enable Query Monitor plugin
2. View the Duplicate Queries
3. See the duplicate query: https://jumpshare.com/v/TDhTbgX5P5Wz3gb8ByiF

**Expected behavior**
No duplicate query

**Screenshots**
https://jumpshare.com/v/TDhTbgX5P5Wz3gb8ByiF

Per @engahmeds3ed :

> It easily can be fixed [here](https://github.com/wp-media/wp-rocket/blob/b2f0b8f870002148959cb3d28a62671489ac7228/inc/Engine/Optimization/RUCSS/ServiceProvider.php#L53)
> by replacing `add` with `share`
> this will create only one instance from the table class and share it with whatever class calls it.

Original Ticket: https://secure.helpscout.net/conversation/2305707443/431357?folderId=377611

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Fixed the issue where a duplicate query was run to check the existence from the table RUCSS.

Fixes #6068

## Type of change

*Please delete options that are not relevant.*

- Bug fix (non-breaking change which fixes an issue).

## Is the solution different from the one proposed during the grooming?

No.

# Checklists

## Generic development checklist

- [ ] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

### CODE REVIEW

**Comment by remyperona** [comment]
The solution is different from the grooming, can you explain the change?

**Comment by CrochetFeve0251** [comment]
> The solution is different from the grooming, can you explain the change?

The solution is the same:
```
It easily can be fixed [here](https://github.com/wp-media/wp-rocket/blob/b2f0b8f870002148959cb3d28a62671489ac7228/inc/Engine/Optimization/RUCSS/ServiceProvider.php#L53)
by replacing add with share
this will create only one instance from the table class and share it with whatever class calls it.
```

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@piotrbak There are no requests when visiting back-end admin pages. :+1: 

When visiting WP Rocket's settings page the requests were reduced from 5 to  4:
image

Is there a way/need to further reduce them?

**Comment by piotrbak** [comment]
@vmanthos The initial problem is solved. The checks here are guards against non-existing tabled while doing operations, that seems to be okay for now

**Review by vmanthos — APPROVED** [review]
Thank you @piotrbak. :pray: 

We are good to go here! :+1:

**Pull request merged**
