### PR TITLE
Fixes #6865 Container V4 service provider error about providing (options_debug) service

### LINKED ISSUE #6865: Container V4 service provider lied about providing (options_debug) service
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
After [updating the container to V4](https://github.com/wp-media/wp-rocket/issues/6539), we cannot use `options_debug` in Rucss debug tool.

we are getting this error
```
Fatal error: Uncaught WP_Rocket\Dependencies\League\Container\Exception\ContainerException: Service provider lied about providing (options_debug) service in /home/mostafa/Local Sites/wp-copra/app/public/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Container.php:195 Stack trace: #0 /home/mostafa/Local Sites/wp-copra/app/public/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Container.php(118): WP_Rocket\Dependencies\League\Container\Container->resolve('options_debug') #1 /home/mostafa/Local Sites/wp-copra/app/public/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Container.php(203): WP_Rocket\Dependencies\League\Container\Container->get('options_debug') #2 /home/mostafa/Local Sites/wp-copra/app/public/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Container.php(118): WP_Rocket\Dependencies\League\Container\Container->resolve('options_debug') #3 /home/mostafa/Local Sites/wp-copra/app/public/wp-content/plugins/rucss-debug-tool/configs/binding.php(87): WP_Rocket\Dependencies\League\Container\Container->get('options_debug') #4 /home/mostafa/Local Sites/wp-copra/app/public/wp-content/plugins/rucss-debug-tool/inc/main.php(24): require_once('/home/mostafa/L...') #5 /home/mostafa/Local Sites/wp-copra/app/public/wp-includes/class-wp-hook.php(324): WPRocket\RUCSSDebugTool\init('') #6 /home/mostafa/Local Sites/wp-copra/app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #7 /home/mostafa/Local Sites/wp-copra/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #8 /home/mostafa/Local Sites/wp-copra/app/public/wp-content/plugins/wp-rocket/inc/main.php(102): do_action('wp_rocket_loade...') #9 /home/mostafa/Local Sites/wp-copra/app/public/wp-includes/class-wp-hook.php(324): rocket_init('') #10 /home/mostafa/Local Sites/wp-copra/app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #11 /home/mostafa/Local Sites/wp-copra/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #12 /home/mostafa/Local Sites/wp-copra/app/public/wp-settings.php(550): do_action('plugins_loaded') #13 /home/mostafa/Local Sites/wp-copra/app/public/wp-config.php(108): require_once('/home/mostafa/L...') #14 /home/mostafa/Local Sites/wp-copra/app/public/wp-load.php(50): require_once('/home/mostafa/L...') #15 /home/mostafa/Local Sites/wp-copra/app/public/wp-blog-header.php(13): require_once('/home/mostafa/L...') #16 /home/mostafa/Local Sites/wp-copra/app/public/index.php(17): require('/home/mostafa/L...') #17 {main} thrown in /home/mostafa/Local Sites/wp-copra/app/public/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Container.php on line 195

Notice: Function is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /home/mostafa/Local Sites/wp-copra/app/public/wp-includes/functions.php on line 6078

Notice: Function is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /home/mostafa/Local Sites/wp-copra/app/public/wp-includes/functions.php on line 6078
There has been a critical error on this website.
Learn more about troubleshooting WordPress.
```
With @CrochetFeve0251  help  we checked and in wp-rocket we are bailing out [here](https://github.com/wp-media/wp-rocket/blob/abee9d80060974b894ffd846e4d6d857ed9d0c02/inc/Engine/Debug/ServiceProvider.php#L64) and we don't serve it

**To Reproduce**
1. Add rucss-debug-tool and switch to the branch of this [PR](https://github.com/wp-media/rucss-debug-tool/pull/16/)
2. open admin page

**Expected behavior**
We should use the  `options_debug` like this
`$container->get('options_debug' ),`

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Khadreal**
# Description

Fixes #6865 

### User documentation

No impact.

### Technical documentation

Add `options_debug` directly to the `boot` method since it doesn't have a service registered.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

## Detailed scenario
Check issue #6865  for detailed scenario

### Documentation
Fix service provider error for container without a registered service

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I did not introduce unecessary complexity.

### CODE REVIEW

**Comment by CrochetFeve0251** [comment]
hmmm I don't really get the solution provided on this branch as it doesn't seem to match what was said during grooming.

Instead, doing this would fix the issue and match the grooming:

```php
<?php
namespace WP_Rocket\Engine\Debug;

use WP_Rocket\Dependencies\League\Container\ServiceProvider\{AbstractServiceProvider, BootableServiceProviderInterface};
use WP_Rocket\Admin\Options_Data;

/**
 * Service provider for Debug
 */
class ServiceProvider extends AbstractServiceProvider implements BootableServiceProviderInterface {
	/**
	 * Array of services provided by this service provider
	 *
	 * @var array
	 */
	protected $provides = [
		'debug_subscriber',
	];

	/**
	 * Array of available debug services.
	 *
	 * @var array
	 */
	protected $services = [];

	/**
	 * Check if the service provider provides a specific service.
	 *
	 * @param string $id The id of the service.
	 *
	 * @return bool
	 */
	public function provides( string $id ): bool {
		return in_array( $id, $this->provides, true );
	}

	/**
	 * Register the service in the provider array
	 *
	 * @return void
	 */
	public function boot(): void {
		$this->services = $this->getContainer()->get( 'debug_resolver' )->get_services();

		if ( empty( $this->services ) ) {
			return;
		}

		$this->provides []= 'options_debug';

		foreach ( $this->services as $service ) {
			$this->provides[] = $service['service'];
		}
	}

	/**
	 * Registers items with the container
	 *
	 * @return void
	 */
	public function register(): void {
		$this->container->add( 'debug_subscriber', DebugSubscriber::class );

		if ( empty( $this->services ) ) {
			return;
		}

		$this->container->add( 'options_debug', Options_Data::class )
			->addArgument( $this->container->get( 'options_api' )->get( 'debug', [] ) );

		foreach ( $this->services as $service ) {
			$this->getContainer()->add( $service['service'], $service['class'] )
				->addArgument( $this->getContainer()->get( 'options_debug' ) )
				->addArgument( $this->getContainer()->get( 'options_api' ) );
		}
	}
}

```

**Review by Miraeld — APPROVED** [review]

**Comment by mostafa-hisham** [comment]
@Khadreal  
It didn't work with `rucss-debug-tool `in my end
but after removing `options_debug` from [the protected $provides  array](https://github.com/wp-media/wp-rocket/blob/5a5f387c7900af4b57bc57c60afca52a46868a6a/inc/Engine/Debug/ServiceProvider.php#L18) like @CrochetFeve0251 suggested [here](https://github.com/wp-media/wp-rocket/pull/6902#issuecomment-2309514781) it worked

**Comment by MathieuLamiot** [comment]
I just pushed the change showed by @mostafa-hisham.
It is working on my side as well.

**Review by jeawhanlee — APPROVED** [review]

**Comment by MathieuLamiot** [comment]
Tested with the RUCSS Debug tool and working fine.

**Pull request merged**
