### PR TITLE
Fixes #3001 Delay JS alpha issues

### LINKED ISSUE #3001: Delay JS alpha issues
- [x] When I updated from a previous version, I didn’t get the pre-filled list of of JS files until I clicked “Restore Defaults” https://recordit.co/ujbBNTejit

- [x] Could we increase the height of the textarea for Delay JS to be able to view all inclusions without needed to scroll inside the textarea?

- [x] When delay JS is disabled and try enable/disable any addon it will enable delay JS automatically https://share.getcloudapp.com/o0u8q59o

### PR DESCRIPTION
**Pull request by engahmeds3ed**
Fixes #3001 

- [x] When I updated from a previous version, I didn’t get the pre-filled list of of JS files until I clicked “Restore Defaults” https://recordit.co/ujbBNTejit

- [x] Could we increase the height of the textarea for Delay JS to be able to view all inclusions without needed to scroll inside the textarea?

- [x] When delay JS is disabled and try enable/disable any addon it will enable delay JS automatically https://share.getcloudapp.com/o0u8q59o

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Review by hellofromtonya — APPROVED** [review]

**Comment by Davidacu** [comment]
Getting a fatal error when activating the plugin
image

**Review by Davidacu — COMMENTED** [review]
**Working as expected**:
- The default list of safe scripts to delay does appear when updating from previous versions.
- The delay js option appears enabled by default for new users
- The delay js option appears disabled when updating from previous version.
- The height of the textarea for introducing the scripts to delay has now increased.
  before:https://i.imgur.com/bfw3QUj.png
  after: https://i.imgur.com/JqWbwJr.png
- Issue with auto-enabling delay js option is fixed.

**Issues:**
- The delay js option is still not applied in uncached pages.
I noticed the scripts are now added in the page source, however the feature doesn't seem to work.
when the page can be cached the feature does work -> https://screencast-o-matic.com/watch/cYjF0UGR7R

**Comment by Tabrisrp** [comment]
@hellofromtonya @arunbasillal @GeekPress 

I looked back at it, and in fact in the current state we can't apply it on uncached pages, because the optimization process using `rocket_buffer` is not applied for now (see related issue #2713). This is because a page excluded from page doesn't trigger the hook, the process bails out early.

This means that while the script are inserted (since they use the `wp_enqueue_scripts` hook), the rewrite of the HTML to lazyload the scripts is not happening.

We _could_ switch to a different hook like `template_redirect`, but it would come at the cost of doing another output buffering, additional checks to make sure we're on a real front end page, etc. I'm not sure the trade-off is worth it, and it would increase the time to finish this feature.

It could be valuable to keep this for cached page only for now, and switch it with the other optimizations when we work on the epic linked above.

Thoughts?

**Comment by GeekPress** [comment]
> It could be valuable to keep this for cached page only for now, and switch it with the other optimizations when we work on the epic linked above.

To not delay the 3.7 release, let's do like that. Having this feature on cached page is already a big improvement :)

**Pull request merged**
