### PR TITLE
Closes #5104 with fatal error on rollback from 3.11.3 to 3.10.9

### LINKED ISSUE #5104: Fatal error on Rollback from 3.11.3 version to 3.10.9
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.11.3
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
The following fatal error comes up on rollback from 3.11.3 to 3.10.9:

```
[01-Jun-2022 09:47:54 UTC] PHP Fatal error:  Uncaught Error: Class 'ActionScheduler_Lock' not found in .../wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler.php:29
Stack trace:
#0 .../wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_QueueRunner.php(103): ActionScheduler::lock()
#1 .../wp-includes/class-wp-hook.php(307): ActionScheduler_QueueRunner->maybe_dispatch_async_request('')
#2 .../wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#3 .../wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#4 .../wp-includes/load.php(1100): do_action('shutdown')
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in .../wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler.php on line 29
```

**To Reproduce**
1. Have version 3.11.3 installed and activated
2. Use Tools tab option to Rollback to 3.10.9
3. The fatal error will be logged

**Expected behavior**
No errors should be logged

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1905508352/346096/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

Fixes fatal error thrown during rollback from v3.11.3 to v3.10.9

Fixes #5104 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

This solution is in no way different from the proposed.

## How Has This Been Tested?

Follow steps [here](https://github.com/wp-media/wp-rocket/issues/5104#issuecomment-1147485031)
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@jeawhanlee @piotrbak I'm still getting the fatal error with this branch:
```
[14-Jun-2022 11:12:07 UTC] PHP Fatal error:  Uncaught Error: Class "ActionScheduler_Lock" not found in /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler.php:29
Stack trace:
#0 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_QueueRunner.php(103): ActionScheduler::lock()
#1 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(307): ActionScheduler_QueueRunner->maybe_dispatch_async_request()
#2 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#3 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(476): WP_Hook->do_action()
#4 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/load.php(1102): do_action()
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler.php on line 29
```
🤔 

Do you mind taking another look? 🙏

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@jeawhanlee @piotrbak even with the latest changes the error is still there:
```PHP
[17-Jun-2022 09:45:13 UTC] PHP Fatal error:  Uncaught Error: Class 'ActionScheduler_Lock' not found in /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler.php:29
Stack trace:
#0 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_QueueRunner.php(103): ActionScheduler::lock()
#1 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(307): ActionScheduler_QueueRunner->maybe_dispatch_async_request()
#2 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#3 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(476): WP_Hook->do_action()
#4 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/load.php(1102): do_action()
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler.php on line 29

```

**Comment by vmanthos** [comment]
We tested this with @jeawhanlee while using `PHP 7.4`. The error didn't take place.

I realized that the previous time I reported it I was running `PHP 8.1.7`. I checked this for a third time now using that version and it occurred again.

**Review by vmanthos — APPROVED** [review]
After the latest commits, I cannot reproduce the issue anymore with PHP `8.1.7`. 👏

**Pull request merged**
