### PR TITLE
fix deprecation notice

### LINKED ISSUE #5801: PHP Deprecated: notices with PHP 8.2.3
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.6.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
PHP Deprecated notice  (count 150+) exists in debug.log while site is using PHP 8.2.3
`[08-Mar-2023 14:51:05 UTC] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php on line 253`
`[08-Mar-2023 14:51:09 UTC] PHP Deprecated:  Creation of dynamic property WP_Rocket\Engine\Preload\Database\Rows\CacheRow::$id is deprecated in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/Database/Base.php on line 266
`
**To Reproduce**
1. Website using PHP 8.2.3
2. Install and activate WPR
3. check debug.log

**Expected behavior**
no deprecated notice in debug.log

**Additional context**
- This doesn't exist with PHP 8.1.14

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

Fixes deprecation warning.

Fixes #5801 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Automated tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by piotrbak** [comment]
@jeawhanlee How is it going with this one?

**Comment by jeawhanlee** [comment]
@piotrbak This PR fixes @vmanthos comment [here](https://github.com/wp-media/wp-rocket/issues/5801#issuecomment-1484884813) but the errors @Mai-Saad reported [here](https://github.com/wp-media/wp-rocket/issues/5801#issuecomment-1467481105) are from berlin db. Should I open this PR for review?

**Comment by piotrbak** [comment]
@jeawhanlee I opened a new issue for this problem. Could you open a new PR that will fix those errors mentioned by @vmanthos there?

**Comment by jeawhanlee** [comment]
@piotrbak Yes I can

**Pull request closed without merging**
