### PR TITLE
Refactor clean RUCSS/Critical images dashboard button

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Refactor the code for the clean RUCSS/Critical images dashboard button, moving it from hardcoded in the template to an action and a callback

## Type of change

- Enhancement (non-breaking change which improves an existing functionality).

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.

### CODE REVIEW

**Comment by Mai-Saad** [comment]
@Tabrisrp Thanks for the PR. Please find exploratory test notes about clear critical images below. (note, the same points already exist on the base branch)
1- When click clear critical images, we get the following fatal error (we will have  same error if we click clear used css from admin )
```
[18-Dec-2023 07:23:21 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function WP_Rocket\Engine\Saas\Admin\apply_filter() in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Saas/Admin/Clean.php:26
Stack trace:
#0 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Saas/Admin/Subscriber.php(97): WP_Rocket\Engine\Saas\Admin\Clean->clean_saas()
#1 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Saas\Admin\Subscriber->clean_saas()
#2 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /var/www/new.rocketlabsqa.ovh/htdocs/wp-admin/admin-post.php(85): do_action()
#5 {main}
  thrown in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Saas/Admin/Clean.php on line 26
```
2- clear critical image for this URL is displayed at each admin page
Screenshot from 2023-12-18 09-21-47
Screenshot from 2023-12-18 09-21-37
3- When click clear critical images, we will have this deprecated notice 
`[18-Dec-2023 07:23:21 UTC] PHP Deprecated:  Creation of dynamic property WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS::$optimize_url_context is deprecated in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 106` => same notices when clear and preload cache

**Review by jeawhanlee — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Tabrisrp Thanks for the update. using commit id 52538566e515f6e56f7189a57b2d21f98b58e9b7
1- Here, no deprecated notice nor fatal error now :tada: but when clicking clear critical images, admin keeps loading sign in the browser tab, and nothing cleared from the database => if RUCSS is enabled, clear used CSS won't reflect on database nor file system as well
2- Clear critical image for this URL still displayed on non-related pages => if RUCSS is enabled, clear used CSS for this URL will be displayed on non-related pages as well
Screenshot from 2023-12-26 14-19-00
Note: Exploratory Test done on https://newer.rocketlabsqa.ovh/

**Comment by remyperona** [comment]
Thank you, the latest commits should fix the 2 issues reported.

**Review by Miraeld — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Tabrisrp Thanks for the update. 
- Now clear critical images for this URL is displayed to post(view), page(view/edit), product (edit/view) and media (view/edit) but **it is displayed now at private post while it shouldn't as same as with rucss**
- Clear critical images now is clearing the critical images so no loop, but **in this case we shall clear cache as same as with RUCSS (Clear critical images shall interact as same as clear used css in terms of cache clear).**

**Comment by remyperona** [comment]
Both points should be fixed now

**Comment by Mai-Saad** [comment]
@Tabrisrp Thank you, Working fine now :tada:

**Pull request merged**
