### PR TITLE
Fixes #4759 Hide scripts from the buffer

### LINKED ISSUE #4759: Add missing image dimensions feature breaks scripts that contain image
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.10.8
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
**Add missing image dimensions** feature is being applied within scripts when they append HTML. This may break the script due to mismatch of the single/double quotes.

**To Reproduce**
1. Add a script like this to a page:
```
<script type="text/javascript">// <![CDATA[
jQuery(document).ready(function(){ jQuery("#footer-info").text(' '); jQuery("<p align='center'><img src='https://your-site.com/image.jpeg' /></p>").insertAfter("#footer-info"); });
// ]]></script>
```
Make sure to have the image src leading to an existing image on the site where it is tested.
2. Enable **Add missing image dimensions** option
3. Check page source code in the incognito browser window. The script will be replaced by this:
```
<script type="text/javascript">// <![CDATA[
jQuery(document).ready(function(){ jQuery("#footer-info").text(' '); jQuery("<p align='center'><img width="1920" height="1080" src='https://testsite.nataliadrause.com/wp-content/uploads/2021/12/Pexels-Videos-1580455-1-poster.jpeg' /></p>").insertAfter("#footer-info"); });
// ]]></script>
```
4. Console will have this error:
`Uncaught SyntaxError: missing ) after argument list`
image

This is because the double quote `''` from the image attribute is closing the HTML string too soon.

This is how it is interpreted:
image

**Expected behavior**
Possibly we should not apply the feature within scripts.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1794018812/327474?folderId=3864740

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### LINKED ISSUE #4767: PHP fatal error when lazyloading images
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.10.8`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

A PHP fatal error, like the following:
```
PHP Fatal error: Uncaught TypeError: preg_match_all() expects parameter 2 to be string, null given in /nas/content/live/exampleprod/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php:257

Stack trace:
#0 /nas/content/live/exampleprod/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php(257): preg_match_all('#<picture(?:.*)...', NULL, NULL, 2)
#1 /nas/content/live/exampleprod/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php(372): WP_Rocket\\Dependencies\\RocketLazyload\\Image->lazyloadPictures('<!DOCTYPE html>...', NULL)
#2 /nas/content/live/exampleprod/wp-includes/class-wp-hook.php(303): WP_Rocket\\Engine\\Media\\Lazyload\\Subscriber->lazyload('<!DOCTYPE html>...')
#3 /nas/content/live/exampleprod/wp-includes/plugin.php(189): WP_Hook->apply_filters('<!DOCTYPE html>...', Array)
#4 /nas/content/live/exampleprod/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-optimization.php(104): apply_filters('rocket_buffer', '<!DOCTYPE html>...')\
n#5 [internal function","PHP Fatal error: Uncaught TypeError: preg_match_all() expects parameter 2 to be string, null given in /nas/content/live/exampleprod/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php:257
Stack trace:
#0 /nas/content/live/exampleprod/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php(257): preg_match_all('#<picture(?:.*)...', NULL, NULL, 2)
#1 /nas/content/live/exampleprod/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php(372): WP_Rocket\\Dependencies\\RocketLazyload\\Image->lazyloadPictures('<!DOCTYPE html>...', NULL)
#2 /nas/content/live/exampleprod/wp-includes/class-wp-hook.php(303): WP_Rocket\\Engine\\Media\\Lazyload\\Subscriber->lazyload('<!DOCTYPE html>...')
#3 /nas/content/live/exampleprod/wp-includes/plugin.php(189): WP_Hook->apply_filters('<!DOCTYPE html>...', Array)
#4 /nas/content/live/exampleprod/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-optimization.php(104): apply_filters('rocket_buffer', '<!DOCTYPE html>...')
#5 [internal function]: WP_Rocket\\Buffe in /nas/content/live/exampleprod/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php on line 257, referer: https://www.example.com/collaboration/","Fri Feb 25 2022 11:31:34 GMT+0530 (India Standard Time)"
```

occurs if either of the following two lines:
https://github.com/wp-media/wp-rocket/blob/c2f41672833937b3025e6b6acf59cf9f27116007/inc/Engine/Media/Lazyload/Subscriber.php#L359-L360

returns `NULL`, e.g. because of a `PREG_BACKTRACK_LIMIT_ERROR`.

This is because we aren't safeguarding the `ignore_scripts()` and `ignore_noscripts()` methods from returning such a value.

**To Reproduce**

The page where this occurred can be downloaded from here:
https://drive.google.com/uc?id=18G-DrCTU1ENDbDZndG79ACHXk5-Wgckd

**Expected behavior**

No PHP fatal errors should occur with lazyload.

**Additional context**

We can check what both methods return, and if `empty()` return the unprocessed HTML.
The feature will not be applied, but no PHP fatal errors will occur.

Also, given that we apply those methods in the subscriber, I'm thinking we don't need these two lines:
https://github.com/wp-media/wp-rocket/blob/b34218065e5935e7482c7c60721becc26e237c97/inc/Dependencies/RocketLazyload/Image.php#L26-L27

If we need them, we have to safeguard them as well.

**Ticket:** https://secure.helpscout.net/conversation/1797267220/328111?folderId=2135277
The customer didn't provide access, so the investigation was done only by checking the code.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description
Fix a bug where images inside scripts were having dimensions too breaking the JS script.
Centralized hide functions in RegexTrait.

Fixes #4759
Fixes #4767 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?
No the grooming was right

## How Has This Been Tested?

- [x] Automated tests
- [x] Local tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@CrochetFeve0251 @Tabrisrp please find exploratory test notes below:
- Can see this fatal error with LL images on the test template, can you please check it.
```
29-Mar-2022 12:00:54 UTC] PHP Fatal error:  Uncaught TypeError: preg_match_all() expects parameter 2 to be string, null given in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php:29
Stack trace:
#0 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php(29): preg_match_all('#<img(?<atts>\\s...', NULL, NULL, 2)
#1 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php(378): WP_Rocket\Dependencies\RocketLazyload\Image->lazyloadImages('\n<!DOCTYPE html...', '\n<!DOCTYPE html...', false)
#2 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(307): WP_Rocket\Engine\Media\Lazyload\Subscriber->lazyload('\n<!DOCTYPE html...')
#3 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(189): WP_Hook->apply_filters('\n<!DOCTYPE html...', Array)
#4 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-optimization.php(104): apply_filters('rocket_buff in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php on line 29
```
- @piotrbak LL image is applied on commented/uncommented NoScript and on commented `<img`, is this ok, or do we need GH for this?
- Missing dimension is added to commented images` <img `, is this expected with the latest change?

**Comment by CrochetFeve0251** [comment]
@Tabrisrp should I use the RegexTrait also in Image?

**Comment by piotrbak** [comment]
🤔 We should not apply lazy load markup to the images that are inside the `<noscript></noscript>`. Our library is based on JS so it won't work when JS is not available

**Comment by remyperona** [comment]
We can hide the comments in lazyload and image dimensions too

**Review by Mai-Saad — APPROVED** [review]
Working as expected with the following notes:
- LL images and add missing dimensions are applied on commented `<img`
- CDN is applied to URLs in comments
- Delay js is applied to commented scripts
[testrail-report-366.pdf](https://github.com/wp-media/wp-rocket/files/8419327/testrail-report-366.pdf)

**Pull request merged**
