### PR TITLE
Update TravisCI configuration

### PR DESCRIPTION
**Pull request by Tabrisrp**
- Remove PHP 7 & 7.1
- Name Legacy build running PHP 5.6 & WP 4.9
- Add specific build for coding standards
- Move some commands from `before_script` to `before_install`
- Run composer on `install step`
- Run PHP CS only on coding standards build

### CODE REVIEW

**Comment by Tabrisrp** [comment]
I'm having a doubt about the `composer phpcs` command:
- On local it's marking 274 files checked
- On Travis it's only marking 46 files checked

**Comment by hellofromtonya** [comment]
@Tabrisrp Are you running it locally on PHP 7.3 version to match Travis?

**Comment by Tabrisrp** [comment]
Yes I'm running 7.3 too on local

**Comment by hellofromtonya** [comment]
@Tabrisrp Here's the results on my machine (ssh into the localhost):

```
root@0393426ee26a:/app/public/wp-content/plugins/wp-rocket# composer phpcs
> phpcs --basepath=.
.............................................. 46 / 46 (100%)
```

**Pull request merged**
