### PR TITLE
Fixes #6786 Exclude the regular image when a nextgen is detected on OCI

### LINKED ISSUE #6786: Exclude the regular image when a nextgen is detected on OCI
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version [x]
- Used the search feature to ensure that the bug hasn’t been reported before [x]

**Describe the bug**
After the following enhancement - https://github.com/wp-media/wp-rocket/issues/6638

Images are preloaded correctly but not excluded from lazyload. 

This is caused by the exclusion targeting the `img` element on lazyload that won't find the next-gen image detected as LCP. 

The exclusion system needs to include the `source` element as a verifiable exclusion targe. 

**To Reproduce**
1. Add an image with a plug that will add a `picture` tag with nextgen
2. Run beacon
3. See image preloaded but not excluded from lazyload

**Expected behavior**
When a next gen is detected as LCP, the right source image should be excluded from lazyload. 

**Screenshots**
N/A

**Additional context**
Slack - https://wp-media.slack.com/archives/C072P5EU5DF/p1721065409522049

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

### PR DESCRIPTION
**Pull request by Khadreal**
# Description
Update the pattern to capture nextgen excluded lcp image for lazyload
Fixes #6786 

### User documentation
Fix lcp and lazyload bug with next gen image plugin. 

### Technical documentation
Modify the `canLazyload` method to check  both image `src` and `srcset` for exclusion src before applying lazyload to image.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

## New dependencies
N/A

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [x] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

### CODE REVIEW

**Review by Miraeld — APPROVED** [review]

**Comment by remyperona** [comment]
Can you update the technical documentation to explain why this is the change that fixes the issue, and also add test cases to cover this?

**Comment by Khadreal** [comment]
> Can you update the technical documentation to explain why this is the change that fixes the issue, and also add test cases to cover this?

Updated now, please check again

**Comment by remyperona** [comment]
I still don't understand the context of the change related to `srcset`, what is the root cause? The test added also doesn't cover exclusion of `srcset`, only `src`.

**Comment by MathieuLamiot** [comment]
Based on https://github.com/wp-media/wp-rocket/issues/6786 grooming, the fix we will settle on is different. I am closing this PR for now.

**Pull request closed without merging**
