### PR TITLE
Fix #6526 LCP/ATF messages that is not working correctly

### LINKED ISSUE #6526: Messages of LCP/ATF isnot working correctly
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => commit f488281de0de219b5db95ce5f29bc167fea903ad (HEAD -> 6519-316-bug-front-end-optimizations-are-not-applied-even-when-lcpatf-data-is-in-the-db
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
- With fresh install of 3.16 , the success message of rucss is displayed => no message while Rucss is off
- when enable RUCSS, no message is displayed at all =>  updated counter message shall be displayed then updated success message shall be displayed
-  when external request is blocked, no message is displayed => updated message shall be displayed while rucss is on

**Expected behavior**
Apply the messages mentioned here https://www.notion.so/wpmedia/Beacon-Auto-optimize-LCP-image-Auto-exclude-images-above-the-fold-from-LazyLoad-56226bccec874b45aed4a57f08690029?pvs=4#c6830acbda4a44fbb723749c9116211f

**Screenshots**

**Additional context**
- Currently after clear used CSS while RUCSS is on, message is `WP Rocket: Used CSS cache cleared!`, shall we change this too @piotrbak ? if yes, to what?

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

### PR DESCRIPTION
**Pull request by Khadreal**
# Description
Fixed ATF/LCP message not showing

Fixes #6526 

### User documentation

*Explain how this code impacts users.*

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation
- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote self-explanatory code about what it does.

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by remyperona** [comment]
Changes LGTM, can you update:
- The PR title to respect our naming convention
- The checklist
- The assignee, label, milestone

**Comment by Mai-Saad** [comment]
@Khadreal Thanks for the PR. Please find exploratory test notes below: 

1. The successful old RUCSS notice with a fresh install of 3.16 is still displayed
2. The new notices when enabling RUCSS aren't displayed => counter https://github.com/wp-media/wp-rocket/pull/6562/files#diff-25f931bcb7ef216b9bad8ed4e4827d5207d72c450cc54a27e5e0db362be9e8cdR104 and success https://github.com/wp-media/wp-rocket/pull/6562/files#diff-25f931bcb7ef216b9bad8ed4e4827d5207d72c450cc54a27e5e0db362be9e8cdR147
3. @piotrbak Do we need any updates in the notice for nulled license https://github.com/wp-media/wp-rocket/pull/6562/files#diff-25f931bcb7ef216b9bad8ed4e4827d5207d72c450cc54a27e5e0db362be9e8cdR232 ?


For testing the PR
- Related test run https://wpmediaqa.testrail.io/index.php?/runs/view/842&group_by=cases:section_id&group_order=asc 
- We need to explore what will happen when updating while RUCSS is on/off in terms of msgs
- Rollback while blocking external request caused error => we need to explore Rollback in this case while RUCSS is on/off (may be it's due BG process)
[debug.log](https://github.com/wp-media/wp-rocket/files/15033868/debug.log)

**Comment by jeawhanlee** [comment]
@Khadreal 
### Something overlooked during the grooming:
- We need to also check here if RUCSS is disabled
https://github.com/wp-media/wp-rocket/blob/88ceebfbc9ae84a61b69c4af819989fe9e879e4d/inc/Engine/Saas/Admin/Notices.php#L141

we can do something like this: `if ( false !== $transient || ( ! $this->options->get( 'remove_unused_css', 0 ) ) )`

### Somethings that was not implemented in this PR:
- I can see this [here](https://github.com/wp-media/wp-rocket/blob/0a85128435a8ae95527fda648111120e4a9ae6cc/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L420) was not updated to `rocket_saas_processing`
- The updated script was not also bundled, try using `gulp run:build`
- And I think we need to update related tests that still have `rocket_rucss_processing`
- The messages has not been updated to those on the epic: https://www.notion.so/wpmedia/Beacon-Auto-optimize-LCP-image-Auto-exclude-images-above-the-fold-from-LazyLoad-56226bccec874b45aed4a57f08690029?pvs=4#29b2990bb3d34436930a5577b66881e1

**Comment by Khadreal** [comment]
@jeawhanlee not just that, the `get_transient` is still referencing the old value on line 138. I've changed that and couple of other things

**Review by remyperona — APPROVED** [review]

**Comment by MathieuLamiot** [comment]
@Khadreal I checked [the test plan shared by Mai above]. There are issues for 2 tests related to this PR I think. Can you check? (https://wpmediaqa.testrail.io/index.php?/runs/view/842&group_by=cases:section_id&group_order=asc):
- [Shouldn't display any notice after fresh install of 3.16](https://wpmediaqa.testrail.io/index.php?/tests/view/41745): This is still failing with this PR

https://github.com/wp-media/wp-rocket/assets/15233030/18b56f1a-808b-4d7a-80c7-67b2adea4498

- [Should display new success notice after RUCSS is generated](https://wpmediaqa.testrail.io/index.php?/tests/view/41743): Just after activating I have the message but there are two dots at the end.

image

- [Should display notice while API URL not reachable even if RUCSS is off](https://wpmediaqa.testrail.io/index.php?/tests/view/41740): for step 1, I add to click "Clear Critical Images" to trigger the SaaS requests and hence the banner. I think it's OK and the test step should just be more precise (@Mai-Saad). Other than that ✅ 

- [Should display banner when license is expired /about to expire](https://wpmediaqa.testrail.io/index.php?/tests/view/41739) : ✅

**Review by remyperona — APPROVED** [review]

**Comment by MathieuLamiot** [comment]
All good now https://wpmediaqa.testrail.io/index.php?/runs/view/842&group_by=cases:section_id&group_order=asc

**Pull request merged**
