### PR TITLE
Enhancement: Fix the completed action after preload to match the one on wp-rocket.me

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Make the code match wp-rocket.me version.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by remyperona** [comment]
Can you explain a bit this code change?

**Review by remyperona — APPROVED** [review]

**Comment by piotrbak** [comment]
@CrochetFeve0251 What should be tested in this PR?

**Comment by CrochetFeve0251** [comment]
> @CrochetFeve0251 What should be tested in this PR?

We just need to test the action is executed after some cache is loaded.

**Comment by vmanthos** [comment]
The action is firing as expected for both desktop and mobile devices.

However, it's not taking into consideration the value of this filter:
https://github.com/wp-media/wp-rocket/blob/498e405a9eb0a7bc0aaf8f27e01406bf9470030e/inc/functions/files.php#L103

If the [WP Rocket | Set Tablets As Mobile](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-tablet) helper is used to change how WP Rocket treats tablets from `desktop` (default setting) to `mobile`, for a  tablet request the action will mistakenly return `desktop` instead of `mobile`.

**To reproduce**

**Preconditions**
- Enable the **Separate cache files for mobile devices** feature.
- Add the following snippet to log the preload URL and device type:
```PHP
add_action( 'rocket_preload_completed', function( $url, $detected ){
	if( ! defined( 'WP_ROCKET_VERSION' ) ) return;
	error_log( "URL: $url\tDevice: $detected\tUser Agent: " . $_SERVER['HTTP_USER_AGENT']. "\n", 3, ABSPATH . 'PRELOAD_COMPLETED.log');
}, 10, 2);
```

Then:
1. Visit an uncached URL using an iPad simulator in Chrome Dev Tools. You'll get this in the log:
```
 https://wprocketest.test/blog	Device: **desktop**	User Agent: Mozilla/5.0 (iPad; CPU OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1
```
2. Install/activate the [WP Rocket | Set Tablets As Mobile](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-tablet) helper plugin.
3. Repeat step 1. Instead of getting `Device: mobile` in the log, you'll get the same device type as previously.

@piotrbak Is this something that should be handled in this PR, or should I create a new GitHub issue about it?

**Comment by piotrbak** [comment]
@vmanthos Is this a regression when comparing to the previous version?

**Comment by vmanthos** [comment]
@piotrbak This has been there in previous versions as well. But that hook isn't used in WP Rocket yet, so there aren't any issues with it.

**Comment by piotrbak** [comment]
@vmanthos Let's go with a separate issue for that one. Good job for spotting it! 🚀

**Review by vmanthos — APPROVED** [review]
Working as expected. :+1: 

**Note**

Related issue: #5825

**Pull request merged**
