### PR TITLE
Closes #2377 CPCSS for specific pages

### LINKED ISSUE #2377: CPCSS for specific pages (using metabox)
## Why are we doing this feature?

The feature proposal is currently to add page specific CPCSS to any post type that is public and has an editor interface (i.e. the WP Rocket options metabox will be available). It's very common for a lot of publishers to have custom page layouts. We have many examples on our WP Rocket website (example: <https://wp-rocket.me/features>). 

Having page specific CPCSS will benefit websites with such custom layouts. 

## User expectations and experience 

Users will be able to generate custom CPCSS for their pages in one click. 

## How will we do this feature?

- In the beginning, the page uses the default CPCSS. At this point, we need only one button that says, "Generate CPCSS For This Page".
- On clicking it, CPCSS is generated and saved with other CPCSS CSS files as post_type-id.css (example page-19.css)
- "Generate CPCSS" now renamed to "Regenerate CPCSS". Click it will regenerate the CPCSS. 
- Below it a small link says "Disable custom CPCSS". This will delete the custom generated CPCSS and fall back to the common CPCSS for the post type. 

UI being discussed here: <https://wp-media.slack.com/archives/CFSCRLVGB/p1580933950000100>

Technical overview

Flowchart for admin/front: <https://drive.google.com/file/d/1K5vPc0_JURHWiWX7KujZAo1OhJczZbpj/view?usp=sharing>

  
**Code**
- [x] [UI](https://github.com/wp-media/wp-rocket/issues/2443)
- [x] [AJAX](https://github.com/wp-media/wp-rocket/issues/2444)
- [x] [CPCSS generation](https://github.com/wp-media/wp-rocket/issues/2445)
- [x] [CPCSS deletion](https://github.com/wp-media/wp-rocket/issues/2446)
- [x] [Update common CPCSS deletion](https://github.com/wp-media/wp-rocket/issues/2447)
- [x] [Front](https://github.com/wp-media/wp-rocket/issues/2448)

- New REST API endpoint for the CPCSS, with a subscriber class to register it, handle the validation & callbacks
- New JS script on the edit.php page to add the AJAX handlers
- New subscriber for the CPCSS metabox
- Update CPCSS subscriber to use the specific CPCSS when it exists
- Update clean method from CPCSS class, to ignore pages CPCSS
- Add automated tests for all the above
  
**Estimate**

~~2 weeks~~ 1 week of work with Tonya (doing the JS) and Remy doing the plugin work.

## Risks

Risk should be minimal because: 

- We already generate CPCSS using the same tool. So we are not inviting additional risk. 

- This is an opt-in feature that the user initiates. They will know what is broken immediately and will be able to fix it. 

## Testing

- If Optimize CSS delivery is disabled, make sure that the buttons do not show up or is disabled. This is being discussed here: <https://wp-media.slack.com/archives/CFSCRLVGB/p1580934249001600>

- Generate the CPCSS for the page. Assuming the page layout is different from others, see if the generated CPCSS works and is different from the default one. 

- Change the page layout and regenerate the CPCSS. Make sure regeneration works. 

- Clear the CPCSS and make sure that it falls back to the default one. 

- If the user disabled "Optimize CSS delivery" via the meta box make sure no CPCSS is delivered on the front end. 

- UI Spec: https://github.com/wp-media/wp-rocket/issues/2443#issuecomment-617579591

- Test the UI in Block editor and Classic editor (https://github.com/wp-media/wp-rocket/issues/2443#issuecomment-619200123)

## Documentation and Translations

<What changes or additions will need to be made to documentation and translations?>

### PR DESCRIPTION
**Pull request by remyperona**
Closes #2377 

PR to close the epic.

👉 No code review is needed for this one as it's an epic and filled with PRs of user stories we've already reviewed and approved.

- [x] #2622 Refactor CPCSS code
- [x] QA

### CODE REVIEW

**Comment by webtrainingwheels** [comment]
There is a "more info" link in the metabox. Let's link it to our main doc about Optimize CSS Delivery, that's where the info will be updated:
- https://docs.wp-rocket.me/article/1266-optimize-css-delivery 
- https://fr.docs.wp-rocket.me/article/1268-optimiser-le-chargement-du-css

**Comment by Tabrisrp** [comment]
@wp-media/dev-qa This is ready for QA.

This is the feature branch with everything CPCSS for specific pages in it, including a refactor code that should change nothing on the outside, but we want to validate it all works as expected.

**Comment by hellofromtonya** [comment]
@arunbasillal @vmanthos @piotrbak This PR is 🔥 HOT 🔥 as it's blocking progress on several other PRs. Please move the QA for this one to the top of the list.

Our goal is get it merged tomorrow (Wednesday) to unblock CPCSS for mobile. Thanks!!

**Comment by arunbasillal** [comment]
QA: 

- No warning or errors recorded in `debug.log`.
- Notices in the meta box are displayed as per design.
- Page uses specific CPCSS when available.
- Deletion of CPCSS works as expected.

The `more info` link isn't linked to this: https://github.com/wp-media/wp-rocket/pull/2639#issuecomment-628910439 
^ @Tabrisrp please note. Is this expected at this point?

I noticed an issue on the mega site: 

- The message in the UI said that CPCSS was generated
- But in fact, the file was not generated. 
- Please see: https://youtu.be/eZVEEOSUlJQ
- You can try it here, this branch is installed here (unless someone changes it during the day): http://mega.wp-rocket.me/wp-admin/post.php?post=9217&action=edit

**Comment by engahmeds3ed** [comment]
@arunbasillal , Now issue is resolved related to file not generated but the message say that it's generated.
Waiting for your feedback.
Thanks

**Review by hellofromtonya — APPROVED** [review]

**Review by arunbasillal — APPROVED** [review]
QA: 

- Retested everything from before. Looking good 👍 
- Specific CPCSS is generated correctly and deleted correctly 👍 
- Link to doc is valid for both EN and FR 👍 

Everything looks good 🚀

**Review by hellofromtonya — APPROVED** [review]

**Comment by arunbasillal** [comment]
@hellofromtonya @Tabrisrp Should I redo the QA on this one again? I see few many commits after my review.

**Pull request merged**
