### PR TITLE
Fixes #6814 Prevent PHP warning undefined property type

### LINKED ISSUE #6814: LCP / ATF / Critical Images - PHP Warning Undefined Property in Controller.php
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
Some users are saying they see the following error in their logs:

`PHP Warning: Undefined property: stdClass::$type in /data/sites/web/baniwafelsbe/www/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php on line 498; PHP message: PHP Warning: Undefined property: stdClass::$type in /data/sites/web/baniwafelsbe/www/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php on line 498; `

**To Reproduce**
- We're still not sure yet
- May potentially be related to 'not found' fields in the `lcp` coloum of the `wp_wpr_above_the_fold` table:
https://imagizer.imageshack.com/a/img922/3025/lawUD6.png

**Expected behavior**
The error should not happen.

**Additional context**
[Ticket](https://secure.helpscout.net/conversation/2655008789/503185)
[Slack](https://wp-media.slack.com/archives/C08N8J6VC/p1721308501996289?thread_ts=1718960088.185539&cid=C08N8J6VC)

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

### PR DESCRIPTION
**Pull request by remyperona**
# Description

Fixes #6814

### User documentation

Prevent PHP warning `Undefined property: stdClass::$type`

### Technical documentation

Make sure each object item in the `sources` array has all the properties defined before saving in the database, by using `wp_parse_args()` to merge defaults values with the provided item values.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

# Checklists

## Feature validation

- [ ] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [ ] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [ ] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

### CODE REVIEW

**Comment by MathieuLamiot** [comment]
@Tabrisrp would it make sense to add a log in case the incoming source does not have a type, reporting the incoming object?

 Maybe using our logger. 

So that we can confirm on a customer website that the issue is coming from the JS part, or at least spot if it is happening again?

I am afraid we will just silence a remaining issue and never have a chance to go through it.

**Comment by MathieuLamiot** [comment]
Also, think8ng out loud: should we make the OCI row "failed" in case we used the fallback?
If a property is missing, maybe the front end optim won't be applied correctly, or at all. Hence, using the fail mechanism would allow to retry?

**Comment by remyperona** [comment]
Having a missing `type` for the preloaded `source` is not going to break the optimization, because it's only an optional, additional hint for the browser. The image itself can still be preloaded without it.

We could add a log to see when it's missing though.

**Comment by MathieuLamiot** [comment]
> because it's only an optional, additional hint for the browser.

Oh ok, got it. Thanks.

> We could add a log to see when it's missing though.

👍

**Comment by Mai-Saad** [comment]
Exploratory Notes: 
- e2e LCP is green
```
npm run test:lcp

> wp-rocket-e2e@1.0.0 test:lcp
> $npm_package_config_testCommand --tags @lcp

This Node.js version (v20.12.2) has not been tested with this version of Cucumber; it should work normally, but please raise an issue if you see anything unexpected.
Error deleting folder "./backstop_data/bitmaps_test": ENOENT: no such file or directory, lstat './backstop_data/bitmaps_test'
13/32 steps [=====================================================================                                                                                                    ] 1
20/32 steps [==========================================================================================================                                                               ] 0
0
3 scenarios (3 passed)
32 steps (32 passed)
19m14.858s (executing steps: 19m07.387s)

```
- If we visit a page with a picture that has no type, we will see the notice in WPR logs, however, no error in debug.log (same on the trunk for debug.log, no warning) https://new.rocketlabsqa.ovh/lcp_picture_error/
Screenshot from 2024-08-02 12-53-04
- If we manually delete the type of picture in DB then clear the cache and visit the page, we will see this error (shouldn't be a real case to happen that way at least)
`[02-Aug-2024 09:19:03 UTC] PHP Warning:  Undefined property: stdClass::$type in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Frontend/Controller.php on line 278`
- The exact error on the main issue is not reproducible on the test site while using a picture without a type

**Review by Miraeld — APPROVED** [review]

**Comment by MathieuLamiot** [comment]
@Tabrisrp There might be an issue with the fix? https://wp-media.slack.com/archives/C08N8J6VC/p1722637794605269?thread_ts=1718960088.185539&cid=C08N8J6VC

**Comment by jeawhanlee** [comment]
@MathieuLamiot Is there still something to be done on this PR?

**Comment by MathieuLamiot** [comment]
Based on the Slack thread, I would say no. You can confirm with @Tabrisrp

**Pull request merged**
