### PR TITLE
Integrate Beacon 2.0

### PR DESCRIPTION
**Pull request by Tabrisrp**
Integrate the new Beacon version into the plugin

### CODE REVIEW

**Comment by webtrainingwheels** [comment]
Is there anything we can do about this? 

WP_Rocket_‹_WordPress_Themes_—_WordPress

On my 13" MacBookPro, if I have either of the Bookmarks Bar or Downloads bar displayed (which normally they are), it hides the top of the Beacon.

**Comment by webtrainingwheels** [comment]
For comparison, with both bookmarks and downloads off: 
WP_Rocket_‹_WordPress_Themes_—_WordPress

still a bit overlapped, but at least legible.

**Comment by Screenfeed** [comment]
Put your screen vertically.

**Comment by Tabrisrp** [comment]
Unfortunately we can't control the dimensions of the box

**Pull request merged**
