### PR TITLE
Fixes #5801: PHP Deprecated notice

### LINKED ISSUE #5801: PHP Deprecated: notices with PHP 8.2.3
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.6.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
PHP Deprecated notice  (count 150+) exists in debug.log while site is using PHP 8.2.3
`[08-Mar-2023 14:51:05 UTC] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php on line 253`
`[08-Mar-2023 14:51:09 UTC] PHP Deprecated:  Creation of dynamic property WP_Rocket\Engine\Preload\Database\Rows\CacheRow::$id is deprecated in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/Database/Base.php on line 266
`
**To Reproduce**
1. Website using PHP 8.2.3
2. Install and activate WPR
3. check debug.log

**Expected behavior**
no deprecated notice in debug.log

**Additional context**
- This doesn't exist with PHP 8.1.14

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description
Updated BerlinDB Package.

Fixes #5801 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@jeawhanlee I'm still getting the following notices:

```PHP
PHP Deprecated:  Creation of dynamic property WP_Rocket\Engine\Preload\Database\Rows\CacheRow::$id is deprecated in /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/Database/Base.php on line 273
PHP Deprecated:  Creation of dynamic property WP_Rocket\Engine\Preload\Database\Rows\CacheRow::$url is deprecated in /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/Database/Base.php on line 273
PHP Deprecated:  Creation of dynamic property WP_Rocket\Engine\Preload\Database\Rows\CacheRow::$status is deprecated in /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/Database/Base.php on line 273
PHP Deprecated:  Creation of dynamic property WP_Rocket\Engine\Preload\Database\Rows\CacheRow::$modified is deprecated in /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/Database/Base.php on line 273
PHP Deprecated:  Creation of dynamic property WP_Rocket\Engine\Preload\Database\Rows\CacheRow::$last_accessed is deprecated in /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/Database/Base.php on line 273
PHP Deprecated:  Creation of dynamic property WP_Rocket\Engine\Preload\Database\Rows\CacheRow::$is_locked is deprecated in /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/Database/Base.php on line 273
```
To reproduce:
1. Use PHP `8.2.*`.
2. Clear and Preload cache.
3. Check the `debug.log`.

Can you please look into this? :pray:

**Comment by jeawhanlee** [comment]
I opened another [PR](https://github.com/berlindb/core/pull/158) at BerlinDB that corrects the previous [PR](https://github.com/berlindb/core/pull/155) there also.

**Comment by jeawhanlee** [comment]
Moving this back for CR as [PR](https://github.com/berlindb/core/pull/158) is now merged in BerlinDB.

**Review by remyperona — APPROVED** [review]

**Review by vmanthos — APPROVED** [review]
There aren't any deprecation errors related to WP Rocket after the latest commit. :+1:

**Pull request merged**
