### PR TITLE
Preserve chosen inline styles when removing CSS from HTML while using RUCSS

### LINKED ISSUE #4549: RUCSS - Extra theme JavaScript console error when Remove Unused CSS is active
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When:
1. The Extra theme (checked with version `4.13.0`) is used with the following options (https://i.vgy.me/Iyfwl7.jpg, https://i.vgy.me/dDr8b5.jpg)
2. Remove Unused CSS is active. 

the following JavaScript error appears in the console:
```
Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
```

This comes from the following script:
https://snippi.com/s/2tvjml4

which is trying to find:
```HTML
<style id="extra-style-inline-inline-css" type="text/css"></style>
```
 in the `<head>`. 

With Remove Unused CSS that is removed, and the error pops up.

**To Reproduce**

1. Install the Extra theme - the same could happen with Divi, although I haven't checked.
2. Make sure the options there are these: https://i.vgy.me/Iyfwl7.jpg, https://i.vgy.me/dDr8b5.jpg
3. Activate Remove Unused CSS.
4. Make sure it's removing all CSS.
5. Check the console for the error.

**Expected behavior**

No errors should appear in the console.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1702421034/308998?folderId=2135277
Code that produces the inline script: https://snippi.com/s/1mkefvx

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### LINKED ISSUE #4554: Remove Unused CSS should preserve empty stylesheets acting as a place holder
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Some themes and plugin will set an empty stylesheet with an ID to act as a placeholder to a style injected later. 

Example: 

```
<style type="text/css" id="gsf-custom-css"></style>
```
```
<script>jQuery("style#gsf-custom-css").append(".some-style{}");</script>
```

After processing RUCSS, the empty `<style>` is removed.  And the style inside `.append()` is not processed. Leaving any elements relying on CSS inside the `.append()` missing their style.

Safelisting selectors from inside `.append()` doesn't fix the issue.

**To Reproduce**
1. Add the above and target an element on the page using `.append()`
2. . See the missing style

**Expected behavior**
Ideally, we should check if `.append()` or the vanilla JS equivalent is trying to append style on an existing inline stylesheet and preserve it after RUCSS. 

An alternative is just to preserve empty inline stylesheets. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1714492173/312129/

Behavior noticed on the [Auteur](https://auteur.g5plus.net/) theme. But likely to be the same on all [G5Plus themes](https://g5plus.net/projects/) and other themes/plugins as well.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### LINKED ISSUE #4598: RUCSS should preserve some <style> in some cases
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Some themes and plugin will try to manipulate existing `<style>`. 

When RUCSS is used, the target `<style>` element will be deleted. Leaving a console error in some cases.

Example: 

```
<html>
<body>
<!--StartFragment-->

<style id='divi-style-parent-inline-inline-css' type='text/css'>
/*!
Theme Name: Divi
Theme URI: http://www.elegantthemes.com/gallery/divi/
Version: 4.14.3
Description: Smart. Flexible. Beautiful. Divi is the most powerful theme in our collection.
Author: Elegant Themes
Author URI: http://www.elegantthemes.com
License: GNU General Public License v2
License URI: http://www.gnu.org/licenses/gpl-2.0.html
*/
</style>
```
```
<script type="application/javascript">
(function() {
    var file     = ["https:\/\/www.domain.com\/ka_seite\/et-cache\/222441\/et-divi-dynamic-tb-222629-222441-late.css"];
    var handle   = document.getElementById('divi-style-parent-inline-inline-css');
    var location = handle.parentNode;

    if (0===document.querySelectorAll('link[href="' + file + '"]').length) {
        var link  = document.createElement('link');
        link.rel  = 'stylesheet';
        link.id   = 'et-dynamic-late-css';
        link.href = file;

        location.insertBefore(link, handle.nextSibling);
    }
})();
</script>
```

After processing RUCSS, the `<style>` is removed.  And the style inside `.insertBefore()` is not processed. 

In this case, it's resulting in a console error: 

```
(index):1183 Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
    at (index):1183
    at (index):1193
(anonymous) @ (index):1183
(anonymous) @ (index):1193
```

Safelisting selectors from inside `.insertBefore()` doesn't fix the issue.

**To Reproduce**
1. Add the above and target an element on the page using `.insertBefore()`
2. . If the script doesn't have a fallback in cache the targeted element doesn't exist, it will result in a console error.

**Expected behavior**
Ideally, we should check if `.insertBefore()` and preserve a placeholder with the selectors after Used CSS is injected. 

A broader approach would be to simply preserve placeholders for all inline `<style>` after getting processed by RUCSS. It should also work for https://github.com/wp-media/wp-rocket/issues/4554

**Screenshots**
N/A

**Additional context**
Related to https://github.com/wp-media/wp-rocket/issues/4554 but since the `<style>` wasn't empty, I added it as a separate issue.

Ticket - https://secure.helpscout.net/conversation/1727751196/314385

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
## Description

This PR aims to add a way to preserve some inline styles when removing CSS from HTML while remove unused CSS is active.

This can avoid issues with some themes that are using either:
- JS-based injection of content based on an ID attribute of a style tag
- CSS with dynamic values changing everytime a page is loaded

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## How Has This Been Tested?

- [x] New fixture to test this case

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by iCaspar — APPROVED** [review]

**Comment by iCaspar** [comment]
Looks like the tests that are failing here are to do with image dimensions, not with the new testcase introduced here.

**Comment by piotrbak** [comment]
@Tabrisrp We need to add there the following ones too:
`<style id='woodmart-inline-css-inline-css' type='text/css'>` 
`<style data-type="woodmart_shortcodes-custom-css">`

**Comment by piotrbak** [comment]
@Tabrisrp Could you merge new RUCSS approach into this PR? 🙏

**Comment by piotrbak** [comment]
@Tabrisrp Looks like Used CSS is not injected to the source when the specified excluded CSS is present in the source:
https://rocketlabsqa.ovh/rucss-preserve/

The CSS content is correct in the DB but not added to the source.

**Comment by remyperona** [comment]
🤔 there is nothing in the code change that can prevent adding the used CSS to the source

**Comment by piotrbak** [comment]
@Tabrisrp It was my mistake, no `<title>` tag in the template. We're good here, working perfectly 🙏

**Pull request merged**
