### PR TITLE
Closes #7075: Plugin - Accommodate new oneclick exclusions UI for delayjs

### LINKED ISSUE #7075: Plugin - Accommodate new oneclick exclusions UI for delayjs
**Is your feature request related to a problem? Please describe.**
Accommodate the new structure from the backend exclusion lists to fit the new UI.
Parent [issue](https://github.com/wp-media/wp-rocket/issues/7041)

**Describe the solution you'd like**
Update the UI to fit new changes.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by jeawhanlee**
# Description

Fixes #7075 
*Explain how this code impacts users.*

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

## Detailed scenario

N/A

### Documentation

This code adds a parent category to the scripts and adapts compatibility with the new delayjs backend exclusion list structure. it also adds some enhancement to the UI/UX.

### New dependencies

N/A

### Risks

N/A

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I did not introduce unnecessary complexity.

# Additional Checks
- [x] In the case of complex code, I wrote comments to explain it.
- [x] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

**Comment by jeawhanlee** [comment]
### Old UI
Screenshot 2024-11-05 at 14 31 06

### New UI Changes
Screenshot 2024-11-05 at 14 28 14

**Comment by jeawhanlee** [comment]
Automated testing passes with the new data structure, awaiting backend implementation to be sure it truly passes for manual testing.

**Comment by jeawhanlee** [comment]
Icons implementation pending.
CC @piotrbak

**Comment by piotrbak** [comment]
@jeawhanlee I don't have access to this Figma. Checking with @DahmaniAdame if he has

**Comment by DahmaniAdame** [comment]
> @jeawhanlee I don't have access to this Figma. Checking with @DahmaniAdame if he has

@piotrbak I don't. Ben was the only one with access to it.

**Review by Miraeld — APPROVED** [review]

**Comment by jeawhanlee** [comment]
@wp-media/qa-team For testing you can replace this [line](https://github.com/wp-media/wp-rocket/blob/b2f0b8f870002148959cb3d28a62671489ac7228/inc/Engine/Optimization/DynamicLists/AbstractAPIClient.php#L13) with the last endpoint in the comment [here](https://github.com/wp-media/rucss-backend/issues/149#issuecomment-2475466364) and update lists from tools section in WPR dashboard.

**Review by Miraeld — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@jeawhanlee Thanks for the PR.
[WIP]Here are exploratory notes based on https://www.notion.so/wpmedia/New-UI-for-Delay-JS-one-click-exclusions-1b2557aa5c904718ac40274c85ecdbb1
1- The main label of a section shall be bold
2- Do we need select all for theme or if only single item is there at BE @wp-media/product ?
3- When click select all and save, items in list are selected but select all gets unchecked, it should remain selected in this case
Screenshot from 2024-12-02 15-43-26

**Review by wordpressfan — CHANGES_REQUESTED** [review]
@jeawhanlee I believe we need to change this line:
https://github.com/wp-media/wp-rocket/blob/06381b8860eb46e570911b2812652f54a676dd6d/inc/Engine/Optimization/DynamicLists/DelayJSLists/APIClient.php#L16

to be 
```
return 'v2/delay-js-exclusions/list';
```

and for testing, we will just need to change the constant `WP_ROCKET_EXCLUSIONS_API_URL` to be `https://staging-sass-backend.wp-rocket.me/api/` without changing the code itself.

**Review by wordpressfan — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@jeawhanlee Thanks for the update , remain updating the 3rd party icons
Screenshot from 2024-12-06 12-19-13
Note: 
- after update from 3.17.3.1 , we need to manually update dynamic lists to see scripts, this will probably be handled here https://github.com/wp-media/wp-rocket/issues/7113 (we may need to update the snippet which creates zip for testing)
- When rollback from PR while some items are checked , we will have this warning and analytics will be empty @jeawhanlee can you please check 
`[06-Dec-2024 10:34:22 UTC] PHP Warning:  Attempt to read property "title" on array in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/Admin/SiteList.php on line 215`
Screenshot from 2024-12-06 12-39-16

**Comment by DahmaniAdame** [comment]
Icons can be found on this thread - https://wp-media.slack.com/archives/C06CQPWEJSK/p1733497507056019?thread_ts=1733395114.523529&cid=C06CQPWEJSK

**Review by wordpressfan — CHANGES_REQUESTED** [review]
Icons image sizes are not exactly the same which is causing not good UI:

image

Can we make sure that the size is 16X16 so it has no UI problems?
also I can see that not all of them are images but some of them are dashicons so make sure that their width and height are exactly the same too and if it's not working properly with dashicons convert all of them to be images.

what do u think?

**Review by wordpressfan — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@jeawhanlee Thanks for the update, rollback is good now. But Ads and other icons do not match the ones here https://github.com/wp-media/wp-rocket/pull/7090#issuecomment-2523449533
Screenshot from 2024-12-13 10-27-10

**Comment by jeawhanlee** [comment]
@Mai-Saad This is because they don't match the redesign on [notion](https://www.notion.so/wpmedia/New-UI-for-Delay-JS-one-click-exclusions-1b2557aa5c904718ac40274c85ecdbb1?pvs=4#5c75817a1fad4549ab4c6e4fcb88899d)

**Comment by Mai-Saad** [comment]
Thanks @jeawhanlee , Icons are matching the slack thread now
Screenshot from 2024-12-13 15-03-05

**Pull request merged**
