### PR TITLE
Closes 5510: Thirdparty class for the events calendar

### LINKED ISSUE #5510: Cache folder grows large due to URLs coming from The Events Calendar empty dates
**Before submitting an issue please check that you’ve completed the following steps:**
**Yes** - Made sure you’re on the latest version
**Yes** - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
[The Events Calendar](https://theeventscalendar.com/) plugin allows browsing empty dates as URLs, for example:

```
https://example.com/calendar/2021-05-31
https://example.com/calendar/2019-03
https://example.com/calendar/2019-08-10
https://example.com/calendar/2016-12-10
etc
```

These URLs are added to the `wpr_rocket_cache` table.

If a bot visits these URLs, for example, we might end up with thousands of empty dates to preload, this will overload the database and the path where the calendar is published will start growing (`/calendar/` in this case).
 
The cache folder can grow a lot mostly with not really useful cached URLs. 
Additionally, this will be increasing the overall processing  time, preload, used CSS generation, etc.

Excluding  `/calendar/20(.*)` fixed the issue in a particular case.

**To Reproduce**
1. install The Events Calendar
2. Enable Preload
3. Start browsing random empty calendar dates
4. See the cache folder and the **wpr_rocket_cache** table grows

**Expected behavior**
We should exclude the empty calendar dates from being preloaded.

**Screenshots**
2NdJoli
https://i.imgur.com/2NdJoli.png

**Additional context**
**Ticket**
https://secure.helpscout.net/conversation/2036275504/374580?folderId=2683093

**Slack thread:**
https://wp-media.slack.com/archives/C43T1AYMQ/p1666015442151769

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Fix a problem where the db was flooded with calendar rows.
For that we excluded urls from the calendar from the preload.

Fixes #5510 

## Type of change

Please delete options that are not relevant.
- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

Yes, I added code to work with an option value instead of a constant.

## How Has This Been Tested?
- [ ] Automated Tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by piotrbak** [comment]
@CrochetFeve0251 @Tabrisrp We need to exclude the list of events, not the single posts itselves. I think that it should be `eventsSlug`, not `singleEventSlug`. What we want to exclude is that kind of URL: https://rocketlabsqa.ovh/events/2032-08-01/

image

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
The solution this PR brings is working as expected but may need to be extended.

During exploratory testing, I found that if an event belongs to a category, e.g. "conferences", the URL for the category is:
https://vasilis.rocketlabsqa.ovh/events/category/conferences

If you visit that, you'll be able to access events like the following:
https://vasilis.rocketlabsqa.ovh/events/category/conferences/day/2022-11-17/

**Screencast:** https://youtu.be/zKafbPKHonU

While https://vasilis.rocketlabsqa.ovh/events/20(.*) are not preloaded, the previous URLs are and we have the same issue that Alfonso mentioned in https://github.com/wp-media/wp-rocket/issues/5510.

@piotrbak Is this something we should address in the current PR or should we monitor and act on it if the occasion arises?

**Comment by piotrbak** [comment]
@vmanthos Let's leave it like it's for now. I wonder if it has anything to do with the way how WordPress is doing its things there:
https://vasilis.rocketlabsqa.ovh/about-us/page/1234567890

**Comment by vmanthos** [comment]
>  I wonder if it has anything to do with the way how WordPress is doing its things there

Good point. It could be.

**Review by vmanthos — APPROVED** [review]
Working as expected. 👍

**Pull request merged**
