### PR TITLE
Fixes #4875 Clean Varnish cache when used CSS is completed or purged

### LINKED ISSUE #4875: Varnish's cache isn't cleared when clearing page-specific used CSS
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.11.0.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When clearing the used CSS for a specific URL, the cache of the URL is properly cleared:
https://github.com/wp-media/wp-rocket/blob/37eaa0016d79c21fbdc3bfc32102afd5eb750fdd/inc/Engine/Cache/PurgeActionsSubscriber.php#L54

However, if Varnish is used, e.g. on Cloudways, the cache of the URL won't be cleared at that time, and:
- the page won't be preloaded - the `wp_remote_get()` request will never reach WordPress
- Remove Unused CSS won't be created/applied there, until the specific URL's cache is cleared using the admin bar menu item, or the whole cache is cleared

**To Reproduce**

1. In an environment where Varnish is used, clear page-specific used CSS using the admin bar menu item.
2. Check the `age` header of the Varnish. That will be larger than `0`.

**Expected behavior**

 Varnish's cache should be cleared when using the "Clear used CSS of this URL" button.

**Additional context**

We should hook `clean_file` to `rocket_rucss_after_clearing_usedcss` here:
https://github.com/wp-media/wp-rocket/blob/37eaa0016d79c21fbdc3bfc32102afd5eb750fdd/inc/Addon/Varnish/Subscriber.php#L41-L47

**Ticket:** https://secure.helpscout.net/conversation/1828951060/334087/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description
Fix a problem with cache from Varnish that wasn't cleaned.
For that we hooked `clean_file` method to `rocket_rucss_after_clearing_usedcss` hhook.

Fixes #4875

## Type of change

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [ ] Automated testing

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by remyperona** [comment]
@CrochetFeve0251 Can you also add the clearing on `rocket_rucss_complete_job_status`

**Comment by CrochetFeve0251** [comment]
@Tabrisrp I added the hook

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@piotrbak please find exploratory test notes/Qs below: (using the test site http://wprocket-test.odns.fr/)
1- Switching theme while the separate mobile cache is enabled, only recreating the desktop version in the used CSS table. although, the new labs test site, is generating both desktop and mobile versions. is this something that we need to handle here or on another ticket?
2- When we change the safelist, the Cache of any page other than the home page is cleared (age header set to 0) while it is not cleared for the home page. Do we need a Separate GH for this?

**Comment by piotrbak** [comment]
@Mai-Saad 

1. Was it happening when the server-side cache was enabled (Varnish or similar)?
2. Is the `age` on homepage reduced or it's increased after changing the safelist?

**Comment by Mai-Saad** [comment]
> @Mai-Saad
> 
> 1. Was it happening when the server-side cache was enabled (Varnish or similar)?
> 2. Is the `age` on homepage reduced or it's increased after changing the safelist?

@piotrbak 
1. The problem is happening here http://wprocket-test.odns.fr/ and Yes Varnish is used
2. Age is reduced but does not reach 0 even after UCSS is completed in this case

**Comment by piotrbak** [comment]
@Mai-Saad I think we are fine then. 

For the first one:
I believe that this Varnish setup doesn't have the `Separate Cache for Mobiles` feature and serves the same set of cache for both options. Here's the scenario:
1. We're switching the theme
2. Request is being done on the desktop, Varnish saves the cache
3. Request is being done on the mobile, Varnish serves the same cache

For the second one:
If the `age` header is decreased, it means that it was cleared in the meantime. We could confirm that by changing the safelist that would make a change in the Used CSS of the homepage.

**Review by Mai-Saad — APPROVED** [review]
Working as expected then.
Note: Dreampress tests were run on o2switch env and failed tests due to https://github.com/wp-media/wp-rocket/issues/2264
[testrail-report-389.pdf](https://github.com/wp-media/wp-rocket/files/8804494/testrail-report-389.pdf)

**Pull request merged**
