### PR TITLE
Fixes #2504 Prevent deprecated notice on WooCommerce terms list pages

### LINKED ISSUE #2504: Deprecated: tag_row_actions after update to WooCommerce 4.0
Screenshot_2
This occurs when Wp-rocket 3.5.2 is active
Deprecated: tag_row_actions has been deprecated since version 3.0.0. Use {$ taxonomy} _row_actions instead.

**Describe the bug**
A message displayed from a function listed as "deprecated"

**To Reproduce**
1. With WooCommerce installed, we go to products
2. We go to categories
3. Just below the category name you see the message

### PR DESCRIPTION
**Pull request by Tabrisrp**
Fixes #2504 

- [x] Deprecate `rocket_tag_row_actions`
- [x] Create a `Cache\AdminSubscriber`
- [x] Add methods to add the purge term link for each public taxonomy
- [x] Write tests
- [x] QA

### CODE REVIEW

**Comment by Tabrisrp** [comment]
@hellofromtonya I'd like to have your eyes on the integration tests here. Somehow it looks like `admin_init` doesn't execute, even though the tests are in `AdminOnly`.

**Comment by hellofromtonya** [comment]
>@hellofromtonya I'd like to have your eyes on the integration tests here. Somehow it looks like admin_init doesn't execute, even though the tests are in AdminOnly.

Will do. Added to my TODO list.

**Comment by hellofromtonya** [comment]
>@hellofromtonya I'd like to have your eyes on the integration tests here. Somehow it looks like admin_init doesn't execute, even though the tests are in AdminOnly.

@Tabrisrp Updated the integration tests by adding an `AdminTestCase` for handling the various tasks. Check it out.

**Comment by Tabrisrp** [comment]
@wp-media/dev-qa ready for QA

**Pull request merged**
