### PR TITLE
Add preload links for fonts found in the used CSS

### PR DESCRIPTION
**Pull request by remyperona**
## Description

In this PR, we use the used CSS content to check if there is font-face declaration in it, and add preload links for each font.

Considering the case of a font having multiple font type declarations, only the first one is preloaded.

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

- [x] Added a new case fixture to existing tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by mostafa-hisham — APPROVED** [review]

**Comment by piotrbak** [comment]
@Tabrisrp Can we exclude `EOT` format from being preloaded?

**Comment by remyperona** [comment]
@piotrbak I pushed a change to skip `.eot` fonts

**Comment by piotrbak** [comment]
@Tabrisrp There are 2 things more:
1. Can we make sure that if `EOT` is there, we'll preload the next font format (if exists)? Right now, if `EOT` is there, we'll bypass thsi font completely.
2. We'll also need a filter to disable this optimization

🙏

**Comment by GeekPress** [comment]
> We'll also need a filter to disable this optimization

Must be a decision, not option here, isn't it?

For which reason should we allow to bypass our choice?

**Comment by piotrbak** [comment]
@Tabrisrp If there are two the same `@font-face` definitions, we'll add 2 preload links related to the same font.

It doesn't seem to cause side effects, but maybe it's easily fixable?

**Comment by remyperona** [comment]
It is, I updated the code to remove duplicate entries in the fonts array

**Review by piotrbak — APPROVED** [review]

**Pull request merged**
