### PR TITLE
Closes #6474: Update maintenance LCP/ATF

### LINKED ISSUE #6474: Update maintenance for LCP/ATF data storage
#### Engine\Common\JobManager\ServiceProvider
- remove `atf_factory` from the `$factories` array

#### Engine\Media\AboveTheFold\Cron\Controller
- Add a method `schedule_atf_cleanup()` to schedule the cleanup (daily), with the hook name `rocket_atf_cleanup`
- Add a method `atf_cleanup()` to perform the cleanup, removing the rows with failed status or not accessed since (1 month by default, filterable)
- Add a method `unschedule_atf_cleanup()` to unschedule the cleanup

#### Engine\Media\AboveTheFold\Cron\Subscriber
- Add callback `atf_cleanup()` for `rocket_atf_cleanup`
- Add callback `schedule_atf_cleanup()` for `init`
- Add callback `unschedule_atf_cleanup()` for `rocket_deactivation`

#### Engine\Media\AboveTheFold\Database\Queries\AboveTheFold
- Add a method to delete failed and not accessed rows

#### Engine\Media\AboveTheFold\ServiceProvider
- Add the cron controller and subscriber to the instantiation

### Estimate the effort ✅
Effort [M]

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #6474 

### User documentation

This allow to delete old OR failed results from LCP / ATF. 

The `rocket_atf_cleanup_interval` filter is a new feature introduced in this PR. It allows developers to modify the interval at which the Above The Fold (ATF) cleanup process considers a row to be old and therefore eligible for deletion. By default, this interval is set to 1 month. If a row's `last_accessed` date is more than 1 month ago, it will be deleted during the cleanup process.  However, by using this filter, developers can change this interval. For example, if the interval is set to 2 months, then the cleanup process will delete rows where the last_accessed date is more than 2 months ago.  Here's an example of how to use this filter:
``` php
// Change the ATF cleanup interval to 2 months.
add_filter( 'rocket_atf_cleanup_interval', function() {
    return 2;
});
```

### Technical documentation

- The `schedule_atf_cleanup` method is used to schedule the 'above the fold' cleanup process to run daily. It checks if the cleanup process is already scheduled using the` wp_next_scheduled` function. If it's not scheduled, it schedules the event using the `wp_schedule_event` function.  
- The `atf_cleanup` method is used to execute the 'above the fold' cleanup process. It calls the `delete_old_rows` method of the ATFTable class to delete the rows with `failed` status or not accessed since the interval.  
- The `unschedule_atf_cleanup` method is used to unschedule the `above the fold` cleanup process. It gets the timestamp of the next scheduled cleanup using the `wp_next_scheduled` function. If a timestamp is found, it unschedules the event using the `wp_unschedule_event` function

## Type of change
*Delete options that are not relevant.*
- [x] Enhancement (non-breaking change which improves an existing functionality).

## Risks

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [x] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [x] I listed the introduced external dependencies explicitely on the PR.
- [x] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [x] I handled errors when needed.
- [x] I wrote user-facing messages that are understandable and provide actionable feedbacks.

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
Related test plan https://wpmediaqa.testrail.io/index.php?/runs/view/845&group_by=cases:section_id&group_id=5031&group_order=asc

For exploratory :
- never cache/always purge with the feature (with never cache, URL won't have lcp nor added to atf on visit. While for always purge, edit URL x will clear only the URL in always Purge from cache but not atf table as in RUCSS) :heavy_check_mark:

**Comment by Miraeld** [comment]
Here is the related test results: 
[testrail-report-597.pdf](https://github.com/wp-media/wp-rocket/files/15085004/testrail-report-597.pdf)

**Comment by MathieuLamiot** [comment]
Step 4 of https://wpmediaqa.testrail.io/index.php?/tests/view/41770&group_by=cases:section_id&group_id=5031&group_order=asc worked for me 🤔 
For step 3, I don't have the "Clear for this URL" but only "Clear Used CSS" which seem to clear all LCP/ATF.

Probably @wp-media/qa-team can manually run those two steps to confirm for us 😬

**Comment by MathieuLamiot** [comment]
After discussion with @piotrbak and checking, the test plan is OK for LCP/ATF and failing parts are also failing on trunk:
- clear used CSS for this URL is not available on the editor: https://github.com/wp-media/wp-rocket/issues/6594
- When using the clear used CSS for this URL in the front-end, the row is deleted instead of being put back to "to submit".

**Pull request merged**
