### PR TITLE
Closes 6037: Clear apo on deactivate

### LINKED ISSUE #6037: Clear APO cache upon WP Rocket deactivation
**Is your feature request related to a problem? Please describe.**
Deactivating WP Rocket is a fairly common practice among customers that find issues with our optimizations. 
This "quick fix" doesn't have an automatic effect after 3.14 because WP Rocket doesn't clear its own cache, thus, APO cache is not cleared either, keeping the broken version of the site live until APO cache is manually cleared.

**Describe the solution you'd like**
Clear APO cache when deactivating WP Rocket, to make sure the site is synchronized with WP Rocket deactivated status.
May be useful to clear APO cache after activating WP Rocket too.
This can be "risky" in high-traffic sites where the site relies on having one set of cache files at least.

**Describe alternatives you've considered**
We can show a notice to tell customer to clear their APO cache.

**Additional context**
Slack thread here: https://wp-media.slack.com/archives/C08N8J6VC/p1689010919320849

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Add a call to clear the APO on the plugin deactivation.

Fixes #6037

## Type of change

*Please delete options that are not relevant.*

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

No.

# Checklists

## Generic development checklist

- [ ] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@piotrbak When deactivating both WP Rocket & Cloudflare at the same time we are not clearing APO's cache.
What do you think?

If this is fine then the PR is good to go.

**Comment by piotrbak** [comment]
@vmanthos you mean using bulk deactivation?

**Comment by vmanthos** [comment]
Exactly!

**Comment by piotrbak** [comment]
@vmanthos I think we're good here, that's acceptable edge case.

**Review by vmanthos — APPROVED** [review]
Thank you @piotrbak. :pray: 

We are good to go here! :+1:

**Pull request merged**
