### PR TITLE
Refactor kinsta.php to not rely on CDN class

### LINKED ISSUE #4717: Update Kinsta Compatibility
Kinsta no longer use KeyCDN and they have updated their MU Plugin to remove the `\Kinsta\CDN_Enabler` class. 
That is causing the following notice to always show for users due to the logic in this file https://github.com/wp-media/wp-rocket/blob/develop/inc/3rd-party/hosting/kinsta.php :

> **Your installation seems to be missing core Kinsta files managing Cache clearing and CDN, which will prevent your Kinsta installation and WP Rocket from working correctly. Please get in touch with Kinsta support through your MyKinsta account to resolve this issue.**

This could also causes WP Rocket to no longer clear the Kinsta cache.

**Additional context**
HS Ticket from Kinsta support: https://secure.helpscout.net/conversation/1781767741/324931/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by alexstine**
## Description

Please include a summary of the change and which issue is fixed/closed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #4717 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

Please describe in this section if there is any change to the solution, and why.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by remyperona** [comment]
How does the Kinsta CDN URL works now? With this change, we are not automatically adding it in our config anymore, so it's not ideal.

**Comment by alexstine** [comment]
@Tabrisrp Kinsta now uses Cloudflare and everything works via proxy. There is no need for CDN URL rewriting or anything like that anymore so should be no need to store the URL.

Thanks.

**Comment by remyperona** [comment]
@alexstine Thank you, what about the caching part of the MU plugin, is this still being used? We are doing call to `kinsta-clear-cache` endpoint to clear the cache of specific URLs, is it still valid?

**Comment by alexstine** [comment]
@Tabrisrp Yes, it's still valid. I left test site credentials in the linked Issue if you want to give it a test.

**Comment by remyperona** [comment]
ok great, one thing I would suggest for this PR is to update the notice message to also remove the part about the CDN then, and that should be good to go.

**Comment by alexstine** [comment]
@Tabrisrp Done.

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@alexstine Can you please provide us with FTP access? Thank you

**Comment by alexstine** [comment]
@Mai-Saad That really wouldn't be possible at this point. Do you need me to check error logs?

If it's really needed, happy to send via email.

Thanks.

**Comment by Mai-Saad** [comment]
> @Mai-Saad That really wouldn't be possible at this point. Do you need me to check error logs?

@alexstine Thanks for the reply. Can you please remove the last test line in functions.php of the active theme?

**Comment by alexstine** [comment]
@Mai-Saad Fixed.

**Comment by Mai-Saad** [comment]
Can see the main problem fixed but with the following notes:
1- If we hard refresh the page multiple times i.e 3 before we clear cache from admin bar => we will need to hard refresh n times so Kinsta Cache be Miss ( same case if we clear cache from Kinsta itself, while if we didn't refresh the page multiple times then the clear cache will reflect with the 1st refresh of the page)
2- Always Purge URL is not working probably i.e if we added `/test/ `or `/test `in Always Purge URL, cache /test page then we edited any post, /test will still be Hit after refresh => /test shall be Miss (as per discussion with Piotr, this is not related to PR and will need separate GH issue, couldn't check trunk yet as the folder is R access) 
[testrail-report-357.pdf](https://github.com/wp-media/wp-rocket/files/8074530/testrail-report-357.pdf)

**Comment by Mai-Saad** [comment]
@alexstine Can you please allow the delete/upload of the WPR plugin from the dashboard? (we will need this for regression test after merging the PR to ensure that everything else is working fine)

**Comment by alexstine** [comment]
@Mai-Saad Fixed, plugin can now be deleted.

**Pull request merged**
