### PR TITLE
Closes #5198 Add RUCSS warning modal when rollback

### LINKED ISSUE #5198: RUCSS Deactivation  for Non Expired Users Rollingback
The RUCSS feature available in versions prior to 3.11 has been shut down in May 2022. 
When non-expired users are rolling back to a previous version, we need to inform them that the RUCSS feature won’t be available.

[Details are available here](https://docs.google.com/document/d/1jlyfrU4hYqhFxT_Ol9f-sNJp8h8_ZRo7R4o_5IOjjV8/edit?usp=sharing)

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Add a modal to warn about rollback when remove unused CSS is active since the previous version is not available anymore

The patch versions containing the updated RUCSS notices:
- https://github.com/wp-media/wp-rocket/tree/v3.9.5.1
- https://github.com/wp-media/wp-rocket/tree/v3.10.10.1

Fixes #5198

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## How Has This Been Tested?

- [x] Manual tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jeawhanlee — APPROVED** [review]

**Comment by vmanthos** [comment]
@Tabrisrp Please find my notes about the PR:

1. The modal is displayed but its style:


is different compared to the one in the [details doc](https://docs.google.com/document/d/1jlyfrU4hYqhFxT_Ol9f-sNJp8h8_ZRo7R4o_5IOjjV8/edit?usp=sharing):



2. In `3.10.10.1`, clicking on the `x` close button doesn't close the banner. If it's not meant to be dismissed, the `x` button should not be displayed.

3. In `3.9.5.1`, clicking on the `x` close button dismisses the dashboard "Congratulations" banner but not the actual RUCSS notice: https://youtu.be/UBfWqOqk5ag

Refreshing the page brings the "Congratulations" banner back.

4. For expired users on `3.9.5.1` we display the banner in WP Rocket's dashboard explaining that users must renew their license:


but only the following is displayed in the file optimization tab:


There isn't any info about the fact that they need to renew their license.

This is how the same is displayed in `3.10.10.1`:


 @Agathemed is this the way you want this displayed?

Lastly, because of #3077 it's not really possible to roll back to these versions. A customer seeing that modal will get a version, e.g. `3.11.4`, where Remove Unused CSS is actually enabled and this can be confusing.

@wp-media/productrocket maybe #3077 should be addressed with priority?

**Comment by remyperona** [comment]
@vmanthos For point 1. can you try with the browser cache refreshed/disabled?

**Comment by vmanthos** [comment]
@Tabrisrp Thank you for the suggestion.

It was indeed an issue coming from the browser caching the previous version of the CSS files. Now the modal is displayed as expected:

**Comment by vmanthos** [comment]
@Tabrisrp Agathe confirmed that for expired users we should display the [same banner](https://camo.githubusercontent.com/909726b7ef882ef210d2031301ccd6fea2aedb61181e8f49c11c18b707f172ee/68747470733a2f2f692e7667792e6d652f523530625a412e6a7067) in the file optimization tab both on `3.9.5.1` and `3.10.10.1`

Will you take care of it in the current PR or do you want me to create a separate GitHub issue?

PS: It's number 4 on the list in [my comment](https://github.com/wp-media/wp-rocket/pull/5225#issuecomment-1180257326).

**Comment by remyperona** [comment]
I pushed a commit to add the warning message when trying to enable the option as an expired user

**Review by vmanthos — COMMENTED** [review]
@Tabrisrp I can see the banner for expired `3.9.5.1` users but the old message is displayed as well. Also, it's not possible to dismiss the banner unless the page is refreshed:


Can this be changed to work as it does on `3.10.10.1`?


Lastly, depending on the screen's resolution, on mobile devices, the tools tab is larger than the viewport, and so is the modal:


Can you please look into these topics? 🙏

**Comment by remyperona** [comment]
I updated the CSS to avoid the display issue and better display the modal on small screens too.

For the `3.9.5.1` version:
> the old message is displayed as well.

Shouldn't it be displayed still to communicate that it's not available?

> Also, it's not possible to dismiss the banner unless the page is refreshed

Yes this warning has never been dismissible.

> Can this be changed to work as it does on 3.10.10.1?

It's not the same type of field, so we can't.

**Comment by vmanthos** [comment]
> I updated the CSS to avoid the display issue and better display the modal on small screens too.

🙏

This is working as expected now:


> Shouldn't it be displayed still to communicate that it's not available?

Although GitHub showed the .gif I added when I previewed my reply I'm not seeing it anymore. ¯\_(ツ)_/¯

Here is a screenshot of what this looks like for `expired` users in `3.9.5.1`
 

Both the banner and the message are displayed. We should hide the message for expired licenses and instead display the banner.

**Comment by remyperona** [comment]
@vmanthos This should be updated now

**Review by vmanthos — APPROVED** [review]
This is working as expected! 👍

**Pull request merged**
