### PR TITLE
AIOSEO V4 Compatibility fixes

### PR DESCRIPTION
**Pull request by benjaminprojas**
These changes keep backwards compatibility with AIOSEO V3 as well.

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Tabrisrp** [comment]
@benjaminprojas Thank you for the PR!

We're going to have it go through our QA process, and it will likely be integrated in the next minor version after 3.8.

**Comment by benjaminprojas** [comment]
> @benjaminprojas Thank you for the PR!
> 
> We're going to have it go through our QA process, and it will likely be integrated in the next minor version after 3.8.

Sounds good, thanks!

**Comment by iCaspar** [comment]
Ben! Great to see you here! Thanks for the contribution!

**Comment by benjaminprojas** [comment]
> Ben! Great to see you here! Thanks for the contribution!

Caspar! Long time no talk. Hope all is well and great to see you too! 😄

**Comment by piotrbak** [comment]
@Tabrisrp @benjaminprojas I did the QA for 3.7.1 and 4.0.9 versions of AIOSEO.

**V3**
- We're not showing the UI to enable our compatibility 👎
- It's happening also for the previous version of the code (before this branch), tested on two separate environments ❗ 

**V4**
- We're showing the UI to enable the compatibility 👍 
- The sitemaps are not added to the preload list 👎

The above problem is related to the fact that an empty array is returned here:
https://github.com/wp-media/wp-rocket/blob/95e5797c9590b6c5be73bb0aef6108faa6739516/inc/3rd-party/plugins/seo/all-in-one-seo-pack.php#L82

That's because `$aioseo_v3` and `$aioseo_v4` are empty too, so we're not setting the sitemap at all in the if statement just above the mentioned line.

**Review by piotrbak — CHANGES_REQUESTED** [review]
The changes are needed. Should we dig into the v3 compatibility too?

**Comment by Tabrisrp** [comment]
The changes are supposed to keep backward compatibility with the v3, so something is not quite right.

@benjaminprojas By any chance, do you have time to review what was found during QA?

**Comment by benjaminprojas** [comment]
@Tabrisrp yes, we'll take another look and see if we missed anything.

**Comment by benjaminprojas** [comment]
@Tabrisrp I've updated the PR so it should address these issues. Let me know if you are still seeing issues with the integration.

**Comment by benjaminprojas** [comment]
Also, one other note, when you are testing in V3, make sure to go into the sitemap settings and click "Save" at least once. Due to limitations with how that plugin is coded it will require that for the options to appear in the WP Rocket side.

**Comment by piotrbak** [comment]
@benjaminprojas @Tabrisrp It passed the QA:
[testrail-report-101.pdf](https://github.com/wp-media/wp-rocket/files/5810729/testrail-report-101.pdf)

**Review by remyperona — APPROVED** [review]

**Comment by remyperona** [comment]
Thank you @benjaminprojas, the changes will be included in the next release of the plugin 👍🏼

**Pull request merged**
