### PR TITLE
Closes #4190 TranslatePress compatibility enhancements

### LINKED ISSUE #4190: Compatibility with TranslatePress
When using TranslatePress and WP Rocket we don't purge the cache for additional languages when updating content.

The permalink structure in this case is like this: 
Default language: example.com
Additional language: example.com/de/

The customer in this case noted it specifically related to WooCommerce products, but the issue is the same for non-Woo content as well since I guess WP Rocket won't be aware of any other language.

We could create compatibility as we do for Polylang etc.
As with other multilingual plugins, various URL configurations are allowed and should be detected: https://jmp.sh/QAwHjUf

Ticket: https://secure.helpscout.net/conversation/1573104333/280196?folderId=377611

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Improve compatibility with TranslatePress

Fixes #4190

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)
- [x] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

This PR adds more compatibility than planned, as there is a number of i18n compatibility functions we have that were currently only handling WPML/Polylang/qTranslate.

This solution adds filters to those functions so they can be extended in the future with any other i18n plugin.

## How Has This Been Tested?

- [x] Unit tests
- [x] Manual tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by piotrbak** [comment]
@Tabrisrp Is this one ready for review, or still some work needs to be done here?

**Comment by mostafa-hisham** [comment]
@Tabrisrp some tests didn't pass

**Review by CrochetFeve0251 — APPROVED** [review]

**Comment by vmanthos** [comment]
@Tabrisrp Thank you for the PR.

I found the following issues:
1. When updating a post, we only clear the specific post's cache, i.e. we don't clear the cache of the translated posts as well.
2. When changing the translation of a string using TranslatePress's UI (open a post in the editor -> click "Translate Page", we won't clear the cache of the translated post.
3. Clearing the default language's cache from the admin bar menu isn't working.

Can you please look into these? :pray: 

**Testing Conditions**
TranslatePress 2.5.8
Settings:
image

**Comment by remyperona** [comment]
I updated the code to add 2 methods to handle point 1 & 2.

For point 3, I was not able to replicate it, going to admin bar, clear cache, and select default language (english) was correctly clearing the cache for me.

**Comment by vmanthos** [comment]
@Tabrisrp Thank you for the fixes. :pray: 

I'm still getting the third issue. :thinking: 

I have the settings mentioned in [the comment](https://github.com/wp-media/wp-rocket/pull/6047#issuecomment-1669278027):
**Default Language:** English (United States)
**Use a subdirectory for the default language**: No

I debugged this and found that for English (default language) the URL that's passed to `rocket_clean_domain()` is:
https://example.com/en_us/

When content for the default language is cached, that's happening in the root cache folder, i.e. `/cache/wp-rocket/example.com/`. So, there isn't an `en_us` folder to remove.

Ideally, when the default language doesn't have its own directory,  clearing its cache should delete whatever is in `/cache/wp-rocket/example.com/` while preserving the cache of additional languages, e.g. for `fr` the cache in `/cache/wp-rocket/example.com/fr/`.

**Comment by remyperona** [comment]
Should be good for this now!

**Review by vmanthos — APPROVED** [review]
This is working according to the acceptance criteria. :+1: 

**NOTE**

There is a regression of https://github.com/wp-media/wp-rocket/issues/5640 present in the `trunk`.
I'll reopen the issue.

**Pull request merged**
