### PR TITLE
Fix some minor issues with new OptimizeCSS UI

### PR DESCRIPTION
**Pull request by iCaspar**
## Description
This fixes a couple minor issues with the new Optimize CSS noted by Product and Support team on the 1.10-alpha1:

- [X] Missing text for RUCSS description: "Recommended for best performance. Test Thoroughly!"
- [x] Unnecessary Warning/confirmation for RUCSS appears when switching UI back from CPCSS option, when RUCSS is already active.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Locally in Rocket settings page.

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by mostafa-hisham — COMMENTED** [review]
Nice Work @iCaspar
I just edited the code for `wprShowRadioWarning` so it can work with all radio buttons fields in case we add new ones in the future
Can you please have a look?

**Comment by Mai-Saad** [comment]
@mostafa-hisham @iCaspar Can we please remove `for better performance` after `Removes unused CSS per page and helps to reduce page size and HTTP requests`
Note: we need to add supported translations as well

**Comment by iCaspar** [comment]
Can't approve my own PR, but @mostafa-hisham changes look good, and text is updated per @Mai-Saad review.
Moving this to ready for @wp-media/qa 
Translations will be added as transifex is updated.

**Review by Mai-Saad — APPROVED** [review]
[debug.log](https://github.com/wp-media/wp-rocket/files/7222439/debug.log)

Note: The fatal error when switch to the trunk without deactivating the plugin appears here.. isn't the fix merged to this branch? (same case when switch develop to trunk)  => will be handled here #4381 fix class aliases in deprecated 3.10

**Pull request merged**
