### PR TITLE
Closes #4074 Grey-out delay JS option when WP Meteor is active

### LINKED ISSUE #4074: Grey out Delay JS option when WP Meteor is activated
**Is your feature request related to a problem? Please describe.**
After discussing with WP Meteor's author, we decided to implement the same kind of compatibility we are doing for some plugins when we grey out our option when we detect the same option is activated on another plugin.

e.g: https://share.getcloudapp.com/jkuPPqQq

It will be in replacement of the global notice we are now displaying when WP Meteor is active.

**Describe the solution you'd like**
Grey out the Delay JS option when WP Meteor is activated and display a message to let the user know why.

**Additional context**
Discussion with WP Meteor is here: https://github.com/wp-media/wp-rocket/issues/3945#issuecomment-860182734

### PR DESCRIPTION
**Pull request by remyperona**
## Description

In this PR, we remove the incompatibility notice when WP Meteor is active. Instead, we are adding a compatibility class to detect it, and if it's activated, we grey-out the delay JS option with an explanation message.

Delay JS disabled field

Closes #4074

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Automated tests
- [x] Manual tests

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by mostafa-hisham — APPROVED** [review]
using a filter to display delay js filed is a great idea

**Comment by remyperona** [comment]
@wp-media/qa Ready for QA

**Comment by piotrbak** [comment]
@Tabrisrp I updated from version with old Delay JS feature enabled, this is what I see in the UI now:
image

We're saying that Delay JS is disabled, but it's enabled (also in the frontend) and it's not possible to disable it.

Do we want to handle that kind of case? To reproduce:
1. Use the old Delay JS (pre 3.9.1), keep it enabled
2. Enable WP Meteor
3. Update WP Rocket to the newest one

**Edit**

The same happens when updating from 3.9. We grey out the checkbox, with feature enabled. WP Meteor is asking to disable our Delay JS as it's not compatible with WP Meteor, but we are not giving this possibility.

**Comment by remyperona** [comment]
@piotrbak We can add a method checking if WP Meteor is active on plugin update to 3.9.2, and disable the option if we detect it?

**Comment by piotrbak** [comment]
@Tabrisrp Yes, `on plugin update to 3.9.2`, or when updating from `pre` 3.9.2 to higher version. Because we should also cover the updates from 3.9.05 to 3.9.3. What do you think?

**Comment by piotrbak** [comment]
@GeekPress Could you confirm that this is what we expect here?

Problem is described here:
https://github.com/wp-media/wp-rocket/pull/4205#issuecomment-889985005

**Comment by GeekPress** [comment]
> @GeekPress Could you confirm that this is what we expect here?

We should check if WP Meteor is active and deactivate our Delay JS if it'sactivated.

**Comment by remyperona** [comment]
@piotrbak I pushed a change to perform the deactivation on plugin update too

**Comment by piotrbak** [comment]
@Tabrisrp Could you change the WP Rocket version to 3.9.2 😃 ?

**Comment by remyperona** [comment]
@piotrbak Done

**Comment by piotrbak** [comment]
@Tabrisrp Thank you! The same thing as in the https://github.com/wp-media/wp-rocket/pull/4205#issuecomment-889985005 (WP Meteor telling that it's disabled because of WP Rocket's Delay JS. Asking customer to disable our Delay JS, but our Delay JS is greyed out) is happening when importing settings with delat JS turned on.

Should we handle that case?

**Comment by remyperona** [comment]
@piotrbak Pushed another change to cover this case

**Review by piotrbak — APPROVED** [review]
Looks good!
[testrail-report-231.pdf](https://github.com/wp-media/wp-rocket/files/6918390/testrail-report-231.pdf)

**Pull request merged**
