### PR TITLE
Add Matomo & Piwik Pro query strings

### PR DESCRIPTION
**Pull request by GeekPress**
Like we do for Google Analytics campaigns (utm_xxx), this PR will automatically serve the caching file to Matomo and Piwik Pro (Paid Search) query string.

Here the docs:
- https://help.piwik.pro/support/analytics-new/piwik-pro-url-builder/
- https://plugins.matomo.org/MarketingCampaignsReporting

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Tabrisrp** [comment]
@wp-media/qa Ready for QA

**Comment by piotrbak** [comment]
@Tabrisrp I can see that in similar PR the parameters are also added to the `process.php`, should it be the case here too?
https://github.com/wp-media/wp-rocket/pull/3163/files#diff-0c17e810a089723f9f5e57047e2a7265

**Comment by Tabrisrp** [comment]
No it's fine, the file is deprecated anyway

**Review by piotrbak — APPROVED** [review]
Worked as expected
[testrail-report-37.pdf](https://github.com/wp-media/wp-rocket/files/5349137/testrail-report-37.pdf)

**Pull request merged**
