### PR TITLE
Fixed the filter used to add webp  headers

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Fix an issue where we need to add also requests without the webp header when the webp addon is activated.

For that we moved the `add_accept_header` to the `rocket_preload_before_preload_url` filter so we can have a control on this.

## Type of change

Please delete options that are not relevant.

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Test on local env

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by mostafa-hisham — APPROVED** [review]

**Comment by piotrbak** [comment]
@CrochetFeve0251 Could you provide us with the code that would allow us to provide both versions of the cache when WebP add-on is enabled?
1. Webp version
2. Non-webp version

Also taking into the consideration mobile and desktops if Separate Cache for Mobiles is enabled.

**Comment by vmanthos** [comment]
@CrochetFeve0251 With the current changes, when the WebP add-on is enabled the _non-webp_ version of a page is preloaded.

The headers are added like this:
```PHP
    [blocking] => false
    [timeout] => 0.01
    [user-agent] => WP Rocket/Preload
    [Accept] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
    [sslverify] => false
```

instead of this:
```PHP
    [blocking] => false
    [timeout] => 0.01
    [user-agent] => WP Rocket/Preload
    [sslverify] => false
    [headers] => Array
        (
            [Accept] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
            [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
        )
```

Can you please look into this?

**Comment by piotrbak** [comment]
@CrochetFeve0251 Can you check this one? 😁

**Comment by piotrbak** [comment]
@CrochetFeve0251 This one is ready for QA already?

**Comment by CrochetFeve0251** [comment]
> @CrochetFeve0251 This one is ready for QA already?

@piotrbak yes sry, I left it there due to the failling test but after a small talk with @engahmeds3ed we can ignore the error.

**Comment by vmanthos** [comment]
This is working as expected as far as acceptance criteria are concerned:

When the WebP add-on is enabled:
* By default, the `-webp` versions of cached pages (mobile/desktop) are generated 
* Both the `-webp` and the non-webp versions are generated when using this helper: https://gist.github.com/vmanthos/dcb0c3ee6b6114986378338af0e41469

**Notes**

Using the following snippet:
```PHP
add_filter( 'rocket_preload_before_preload_url', function( $requests ){
	return null;
});
```
I'm getting PHP fatal errors when the:
1. WebP add-on is disabled:
```PHP
PHP Fatal error:  Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Controller/PreloadUrl.php:98
Stack trace:
#0 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Controller/PreloadUrl.php(98): array_filter()
#1 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Frontend/Subscriber.php(86): WP_Rocket\Engine\Preload\Controller\PreloadUrl->preload_url()
#2 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Preload\Frontend\Subscriber->preload_url()
#3 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#5 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/actions/ActionScheduler_Action.php(43): do_action_ref_array()
#6 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(65): ActionScheduler_Action->execute()
#7 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_QueueRunner.php(162): ActionScheduler_Abstract_QueueRunner->process_action()
#8 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_QueueRunner.php(132): ActionScheduler_QueueRunner->do_batch()
#9 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(308): ActionScheduler_QueueRunner->run()
#10 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#11 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#12 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-cron.php(188): do_action_ref_array()
#13 {main}
  thrown in /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Controller/PreloadUrl.php on line 98
```
2. WebP add-on is enabled:
```PHP
[07-Nov-2022 10:47:54 UTC] PHP Fatal error:  Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, null given in /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/classes/subscriber/Media/class-webp-subscriber.php:433
Stack trace:
#0 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/classes/subscriber/Media/class-webp-subscriber.php(433): array_map()
#1 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(308): WP_Rocket\Subscriber\Media\Webp_Subscriber->add_accept_header()
#2 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#3 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Controller/PreloadUrl.php(96): apply_filters()
#4 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Frontend/Subscriber.php(86): WP_Rocket\Engine\Preload\Controller\PreloadUrl->preload_url()
#5 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Preload\Frontend\Subscriber->preload_url()
#6 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#7 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#8 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/actions/ActionScheduler_Action.php(43): do_action_ref_array()
#9 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(65): ActionScheduler_Action->execute()
#10 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_ListTable.php(557): ActionScheduler_Abstract_QueueRunner->process_action()
#11 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_ListTable.php(526): ActionScheduler_ListTable->process_row_action()
#12 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler_Abstract_ListTable.php(615): ActionScheduler_ListTable->row_action_run()
#13 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler_Abstract_ListTable.php(728): ActionScheduler_Abstract_ListTable->process_row_actions()
#14 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_AdminView.php(107): ActionScheduler_Abstract_ListTable->process_actions()
#15 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_AdminView.php(88): ActionScheduler_AdminView->get_list_table()
#16 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(308): ActionScheduler_AdminView->process_admin_ui()
#17 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#18 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#19 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-admin/admin.php(237): do_action()
#20 /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-admin/tools.php(40): require_once('...')
#21 {main}
  thrown in /var/www/alfonso.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/classes/subscriber/Media/class-webp-subscriber.php on line 433
```

@CrochetFeve0251  Can you please safeguard the filter for all cases where the `$requests` isn't an array?
I believe the same should be done for `rocket_preload_url_request_args`. 🙏

**Comment by vmanthos** [comment]
@CrochetFeve0251 I'm still getting a PHP fatal error (PHP 8.1.x) when the WebP add-on is enabled. It's the same as point 2 in my previous comment. Can you please check this? 🙏 

I believe this should be safeguarded in the `add_accept_header()` method:
https://github.com/wp-media/wp-rocket/blob/b55cf2ea1133d72d433114f1dcd644719c4992f5/inc/classes/subscriber/Media/class-webp-subscriber.php#L426-L440

**Review by vmanthos — APPROVED** [review]
Thank you for the changes, @CrochetFeve0251.

No errors appear now. 👍

**Pull request merged**
