### PR TITLE
Added Umami to JS Minify exclusion list

### LINKED ISSUE #5024: Umami.js needs to be excluded from Minification by default
**Describe the bug**
When Minification is enabled, Umami.js (an analytics tracker, alternative to Google Analytics & Matomo) fails to run properly. I must exclude it on each site from WP Rocket Minification in order for it to work properly. Requesting that the umami.js script be excluded by default as this will surely affect all customers using Umami for data collection / website analytics.

Umami script looks something like this:

<script async defer data-website-id="<UUID>" src="https://<UmamiHostname>/umami.js"></script>

When minification is enabled, it of course adds the data-minify="1" to it too.

Can learn more about Umami here: https://umami.is/docs/collect-data

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a Umami tracker script to a website2. 
2. Run WP Rocket to clear cache and enable Minification
3. Preload cache, and test if script is running (can confirm if analytics show up in Umami server)
4. You should see that no data is collected using the script.
5. Exclude umami.js from Minification, then clear and preload cache again and test - you should now see it works correctly

**Expected behaviour**
Umami analytics script should work without needing to modify WP Rocket, as it'd require every site under management by an admin to have to exclude that script, and any mistakes in missing it will be a loss of important website metrics.

**Screenshots**
N/A

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by d19dotca**
Resolves #5024

## Description

Adds umami to the list of minify JS default exclusions.

Fixes #5024 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

N/A

## How Has This Been Tested?

N/A

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
Hi @d19dotca.

You've added the exclusion to the array that holds external files. Is the `umami.js` always going to be served from a URL that's different from that of the site? For example:
Site: www.example.com
`umami.js`: app.something.com/umami.js

If not, are there issues when `umami.js` is served from the same TLD as that of the site?

**Comment by d19dotca** [comment]
Hi @vmanthos - Umami is a self-hosted [analytics server](https://umami.is) so it won't be always be included in the same domain as the website referencing it and at closest will be a different subdomain still. In my case, I run the server and have it on my client sites, so beyond my own website which will talk to Umami on a subdomain, the rest will be entirely different domains.

**Comment by vmanthos** [comment]
Thank you for your reply, @d19dotca! 🙏

**Review by vmanthos — APPROVED** [review]
This is working as expected. 👍

**Note:** If the `umami.js` file is served from the same TLD as that of the site, e.g. for `example.com` that would be `example.com/(.*)umami.js`, the specific exclusion won't be applied.

**Pull request merged**
