### PR TITLE
Fixes #4706 Exclude use.typekit.com from minify & Defer JS

### LINKED ISSUE #4706: Defer and minify JS compatibility with Typekit
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using the Typekit fonts with Defer JS, fonts are not rendered properly on Safari mobile. But they work fine on Desktop on Safari, and on both Desktop and Mobile of Android devices. 

Sample of the script added by Typekit - https://use.typekit.com/sgs4pbn.js (the file name is a random string)

A separate cache for mobile devices was enabled to exclude that possibility. 

Only excluding `use.typekit.com` fixes the issue. 

The same should be excluded from JS Minify to avoid the exclusion to stop working when the script is hosted. 

**To Reproduce**
1. Use Typekit to add a font
2. Enable Defer JS
3. See error (font-family not applied to target selector)

**Expected behavior**
Typekit fonts should work out of the box.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1770086284/322313/
Related to - https://github.com/wp-media/wp-rocket/issues/1912 - the only difference is that JupiterX has its own Typekit integration through the API using a hosted file.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by DahmaniAdame**
https://secure.helpscout.net/conversation/1770086284/322313/

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Tabrisrp @DahmaniAdame In the test template we have 
```
<script type='text/javascript' src='//use.typekit.com/sgs4pbn.js'></script>
<script type='text/javascript'>try{Typekit.load();}catch(e){}</script>
```
1st script is excluded from Combine JS while the 2nd script is combined which may cause FOUC, As per discussion with Piotr, we think that this shall be excluded from Combine JS as well `try{Typekit.load` . What do you think?

**Comment by remyperona** [comment]
I agree

**Comment by DahmaniAdame** [comment]
@Mai-Saad sounds good 👍

**Comment by Mai-Saad** [comment]
@Tabrisrp Seems working fine but the inline script now moves after the combined file, is this what we need or just exclude without changing location in the source (as same as if excluded from UI)?

**Comment by remyperona** [comment]
@Mai-Saad That was a mistake on my part, I moved it to the correct exclusion so that it doesn't move.

**Review by Mai-Saad — APPROVED** [review]
Working as expected

**Pull request merged**
