### PR TITLE
Fixes #4616 Exclusion for yanovis.Voucher.js from JS minification

### LINKED ISSUE #4616: External script automatic exclusion from minification and/or deferred yanovis.Voucher.js
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The following external script creates console errors when hosted and/or deferred - [voucher.getavo.it/public/js/yanovis.Voucher.js](https://voucher.getavo.it/public/js/yanovis.Voucher.js)

```
yanovis.Voucher.js?ver=1640671223:4 GET https://www.sporthotel-zoll.com/ka_seite/cache/min/1/?ver=1640671223/de/getavo/b56bda8af7f6fa5f96768203b81f51c7/?version=2 403
createIframe @ yanovis.Voucher.js?ver=1640671223:4
init @ yanovis.Voucher.js?ver=1640671223:31
window.yanovis.Voucher @ yanovis.Voucher.js?ver=1640671223:43
(anonymous) @ (index):540
yanovis.Voucher.js?ver=1640671223:28 GET https://www.sporthotel-zoll.com/ka_seite/cache/min/1/?ver=1640671223/public/js/iframeResizer.js net::ERR_ABORTED 403
loadScript @ yanovis.Voucher.js?ver=1640671223:28
init @ yanovis.Voucher.js?ver=1640671223:31
window.yanovis.Voucher @ yanovis.Voucher.js?ver=1640671223:43
(anonymous) @ (index):540
yanovis.Voucher.js?ver=1640671223:23 GET https://www.sporthotel-zoll.com/ka_seite/cache/min/1/?ver=1640671223/bundles/endo7lauraiframe/css/yanovis-voucher.css net::ERR_ABORTED 403
```
image

Excluding it from minification and deferring fixes the issue. 

**To Reproduce**
1. Add the following script: 
```
<div id="test"></div>
<script type="text/javascript" src="https://voucher.getavo.it/public/js/yanovis.Voucher.js"></script>
<script>
    var yanovisVoucher = new yanovis.Voucher({
        widget: '',
        lang: 'de',
        container: '#test',
        previewOffset: 100,
    });
</script>
```
2. Enable minification and/or defer
3. See error

**Expected behavior**
`https://voucher.getavo.it/public/js/yanovis.Voucher.js` should be excluded automatically from minification to avoid any issues.

**Screenshots**
Added above.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1727751196/314385

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by DahmaniAdame**
Ticket - https://secure.helpscout.net/conversation/1727751196/314385

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@DahmaniAdame @Tabrisrp Script is excluded now. However, on the test site, there was no error when adding the script in the body (using 3.10.6). Do we still need to add the exclusion?
`<script type='text/javascript' src="https://voucher.getavo.it/public/js/yanovis.Voucher.js"></script>`

**Comment by DahmaniAdame** [comment]
@Mai-Saad the script standalone won't trigger an error. It needs to be tested with the full embedable script provided by the service. 
Here is a sample: 

```
<div id="test"></div>
<script type="text/javascript" src="https://voucher.getavo.it/public/js/yanovis.Voucher.js"></script>
<script>
    var yanovisVoucher = new yanovis.Voucher({
        widget: '',
        lang: 'de',
        container: '#test',
        previewOffset: 100,
    });
</script>
```

I will update the original GH issue with the sample script.

**Comment by Mai-Saad** [comment]
@DahmaniAdame Can see the error and confirm the fix with the script mentioned above. But can see another error with Defer JS, which will be fixed by excluding `yanovis.Voucher.js` from Defer JS. So what do you think about adding an exclusion for Defer JS as well? @DahmaniAdame @Tabrisrp 
Screenshot from 2022-01-12 08-44-43

**Comment by DahmaniAdame** [comment]
@Mai-Saad I confirm the same. I created the PR and updated the GH issue to include the defer exclusion as well.
Thanks 🙏

**Pull request merged**
