### PR TITLE
Closes #6033 Add partial clean of SpinupWP cache

### LINKED ISSUE #6033: Compatibility with SpinupWP cache purging (indiviual URLs)
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using WP Rocket with SpinupWP, we disable our cache, and only sync full site cache purging: 

https://github.com/wp-media/wp-rocket/blob/b11a9ef010188cdf41a1335819b0102fbc63c524/inc/ThirdParty/Hostings/SpinUpWP.php#L29

Individual pages cache purge is not synced. 

They do have a way to purge individual URLs are well: 

```
function spinupwp_purge_url( $url ) {
    return spinupwp()->cache->purge_url( $url );
}
```
https://github.com/spinupwp/spinupwp-plugin/blob/62ae3ec7c53f602f80cd10c742fae6c361c790f4/functions.php#L38-L40C6

We should hook to this method whenever `after_rocket_clean_post` is triggered.

**To Reproduce**
1. Use SpinupWP
2. Purge an individual page
3. See that the page is not purged from the server-side cache (it will still have `Fastcgi-Cache: HIT` response header returned)

**Expected behavior**
We should also sync individual pages cache when needed to ensure page content is always current.

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2289462527/427935/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Add partial clean of SpinUpWP cache on our clean actions

Fixes #6033

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## How Has This Been Tested?

- [ ] Manual test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by piotrbak** [comment]
Access to the website and SFTP is on Bitwarden.

**Review by mostafa-hisham — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Tabrisrp Thanks for the PR. During exploratory testing, can see that Purge this URL from the Admin bar at page view or clear this cache from the posts list is not working (i.e not setting cache header to Miss) when permalinks without `/` i.e `/%postname%` However, it is working when permalinks with`/` i.e `/%postname%/`. can you please check :pray: 
Tested env: https://spinupwp.rocketlabsqa.ovh/
Active plugins
Screenshot from 2023-09-18 09-39-35

**Comment by remyperona** [comment]
I updated the code to add a trailing slash to the URL to purge

**Review by CrochetFeve0251 — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Tabrisrp Thanks for the update. can still see the [problem](https://github.com/wp-media/wp-rocket/pull/6100#issuecomment-1710692171) on the test site using the latest version of the PR. can you please check :pray:

**Comment by remyperona** [comment]
I can't find the reason why it's not working without trailingslash in the code itself. There is nothing that should impact it, looking at their code: https://github.com/spinupwp/spinupwp-plugin/blob/62ae3ec7c53f602f80cd10c742fae6c361c790f4/src/Cache.php#L289

We might need to ask them if there is a reason on their side

**Comment by MathieuLamiot** [comment]
@Mai-Saad, @piotrbak, would it make sense to close the issue as is and open a new one to identify the issue with trailing slash? As this probably needs discussion with Spinup and/or R&D?

@piotrbak, do you have a contact at Spinup we could reach out to?

**Comment by Mai-Saad** [comment]
@MathieuLamiot I am fine with that, can execute the test plan only while Permalinks having `/` for now

**Comment by piotrbak** [comment]
@MathieuLamiot @Tabrisrp @Mai-Saad Agreed, let's do it like that. As soon as the issue is opened, I'll reach SpinupWP and ask them to collaborate there

**Comment by MathieuLamiot** [comment]
Ok, @Tabrisrp can you open an issue? I think you have more insights on the matter :) Moving this to "Ready for QA" in case there are other things to check :) 
Thanks!

**Comment by Mai-Saad** [comment]
Working as expected with the following notes.
- on the trunk with spinupWP (preload off)=> it seems they don't differentiate mobile from desktop
1- Enable separate mobile cache
2- clear cache from admin
3- visit the desktop of the page => cache miss
4- visit mobile of same page => cache hit
=> As per discussion, SpinupWP does not provide this option
- edit post => clear whole cache (same on trunk and even without wpr)
- switch theme => not clearing home hit header ( UI is correct but the cache is hit, same on the trunk but without wpr cache will be miss in this case), it will cause UI issue even on the trunk while RUCSS is on due to https://github.com/wp-media/wp-rocket/issues/6076#issuecomment-1722930989
[testrail-report-525.pdf](https://github.com/wp-media/wp-rocket/files/12647447/testrail-report-525.pdf)

**Pull request merged**
