### PR TITLE
Closes #3597 Remove Facebook and Google tracking add-ons

### LINKED ISSUE #3597: Get rid of Google Tracking and Facebook Pixels add-ons
## What are we proposing to do?

With this update we are hoping to remove the « Google Tracking » and « Facebook Pixels » add-ons from WP Rocket UI (Add-ons tab).

## Why are we doing this? 

We originally released these features to fix the old « Leverage browser caching » PageSpeed Insight recommendation on Google Analytics and Facebook Pixels JS files. Both have a small cache policy.

By hosting these files locally we fix the browser caching issues.

Since 3.7, we introduced a feature to delay JS execution. The principle behind that is to load non-critical JS files after a user interaction (a kind of Lazy-Load).

Today, this is the way to go to optimize third-party JS files. 

Here what Google itself recommends: If they aren't critical or are below the fold (that is, if users have to scroll to view them), lazy-loading is a good way to improve page speed and paint metrics. This way, users will get the main page content faster and have a better experience. One effective approach is to lazy-load third-party content after the main page content loads. Ads are a good candidate for this approach. (source: https://web.dev/efficiently-load-third-party-javascript/)

Delaying third-party JS files would be a much better UX improvement than hosting the file locally.

We already pre-populates our Delay JS option with a list of third-party scripts including Google Tracking and Facebook Pixels.

Based on that, our add-ons to host locally Google Tracking and Facebook Pixels files are now useless.

## Benchmark Tests

Here the conclusion of our benchmark.

* Hosting locally Google Tracking and Facebook Pixels decrease the general Google PageSpeed score even if they aren't delayed.
* Delaying Google Tracking and Facebook Pixels JS files is confirmed to be the way to go to get better performance.

## User expectations and experience. How will we do this feature?
From 3.9, all users will not have Google Tracking and Facebook Pixels add-ons in WP Rocket UI and the optimizations won’t be applied anymore.

Both existing and new users will have the same experience.

## Risks

Since we are removing a feature, this should be low risk. The major concern is educating customers.

## Acceptance Criteria

* Update WP Rocket to 3.9.
* The UI for « Google Tracking » and « Facebook Pixel » add-ons are removed.
* On front-end, the tracking for Google and Facebook should not be modified

## Documentation and Translations

* https://docs.wp-rocket.me/article/1103-google-tracking-add-on
* https://docs.wp-rocket.me/article/1117-facebook-pixel-add-on
* https://docs.wp-rocket.me/article/1361-google-analytics-not-detected (Google Tracking Add-on is listed)
* https://docs.wp-rocket.me/article/115-can-i-use-wp-rocket-with-sg-optimizer (Google Tracking Add-on is listed)
* https://docs.wp-rocket.me/article/59-getting-started (Google Tracking and Facebook Pixels add-ons are listed)
* https://docs.wp-rocket.me/article/1419-minimize-main-thread-work (Google Tracking and Facebook Pixels add-ons are listed)
* https://docs.wp-rocket.me/article/1413-reduce-the-impact-of-third-party-code (Google Tracking and Facebook Pixels add-ons are listed)
* https://docs.wp-rocket.me/article/893-handling-external-resources (Google Tracking and Facebook Pixels add-ons are listed)

## Github issues
All opened issues related to Google Tracking and Facebook Pixels add-ons will be closed:

* https://github.com/wp-media/wp-rocket/issues?q=is%3Aopen+is%3Aissue+label%3A%22module%3A+Google+tracking+add-on%22+-label%3A%22epics+%F0%9F%94%A5%22+
* https://github.com/wp-media/wp-rocket/issues?q=is%3Aopen+is%3Aissue+label%3A%22module%3A+Facebook+Pixel+add-on%22+-label%3A%22epics+%F0%9F%94%A5%22+

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Remove the Facebook and Google tracking add-ons from the plugin

Fixes #3597 

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Manual testing on the settings page and the frontend

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Existing unit tests pass locally with my changes

### CODE REVIEW

**Review by crystinutzaa — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Tabrisrp @crystinutzaa  Please find my questions below:
-  when import 3.8 settings (has FB and GT) in 3.9 , then export settings from 3.9 => shall FB and GT be removed from settings?? (currently they aren't removed , although fresh install for 3.9 then export settings, FB and GT won't be there)
- If GA was cached before 3.9 then clear cache won't delete it, Donn we need to delete this?
- For the Beacon articles, those GT and FBP not removed yet .. I think this shall be from helpscout ... or shall we remove them at all so won't even appear in search of beacon? ... if we downgraded, they will appear in beacon normally, right?

**Comment by remyperona** [comment]
@Mai-Saad 

> when import 3.8 settings (has FB and GT) in 3.9 , then export settings from 3.9 => shall FB and GT be removed from settings?? (currently they aren't removed , although fresh install for 3.9 then export settings, FB and GT won't be there)

This is ok, even if the setting is still present, it won't do anything.

> If GA was cached before 3.9 then clear cache won't delete it, Donn we need to delete this?

I pushed a commit to clean this folder when updating to 3.9

> For the Beacon articles, those GT and FBP not removed yet .. I think this shall be from helpscout ... or shall we remove them at all so won't even appear in search of beacon? ... if we downgraded, they will appear in beacon normally, right?

This is handled on Helpscout by the support team. The docs will probably be kept for a time, with a notice to say that it's deprecated.

**Comment by remyperona** [comment]
@Mai-Saad Fixed the clean folders (facebook-tracking and google-tracking) issue on update. I tested it locally and they were correctly deleted when updating.

**Review by Mai-Saad — APPROVED** [review]
- cached GT and FB pixel cached folders are now deleted from cache after activating 3.9 version

**Pull request merged**
