### PR TITLE
Fixes #2970 Add new post-type exclusion "cms_block" from CPCSS generation

### LINKED ISSUE #2970: Exclude cms_block post type from CPCSS generation
There is a post type `cms_block` (I think it's from the Woodmart theme) which generates an "error url unreachable" from our CPCSS generation - it's not a publicly available post type. We have at least 3 tickets related to this so we could automatically exclude it. 

https://secure.helpscout.net/conversation/1244958588/184550/
https://secure.helpscout.net/conversation/1240422850/183633/
https://secure.helpscout.net/conversation/1232777347/181911/

### PR DESCRIPTION
**Pull request by sandyfzu**
Fixes: https://github.com/wp-media/wp-rocket/issues/2970

Exclude the `cms_block` custom post type from CPCSS generation. This CPT is added by the Woodmart theme.

**Impacts**
This impacts the "optimize CSS delivery" feature of WP Rocket, on the generation part specifically.

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by piotrbak** [comment]
@Tabrisrp cms_block post type is set in the `Woodmart Core` plugin that is obligatory for `Woodmart` theme. At least since `1.0.22` version of this plugin (dated 15-04-2020), the `cms_block` is defined with `'publicly_queryable'  => false`.
image

`Woodmart Core` plugin doesn't have any changelog, so I'm no sure when this change happened, but I can see we have a ticket there. I'm not able to reproduce this, since WP Rocket [is not fetching this post type at all](https://github.com/wp-media/wp-rocket/blob/40ecc6c70de1995295a1994fb77a6ecb93885287/inc/Engine/CriticalPath/CriticalCSS.php#L209).

What do you think?

**Comment by remyperona** [comment]
As validated with QA and product, since the recent version of the `woodmart core` plugin already is compatible (`publicly_queryable = false`), we are not going forward with this.

**Comment by vmanthos** [comment]
@Tabrisrp 

I faced this issue on a customer's website where WoodMart  5.3.6 was installed, i.e. the latest version:
https://themeforest.net/item/woodmart-woocommerce-wordpress-theme/20264492


The URL that we are trying to generate CPCSS for isn't accessible ( `error 400`):


Here is the `register_blocks()` code:  https://snippi.com/s/16ldw4k
`publicly_queryable` isn't set there.

So, this PR should be merged.

**Related ticket:** https://secure.helpscout.net/conversation/1432986773/241468?folderId=2135277

**Comment by piotrbak** [comment]
@vmanthos You're right, I can see that it's removed in the version you have on the customer's site. Seems that I was on the latest theme version but not the latest plugin core one and I'm not able to update...

**Comment by wilmerlm11** [comment]
@Tabrisrp 
I have the latest core plugin version + theme and this issue still happens.
Woodmart Theme 5.3.6
Woodmart Core plugin 1.0.27

cms_block register function:
image

errors crushing my logs:
image

Is this going to be reopened for a future release fix?
Or will you contact Woodmart team so they can re-add the queryable = false parameter?
Idk which side is wrong Woodmart or WPRocket :/

regards

**Pull request merged**
