### PR TITLE
delay js exclude scripts with invalid type

### LINKED ISSUE #3944: Delay JS - Automatically exclude scripts with invalid type
**Is your feature request related to a problem? Please describe.**

An invalid type will lead to a freeze during the delay JS process.

To fix that problem, we must not transform these scripts to be delayed.

Here a list of valid JS type:

```
'text/javascript',
'text/x-javascript',
'text/ecmascript',
'text/jscript',
'application/javascript',
'application/x-javascript',
'application/ecmascript',
'application/jscript'
'module'
```

**Describe the solution you'd like**
Detect and exclude automatically scripts with an invalid type.

### PR DESCRIPTION
**Pull request by mostafa-hisham**
## Description

delay js- exclude scripts with invalid type

Fixes #3944

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Is the solution different from the one proposed during the grooming?

No
## How Has This Been Tested?

- [x] Local testing
- [x] unit and integration test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by remyperona — CHANGES_REQUESTED** [review]
We can remove the conditional for `ld+json` at lines 171-173 now, as the new one will skip those too

**Review by remyperona — APPROVED** [review]

**Comment by piotrbak** [comment]
@Tabrisrp @mostafa-hisham How detailed we should be while testing this regex itself?

For example, it accepts `type="module2345"` not sure if that's an issue though.

**Comment by remyperona** [comment]
@piotrbak I updated the regex a bit to avoid this case. But mainly if we validate that the valid script types are all correctly working, anything else can be treated as an edge case.

**Review by piotrbak — APPROVED** [review]
Looks good!
[testrail-report-206.pdf](https://github.com/wp-media/wp-rocket/files/6766220/testrail-report-206.pdf)

**Pull request merged**
