### PR TITLE
Closes #2899 New Feature: Delay JS execution

### LINKED ISSUE #2899: Delay JS execution time (LazyLoad Script)
## What are we proposing to do? 

With this feature WP Rocket will delay the execution of JavaScript files. This will essentially be a LazyLoad for JavaScript.

**Note**: We once planned a similar feature, but only for third party scripts (#[<u>2581</u>](https://github.com/wp-media/wp-rocket/issues/2581)). With this feature we are extending this to both internal and external JS files. 

## Why are we doing this? 

Not all scripts are relevant for the initial page render and delaying them can improve the loading time. For example, a script useful for an “Exit Popup” is not relevant during initial page load and can be delayed. This can have huge performance gains as evident from the Benchmark tests. 

As a side effect, delaying the execution of JavaScript will help improve PageSpeed score and speed test results. 

<p></p>

**Note**: We decided not to go ahead with #2581 because we thought of a better way to do it. However, that approach will take some development time and we are hoping the current approach will serve as an intermediate solution for our customers. 

## Benchmark Tests

Jonathan has been using this feature on our own website for a while with impressive results. We also did detailed benchmarking for #[<u>2581</u>](https://github.com/wp-media/wp-rocket/issues/2581) and are available in the issue. 

## User expectations and experience. How will we do this feature?

We are going to keep it simple and lean for our first iteration.   

- We will do it with a simple checkbox to enable the option. 

- The whole feature will be opt-in. Meaning that only the scripts that the users have selected will be delayed. 

- Enabling the option will reveal a text area where users can enter the scripts that they wish to delay. 

- We will pre-populate this textarea with some scripts that we have identified as safe to delay. Example: Facebook Social Plugins.

- Users can add their own scripts (both internal and external) to the list. They can also specify a keyword from the inline JS to be delayed. 

- If any of the scripts we include by default causes issues, users can remove them from the list as well. 

- A link « Restore default settings » will restore the default list if the user clicks on it. This will provide users an easy way to restore the default list. 

<p></p>

**Updating the default list as we discover more scripts that can be safely delayed**

<p></p>

- For now, let’s not do an automatic update for existing users. We can update our documentation and maintain a public list. Users can copy from our public list when needed. After they set-up the page initially, it wouldn’t make sense to modify the list. 

- Once we have more feedback and also see how we can handle this feature in other ways, we can work on an update strategy. Let’s keep this lean for now. 

- The updated list can be included for new users.

- This updated list can also be included if the user deletes all the scripts from the list and save settings. 

<p></p>

**UI proposal**

<p></p>

- Option name: **Delay JavaScript execution**

- Option description: **Improves performance by delaying the loading of JavaScript files until user interaction (e.g. scroll, click). More info**

- Option location: **WP Rocket > File Optimization tab > after “Load JavaScript deferred”**

- Text area title: **Scripts to delay**

- Text are description: **Specify keywords that can identify inline or JavaScript files to be delayed (one per line).**

<p></p>

**New users:**

- This option will be turned on by default on new installations.

<p></p>

**Both existing and new users:** 

- Enabling “Safe Mode” will disable the feature.

- This option will be applied on uncached pages too.

## Pre-selected scripts

Please refer this doc for suggestions: <https://www.notion.so/wpmedia/95155dc2f51f47fd94f3c942096a02d7?v=970b622c689843f9b2aa5235bf394420>

<p></p>

We will be including this as the default list for all users. 

## Technical Specs

The following is meant to be a starting point for the dev team found during research. 

<p></p>

**A good starting point is Flying Scripts WordPress plugin -** [<u>**https://wordpress.org/plugins/flying-scripts/**</u>](https://wordpress.org/plugins/flying-scripts/)

<p></p>

This plugin does the following conversion for scripts and replaces them during runtime. Similar to what we do for LazyLoad.

```
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v6.0"></script>
```

to

```
<script async defer crossorigin="anonymous" data-type="lazy" data-src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v6.0"></script>
```

<p></p>

**And for inline JS:**

```
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

```

To

```
<script data-type="lazy" data-src="data:text/javascript;base64,KGZ1bmN0aW9uKGQsIHMsIGlkKSB7DQogICAgdmFyIGpzLCBmanMgPSBkLmdldEVsZW1lbnRzQnlUYWdOYW1lKHMpWzBdOw0KICAgIGlmIChkLmdldEVsZW1lbnRCeUlkKGlkKSkgcmV0dXJuOw0KICAgIGpzID0gZC5jcmVhdGVFbGVtZW50KHMpOyBqcy5pZCA9IGlkOw0KICAgIGpzLnNyYyA9ICJodHRwczovL2Nvbm5lY3QuZmFjZWJvb2submV0L2VuX1VTL3Nkay5qcyN4ZmJtbD0xJnZlcnNpb249djIuNSI7DQogICAgZmpzLnBhcmVudE5vZGUuaW5zZXJ0QmVmb3JlKGpzLCBmanMpOw0KICB9KGRvY3VtZW50LCAnc2NyaXB0JywgJ2ZhY2Vib29rLWpzc2RrJykpOw=="></script>
```

<p></p>

**Note**: Flying Scripts adds a delay (default 5 seconds) or waits for user interaction (mouse movement, scroll etc) with the website, whichever is first. Let’s default to an “infinite” delay, which means the scripts will only be loaded on first user interaction.   

( Another method of handling inline JS is described here: [<u>https://stackoverflow.com/questions/8946715/lazy-loading-javascript-and-inline-javascript</u>](https://stackoverflow.com/questions/8946715/lazy-loading-javascript-and-inline-javascript) )

<p></p>

Swift performance Lite has this feature and it handles it a bit differently. The third party JS is included and delayed from within in the combined JS file. 

- To test this, go to Swift Performance Lite > Settings tab

- Switch to advanced view - [<u>https://jmp.sh/4X4denu</u>](https://jmp.sh/4X4denu)

- Under optimization > scripts. Enable “Merge Scripts” - [<u>https://jmp.sh/1s5JpfK</u>](https://jmp.sh/1s5JpfK)

- Add a keyword from the script to LazyLoad - [<u>https://jmp.sh/tXmasBj</u>](https://jmp.sh/tXmasBj)

## Risks

We are not expecting any major risk since the entire feature is enabled manually by the user. 

<p></p>

The list of scripts that we include by default are tested and shouldn’t cause any issue. But if that is the case, users can easily remove it by simply deleting it from the UI

## Acceptance Criteria

- On activation of the setting, the text area will be pre-populated with the scripts that we have identified as safe to delay.

- New scripts can be added and existing scripts can be removed from the text area. 

- If a keyword matches with a JavaScript file, this file won't be minified / concatenated and deferred. If a keyword matches an inline JS, this script won't be inserted into the concatenated file if the « Combine JavaScript files » option is activated.

- These scripts will not be loaded when the page loads until a user interaction. 

- On user interaction, the script will be loaded. 

- Restore the default scripts list when a user clicks on « Restore default settings ». 

<p></p>

**Testing notes:** 

- Cross browser testing is recommended for this to make sure we don’t break things on different browsers. 

## Documentation and Translations

- A new document to be created explaining the feature. 

- The documentation will list the current exclusions and we can maintain this list with new scripts that are safe to be delayed.

### PR DESCRIPTION
**Pull request by Tabrisrp**
Closes epic #2899 

Adds a new option in WP Rocket settings page to delay JS execution, with a textarea to add the JS URLs or patterns to delay. A default list of values is used, which can be restored by clicking the button under the textarea.

On the frontend, Delayed JS are modified to use a `data-rocketlazyloadscript` attribute that will be containing either the original URL from the `src` attribute, or a base64 encoded version of the content for inline scripts.

An inline script is also inserted to handle the conversion from the `data-rocketlazyloadscript` back to the `src` attribute.

### Acceptance Criteria

- On activation of the setting, the text area will be pre-populated with the scripts that we have identified as safe to delay.
- New scripts can be added and existing scripts can be removed from the text area. 
- If a keyword matches with a JavaScript file, this file won't be minified / concatenated and deferred. If a keyword matches an inline JS, this script won't be inserted into the concatenated file if the « Combine JavaScript files » option is activated.
- These scripts will not be loaded when the page loads until a user interaction. 
- On user interaction, the script will be loaded. 
- Restore the default scripts list when a user clicks on « Restore default settings ». 

**Testing notes:**

- Cross browser testing is recommended for this to make sure we don’t break things on different browsers.

### CODE REVIEW

**Comment by iCaspar** [comment]
@wp-media/qa Ready for QA, acceptance criteria in OP

**Comment by Tabrisrp** [comment]
@hellofromtonya Can you have a look at point 2, 4 & 5 above?

@Davidacu For point 1, it could be browser caching of the WPR admin script, seeing how the page reloaded when you clicked on the button instead of executing the AJAX action. Does it work if you force a browser cache clear?

For point 3, it's doable, but it was not part of the spec for this release. Everyone can add/change the values they need in the field, and it's unlikely you'll have a ton of different languages versions on your site. @arunbasillal What do you think?

**Comment by arunbasillal** [comment]
> For point 3, it's doable, but it was not part of the spec for this release. Everyone can add/change the values they need in the field, and it's unlikely you'll have a ton of different languages versions on your site. @arunbasillal What do you think?

I agree with this. Let's keep it simple for now. Even if they use multiple languages, they can add all that to the list manually. EN and GB covers plenty of use cases. Our aim is to have a starting point, not to be comprehensive.

**Comment by arunbasillal** [comment]
On a related note, now that we know that the `connect.facebook.net/ru_RU/sdk.js` exist and it can be delayed, shall we add it to the safe list @Tabrisrp ?

**Comment by Tabrisrp** [comment]
It wouldn't make sense to me to add the RU version before the FR one, knowing our userbase. I would vote to keep what we have now, and let our users decide what they need.

**Comment by arunbasillal** [comment]
@Davidacu I tested leadpages - https://jmp.sh/YGoPWsq and it seems to work well with WP Rocket. 
As you can see, the script is not loaded when the page is loaded. As soon as I move my mouse, it starts downloading.

**Comment by hellofromtonya** [comment]
>Added a simple script that prints "hello world" and I made sure to add it to the list ofDelay scripts, however the script never runs, the attribute `data-rocketlazyloadscript` is added but after user interaction there is no request made.

Bringing the slack conversation to here.

The original script:

```html
<script src='https://rocketlabsqa.dev/wp-content/rocket-test-data/scripts/print-helloworld.js' >       </script>
```

Notice the extra spaces within the open tag and between the opening and closing tags.

The script after this PR processes it:

```html
<script data-rocketlazyloadscript='https://rocketlabsqa.dev/wp-content/rocket-test-data/scripts/print-helloworld.js' >       </script>
```

After our lazyload-script runs with the above HTML, the external script is not fetched from the browser; thus, the `console.log` inside of it never runs because the script is never fetched.

If we remove the whitespace in the HTML, it works fine.

```html
<script data-rocketlazyloadscript='https://rocketlabsqa.dev/wp-content/rocket-test-data/scripts/print-helloworld.js'></script>
```

## What's going on? Why does extra whitespaces in the HTML cause this to occur?

Here's what I _think_ is going on:

In the browser, as it parses the HTML, this `<script>` is seen as inline script. There’s no external `src` specified and there are characters between the opening and closing tags. I suspect the browser's HTML parser interprets this element as an inline script, not external script. When it builds the DOM tree, that node is an inline script. 

When our script changes the data attribute to `src` attribute, it doesn't work because the node is an "inline" element, not external `script` element. So the browser doesn't know to go fetch the external script from the server.

## How can we fix this?

Option 1: In PHP (server side), strip the extra whitespaces to ensure this element is kept in the right format for the browser.

Option 2: In JavaScript (browser side): delete the `script` element and insert a new `script` element.

### Which option is better?

Option 1: relatively easy solution and serves the element to the browser in the right format.

Option 2: could cause a little bitty performance hit. Why?
Removing and inserting nodes causes the browser engine to reprocess. Depending upon the change, it can cause it to redo the rendering process. That blocks the main thread of the browser to do this work. It could have a performance hit if the user is trying to interact at the same time.

**Comment by Davidacu** [comment]
@Tabrisrp regarding point 1, weird but I cannot reproduce it anymore 🤔 .
Point 2 - fixed.
Point 3 - won't fix.
Point 4. Pending investigation?
point 5. hmm strange I cannot reproduce it anymore, leadpage script is delayed as expected 👍

**Comment by Tabrisrp** [comment]
@Davidacu we removed eucookielaw from the default list, so point 4 is fixed too

**Comment by Davidacu** [comment]
I can confirm the eucookielaw has been removed from the default list 👍

**Pull request merged**
