### PR TITLE
Closes #7161: Host Google Fonts - Measure time

### LINKED ISSUE #7161: Host Google Fonts - Measure time
**Context**
The Host Google Fonts feature presents a risk to slow down the loading of the page, during preload for instance. We must have a way to measure the impact of the feature on processing time.

**Expected behavior**
We must be able to retrieve logs (typically when WPR DEBUG is enabled) about:
- Time it takes to run the Host Google Fonts feature when processing a new page
- Details about the time taken for main steps of the process. We expect the risk to come from downloading the fonts and CSS so those two steps should be measured. Other steps could be measured too if it seems relevant.

You can check [this](https://www.notion.so/wpmedia/WP-Rocket-Logs-265376f5033343d8a2c4e0c19a8dcc55?pvs=4) to see how to add logs.

**Acceptance Criteria**
I can retrieve logs about how long it takes to process the Host Google Fonts feature on a page:
- Activate the logs
- Browse a page that has not been preloaded yet, nor has Google Fonts optimization ready yet (no files downloaded, etc).
- Check the logs: the total execution time of Google Fonts, as well as time to download the CSS files and the time to download the fonts must be available.

When logs are deactivated, timing measurments must not happen.

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #7161 
Nothing will impact the user. 

## Type of change

- [x] Chore

## Detailed scenario

No special scenario, just enable the feature host google font and load a page. Within WP Rocket debug file you'll find the execution time logged.

### Documentation

This pull request introduces performance measurement and logging for the `rewrite_fonts` method in the `Frontend/Controller.php` file. The most important changes include adding start and end time measurements and logging the total execution time for the method.

Performance measurement and logging:

* [`inc/Engine/Media/Fonts/Frontend/Controller.php`](diffhunk://#diff-3f1e418966792d4b51109c090fb00e9fe1ec75469559e0ce738d27d386e0f974R73-R75): Added start time measurement at the beginning of the `rewrite_fonts` method for test purposes.
* [`inc/Engine/Media/Fonts/Frontend/Controller.php`](diffhunk://#diff-3f1e418966792d4b51109c090fb00e9fe1ec75469559e0ce738d27d386e0f974R98-R104): Added end time measurement and logged the total execution time for the `rewrite_fonts` method.

### New dependencies

None

### Risks

None

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification

No tests required for this tasks.

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by MathieuLamiot** [comment]
cc @piotrbak @DahmaniAdame This PR should allow you to further investigate timing of the feature if you want.

**Comment by Miraeld** [comment]
## Update status of this PR: 

This pull request introduces changes to the `rewrite_fonts` function in the `inc/Engine/Media/Fonts/Frontend/Controller.php` file to add performance measurement and logging for test purposes. The most important changes include the addition of time measurement, font counting, and logging of execution time and font counts.

Performance measurement and logging:

* Added start time measurement at the beginning of the `rewrite_fonts` function to track execution time.
* Counted the number of fonts processed, including separate counts for `v1_fonts` and `v2_fonts`.
* Added end time measurement and logged the total execution time along with the number of fonts processed and their breakdown.

**Review by wordpressfan — APPROVED** [review]

**Review by hanna-meda — APPROVED** [review]
Thank you, @Miraeld, for this PR.
We can now see measurements in logs for duration & fonts processed:
Screenshot 2024-12-04 at 18 18 58

FYI, @DahmaniAdame & @piotrbak

**Comment by DahmaniAdame** [comment]
The count `count( $v1_fonts )` and `count( $v1_fonts )` is wrong. 

You are basically counting how many items are on this array: 

```
array (
    0 => array (
        0 => '',
        1 => '"',
        'url' => 'https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Montserrat+Underline:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Montserrat+Underline:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Yuji+Mai&family=Montserrat+Underline:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Yuji+Mai&display=swap',
        2 => 'https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Montserrat+Underline:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Montserrat+Underline:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Yuji+Mai&family=Montserrat+Underline:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Yuji+Mai&display=swap',
    ),
)
```

It will always return 1. 

What needs to be counted is how many font URL are on the font CSS file referred to on `url`. It can be done by checking the recurrence of `fonts.gstatic.com` on it.

**Comment by DahmaniAdame** [comment]
Also, to get a meaningful result, we need to show on the logs an average loading time per font. Basically `$duration / $total_fonts` in addition to individual `$duration` and $total_fonts`.

**Pull request merged**
