### PR TITLE
Changed on_submit to pending

### LINKED ISSUE #6242: RUCSS submitted_at field is incorrect
Context
Follow-up on this https://github.com/wp-media/wp-rocket/issues/6204 which has a bug.
Submitted_at should be the timestamp at which we send the job to the SaaS. So, it should be set to null when putting the job in "to-submit" and set to current timestamp when putting the job "pending".

**Bug reproduction**
Start a lot of  RUCSS jobs from the plugin and limit the number of pending jobs to a small number. Some jobs will remain in to-submit for a while but they already have a submitted_at date.
**How to fix**
Set `submitted_at` to `null` in `create_new_job` and `reset_job`. Set it to current timestamp in `make_status_pending`

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description
Fix an issue with the on submit field that should be only updated when the request is sent to the SAAS.

Fixes #6242
## Type of change

*Please delete options that are not relevant.*

- Bug fix (non-breaking change which fixes an issue).

# Checklists

## Generic development checklist

- [ ] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@CrochetFeve0251 @MathieuLamiot 

The timestamp when the status is `to-submit` for the first time, i.e. a new job is created, is `0000-00-00 00:00:00` and that correctly changes to a valid timestamp when the status becomes `pending`.

In the case of a `408` error code, most likely with retries as well, we reset the status to `to-submit` but the timestamp isn't reset. It will be when the status is changed to `pending`.

Should this behavior change, i.e. should the timestamp be reset when changing the status to `to-submit`?

**Comment by MathieuLamiot** [comment]
Thanks for the detailed observation @vmanthos. I think the current behavior is good: in any case, we know when we sent a job for the last time. @CrochetFeve0251, do you agree with that?

**Comment by CrochetFeve0251** [comment]
> Thanks for the detailed observation @vmanthos. I think the current behavior is good: in any case, we know when we sent a job for the last time. @CrochetFeve0251, do you agree with that?

@MathieuLamiot I would keep it like that cause I think it would make it easier to debug it as we will track that job easier. What do you think @vmanthos ?

Otherwise resetting it isn't a big deal either.

**Review by vmanthos — APPROVED** [review]
The purpose is served so we shouldn't complicate this more. 😄

**Pull request merged**
