### PR TITLE
Fixes #4331 Prevent removing style tags inserted with inline JS when RUCSS is enabled

### LINKED ISSUE #4331: CSS rules added with inline JS script $("head").append are removed and not added to the Used CSS
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.3
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When _Remove Unused CSS_ option is enabled, the CSS rules that are added with inline JS script `$("head").append` are being removed from the source code and not added to the Used CSS. This leads to a broken layout.

**To Reproduce**

1. Add the script with CSS rules to the head as in example here:
```
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script type="text/javascript">
	(function($) {$("head").append("<style>.my-style{color:red;}</style>")})(jQuery);
</script>
```

2. Add an HTML element on a page like here:
`<h3 class="my-style">Hello world</h3>`
3. Check the page and make sure the style is applied.
4. Enable _Remove Unused CSS_ and wait until the process is completed and the used-css is generated.
5. Check the page in the incognito browser window - the style is not applied. 
It is removed, but not added to the Used CSS.
image
Screenshot: https://jmp.sh/7KLsoIj

Safelisting `.my-style` doesn't resolve the issue.

**Expected behavior**
CSS rules added with the inline script must be processed and added to the Used CSS the same way as with inline styles.

**Additional context**
Related ticket with notes: https://secure.helpscout.net/conversation/1620666496/292153/#thread-4732067758

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
## Description

This PR prevents the removal of style tags inserted with inline JS when RUCSS is enabled. It also cleans up the code where needed, notably in tests after the changes in 3.10

Fixes #4331

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Updated fixture to add an inline script inserting a style

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by iCaspar — APPROVED** [review]

**Comment by piotrbak** [comment]
@Tabrisrp In specific circumstances we can change the order of the styles. Will check if that's the case with reported tickets. For example:
```
<head>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<style>.my-style{color:black;}</style>

<script type="text/javascript">
	(function($) {$("head").append("<style>.my-style{color:red;}</style>")})(jQuery);
</script>
<title>Title</title>
```

It'll move the style after `<title>` tag to Used CSS but the style added by script will be added higher in the source.

**Comment by remyperona** [comment]
This seems very edge case though right?

**Comment by GeekPress** [comment]
Indeed, this seems to be an edge case. I don't know for you, on my side I never saw an inline script inserted before the title tag.

I guess the reason is becaise inline CSS are injected by using wp_head hook or wp_add_inline_script function. Both solutions  will mandatory insert the inline CSS after the title tag.

**Review by piotrbak — APPROVED** [review]
Good to go!
[testrail-report-281.pdf](https://github.com/wp-media/wp-rocket/files/7374761/testrail-report-281.pdf)

**Pull request merged**
