### PR TITLE
Update delay JS script

### LINKED ISSUE #3142: Delay JS - Links needs to be clicked twice on iOS / Safari
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 👍 
- Used the search feature to ensure that the bug hasn’t been reported before 👍 

**Describe the bug**
On Safari browser in iOS (and probably in others as per one customer), when delay JS is enabled links have to be clicked twice for them to work. This is even when:
- there aren't any keywords in the delay JS text area.
- link preloading is disabled.
- tested on latest version of iOS and Safari. 

**To Reproduce**
- Enable delay JS
- In an iPhone or in BrowserStack use Safari to visit the page.
- Scroll down (important) and then try to click on a link. Only the second click will register and open the page.

Note that if you click on a link which is in the viewport, i.e. without scrolling, it will open immediately.

**Expected behavior**
Links should load as normal and shouldn't need two clicks. 

**Screenshots**
Screencast: https://youtu.be/D1Pp45wLMhE (Thanks to @vmanthos for this and most of this report)

**Additional context**
Please see this note from Vasilis for some more insights - https://secure.helpscout.net/conversation/1283702266/195256/#thread-3691038967

Potentially related tickets: 
- https://secure.helpscout.net/conversation/1287155173/196167/
- https://secure.helpscout.net/conversation/1283702266/195256/ (Same ticket linked above)
- https://secure.helpscout.net/conversation/1277735438/193444/
- https://secure.helpscout.net/conversation/1277423432/193297/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### LINKED ISSUE #3934: Delay JS - the inline script prevents some JavaScript from firing
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.9`
- Used the search feature to ensure that the bug hasn’t been reported before - #3926 is probably related, but it's too specific.

**Describe the bug**

In some cases, despite excluding all files/inline JavaScript from **Delay JavaScript execution**, some JavaScript is not executed until there is interaction with the page.

**screencast:** https://youtu.be/ZuQj-KiNxNk

Removing the inline JavaScript we add in the `<head>` resolves the issue, of course.

**To Reproduce**

There isn't something solid currently. 

On a customer's website, the following `DOMContentLoaded` script didn't fire :
https://snippi.com/s/8emx5tk

**Expected behavior**

Non-delayed scripts should be executed.

**Additional context**

**Tickets:**
https://secure.helpscout.net/conversation/1497405310/259918/ - credentials to a staging site inside
https://secure.helpscout.net/conversation/1518901270/265435/

Probably related: #3926

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Update delay JS script with latests changes to fix currently known issues.

Fixes #3934

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Mai-Saad** [comment]
@Tabrisrp:  For 3142, still on iPhone  11 need to double click ( for internal post link and for the link which opens in new tab) while for iPad 12.9 pro need to double click to open links which will open in new tab. {using color meg theme, 1st demo site}.. can you please recheck. 

https://user-images.githubusercontent.com/76941962/120226560-b9c39000-c247-11eb-8380-a47d841b6db3.mp4

**Comment by remyperona** [comment]
@Mai-Saad this change is not guaranteed to fix all cases of double-click issue, we took that from user feedback, and it didn't work all the time (it did for some, it didn't for others).

Unfortunately it's the best we can do for now.

**Comment by piotrbak** [comment]
@Mai-Saad Just a quick question here. Did you use mouse scroll to scroll down the screen?

The event that's added to this PR is related to the screen touch event. 

Not sure if it'll be useful but here's the list of events and instructions that are being used in Safari:
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html

**Comment by Mai-Saad** [comment]
@piotrbak using the touchpad of a laptop
@Tabrisrp I can see 3934 fixed but for 3142 with the current theme I am using news portal all footer links need double click on iPhone and iPad so we have many factors here :
- Device
- OS
- Theme
- Link (internal/external)

**Comment by remyperona** [comment]
@Mai-Saad I updated the script with 2 touch events that we were not tracking before

**Comment by piotrbak** [comment]
@Mai-Saad Can you check if using the touchpad's scroll is loading the delayed JS at all in the console?

To test the solution, we need to make sure that it's loaded.

**Comment by Mai-Saad** [comment]
@Tabrisrp still some works and others not 
@piotrbak it's loading for web on laptops

**Comment by remyperona** [comment]
Removed the link to issue #3142 since it's not fixing everything, we'll see how it goes.

**Review by Mai-Saad — APPROVED** [review]
Fixed 3934 (tested on templates of client sites + simple event template "on local and old labs")

**Pull request merged**
