### PR TITLE
Update API endpoints to new domain

### PR DESCRIPTION
**Pull request by remyperona**
# Description

### User documentation

No direct impact for users

### Technical documentation

Update the various endpoints to the new API domain. Also remove the usage of global constants in favour of class constants or hardcoded value.

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

### CODE REVIEW

**Review by Miraeld — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Tabrisrp Thanks for the PR. During exploratory testing, can see that X (closure) of CDN modal is not working. can you please check :pray: (working on 3.16.2.1)

[screen-capture (98).webm](https://github.com/user-attachments/assets/c5c0feec-4dd9-47af-acf5-1deab809fa6d)

**Comment by remyperona** [comment]
The video is not working for me

**Comment by piotrbak** [comment]
@Tabrisrp It works for me, what about this URL?
https://private-user-images.githubusercontent.com/76941962/351257203-c5c0feec-4dd9-47af-acf5-1deab809fa6d.webm?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NDA4NzMsIm5iZiI6MTcyMTc0MDU3MywicGF0aCI6Ii83Njk0MTk2Mi8zNTEyNTcyMDMtYzVjMGZlZWMtNGRkOS00N2FmLWFjZjUtMWRlYWI4MDlmYTZkLndlYm0_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxMzE2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjdkZWRiYmM3YWRhYzA3NjY1YmVlYmZkNTNkYzA0NTU5ZjYwZTRhNTcyMWFhZTNmNTI2ODFjNmNkNmNlN2M0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O1S-6FUzSwhCM8lyXbHJXQbtNCszDpebdy7b1f9JfYE

@Mai-Saad Is this a regression when comparing to the trunk?

**Comment by remyperona** [comment]
No I still can't display it (on Firefox) Error is mime type not handled.

There was no change in term of modal functionality on this PR, only the API URL, which is correctly working.

**Review by Mai-Saad — APPROVED** [review]
CDN Modal closure is working now :tada:
[testrail-report-622.pdf](https://github.com/user-attachments/files/16349836/testrail-report-622.pdf)
If nothing is needed for Codacy coverage then we can merge

**Pull request merged**
