### PR TITLE
Closes #795 - Added a dummy file named lazyload-

### LINKED ISSUE #795: Partial LazyLoad Reference Causes 404 error in Google Search Console
Google search console for some reason picks up the partial file reference from our LazyLoad JS and throws a 404 error saying the following file is missing:

`http://example.com/wp-content/plugins/wp-rocket/inc/front/js/lazyload-`

This is a false positive and can be ignored. But we get tickets regarding this and it bothers some of our users. 

Possible solution - Include a dummy file with the file name. Worked for a user. 

Related tickets: 

- https://secure.helpscout.net/conversation/518136970/59429?folderId=1724284
- https://secure.helpscout.net/conversation/576537433/67559?folderId=273761

### PR DESCRIPTION
**Pull request by arunbasillal**
so that Google Search Console doesn't show the 404 error.

### CODE REVIEW

**Comment by Tabrisrp** [comment]
I'm not a fan of creating a false file for this

**Comment by arunbasillal** [comment]
@Tabrisrp maybe this? https://github.com/wp-media/wp-rocket/issues/795#issuecomment-385900491

**Comment by Tabrisrp** [comment]
You can update this PR with the changes in #795 and we'll include it in 3.1.2

**Comment by Tabrisrp** [comment]
Fixed by https://github.com/wp-media/wp-rocket/commit/d6d442385e140d088d70d674e07e83a3ea666641

**Pull request closed without merging**
