### PR TITLE
Closes #6137: remove unnecessary exclusions css background images' lazyload

### LINKED ISSUE #6137: Lazyload for CSS background images unnecessary exclusions are in WP Rocket's code
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.15`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

For the JavaScript code handling the lazyload of CSS background images, we added exclusions from the JavaScript-handling features in WP Rocket's core:
https://github.com/wp-media/wp-rocket/blob/6417d8f8ce6d465c9430934fcbb60b3fb8e45567/inc/Engine/Media/Lazyload/CSS/Subscriber.php#L147-L149

Those should have been added in the back end (dynamic lists) when we were using the JavaScript file.

Currently, after changing the file to an inline script, we only need to keep the Delay JS Execution exclusion which has already been added to the back end. (Kudos to @Mai-Saad for finding that the inline script was delayed).

**To Reproduce**
N/A

**Expected behavior**

We need to remove the part of the code related to the exclusions.

**Screenshots**
N/A

**Additional context**
N/A

**Acceptance Criteria (for WP Media team use only)**
- Both Lazy Load scripts are excluded from Delay JS, Defer JS and Combine JS using the backend 
- The scripts are not excluded within our codebase
- No JS errors in the console error when activating each feature together with LazyLoad Background CSS Images

### PR DESCRIPTION
**Pull request by Miraeld**
## Description

We deleted the unnecessary filters for css exclusions for background images' lazyload. 
We also deleted linked tests.

Fixes #6137 

## Type of change

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

### CODE REVIEW

**Review by wordpressfan — APPROVED** [review]
Nice job.

I don't think that we need to deprecate those public methods as it's not used by any of our helpers (I checked that)

Also just an explanation, in backend we exclude `rocket_lazyload_css_data` which is a keyword that is contained inside `#rocket_lazyload_css-js-after` script, so we are fine.

**Review by Mai-Saad — APPROVED** [review]
Working as expected
[testrail-report-532.pdf](https://github.com/wp-media/wp-rocket/files/12870824/testrail-report-532.pdf)
Note (problems already on 3.15.2)
1- Images using this markup will be removed from the page  => agreed as edge case 
`<style>.test-new-class{background-image: url("https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/test_internal2.jpg");}.test-new-class{background-image: url("/wp-content/rocket-test-data/images/wp-rocket.svg)");} </style>`
Thanks to @vmanthos investigations 

> The syntax of the following is incorrect:
background-image: url("/wp-content/rocket-test-data/images/wp-rocket.svg)");
There is a ) before "  and that results in WP Rocket picking up the whole thing until the last parenthesis.

2- Problem when LL BGI is enabled while WPML is on (under investigation to gather reproducible steps)(happening with CSS absolute URL files)
- Using rocketlabs env, if we have WPML activated on domain base setup, then install /activate WPR, then cache LL BG template, then enable LL BG I then access the sub language FE and hardrefresh => We will have console error for some images 
Screenshot from 2023-10-12 09-03-03
- Console error when trying to switch language in the following steps: 
1- WPML is domain base
2- cache the page in both languages
3- WPML changed to a directory
4- access the main language page and click on language switch to sub-lang
Screenshot from 2023-10-11 16-25-12
**if we clear the whole cache then repeat step 4 it will work fine**

**Comment by vmanthos** [comment]
@Mai-Saad I was able to reproduce the issue on rocketlabsqa.ovh. However, clearing the cache won't fix it.

For CSS files processed by the lazyload for background CSS images feature, we set the wrong path, resulting in `error 404` for those files. This is because we are adding the language code before the domain name. 

For example:
https://ar.rocketlabsqa.ovh/wp-content/cache/background-css/ar.ar.rocketlabsqa.ovh/wp-content/cache/min/1/wp-content/rocket-test-data/styles/lazyload_css_background_images.css?ver=1697180904&wpr_t=1697180904

has an extra `ar.` before the TLD `ar.rocketlabsqa.ovh`.

The URL should be:

https://ar.rocketlabsqa.ovh/wp-content/cache/background-css/ar.rocketlabsqa.ovh/wp-content/cache/min/1/wp-content/rocket-test-data/styles/lazyload_css_background_images.css?ver=1697180904&wpr_t=1697180904
https://ar.rocketlabsqa.ovh/wp-content/cache/background-css/ar.ar.rocketlabsqa.ovh/

**Update**

I believe this should be on a new GitHub issue.

**Comment by Mai-Saad** [comment]
@vmanthos Thanks for the confirmation, added GH here https://github.com/wp-media/wp-rocket/issues/6224

>  However, clearing the cache won't fix it.

This was for the second scenario, related to `xdomaindata` console error when switching language

**Pull request merged**
