### PR TITLE
rocket_realpath() fix

### PR DESCRIPTION
**Pull request by xbuzz**
See #728

### CODE REVIEW

**Comment by Tabrisrp** [comment]
Thank you for the PR, with which setups did you test this change?

We need to be sure it works if:
- home and site URLs are the same
- home and site URLs are different
- home and site URLs use a subdirectory
- content folder is outside of WP directory

**Comment by xbuzz** [comment]
@Tabrisrp Not a problem. I have tested all of above scenarios on both my environment as well as a fresh vanilla WordPress installation. Feel free to run any additional tests you'd like. Let me know if you need anything else. Cheers! 🍻

**Comment by Tabrisrp** [comment]
Great thank you, we're currently in the process of internal testing the 2.11.5, I'll add this to the new beta

**Comment by xbuzz** [comment]
Excellent. Looking forward to the release. Keep up the good work.

**Pull request merged**
