### PR TITLE
Closes: #6369 Automate delayjs script update

### LINKED ISSUE #6369: Automate the DelayJS Script Update on plugin
**Is your feature request related to a problem? Please describe.**
Whenever we need to update the delayJS on the plugin to a new version, there's quite some manual process involved which creates just enough room for mistakes.
- First we manually copy the unminified script from the branch.
- Paste it in an online tool to minifiy it
- Copy it and update the script on plugin.

**Describe the solution you'd like**
What we can do is to automate this process by running a command from the CLI.
I propose we use a bash script then pass the branch name to be used as an argument
e.g `sudo sh delayjs.sh branch-name`

Breakdown:
- First, We will update the gulp.js file to add specific task to build minified delayjs
- Bash Content process
   - Clone the delayjs repo to a temp dir
   - cd into temp dir
   - Switch to the branch passed as argument
   - Copy the delayjs content into the delayjs file in plugin
   - Run the new gulp task to build unminified delayjs script
   - Delete temp dir

**Describe alternatives you've considered**
Another alternative is to build a minified version of the script on the delayjs branch maybe with gulp, this cut off the gulp step we automate.

**Additional context**
We can also consider updating the related test automatically since it's also just about updating the script in the fixture [here](https://github.com/wp-media/wp-rocket/blob/f471c32f7efda54e7b0ff69ffd2a0acd808a314a/tests/Fixtures/inc/Engine/Optimization/DelayJS/Subscriber/addDelayJsScript.php#L10)

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

Automates the delay js script update.

Fixes #6369 

## Type of change

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

*Please describe in this section if there is any change to the groomed solution, and why.*

# Checklists

## Generic development checklist

- [ ] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

### CODE REVIEW

**Review by Miraeld — APPROVED** [review]

**Comment by remyperona** [comment]
I think this could be taken further, with changes on the delay JS repo too, with the following workflow:
- When an update of the script is done, tag a release on the delay JS repo
- With a Github action: 
1. get the script
2. minify it
3. commit it to a long-lived, protected branch on WP Rocket repo

That way, when we want to update the script on WPR, the remaining task is to create a new PR from this branch to the develop.

**Comment by MathieuLamiot** [comment]
@Tabrisrp Thank you for the feedback and ideas.
@jeawhanlee My understanding is that the current PR is useful already, and could be further enhanced with @Tabrisrp's approach. Is that correct? If yes, then we should:
1 - Move forward with this PR
2 - Open a new GH issue for the next steps suggested above (and possibly deal with it during the cooldown if the timeframe allows it).

**Comment by jeawhanlee** [comment]
@MathieuLamiot Yes! The current PR is already useful and could be further enhanced with @Tabrisrp approach.
Should we leave @gmetais for this as this repo seem to be maintained by him or we can do this ourselves with a PR

**Comment by MathieuLamiot** [comment]
We can do it ourselves, and ask for his review to confirm ;)

**Comment by jeawhanlee** [comment]
@wp-media/qa-team To test this, Run `bash ./bin/delayjs.sh` followed by the name of the delayjs updated branch.
example: `bash ./bin/delayjs.sh develop`

**Comment by jeawhanlee** [comment]
@MathieuLamiot I linked a new issue [here](https://github.com/wp-media/delay-javascript-loading/issues/112)

**Comment by Mai-Saad** [comment]
Note:
- The bash command will update the script as per this test https://wpmediaqa.testrail.io/index.php?/tests/view/41361 
=> This is working but now the .map file is generated with the bash command (that file was not on the trunk)
=> The current generated script not starting by `class RocketLazyLoadScripts` as the one on the trunk, ok @piotrbak?
=> Smoke test that scripts are delayed with the new script enabled without error is fine
- Related test plan https://wpmediaqa.testrail.io/index.php?/runs/view/813&group_by=cases:section_id&group_order=asc
- For test execution of NRT (any test other than https://wpmediaqa.testrail.io/index.php?/tests/view/41361) , we need to manually add the newly generated script inside assets/js/lazyload-scripts.min.js then run the NRT.

**Comment by jeawhanlee** [comment]
@Mai-Saad  I disabled the generation of .map files with the latest commit.

**Comment by jeawhanlee** [comment]
Closing in favor of [this](https://github.com/wp-media/delay-javascript-loading/pull/113)

**Pull request closed without merging**
