### PR TITLE
Fixes #6453 Don't generate sourcemap for lazyload CSS min file

### LINKED ISSUE #6453: 404 error in console on Safari when LazyLoad for CSS BG Images is active
**Describe the bug**
When LazyLoad for CSS Background Images is active, Safari shows a 404 error in the console for: 
`lazyload-css.min.js.map`

It doesn't seem to break anything, but we shouldn't cause a console error.

**To Reproduce**
1. Enable  LazyLoad for CSS Background Images
2. Visit a page in Safari
3. Check the console.
Tested on WPR 3.15.9

**Expected behavior**
No 404.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://jmp.sh/XJ9lfXO1)

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

### PR DESCRIPTION
**Pull request by remyperona**
# Description

Fixes #6453

Remove the reference to the sourcemap file for the lazyload CSS min file since the file is inlined directly in the HTML.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Detailed scenario

Detailed scenario is available at #6453 

### Documentation

Changed the setting for the gulp command to not generate the sourcemap file for the lazyload CSS.

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I did not introduce unnecessary complexity.

### CODE REVIEW

**Review by Khadreal — APPROVED** [review]

**Comment by Mai-Saad** [comment]
For test, please :
- Provide screenshot on safari with the fix
- Provide test report for LLBG on e2e

**Comment by remyperona** [comment]
console
ll-css

**Comment by MathieuLamiot** [comment]
@wp-media/qa-team shouldn't we remove the NoQA tag based on @Mai-Saad's comment above?

**Comment by Miraeld** [comment]
@Mai-Saad , Confirming it's working as expected. 
Here are two screenshot, one before and one after changes. 

Before:
Screenshot 2024-10-04 at 09 19 51


After:
Screenshot 2024-10-04 at 09 21 34


Works as expected.

**Comment by Mai-Saad** [comment]
e2e results (using e2e branch `enhancement/137-vr-on-template
`) and the PR zip (these are 3rd trial results, in all trials VR was green but some test(s) fail due to DB errors in debug.log)
[cucumber-report.json](https://github.com/user-attachments/files/17255139/cucumber-report.json)

Screenshot from 2024-10-04 10-53-49
Screenshot from 2024-10-04 10-53-58
Screenshot from 2024-10-04 10-54-02
Screenshot from 2024-10-04 10-54-08
Screenshot from 2024-10-04 10-54-12
Screenshot from 2024-10-04 10-54-17

**Pull request merged**
