### PR TITLE
Closes #3068 Display renewal notifications in the plugin

### LINKED ISSUE #3068: Be able to renew from the plugin
## What are we proposing to do? 

With this enhancement, WP Rocket users will be notified directly from the plugin that their license is expired or about to expire. We will display a link enabling them to renew directly by clicking on it. They will be redirected to our checkout page. No payment will proceed from the customer website directly.

<p></p>

More info:

<https://docs.google.com/document/d/1oqArI9u1U6frFsFCBwPKEq5WnqahPktpPcDBaCAhVu4/edit#heading=h.fe02x22oxiz3>

<p></p>

### PR DESCRIPTION
**Pull request by Tabrisrp**
Closes #3068 

This PR introduces 2 notifications banner on the WP Rocket settings dashboard, to invite the user to renew their license.

### Acceptance criteria
There is 2 different type of banners:
- One when the license is expired
- One when the license expires in less than 30 days
- No banner displayed if the license is not expired and expires in more than 30 days
- No banner displayed for white label

#### License expired
- The banner is dismissible (for one month, uses a transient)
- The percentage and price depend on the time since expiration, and if the user is "granfathered" or not:
    - License expired since more than 90 days: 20% off, and expired price
    - License expired since less than 90 days: 30% off + price if not grandfathered, 50% + price if grandfathered
- Renew new is a direct link to the renewal on the website

#### License expiring soon
- The banner is not dismissible
- The banner doesn't display if auto-renewal is enabled for the user
- The countdown displays the time until expiration
- The percentage and price depend on if the user is "granfathered" or not:
    - 30% off + price if not grandfathered
    - 50% + price if grandfathered
- Renew new is a direct link to the renewal on the website

### CODE REVIEW

**Comment by piotrbak** [comment]
@Tabrisrp When the countdown reaches 0, the following is displayed:
image

Can we somehow prevent it from happening? Maybe refresh the page?

**Comment by Tabrisrp** [comment]
I added a check to stop the countdown if it reaches zero, can you re-test?

**Comment by piotrbak** [comment]
@Tabrisrp The QA is done, please find the problems below:

1. When there's no connection with our API the `Expired` banner is displayed no matter what is the current expiration date. It also contains wrong data + wrong URL:
image

2. When the user is using 2 Single licenses:
-When the license is expired for more than 90 days (20% of discount), we're getting the wrong price inside the banner ($39.2, when going to the checkout it's $24.50)

3. When coming back to the dashboard after clicking on Renew Now, the button is black, not readable:
image

4. Shouldn't we display $49.50 instead of $49.5? 😁

5. Do we have any `auto-renewal` account that I can use for testing purposes?

**Comment by Tabrisrp** [comment]
1. This is expected, if we can't communicate with the API the default fallback is going to use zero values pretty much everywhere.
2. This is most likely an issue on the website side, because the correct value is the one displayed on the plugin. cc @GeekPress 
3. will fix that in the CSS
4. will fix this too
5. @GeekPress can we enable auto-renew somewhere on a specific account?

**Comment by Tabrisrp** [comment]
@piotrbak 3 and 4 are fixed

**Comment by piotrbak** [comment]
@Tabrisrp 
1. Wouldn't it be good to hide it if that happens? Is this possible?

**Comment by Tabrisrp** [comment]
I pushed a change that should take care of that

**Comment by GeekPress** [comment]
> When the user is using 2 Single licenses:
> -When the license is expired for more than 90 days (20% of discount), we're getting the wrong price inside the banner ($39.2, when going to the checkout it's $24.50)

@piotrbak Can you tell me with which account you did your test?

> @GeekPress can we enable auto-renew somewhere on a specific account?

The only solution is to go into the database and update your user meta `_auto_renew ` to 1

**Comment by piotrbak** [comment]
@GeekPress I used my own license, switched `Account:` to 2 in the admin panel to achieve that. Isn't that a good approach?

@Tabrisrp Can you do that for my account?

**Comment by GeekPress** [comment]
@piotrbak Ok thanks. The difference between the website and the plugin isn't normal. You shouldn't get $24.50 on the website if you are expired more than 90 days ago.

I will check if there is something wrong on the site side.

**Comment by GeekPress** [comment]
@piotrbak @Tabrisrp I confirm it was a bug from the website. I'm going to correct it!

**Comment by GeekPress** [comment]
@piotrbak It's fixed. You should have the right price on the website now.

**Comment by piotrbak** [comment]
@Tabrisrp Everything worked as expected. The only thing we need to do more is to add a redirect similar to the one @GeekPress added for the `Upgrade`. I'm getting the same `The link you followed has expired` when I'm not logged in to the `wp-rocket.me` website.

[testrail-report-53.pdf](https://github.com/wp-media/wp-rocket/files/5447748/testrail-report-53.pdf)

**Pull request merged**
