### PR TITLE
add new filter rocket_rucss_skip_styles_with_attr to skip styles with specific attributes

### LINKED ISSUE #5283: RUCSS compatibility with Mandatory Cookies
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.4.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When RUCSS is used on website using `dynamic cookies`, SaaS is generating the Used CSS against the website without considering the `dynamic cookie`. 

This will result in generating a slight excess in style in most cases, which can be tolerated, with a risk of breaking the website in some of them. 

An example where this would be problematic: 

The [Real Cookie Banner](https://wordpress.org/plugins/real-cookie-banner/) plugin. It has a setting that blurs the content of the page after showing the popup banner. 

It results in adding the following CSS as part of the Used CSS: 

```
body > :not(#a90a3e813-caa6-4718-aec5-8492f0dae523,.rcb-customize-banner-container,#bkBgScrollPrevent,#trp_ald_modal_container) { filter: blur(2px); }#bkBgKeepPos > :not(#a90a3e813-caa6-4718-aec5-8492f0dae523,.rcb-customize-banner-container,#bkBgScrollPrevent,#trp_ald_modal_container) { filter: blur(2px); }
```

This portion will keep the content blurred on the cached page.

The `rocket_usedcss_content` was used to remove the `filter` content to allow RUCSS to be used on the website. 

**To Reproduce**
1. Enable the Real Cookie Banner and set the content to be blurred
2. Add the following mandatory cookie `real_cookie_banner-blog:1`
3. Use RUCSS

**Expected behavior**
Ideally, in this case, we should have sent the request to SaaS to add the following cookie `real_cookie_banner-blog:1` when generating the Used CSS from the website. 

The information about the cookie could be found on the `wp-rocket-config` file on the following variable `$rocket_cache_mandatory_cookies`.

Alternatively, we can build a compatibility file covering a case by case by adjusting the Used CSS if needed. That might turn up to be high maintenance over time.

**Screenshots**
N/A

**Additional context**
Ticket -  https://secure.helpscout.net/conversation/1956114542/357420?folderId=3864735

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by mostafa-hisham**
## Description

create new filter `rocket_rucss_skip_styles_with_attr` that sends specific attributes of styles to be skipped by RUCSS

Fixes #5283 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No
## How Has This Been Tested?

- [x] Unit test

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by CrochetFeve0251 — APPROVED** [review]

**Comment by piotrbak** [comment]
@mostafa-hisham Could you check the expected markup behaviours/changes here, so the QA team is perfectly aligned? It would be also great if you could share the example of the filter usage, so QA have it right away. Thank you 🙏 

Adding the following to request:
`config[skip_attr]="skip_me"`

With the following HTML:
```
<style skip_me="1" id="ssss">
div {display:none;}
</style>
```

Will cause:
`div {display:none;}`

Not being added to the Used CSS, despite the fact that `div` is present in HTML, right?

**Review by remyperona — CHANGES_REQUESTED** [review]
Small code standard issue

**Comment by vmanthos** [comment]
@mostafa-hisham Not adding CSS to the used CSS from `<style>` and `<link>` elements using attributes passed to `rocket_rucss_skip_styles_with_attr` works fine. :+1: 

We need to safeguard the filter from incorrect values, e.g.:
* `null`
* "string"
* booleans
* `int`

These will result in adding the meant-to-skip CSS to the used CSS.

Another scenario is passing wildcards to the filter, e.g. `skip_\(.*\)`. This will result in an `error 500` from the SaaS:
```javascript
Evaluation failed: DOMException: Failed to execute 'querySelectorAll' on 'Document': 'style:not([s]):not([k]):not([i]):not([p]):not([_]):not([\]):not([(]):not([.]):not([*]):not([\]):not([)]), link[rel~="stylesheet"]:not([s]):not([k]):not([i]):not([p]):not([_]):not([\]):not([(]):not([.]):not([*]):not([\]):not([)])' is not a valid selector.
    at pptr://__puppeteer_evaluation_script__:6:24
```

Can you please look into this? :pray:

**Comment by vmanthos** [comment]
Continuing the exploratory testing on this one, I found that the `rocket_rucss_skip_styles_with_attr` filter that's introduced in this PR, can be overridden if the same attributes that are meant to be skipped are added to the `rocket_rucss_inline_atts_exclusions` for `<style>` elements, and to the `rocket_rucss_external_exclusions` filter for `<link>` elements.

@piotrbak Should we prioritize blocking the attributes that are meant to be skipped when the other two filters are used as well? Or should we leave this as it is?

**Comment by piotrbak** [comment]
@vmanthos That's okay 🆗 We need to be clear about this in our documentation and also with Support Team.

**Comment by piotrbak** [comment]
@vmanthos wildcards won't be used here.

It's not ready to QA on the SaaS part so far though.

**Comment by vmanthos** [comment]
This is working as expected! :+1: 

**NOTES**
1. Wildcards aren't supported on the SaaS.
2. The `rocket_rucss_skip_styles_with_attr` filter can be overridden if the same attributes that are meant to be skipped are added to the `rocket_rucss_inline_atts_exclusions` for `<style>` elements, and to the `rocket_rucss_external_exclusions` filter for `<link>` elements. => needs documentation
3. A fatal error:
```PHP
[19-Jun-2023 13:06:12 UTC] PHP Warning:  Undefined array key "jobId" in /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 232
[19-Jun-2023 13:06:12 UTC] PHP Warning:  Undefined array key "queueName" in /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 233
[19-Jun-2023 13:06:12 UTC] PHP Fatal error:  Uncaught TypeError: WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS::create_new_job(): Argument #2 ($job_id) must be of type string, null given, called in /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 231 and defined in /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php:164
Stack trace:
#0 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(231): WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS->create_new_job()
#1 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Frontend/Subscriber.php(49): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->treeshake()
#2 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Optimization\RUCSS\Frontend\Subscriber->treeshake()
#3 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#4 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Buffer/Optimization.php(100): apply_filters()
#5 [internal function]: WP_Rocket\Engine\Optimization\Buffer\Optimization->maybe_process_buffer()
#6 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/functions.php(5309): ob_end_flush()
#7 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(308): wp_ob_end_flush_all()
#8 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#9 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#10 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/load.php(1144): do_action()
#11 [internal function]: shutdown_action_hook()
#12 {main}
  thrown in /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php on line 164
```
will be caused if the SaaS doesn't return values here:
https://github.com/wp-media/wp-rocket/blob/23f372115e7db9bf366a8e100e97fac469cdd3c6/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L232-L233

According to @mostafa-hisham, this should never happen; nevertheless, we can safeguard and log an error.
@piotrbak I'll create a new GitHub issue about this.

**Review by vmanthos — APPROVED** [review]

**Comment by piotrbak** [comment]
@mostafa-hisham When could we push the SaaS part of this issue to trunk?

**Comment by mostafa-hisham** [comment]
the pr need to be approved first

**Pull request merged**
