### PR TITLE
Fixes #4868 Apply CDN to used CSS on output instead of on saving

### LINKED ISSUE #4868: CDN exclusions are not reflected in Used CSS
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using CDN and RUCSS, CDN exclusions are not taken into the consideration.

**To Reproduce**
1. Enable CDN for all files
2. Enable RUCSS
3. Exclude URL from CDN (URL existing in used CSS) i.e /test.svg
4. visit the page and check used CSS

**Expected behavior**
Excluded URL not rewritten to the CNAME

**Additional**
Moving it from private repo:
https://github.com/wp-media/nodejs-treeshaker/issues/46

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Solves a problem where CDN exclusions are not taken in consideration when using RUCSS.
To solve this problem the filter `rocket_usedcss_content` has been moved from `check_job_status` to `get_used_css_markup`

Fixes #4868 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Automated tests

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Review by remyperona — APPROVED** [review]

**Comment by remyperona** [comment]
One thing to fix in the test for PHP 8
```
TypeError: error_reporting(): Argument #1 ($error_level) must be of type ?int, string given

/tests/Unit/inc/Engine/Optimization/RUCSS/Controller/UsedCSS/treeshake.php:31
```

**Comment by CrochetFeve0251** [comment]
@Tabrisrp this is the PR where we got the problem with mockery. That function call is here to prevent the error to raise but we agreed with @engahmeds3ed that wasn't clean.

**Comment by remyperona** [comment]
If this is the solution for now it's fine, but you are passing a string to `error_reporting` and it expects `int` value, so removing the quotes should be enough to prevent this error from showing on PHP 8

**Review by Mai-Saad — APPROVED** [review]
Working as expected

**Comment by remyperona** [comment]
I'd suggest to skip the test for now, as even with the updated test suite it's still not passing. The issue is coming from the dependency, so we can't really change anything at that time.

**Pull request merged**
