### PR TITLE
Closes #6312: Exclude youtube thumbnail from lazyload

### LINKED ISSUE #6312: It's not possible to exclude the YouTube thumbnail from LazyLoad
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Yes
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
It's not possible to exclude the YouTube thumbnail (applied with the **Replace YouTube iframe with preview image** feature) from the **LazyLoad for images**.

- This is not how the `LazyLoad` and `Excluded images or iframes` should work. 
- But it's really problematic when the YouTube thumbnail is the LCP element, because the LazyLoad triggers the `Preload Largest Contentful Paint image` audit of PageSpeed.

**To Reproduce**
1. Create a page with a YouTube video on the viewport.
2. Enable LazyLoad, LazyLoad for iframes and videos and Replace YouTube iframe with preview image features.
3. Try to exclude the thumbnail using the Excluded images or iframes box.
4. The thumbnail is still lazyloaded, even if you use `i.ytimg.com`, `hqdefault.jpg`.

In customer's case, the thumbnail is the LCP element and the is triggered.
**Screenshot:** https://jmp.sh/BCwtJlHz
**PageSpeed report:** https://pagespeed.web.dev/analysis/https-getgoally-com-blog-neurodiversopedia-neurotypical-vs-neurodivergent/e3l1k327s9?utm_source=psi&utm_medium=redirect&form_factor=mobile
**URL:** https://getgoally.com/blog/neurodiversopedia/neurotypical-vs-neurodivergent/
**Ticket:** https://secure.helpscout.net/conversation/2441540551/461496?folderId=2675957

**Expected behavior**
The thumbnail generated with the Replace YouTube iframe with preview image feature should be exclude-able from LazyLoad.

**Additional context**
**Slack thread:** https://wp-media.slack.com/archives/C43T1AYMQ/p1701812279936699

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

This PR excludes youtube thumbnail from lazyload

Fixes #6312

## Type of change
- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?
No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [x] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

### CODE REVIEW

**Comment by jeawhanlee** [comment]
For CR, I Backported PR from https://github.com/wp-media/rocket-lazyload-common/pull/116

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@jeawhanlee Thanks for the PR. Please find exploratory test notes below.
1- When tried to exclude `https://i.ytimg.com/vi/8bUSQjuNedI/hqdefault.jpg` from UI on this page https://new.rocketlabsqa.ovh/video-testing/ (LL image , LL video and preview image are already enabled), the image wasnot excluded from LL
2- If we set the filter to return `Null,` we will have this warning
`[19-Jan-2024 15:13:01 UTC] PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Iframe.php on line 252`
Can you please check :pray:

**Comment by jeawhanlee** [comment]
> When tried to exclude https://i.ytimg.com/vi/8bUSQjuNedI/hqdefault.jpg from UI on this page https://new.rocketlabsqa.ovh/video-testing/ (LL image , LL video and preview image are already enabled), the image wasnot excluded from LL

@Mai-Saad I was checking this but if we support exclusion from the UI, it would exclude the YT iframe from being lazyloaded and we don't want that.
@piotrbak Do we add another UI for this or just leave this as a filter as it is.

**Comment by piotrbak** [comment]
@jeawhanlee Just to be sure, if we'd add `i.ytimg.com/vi/8bUSQjuNedI/hqdefault.jpg` to the UI we'd exclude the iframe? 🤔
 
Iframe doesn't have `hqdefault.jpg` in the source

**Comment by remyperona** [comment]
That exclusion wouldn't do anything. At the time we can manage the exclusion, the thumbnail is not created yet in the page (it's dynamically generated with JS, based on the YT ID).

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@jeawhanlee Thanks for the update. Now we can exclude thumbnail image using UI or filter. However, we need to guard the filter from invalid values as now if set to null, we will have this error. can you please check :pray: 
```
[08-Feb-2024 17:54:42 UTC] PHP Fatal error:  Uncaught TypeError: WP_Rocket\Engine\Media\Lazyload\Subscriber::add_exclusions(): Argument #1 ($exclusions) must be of type array, null given, called in /var/www/newer.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php on line 324 and defined in /var/www/newer.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php:459
Stack trace:
#0 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Media\Lazyload\Subscriber->add_exclusions()
#1 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Assets.php(275): apply_filters()
#3 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Assets.php(209): WP_Rocket\Dependencies\RocketLazyload\Assets->getYoutubeThumbnailScript()
#4 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php(254): WP_Rocket\Dependencies\RocketLazyload\Assets->insertYoutubeThumbnailScript()
#5 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Media\Lazyload\Subscriber->insert_youtube_thumbnail_script()
#6 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#7 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-includes/general-template.php(3068): do_action()
#9 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-content/themes/twentytwentyone/footer.php(78): wp_footer()
#10 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-includes/template.php(790): require_once('...')
#11 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-includes/template.php(725): load_template()
#12 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-includes/general-template.php(92): locate_template()
#13 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-content/themes/twentytwentyone/archive.php(38): get_footer()
#14 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-includes/template-loader.php(106): include('...')
#15 /var/www/newer.rocketlabsqa.ovh/htdocs/wp-blog-header.php(19): require_once('...')
#16 /var/www/newer.rocketlabsqa.ovh/htdocs/index.php(17): require('...')
#17 {main}
  thrown in /var/www/newer.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php on line 459
```

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
Related test plan https://wpmediaqa.testrail.io/index.php?/runs/view/814

**Comment by hanna-meda** [comment]
Relating issue found while testing this: https://github.com/wp-media/wp-rocket/issues/6451

**Review by hanna-meda — APPROVED** [review]
[testrail-report-573.pdf](https://github.com/wp-media/wp-rocket/files/14358978/testrail-report-573.pdf)

**Pull request merged**
