### PR TITLE
Closes #5640: fix translatePress compatibility

### LINKED ISSUE #5640: RUCSS wrong home_url detection with TranslatePress enabled
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.12.3.3
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
RUCSS is failing for all language homepages when TranslatePress plugin is used.
This is the same issue as shared here: https://github.com/wp-media/wp-rocket/issues/5065

The same solution provided by Ahmed resolves the issue:
https://github.com/wp-media/wp-rocket/issues/5065#issuecomment-1133745028

**To Reproduce**

1. Install and activate [TranslatePress](https://wordpress.org/plugins/translatepress-multilingual/) plugin
2. Add a language with a slug and save settings:
image
3. Enable Remove Unused CSS and visit URL like https://example.com/fr/ in the Incognito browser.
4. Wait for RUCSS to process this page.
5. The generation will fail at all attempts with `400 Bad json` error.

**Expected behavior**
Used CSS should be generated with no issues for language homepages.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/2102001423/390024/
Slack: https://wp-media.slack.com/archives/C029G1B5HD2/p1671727809871749

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by Miraeld**
## Description

I've done some refactor to improve the code. And also I've implemented the fixes requested.

Fixes #5640 

## Type of change

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

### CODE REVIEW

**Review by CrochetFeve0251 — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Miraeld Thanks for the PR. Can still see the 400 error for home/fr on https://new.rocketlabsqa.ovh/ while permalinks with/without` /` . Can you please check :pray: 
Screenshot from 2023-10-16 11-46-49

**Comment by CrochetFeve0251** [comment]
@MathieuLamiot for it looks like the code is not working on the call we are fetching the response from the request.
My solution for this would be to add the status from the page (homepage or other ) inside the `wp_wpr_rucss_used_css` table.

Then we would just have to fetch that value from the table to know which queue we need to fetch the result from without having a bad JSON issue.

**Comment by MathieuLamiot** [comment]
@CrochetFeve0251 Sounds like a good approach to me 👍 
Let's compute the is_home at submission time and store it for later use.

**Comment by Mai-Saad** [comment]
Closing this one in favour of https://github.com/wp-media/wp-rocket/pull/6266

**Pull request closed without merging**
