### PR TITLE
Closes #5834 Update One.com detection

### LINKED ISSUE #5834: Change the way how we recognize One.com hosting
**Is your feature request related to a problem? Please describe.**
All hostings from the group will be using the same variable in the `$_SERVER` array.

Instead of looking for this variable:
https://github.com/wp-media/wp-rocket/blob/2f768f904f3b3be3ac44ce56eddd9719745abe75/inc/ThirdParty/Hostings/HostResolver.php#L34

We'll look for `$_SERVER['GROUPONE_BRAND_NAME']`, and for One.com its value will be `one.com`.

Please note that in the next minor versions we'll add another hosting from the group, its `$_SERVER['GROUPONE_BRAND_NAME']` value will be different.

**Describe the solution you'd like**
We need to check for existence of this variable in `$_SERVER` array and then decide on which hosting we're based on the value.

### PR DESCRIPTION
**Pull request by remyperona**
Update One.com hosting detection in the HostResolver

Fixes #5834

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by CrochetFeve0251 — APPROVED** [review]

**Comment by vmanthos** [comment]
@piotrbak Will the value of `$_SERVER['GROUPONE_BRAND_NAME']` always `one.com` in lowercase? 
Do we want to cover the case this changes in the future?

**Comment by piotrbak** [comment]
@vmanthos Yes, it'll always be like this. What kind of changes do you have in mind?

**Comment by vmanthos** [comment]
If `$_SERVER['GROUPONE_BRAND_NAME']` becomes, e.g. `One.com`, we won't detect the environment.
We'd have to `strtolower()` the variable to prevent this.

**Comment by piotrbak** [comment]
@vmanthos I'm not sure if this is going to happen, but let's do it. Better safe than sorry.

**Comment by vmanthos** [comment]
Other than that, the PR is working as expected. :+1: 

**TestRail report:** [testrail-report-464.pdf](https://github.com/wp-media/wp-rocket/files/11061987/testrail-report-464.pdf)

**Pull request merged**
